### ISSUE TITLE
individual jitsi not working

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1002]
today the individual jitsi stream is not working on some instances. (yesterday neither meeting or individual jitsi were working, now the meeting is fixed but not the individual one)

i can see my image moving in the thumbnail, but when i drag it onto the stage it is just buffering/loading and never loads. the meeting is working as expected and i have tried both firefox and chromium. i've also tried on upstage.live, dev-app and refinery install.
it IS working on meta.upstage.live, which is still on stiegl-22. the other instances are all on krombacher-23.

i am pretty sure it is not a network issue as i tested it sitting right next to the modem, where my wifi icon has all bars, & also the jitsi meeting is working as expected.

**Comment by gloriajw** [comment]
Yesterday a syntax error in nginx was fixed. Please ignore whatever happened yesterday.
