### ISSUE TITLE
upload limit appears not to be working

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1003]
the default upload limit for graphics (& audio?) doesn't seem to be working - one of the InterAkt team just started uploading images that are over 3MB and i thought he would get a message saying it was too big, but it just uploaded it. i checked his account and he does not have an increased limit.
not urgent, maybe has been broken for some time?

**Comment by gloriajw** [comment]
Please list the upload limits for each file type, to make this easier for devs. Thank you.

**Comment by vickis** [comment]
everything is 1MB except video 300MB

**Comment by helenvarley** [comment]
everything should be 1 MB, except for video which should be 300 MB

**Comment by helenvarley** [comment]
note: the tool to override the limit for specific players is not granular enough and there is already an issue about this, #609 - not as urgent as ensuring the upload limit is working, but would be good to look at at some point.

**Comment by fuyloon2018** [comment]
I find out on the studio page it doesn't check the upload limit when play upload some file, I have added more code to check that I need to seft test a little before pushing it on Dev-App.
If you can wait more I want to finish that #609 issues after that I will push it all to dev-app

**Comment by vickis** [comment]
thanks! :D

**Comment by helenvarley** [comment]
> I find out on the studio page it doesn't check the upload limit when play upload some file, I have added more code to check that I need to seft test a little before pushing it on Dev-App. If you can wait more I want to finish that #609 issues after that I will push it all to dev-app

yes makes sense to do them together :+1:

**Comment by fuyloon2018** [comment]
I have done #609 and #1003 
@helenvarley please help me verify it on dev-app. Thanks you

**Comment by helenvarley** [comment]
agree - or even a message that stays there somewhere until you do the next action?

**Comment by vickis** [comment]
This is working correctly @fuyloon2018  thanks :)

**Comment by helenvarley** [comment]
i just tested this again & it is working, but the alert when something is too big needs improvements:

- it appears behind the upload window, and disappears very quickly, so it would be very easy not to see it at all. you are then returned to the Studio media list, and don't know why your media didn't upload. is it possible for the message to appear in the upload window itself?
- it would be helpful to add a line in to the text that appears on the upload window. on a new line after the list of accepted formats, saying: "Unless you have been given a higher limit, you cannot upload files larger than 1 MB (or 300 MB for video)."
- the failed upload message should read: "The file cannot be uploaded because it is XX MB, higher than your upload limit of 1 MB." 
- will this message automatically update when someone has a higher limit, e.g. their limit is 5 MB and they try to upload something that is 6 MB, the message then needs to say "The file cannot be uploaded because it is 6 MB, higher than your upload limit of 5 MB."

![Image](https://user-images.githubusercontent.com/3437324/208801712-dd5a8a05-9cd4-4e5e-b0c9-5b9ee7bbf9ea.png)

**Comment by teddyfullstack** [comment]
I've updated how the message should read:

<img width="1006" alt="Screenshot 2023-09-16 at 00 48 21" src="https://github.com/upstage-org/upstage/assets/29925961/3cb9d9eb-6121-4bc4-b5b5-33f8f1ab20f7">

and make it stay until the user dismisses it manually. Let's further discuss the upload limit feature in #1130, since this thread is quite long to read now 😅
