### ISSUE TITLE
on first log-in, no stages shown in Stages list

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1004]
if i've logged out of UpStage, the first time i log in again and come to the Stages list, it tells me "Sorry, no record match your criteria!" and does not show any stages available to me. 
if i reload the page, or go to another part of Backstage and back to the Stages list, then it shows me all my stages.
this is not urgent, but it is slightly confusing, especially when it happens to other players who are new to UpStage and are expecting to see their stage there.
![Screenshot from 2022-08-11 23:09:30](https://user-images.githubusercontent.com/3437324/184243073-f2e00b25-2972-4ac0-b762-7c965692e448.png)

**Comment by helenvarley** [comment]
i'm going to reopen this, as there should always be at least the Demo stage in a player's stage list. all new players should have player access on the Demo stage, & the Stages list should show not only the stages that a player owns, but also those that they have player access to.

**Comment by teddyfullstack** [comment]
The new stage management interface in the Studio should have resolved this 👌
