### ISSUE TITLE
player chat and other problems on smartphone interface

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1008]
today i needed to access UpStage from my phone & ideally use the player chat to communicate with artists who were having difficulties during a presentation. 
i had some trouble logging in on my phone because the menu covered where i needed to enter my username & would not go away. after turning my phone around a few times & then reloading the page i managed to be able to access the username field, but it was not easy.
once in the stage, i tried to get to the player chat. at first this was not possible because the menu was off the bottom of the screen. i tried making the stage fullscreen but still could not access the last icon on the left-hand menu. 
![Screenshot_20220825-195817_Browser](https://user-images.githubusercontent.com/3437324/186740446-cc08a2ad-c0ed-43f9-9a57-769b287e650b.png)
![Screenshot_20220825-195836_Browser](https://user-images.githubusercontent.com/3437324/186740463-9d253cb9-5528-427d-bf81-4c5cdfcbc51c.png)
when i turned the phone to portrait i could see the last icon, and was able to click on it after increasing the size a lot. then i needed to adjust the size and position of the player chat so that i could type in it. i clicked on the star icon and got the frame, & was able to make it fit so that i could type. then i clicked on the star again to try and be able to type - but the frame would not go away. it's not possible to type in the player chat when the frame is selected. nothing i did worked, i could not get rid of the frame and type. i could click on the tool bar icon to close the player chat, then when i opened it again it still had the frame.
![Screenshot_20220825-200022_Browser](https://user-images.githubusercontent.com/3437324/186741140-4c8149a8-f257-423e-ab7e-697b2760def7.png)

i am wondering whether we need to rethink how it works on the phone. i guess it's better on a tablet, but really every time i have tried to do anything on a phone - & it's usually been in a bit of an emergency situation, when something has gone wrong & i'm not at home - it's incredibly difficult if not impossible ... :/  apart from watching a show without interacting, the way it is working at the moment is pretty frustrating.

**Comment by gloriajw** [comment]
Please please please...test with the browserstack emulator I bought. Then we need to decide which phones you wish to support, which Oses, etc based on your emulation results and the most common phones your user has. This can't just be "fixed".
It's like saying that we need a new engine for a car, but leaving out the vital information of which make, model, year it is.

**Comment by helenvarley** [comment]
i think we need to agree that on smartphones, it's not really possible to perform. you can watch as audience and you can use the backstage to upload e.g. images & sounds created on your phone, but to actually operate things on the live stage, on a smartphone screen, is not really ever going to be viable.

**Comment by vickis** [comment]
will try and test some through Refinery.live and the team working there
(but agree let's not try and provide something that can be everything for
everyone! :)

**Comment by helenvarley** [comment]
closing this as it's superceded by #1114
