### ISSUE TITLE
next steps for ticketing / payments / stripe integration

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1009]
thanks to @TuyetGiang we now have Stripe integration (#932) & it is embedded on the Foyer page of every UpStage instance. this is a great start! 

however: presumably it is set up with UpStage's Stripe account, which means that if people are on the refinery, meta or other instances and decide to donate, it will come to UpStage, not to the Refinery or Meta Theater or whoever. is it possible to make it optional on the home page, and for other organisations to enter their own payment processor info? 

it could be a toggle in the Foyer Customisation, similar to the registration one, to display or not the donation strip. if you set the toggle to display the donation form, you then get more fields to enter your own payment details, & perhaps also the option to use UpStage's payment info? this would allow a group that doesn't have a payment system to collect something through UpStage (& we take a small percentage) or a group that doesn't need to collect funds to allow people to make a donation directly to UpStage.

**Comment by gloriajw** [comment]
Each client will need their own Stripe account. Once they have this, we can plug in their Stripe key in the back end, and allow donations. Do any of these clients have a Stripe account?

**Comment by helenvarley** [comment]
i don't know if they have Stripe accounts or not. probably the best thing for now is to make the donation strip at the bottom of the Foyer be just donations to UpStage, and something that can be toggled on or off for other instances.

**Comment by vickis** [comment]
Yes agree we don’t want to be managing others payment systems
Either they have stripe and it goes to them or it’s off
But by default otherwise it’s a donation to upstage
Thanks @giang ***@***.*** :)

**Comment by helenvarley** [comment]
great! thank you :smiley: 
one thing: i expected to find the toggle on the Foyer Customisation interface, but it is in System Configuration. is there a reason for that? if not, it would seem logical to me for it to be in Foyer Customisation, as it will appear on the Foyer page if it is engabled.

**Comment by helenvarley** [comment]
great! thank you - this is now where i expect to find it.

it would be helpful to have a short description for the toggle (also for the registration one, i guess!) in the same style as we have on the Stage Management interface for the toggles there. please add the following texts:

for the registration toggle: "Show or hide the Registration button on the Foyer." 

for the donations toggle: "Show or hide the UpStage Donations bar on the Foyer."

**Comment by helenvarley** [comment]
And one more thing (sorry!!) - it would make more sense for the text in the donation bar on the Foyer page to read "Donate to UpStage:" (rather than "Pay what you can") as in fact this bar on the Foyer does not work as entry to a show, it's for donations directly to UpStage.

**Comment by helenvarley** [comment]
i'm closing this as the original issue has been resolved (to have a toggle in the settings to display or hide the donations strip on the Foyer). issue #1300 from this year is that the donation process isn't working, so we need to look at that.
