### ISSUE TITLE
Foyer image (green brushstrokes) need trimming!

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1010]
the nice dynamic green brushstrokes on the Foyer seem to be growing on uptsage.live and getting a bit out of control - they are now obscuring the text and covering over an image i just added to the text. it is quite curious because on the meta and refinery instances there is not nearly as much of the green brush strokes - it looks like the image is getting multiplied somehow.
![Screenshot from 2022-08-30 12:13:37](https://user-images.githubusercontent.com/3437324/187412159-5ab25301-652a-427a-a100-c7e6de222741.png)
![Screenshot from 2022-08-30 12:16:21](https://user-images.githubusercontent.com/3437324/187412175-f1e56cc4-2320-4b12-b608-1ad5f110c4c2.png)
![Screenshot from 2022-08-30 12:17:37](https://user-images.githubusercontent.com/3437324/187412339-fa8dbc31-5b84-4d8f-adc3-233a67073cd6.png)

**Comment by helenvarley** [comment]
i notice now that on dev-app there is almost no green brush stroke. it seems to have a life of its own ... can it be controlled so that it is always just a bit off at the side?
![Screenshot from 2022-09-18 14:12:35](https://user-images.githubusercontent.com/3437324/190901532-b0e4c1ab-f376-43c0-82e3-bb3732ce01b1.png)

**Comment by vickis** [comment]
Wild!

**Comment by helenvarley** [comment]
i've added the prioritise label to this because it really should be fixed - it's currently not possible to read the information that's there on the Foyer. (i was hoping it might have been corrected with today's update but it hasn't)

**Comment by elisadcg** [comment]
I suggest for this class : <span class="name" data-v-466769c2="">helen's stage</span>
add this css span.name {background-color: rgba(rgb(0, 112, 17,0.5); padding: .2em;}
![Capture d’écran du 2022-10-12 17-05-34](https://user-images.githubusercontent.com/7611913/195379311-80f88343-4a6f-40c7-b7b3-7a3e1b6250ac.png)

**Comment by vickis** [comment]
Looks great thanks Elise :)

**Comment by helenvarley** [comment]
will that make it a green square on all of the foyer tiles? it's a good solution i think - but (to be super detailed & pedantic :wink: ) could it have rounded corners? since the tiles also have rounded corners ...

**Comment by helenvarley** [comment]
also @elisadcg this issue is actually about the proliferation of green brush strokes on upstage.live - do you have any idea about how that could have happened? gloria has just updated it and it is still massively too much green brush strokes. other instances such as refinery.upstage.live, which has also been updated, still only has the minimalist green brush strokes ... :thinking:

**Comment by helenvarley** [comment]
another option would be to remove the green brush strokes entirely, if it's not possible to control them ...

**Comment by fuyloon2018** [comment]
I just reproduced that bug in the local environment, I need time to investigate that thanks

**Comment by vickis** [comment]
Thanks :)

**Comment by fuyloon2018** [comment]
The reason for the green brush strokes is too much, depends on the content we input in the description of foyer customisation interface
If the content is too much the green brush strokes will be bigger
the number of green brush strokes depends on the number of lines in content

**Comment by vickis** [comment]
great work! closed as working as expected by removing images and reducing link text :)

**Comment by fuyloon2018** [comment]
oh! so fast @vickis 
I want to suggest the idea make only one green brush stroke If the content is too much the green brush strokes will be bigger
only bigger and not be duplicated the brush stroke

![image](https://user-images.githubusercontent.com/62701756/205894481-98af9aeb-4fdb-4ed5-81ae-caea1fc92fb3.png)
![image](https://user-images.githubusercontent.com/62701756/205894673-9cb88608-daa4-428a-b5aa-dbf555a7a554.png)

**Comment by vickis** [comment]
>
> hmm sure ... i think it looks a little strange, and just prefer less
> brushstrokes - i think also without so much content to read you always see
> the stages to scroll down to :)
>
let's get the opinion also of @Elisa Godoy de Castro Guerra
***@***.***>  & @helen varley jamieson ***@***.***>

**Comment by helenvarley** [comment]
good to know that there is a logic behind the foliage growth! :stuck_out_tongue_winking_eye: 

what about just removing the brush stroke altogether? it's not necessary, & there can often be reasons to have quite a bit of text and images in that area on the Foyer.

**Comment by vickis** [comment]
I am ok with removing the brush strokes (thanks @Elisa Godoy de Castro
Guerra ***@***.***>  for your work in creating them :)

However either way there is also the issue of having too much text and
information
 pushing the stages down the page and requiring users to scroll which can
be confusing to a new user

**Comment by helenvarley** [comment]
i vote to remove the green brush strokes altogether.

**Comment by webdev604** [comment]
hi @helenvarley we show max 4 green brush-strokes. please test on dev server.

**Comment by helenvarley** [comment]
great, looks better! :sunglasses:
