### ISSUE TITLE
player management layout enhancement

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1011]
as i am using the player management interface, i have thought of a few useful imrpovements to the layout :smile: 

- it would be super useful to be able to see and sort by a "last login" date. 
- the upload limit slider is not very useful, as it is impossible to precisely select a number. normally we would only want to increase the limit from the default 1MB to something like 5MB, but it is just about impossible to do this. clicking next to the slider at its lowest point gives a limit of something like 25 or 30MB.  (furthermore, the upload limit currently does not work at all - see #1003 )
- the hover field for the information entered at registration about a new player's interest in UpStage is impossible to read if they write more than 4-5 words.

my suggestions:
- remove the upload limit slider from the player list 
- add "Last login" as a column before "Date registered"
- in the profile window that opens when you click on the edit icon for a player, add an upload limit tool that is not a slider; it should either allow admins to enter a number, or be a dropdown with options e.g. 2MB, 3MB, 5MB, 10MB, 100MB, 300MB.
- in the profile window, add a field that shows the information provided at registration

additionally, players should be able to see in their own profile (accessed from the Profile link in the top menu):
- an editable field with the information they provided in the registration form about why they want to use UpStage
- a non-editable display of their current upload limit
- it might also be useful for a player to see here the date that they registered their account and the date of their last login. (since non-admins cannot see this info anywhere else for their own account).

**Comment by teddyfullstack** [comment]
- [x] remove the upload limit slider from the player list
- [x] add "Last login" as a column before "Date registered"
- [x] in the profile window that opens when you click on the edit icon for a player, add an upload limit tool that is not a slider; it should either allow admins to enter a number, or be a dropdown with options e.g. 2MB, 3MB, 5MB, 10MB, 100MB, 300MB.
- [x] in the profile window, add a field that shows the information provided at registration

> additionally, players should be able to see in their own profile (accessed from the Profile link in the top menu)

I'll resolve it in another issue 👌

**Comment by vickis** [comment]
Thanks! :)

**Comment by helenvarley** [comment]
great work :smile: 

i'm still seeing the upload limit tool in the player list rather than in the profile pop-up for each player. the dropdown is much better than the slider, but it's not necessary to have it in the player list as it takes up quite a bit of room but is not needed very often.

can the "last login" column be sortable? this would allow us to easily see those players who haven't logged in for ages, & potentially remove them or contact them. or if something seems to have been messed up by a player we can see who has recently been in.

**Comment by teddyfullstack** [comment]
> i'm still seeing the upload limit tool in the player list rather than in the profile pop-up for each player. the dropdown is much better than the slider, but it's not necessary to have it in the player list as it takes up quite a bit of room but is not needed very often.

Got this, I will put it in #995 

> can the "last login" column be sortable? this would allow us to easily see those players who haven't logged in for ages, & potentially remove them or contact them. or if something seems to have been messed up by a player we can see who has recently been in.

I had tried to put sortable on it, but it didn't work like other columns because it is a `generated` field, rather than normally stored fields like the other columns. I could make it work, but I need to know whether it's worth the time. Let me know how badly you want it to be sortable 😅

**Comment by gloriajw** [comment]
You could have the back end sort it and re-render the page. It's not pretty but it works, and would be easier than writing specialized sort code.

**Comment by vickis** [comment]
Sounds like a good solution :)

**Comment by helenvarley** [comment]
i think it will be more useful to be able to sort by "last login" than by "date registered"
it would also be helpful to be able to sort by "display name", and by "status" ...

**Comment by vickis** [comment]
yes agree last login would be useful

**Comment by helenvarley** [comment]
great, the last login column is now sorting as expected 😄 

the upload limit is also looking good, moved to the player profile; i've changed my limit & it shows the change, & i've tried uploading a large-ish file, which took a while but eventually worked. 

i also tried uploading one that was bigger than 300 MB, & it was taking ages so i cancelled it. but really as soon as you try to upload something that is over your limit, there should be a message telling you that you can't upload it. in fact when i reduced my upload limit back down to 2 MB, it still allowed me to upload a 29 MB file. so i'll create a separate issue for that.

**Comment by teddyfullstack** [comment]
It looks like we have a headache number of issues with upload limits 😆
