### ISSUE TITLE
no stages shown after logging out and logging in again

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1014]
i have been noticing this bug for a while now & it's not hugely important, but it would be good to fix as it can be confusing.
if i log out and then log back in again, the stages list shows that i do not own or have player access to any stages. 
the workaround is to refresh the page, and it then shows my stages, however this is confusing for newbies who are trying to find their stages.
![Screenshot from 2022-09-05 14:39:51](https://user-images.githubusercontent.com/3437324/188452405-53e1b0b3-e636-49d8-beda-498bdf97ec24.png)

**Comment by vickis** [comment]
Yes agree confusingvfor newbies :)

**Comment by helenvarley** [comment]
i am not sure if this is what is happening, but it seems that after changing the donations toggle, the stages take a very very very long time to load on both the Foyer and Stages list, or do not even load at all. 
the first time today when i went into both dev-app and upstage.live, the stages appeared on the Foyer and Stages list after a very short time. then i tested the donations toggle, and now they are simply not loading. 
i have tried this on both firefox and chromium (on linux)

**Comment by gloriajw** [comment]
This is next on Giang's list of bugs to fix.

**Comment by helenvarley** [comment]
this has been fixed
