### ISSUE TITLE
with player-only access on a stage, i can still change status & visibility

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1019]
players with player access, but not edit access, to a stage can still change its status and visibility using the toggles on the Stages list. this means that for example, those with guest logins for the walkthrough could make the Demo stage not live or not visible on the Foyer page, without realising that they are making a change that could be problematic for others.
is it possible for these toggles to only be exposed to those who have edit access?

![Screenshot from 2022-10-02 17:11:59](https://user-images.githubusercontent.com/3437324/193461616-63a1d563-af3b-49e2-b88d-a9c4a7c04d5a.png)

**Comment by vickis** [comment]
makes sense yes :)

**Comment by helenvarley** [comment]
further to this, those logged in to a guest account are also currently able to access the profile of the guest account. since the last walkthrough i see that one person who we gave a guest account to, has put her email address into that guest account. so as well as needing to stop guest accounts from changing ANY stage settings (eg visibility & live/rehearsal), they also should NOT have access to the profile.

**Comment by vickis** [comment]
yes definitely - they should register :)

**Comment by fuyloon2018** [comment]
I find out some bug when I investigate this issues, is that right? If right I will fix all this below
first of all I implement "PLAYER Can Edit the stage is not owner or give role "EDIT"" first
 
GUEST and PLAYER can access Admin Page through "customise Foyer"
GUEST can access the backStage and Studio
PLAYER Can Edit the stage is not owner or give role "EDIT"

**Comment by helenvarley** [comment]
GUEST and PLAYER should not see the "Customise Foyer" button at all. they should not be able to access the Admin section at all, only ADMIN or SUPER ADMIN should be able to access the Admin section, or see navigation that leads to the Admin section.

GUEST should not be able to access Backstage or Studio.

PLAYER should only be able to edit stages that they have created, or when the owner of a stage has given them "Player and Edit" access on that stage.

**Comment by vickis** [comment]
Yes agree the above :)

**Comment by fuyloon2018** [comment]
I have done and verified the issues at local env run correctly but when I deploy it on dev env it is some bug I want to verify it a little. thanks

**Comment by vickis** [comment]
sounds good James :)

**Comment by fuyloon2018** [comment]
I have done tasks that I fix listed out below

1. PLAYER should only be able to edit stages that they have created, or when the owner of a stage has given them "Player and Edit" access on that stage.
2. GUEST should not be able to access the Backstage, Studio, Edit Profile, and admin pages.
3. GUEST and PLAYER should not see the "Customise Foyer" button at all. they should not be able to access the Admin section at all, only ADMIN or SUPER ADMIN should be able to access the Admin section, or see navigation that leads to the Admin section.
      - Hide Customise Foyer
      - Hide BackStage if is guest
      - Check the role before entering the admin page

@helenvarley , @vickis You can check it on dev-env

**Comment by fuyloon2018** [comment]
When the User does not have permission to enter the page, it will direct to the home page

**Comment by vickis** [comment]
Sounds good James - the stage that cannot be entered usually has a message
saying
This stage is not open come Back later

**Comment by helenvarley** [comment]
> Sounds good James - the stage that cannot be entered usually has a message saying This stage is not open come Back later
> 
that message is not about guest accounts' permission to enter or not, that's if the stage is in rehearsal mode instead of live. & maybe james you are talking about the Backstage & so on, rather than actual stages? it makes sense to me for it to go back to the Foyer (home page) if they don't have access.

**Comment by helenvarley** [comment]
i just created a guest account on dev-app & tested logging in with it. it's working as expected, & i think it's clearer for the guests not to have any Backstage links visible.

first i logged in using the Login button at top right. after logging in, i was returned to the Foyer. then i clicked on the Demo stage and entered it, with player tools. 

then i logged out, and first clicked on the Demo stage; at the prompt for a nickname, i clicked on "Player login" and logged in as the guest, & got the player tools on the stage.

going back to the Foyer, when logged in with a guest account, i do not see the Backstage or Customise Foyer links. this is what we want :)

as a final test, i typed in the url for the backstage while logged in with the guest account, and this reloaded the Foyer.

all good! :pray:

**Comment by vickis** [comment]
great work! :)

**Comment by vickis** [comment]
I have customised foyer ass admin
and created a new guest role that is unable to see the customise foyer or
backstage access

so seems to be working ok :)

**Comment by helenvarley** [comment]
i am able to access the Customise Foyer interface from the button on the Foyer (on dev-app) :+1:
