### ISSUE TITLE
welsh language request

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1020]
Christina, who is based at Swansea University in Wales, has asked about the possibility of having a Welsh language voice as an option in the avatar voices. She is applying for funding for an UpStage project at her university, & can ask also for some funds for developing a Welsh voice.
First question - is it possible? & second question - approximately how much should we suggest she include in the application for it?

**Comment by gloriajw** [comment]
This is an entire research project, most likely better done in their own
university. If welch pronunciation and inflection, etc. aren't available in
existing open source voice engines, they'd have to spend six months or more
of focused dev work to add it, experiment with it, fix it, refine it. We
would need a team to do this, and we don't have the team. I'm going to
recommend that we pass on this one, and they find the resources in their
own university to add to existing voice engines.

**Comment by vickis** [comment]
Sounds sensible :)

**Comment by helenvarley** [comment]
where did the existing languages come from then? we have quite an eclectic collection - many of which are spoken by small populations (Esperanto, Slovak, Latvian) - there's even Latin! - & also  for sure we ourselves did not spend months researching and developing these languages. Could wherever we got the current package of lanuages from be a source for more languages?
I will also ask Christina if she knows about an existing Welsh digital voice project - there probably is one.

just for the record, here are the languages that are currently available in the voice selection menu:

Catalan
Czech
German
Greek
English (with several regional variations)
Esperanto
Spanish
Spanish - latin american variation
Finnish
French
Hungarian
Italian
Kannada
Latin
Latvian
Dutch
Polish
Portuguese (Brasilian & European)
Romanian
Slovak
Swedish
Turkish
Mandarin Chinese
Canotnese Chinese

**Comment by gloriajw** [comment]
Although this is not my expertise, I'm certain that the engine itself isn't
plug and play. I'm not sure how much code, what type of codecs or DSPs are
required to support a new language. But it's still sounding like a
university level project to me. I'll take a quick look once this conference
is over, and see exactly what is required and let you know.

**Comment by vickis** [comment]
Hey how do you get the stage to stay active - for people coming in after
the show or
Before eg if there is a backdrop and props etc on it … for
Some
Reason

**Comment by helenvarley** [comment]
@vickis is this something to do with the voice languages? if not please create a separate issue :slightly_smiling_face:

**Comment by helenvarley** [comment]
maybe @paul-rohrlach knows how the current languages were found / created / installed ?

**Comment by helenvarley** [comment]
thanks paul, this is helpful information :smiley: in the first instance i will let christina know about this, so that she can make further investigations at her end. maybe there are resources (people and/or money) that she can access through her university, such as funds for promoting welsh language.

**Comment by vickis** [comment]
Awesome Paul :)

**Comment by helenvarley** [comment]
i'm going to close this since any new languages will need to be separate projects, & it's not a priority for us at the moment.
