### ISSUE TITLE
meta stages offline

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1025]
i noticed today that the stages on meta.upstage.live are offline. i have tried different stages & different browsers but it is always showing as offline.
upstage.live and refinery.upstage.live are showing the status as live.

**Comment by gloriajw** [comment]
Fixed. Again, the certs updated but didn't get copied over to mosquitto by
my cron job. Not sure how that can fail. But it's working now.

**Comment by helenvarley** [comment]
great, thank you! :pray: 
is this something that will keep happening, & if we can't fix it immediately can we at least know when it's going to happen & pre-empt it? is it every x months or something? (at different times for each instance??)

**Comment by gloriajw** [comment]
Every time I tweak this script, it gets closer. I'll make one last change
that should make it solid.

**Comment by vickis** [comment]
Thanks Gloria :D
