### ISSUE TITLE
Unable to delete stages

### ISSUE THREAD

**Issue by vickis** [upstage-org/upstage#1026]
I am unable to delete test  or old stages 
<img width="1201" alt="image" src="https://user-images.githubusercontent.com/4249450/197873908-6d392824-d046-400e-85c4-7cbc07d01c5c.png">

**Comment by vickis** [comment]
This is on refinery.upstage.live

**Comment by helenvarley** [comment]
also unable to delete stages on upstage.live and on meta.upstage.live - i guess this problem may have been there for some time as i have not tried to delete a stage for a while:
![Screenshot from 2022-10-26 16-05-23](https://user-images.githubusercontent.com/3437324/197925162-64c109ac-daa9-450b-913b-5f0fd179c9cf.png)
![Screenshot from 2022-10-26 16-09-35](https://user-images.githubusercontent.com/3437324/197925579-3ae345c0-53ae-4b50-b6b4-4348645e61e4.png)

**Comment by vickis** [comment]
tested and successful on Dev app :) wahoo!

**Comment by vickis** [comment]
tested and successful on upstage.live & refinery.upstage.live :D 
<img width="422" alt="image" src="https://user-images.githubusercontent.com/4249450/198112115-6d2e46f9-396c-4b7c-9a07-ddc4787e6093.png">
Thanks team! :D

**Comment by helenvarley** [comment]
you say you tested this on upstage.live, but i just tried to delete the test stage that i created yesterday and it does not work - i got the same error message as yesterday.
i created a new test stage and then deleted that, successfully; so it could be that the bug is fixed but only for newly created stages?? it is important that we can also delete older stages ...
so i am reopening this bug, sorry!

**Comment by gloriajw** [comment]
All good! This is why we ask you to test. Which existing stage is safe to delete?

**Comment by helenvarley** [comment]
i just tried some other older stages and they have deleted ... weird! so maybe it is only the one i created yesterday that doesn't work.

**Comment by gloriajw** [comment]
Ah, it's possible that the stages created during the bug are missing a record. Please post the error in github, we'll fix it.

**Comment by helenvarley** [comment]
ok, it seems like it's just the last 2 stages that i created that i can't delete: Abschiedsparty (created a couple of weeks ago) and testing delete (created yesterday) - it would be good to be able to see somewhere when stages were created!
i've just deleted some other stages created earlier and this did work.

**Comment by gloriajw** [comment]
@fuyloon2018 We're almost done with this bug fix. We need one more tweak to safely delete stages created during the existence of this bug.

**Comment by helenvarley** [comment]
this morning i have successfully deleted the "testing delete" stage that i could not delete yesterday :clap: 
i left the other one (Abschiedsparty) in case @fuyloon2018 or @gloriajw you want to check it yourself, but i think it is working now & i will close this issue. thank you!
