### ISSUE TITLE
stages list: show and sort by date of creation and last access

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1028]
it would be helpful to have in the Stages list, the date of creation and date of last access, and to be able to sort by this - with the most recently created being the first in the list (currently the list begins with the oldest stages, and most often we want to go to the newest one). this was actually in #26 but was not done.

there is already a lot of information in the stages list and i realise that adding two more columns is going to make it more. maybe we can refine what is there? for example, i rarely use the "clone" button - this could perhaps be moved to the Stage Management interface? maybe also the delete button? and the Statistics are not working well here - they take ages to appear and are often not accurate anyway ...
adding @vickis and @elisadcg for thoughts on what is needed here and the layout, before we ask the devs to do it.

**Comment by fuyloon2018** [comment]
![image](https://user-images.githubusercontent.com/62701756/201585247-79422425-8f3e-4a4c-8160-4727bd161f2d.png)
Hi @helenvarley  I changed "Manage Stage" to "Manage" and after the clone stage create date has its own date 
you can check "Create_on" in stage table on the database?

**Comment by vickis** [comment]
Awesome thank you :)

**Comment by helenvarley** [comment]
> ![image](https://user-images.githubusercontent.com/62701756/201585247-79422425-8f3e-4a4c-8160-4727bd161f2d.png) Hi @helenvarley I changed "Manage Stage" to "Manage" and after the clone stage create date has its own date you can check "Create_on" in stage table on the database?

i can see the "Manage" change, that's great, but where can i check the date?

**Comment by vickis** [comment]
Thanks James :)

The question is how do we see the database in order to to check "create_on"
and is it possible to make that information visible in the stage
information area?

**Comment by fuyloon2018** [comment]
Yes I can make Create_on visible on the stage if you need that otherwise, I can show it on the console
do you want to show it on the stage list or on the console?

**Comment by vickis** [comment]
Showing on the stage list would be great thanks :)
_especially_ if we can sort by date created that will find older and unused
stages easier to find and remove to tidy up the server

**Comment by helenvarley** [comment]
in summary the things we want to see in the stages list table are:

- name of stage
- owner (player who created the stage)
**- date of creation (NEW)
- date last used / accessed (if possible? NEW)**
- counter/statistics showing the numbers of players and audience currently on that stage (in fact this is not working accurately so not very useful - probably a separate issue)
- recording (this also needs a bit of a rethink but for now please leave it as it is)
- manage - cog icon link to stage management interface
- status (live or rehearsal)
- visibility (shown on Foyer or not)
- the access i have to each stage (e.g. audience, player, owner)
- Enter - button to enter the stage
    
it would be really awesome if we could sort by the date or creation and date of last use/access.

**Comment by helenvarley** [comment]
i think it could also be useful to have the dates displayed somewhere in the stage management interface, if this is possible & not difficult. it's not essential but could be useful to have, for example, just under the stage name field and above the description field, a line that shows the date of creation and the date of last use/access.
this is not essential - only if easy!

**Comment by fuyloon2018** [comment]
> i think it could also be useful to have the dates displayed somewhere in the stage management interface, if this is possible & not difficult. it's not essential but could be useful to have, for example, just under the stage name field and above the description field, a line that shows the date of creation and the date of last use/access. this is not essential - only if easy!

I think I have to check if the creation interface create-date & last accessed need to be hidden and if in the management interface it has to show out and not allow editing, a lot of things. I will do it if have no priority task

**Comment by fuyloon2018** [comment]
> in summary the things we want to see in the stages list table are:
> 
> * name of stage
> * owner (player who created the stage)
> * **date of creation (NEW)**
> * **date last used / accessed (if possible? NEW)**
> * counter/statistics showing the numbers of players and audience currently on that stage (in fact this is not working accurately so not very useful - probably a separate issue)
> * recording (this also needs a bit of a rethink but for now please leave it as it is)
> * manage - cog icon link to stage management interface
> * status (live or rehearsal)
> * visibility (shown on Foyer or not)
> * the access i have to each stage (e.g. audience, player, owner)
> * Enter - button to enter the stage
> 
> it would be really awesome if we could sort by the date or creation and date of last use/access.

I will show 
date of creation (NEW)
date last used / accessed (if possible? NEW)

**Comment by vickis** [comment]
awesome thanks so much!
very useful :D

**Comment by fuyloon2018** [comment]
the flow of statistics is when a player or guest enters the stage, that action will activate the event and it will calculate and send a  result to a channel, it looks like a storage and the statistics show on backstage get data from that channel.

at the old code when the player or guest is out of the stage it doesn't send new data(I leave the stage) to the channel so the channel still keeps the old data and the statistics get data from that channel so it shows the wrong data

I have fixed that bug, maybe you can see the statistics show the wrong value because the data out update still have on the channel but when we enter the stage it will get the right result from then on

**Comment by helenvarley** [comment]
thanks for the explanation :) i think we will need to monitor this one, as it is quite hard to tell if it's working properly or not when i am testing on my own, or when there aren't so many people. so if the bug is fixed we should roll it out, and then see how it goes :sunglasses:

**Comment by fuyloon2018** [comment]
I have added create date and last access on backstage 
@helenvarley , @vickis please help me verify that on dev-app

**Comment by helenvarley** [comment]
great! this is going to be really helpful :)

my only comment is that you have done the date in the american way (month/day/year) - we in nz do it the british way (day/month/year) - so to my brain that is what makes more sense, day coming before month. 
but don't change it yet - first let's have a quick discussion about what format is going to make the most sense for UpStage. @vickis - thoughts?

**Comment by fuyloon2018** [comment]
> it would be really awesome if we could sort by the date or creation and date of last use/access.
please help me separate the issues above to the new ones because it is not a priority so I will take care of it later

**Comment by helenvarley** [comment]
ok, sorry! i'll close this one now as the original issue (showing date of creation and last access) is achieved. i'll make separate issues for the sorting, and the date format :slightly_smiling_face:

**Comment by fuyloon2018** [comment]
Hi @vickis I fixed that bug, you can check it on dev-app1. thanks

**Comment by vickis** [comment]
Awesome @fuyloon2018 ! works as expected 
thanks :)
