### ISSUE TITLE
object drawing - cannot access lightbulb if trying to make it smaller before showing

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1030]
if i create an object drawing and scale it down (make it smaller) before revealing it to the audience, i can make the frame smaller but the image stays at the original size and is effectively over the lightbulb, which has scaled down with the frame. i then cannot access the lightbulb in order to make the image visible.

**Comment by helenvarley** [comment]
this is actually quite an important bug to fix, as it means that we cannot resize an object drawing before it's made visible to the audience.
![Peek 2023-12-01 11-58](https://github.com/upstage-org/upstage/assets/3437324/39fb56cf-ed40-4a80-bfae-d118085ba6d3)

**Comment by vickis** [comment]
this is still a bug but i do not think it is priority as you are given the translucent backdrop so can draw to size generally ....

**Comment by helenvarley** [comment]
just adding a note to this for future reference - i was testing the new qmu instance and discovered that the object drawing did resize, if i clicked on the opacity slider on the left side of the frame. then i'm able to click on the lightbulb.

**Comment by vickis** [comment]
Great work around :) 
13 Jun 2024 at 02:25 by ***@***.***:
