### ISSUE TITLE
Stage Management - Media - enhancement to layout and information

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1032]
The role of the Media section in the Stage Management (Backstage) has changed since we got the Studio, as it is now not the only way to assign and unassign media to and from a stage. It's now easier to do this via the Studio. However the Media section of Stage Management is still super useful for quite a few reasons, and could be more useful with a bit of enhancement.

**Show total file size of assigned media**
Currently there is no way to easily see the total file size of all media items assigned to a stage. This can be quite helpful if you have a lot of media and want to warn your audience, or if a stage is not loading and it could be caused by a large item. 

**Reorder mode**
This is for changing the order that media items appear in the on-stage toolbars, so it applies only to media that has been assigned to this stage. Therefore it's confusing that it appears above the "Available media" which is actually media that has NOT been assigned to the stage.

i've done a kind of adjustment in the image below - maybe @elisadcg can improve on this, & @vickis do you have any other suggestions, before we assign it to the devs?
![media_interface](https://user-images.githubusercontent.com/3437324/201551133-267cebd5-e518-4ddc-a8b6-8b1ecda1a84d.png)

**Comment by vickis** [comment]
this looks good - and agree especially file size will be useful :)

**Comment by helenvarley** [comment]
updating this: the total file size is now shown at the top of the list of media assigned to the stage, this is great :+1: 
the Reorder functionality is not working at all, i thought we had a separate issue for this but i can't find it so will close this one and make one just for reordering media.
