### ISSUE TITLE
RTMP stream fails to connect

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1033]
a player has created a new stream media item, and cannot make it connect via either larix or OBS. i've just tried it myself, and got the following error message on larix:
![stream_error_larix](https://user-images.githubusercontent.com/3437324/202328796-7cd6d70c-b94b-485b-9052-05effca7d8fc.png)

i was also going to try it on OBS, but when i went to the settings i saw this message, "you can't broadcast with this stream", & remembered that i had previously tried to test another player's stream & one of the devs (maybe phat) said that a player has to create their stream themselves, that we cannot stream to each others' RTMP streams.
![Screenshot from 2022-11-17 14:07:02](https://user-images.githubusercontent.com/3437324/202329198-f2847c74-43d5-4efc-a3fc-c40e24dcf290.png)

i will try to arrange a time when vicki & i can be online with the player to troubleshoot, but from what she has told us she has followed the instructions in the manual & done everything correctly. the stream is there in the Studio and shows as a QR code in the on-stage toolbar, but she cannot actually send a stream.

i'm also currently unable to send my own stream from my phone (the connection just times out). On OBS it appears that i am sending my own stream, but i can't find a stage that it is working on (and we have no other way to test the stream - really need that #693 - studio preview of stream ... ). could this be to do with the 6 month time-out that phat set? there is also no way to know when your 6 months is going to end ...

**Comment by helenvarley** [comment]
to further test this, i deleted all of the streams i had in upstage.live as they were all 7 months or more old. then i created a new stream. from both larix and OBS it appears to be working, however it never appears in the thumbnail in the on-stage toolbar. it might be that the internet connection i'm currently on is just too slow.

**Comment by gloriajw** [comment]
I created a new stream and saw it live on the demo stage. This may be some really odd error with that particular stream. Ask them to retry with a new stream. If the same thing happens again, then maybe we can pin it down.

**Comment by helenvarley** [comment]
ok, i think my problem is my connection. i'm on a different network now, faster but i'm a long way away from the wifi router. the stream i created today is now sending successfully from both OBS & larix, & on the Demo stage i can see the thumbnail in the stream toolbar. but when i put it on stage it's just buffering constantly and never appearing. i'll assume this is just my current weak connection, hopefully next week i will be on a brand new fibre connection & it will all work ...
