### ISSUE TITLE
video: players must request permission to upload video? (& RTMP streams?)

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1036]
we want to limit players' video upload to a maximum of 300 MB, because UpStage is a live performance platform and we don't want to be a video hosting platform; we don't want to end up paying for server space to store a whole lot of video. we also want players to be in the live performance mindset and only use video where necessary, preferably streaming it rather than uploading it.

would it make sense to separate out video from other media (perhaps together with streams?) and have it that players must request permission from an admin to be able to upload video? this could be a toggle in the player's profile that an admin could switch to activate video upload for that player. 

if we did do this, would it also make sense that RTMP streams are bundled with video? players could all automatically have access to the jitsi meeting and individual jitsi stream tools on the live stage, but if they want to have an RTMP stream this needs to be allowed by an admin. this would ensure that there was some training and support for them setting up their stream, and also potentially charge for it.

or should there be two separate toggles? one for video & one for stream? would this help with separating out costs or would it just be a bit more complicated?

are there different data costs for rtmp streams and the playing of pre-uploaded video?

**Comment by vickis** [comment]
I think Gloria mentioned that once uploaded everything is charged at data in / data out so multiple large video are not ideal (and as above live versus too much pre-recorded is preferred) 

If streaming RMTP and jitsi meeting are bundled then yes an option to allow them to particular players will be a good way to limit potential cost over runs and ensure fair use/remuneration etc ...

**Comment by helenvarley** [comment]
i was not suggesting bundling RTMP and jitsi streams together with one toggle, rather RTMP streams with video - so that players have to be given permission to upload video and use RTMP streams.

Jitsi streams are easy for people to use through the browser, & i think if we did not make any kind of streaming available to all players as default we would create a lot of extra work for ourselves. RTMP streams are more like an advanced option for streaming.

**Comment by vickis** [comment]
Ah ok understood
Yes makes sense :)

**Comment by helenvarley** [comment]
ok so this would be the situation:

- Jitsi meeting and individual stream available to all players
- RTMP stream only available with permission from an admin
- video upload only available with permission from an admin

the toggle for this could be either in the Admin section, or in the player profile that you get when you click to edit the player's profile from that list.
i'm inclined to think it would be better in the player profile rather than another column in that list, as it's not something admins would need to do that often (i think) & there's already quite a lot of information in that table. it can also be good for a player to be able to see in their profile whether or not they have this privilege (maybe with an option to request it there?). but it would need to be that the player themselves could not change that toggle in their profile, only request that it be changed (unless of course they are an admin).

**Comment by helenvarley** [comment]
closing this as we don't currently have RTMP streams and the video upload size has been resolved.
