### ISSUE TITLE
live text different sizes on different monitors

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1037]
the artists have reported that the live text displays at different sizes on different monitors. i had noticed this before but not properly thought about it - i guess it is because of different screen resolutions.

ideally we want everyone to see the same thing; is it possible to make the live text also be in the same proportions as other visual elements on the stage? or would this mean that it would have to be made into an image & therefore not editable ... ??

**Comment by tunguyentk** [comment]
After I consider everything in the stage. Almost everything is proportional to the window size, including text. This preserves the layout of the stage.

**Comment by tunguyentk** [comment]
This will help everyone see the same thing but differ only in size. Am I misunderstanding what you mean?

**Comment by vickis** [comment]
agree - as long as text when input displays with the chosen font size it
should appear as proportional to stage layout and should not be considered
a problem

Text may appear to be different due to, device, browser window, screen /
monitor size and resolution
(perhaps in manual we add a not to that affect )

**Comment by helenvarley** [comment]
yes the aim is to have everything proportional - so as long as the text is in the same proportions to the images then it should be fine. i will try to get some screengrabs next time we have a group on different machines, to check that this is correct.

**Comment by helenvarley** [comment]
closing this as it's probably too difficult to solve & we can just decide it's a feature of the platform 😜
