### ISSUE TITLE
ability to sort the Stages list

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1038]
it would be very helpful to be able to sort the Stages list in Backstage.
ideally, i would like to be able to sort by each of the first four columns (stage name, owner, create date, and last access).
i would expect to click on the column title and this would sort it alphabetically or numerically.

**Comment by fuyloon2018** [comment]
I implemented it in issue #1028, you can check it on dev-app1

**Comment by helenvarley** [comment]
yay! this will be super helpful :smile: 

is the default view with the most recent ones at the top of the list? i think that is how it is, just checking.

**Comment by vickis** [comment]
yes :)

**Comment by helenvarley** [comment]
any chance that we can also get sorting by stage name and owner?
owner is probably less important because we can filter by the list of players, but sometimes i can't remember a stage's name to search for it.
this is not urgent, but if it's easy it would be nice.

**Comment by fuyloon2018** [comment]
> any chance that we can also get sorting by stage name and owner?
> owner is probably less important because we can filter by the list of players, but sometimes i can't remember a stage's name to search for it.
> this is not urgent, but if it's easy it would be nice.

Yes I will implement it

**Comment by fuyloon2018** [comment]
@helenvarley I deployed it on dev-app1, please help me verify it, thanks

**Comment by vickis** [comment]
tested and working - Thanks! :)

**Comment by helenvarley** [comment]
fantastic! this is going to be really helpful :smile:

**Comment by helenvarley** [comment]
not sure that this is fully working - for example when i click on the Date column, the hover message says either "click to sort ascending" or "click to sort descending", but clicking does not change the order at all.

note: this is a low priority issue!

**Comment by teddyfullstack** [comment]
We actually have this in Studio now 😎

**Comment by helenvarley** [comment]
great - but i'm still not getting a change in the list when i click on the date & last access columns. but not a high priority!
