### ISSUE TITLE
date formats

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1039]
for discussion: what date format should we use on the site?
james has used the american format (month, day, year) for the new date columns on the Stages list, but i am used to the british format (day, month, year) so it trips me up to see it the other way around.
(i also like to resist american hegemony!! :laughing: )

what are the pros and cons of the different date formats? are there other formats besides these two that are worth considering?

will it make a difference to the sortability of these columns if the format is different?

**Comment by gloriajw** [comment]
Date format has nothing to do with sorting. I prefer the cleaner European
date format.

**Comment by vickis** [comment]
great yes dd/mm/yy is perfect thanks!

**Comment by helenvarley** [comment]
ok that's a decision then :sunglasses: 
@fuyloon2018 can you please make all date formats be dd/mm/yy

**Comment by fuyloon2018** [comment]
> @fuyloon2018 can you please make all date formats be dd/mm/yy

Yes I can, I will check the overview in upstage

**Comment by fuyloon2018** [comment]
![image](https://user-images.githubusercontent.com/62701756/204765768-fb2855b0-89f9-4ced-82f8-d505deef6477.png)
![image](https://user-images.githubusercontent.com/62701756/204765883-cea89926-14d5-4fc5-acca-1c38538b4a4e.png)
I check the format date in the management stage interface and in the player management interface it show in the picture above
I suggest making it in the same style for consistency.

result
![image](https://user-images.githubusercontent.com/62701756/204764161-d532a78c-2bb2-488c-8cfa-1dc3938e8382.png)

**Comment by helenvarley** [comment]
i think that the "5 days ago" format is only useful up to a point; once it's more than about a week ago, then it's more useful to have the actual date. is that possible?

**Comment by fuyloon2018** [comment]
> i think that the "5 days ago" format is only useful up to a point; once it's more than about a week ago, then it's more useful to have the actual date. is that possible?

Yes it is possible I will apply for all date in the Upstage

**Comment by fuyloon2018** [comment]
I deployed it on dev-env,  please help me verify that

**Comment by helenvarley** [comment]
great! i think this is good. let's call the issue closed and once we have used it more on upstage.live we can see if there needs to be any further tweaking. thank you! :pray:

**Comment by vickis** [comment]
agree
also date format for timestamp allows filtering
vicki :)
