### ISSUE TITLE
email failed to send because of umlaut or macron

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1044]
i tried to send an email from the admin notifications system and got the error message shown in the screenshot below. i looked through the body text and saw that there was an umlaut (Malmö) and a macron (Whakatū). i removed both of these and then the email sent, so i'm not sure which one stopped it.
As we are dealing with multiple languages, and will have the interface translated into languages that use umlauts and macrons, we should also be able to send them in email notifications. players might also use them in naming media items. is this difficult to fix?

![Screenshot from 2022-12-20 19-23-18](https://user-images.githubusercontent.com/3437324/208598733-ccd0169c-d306-4498-9987-897378d333c9.png)

**Comment by vickis** [comment]
yes agree - need to consider the diacritical mark in languages

for tohu tō (the macron in te reo maori - used here in Aotearoa / NZ ) you
can add an extra vowel - in fact some consider that a non colonised way to
express the language

:)

**Comment by helenvarley** [comment]
this may be what has caused it to fail again - yesterday i got this error:
![Screenshot from 2023-01-10 21-41-53](https://user-images.githubusercontent.com/3437324/211725344-ab6229bb-ffaf-4ffa-a994-2d2a62fbb1da.png)
i thought it might have beeen "José Flávio" but even when i removed him from the list of recipients it did not send. i then tried sending only to myself, and got the same error.

**Comment by gloriajw** [comment]
Please retest this on upstage.live. I changed the encoding to be more
forgiving of characters. let's see if it works.

**Comment by helenvarley** [comment]
ok, i've sent a test email to all of the players on UpStage.Live (removing the guest accounts & a couple of test accounts), & i've just recieved it myself :smile: 

two things: it seemed to take a long time to send - the circle was going round & round for a long time but then the successfully sent message came up. the second thing, after the success message disappeared, i am on the page with the message and everything in it, as if it hasn't been sent. as the success message doesn't stay for very long, it would be easy (especially when multi-tasking) to not see the success message and not know if it has gone out or not. wouldn't it be better if the success message replaced that screen, so that it stays there until you navigate away?

**Comment by gloriajw** [comment]
Yes, please create a ticket for this.

**Comment by gloriajw** [comment]
What do you consider a long time? It does have to get a temporary token
before it proceeds. I can possibly speed this up, but I need to know how
long it took, roughly.

**Comment by helenvarley** [comment]
ah - i can't remember now how long it really was. it just felt like "too long". but since it did send, let's not worry about it :smile
i'll make an issue about the success message.

**Comment by helenvarley** [comment]
closing as i think this has been resolved
