### ISSUE TITLE
email notifications - success message as new screen

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1054]
when i send an email from the email notification interface in the Admin section, the success message appears quite briefly over the top of the message form and then disappears, leaving your message still there, as if it hasn't been sent. it's very easy, (especially when multi-tasking) to miss the success message and then think that your message hasn't been sent.

it would it be better if the success message replaced the message form screen, so that it's clear that the message has been sent & you can see the success message until you navigate away.

**Comment by tunguyentk** [comment]
@helenvarley  if i make the form clear and then the success message appears. Does it really make you understand that the email was sent ?

**Comment by gloriajw** [comment]
@tunguyentk Please make the success/error popup remain on the screen until the user dismisses it. This way, people can send email and walk away, come back later and see progress.

**Comment by helenvarley** [comment]
yes a persistent success message would be ideal.
having the form clear is also helpful, but more important is the persistent message.

**Comment by tunguyentk** [comment]
@helenvarley @gloriajw ok , When someone sends an email and the email is sent successfully, a success message will be displayed and won't go away if the user doesn't dismiss it. (Of course the form will reset to the original state)

**Comment by gloriajw** [comment]
What happens if there's an error message? Hopefully the same thing?

**Comment by tunguyentk** [comment]
I think in case of error message, the form should not be reset. You never want to lose everything you write down because of a  error.

**Comment by gloriajw** [comment]
Agreed, but the error message should be shown, so the error is obvious and
can be copy-pasted and sent to us.

**Comment by vickis** [comment]
Agree persistent error message also
And I guess red indications where the form is incomplete and / or in
correct formatting ..

**Comment by tunguyentk** [comment]
@vickis we have notification for this. I think I just add the red dots where they are required to fill in the information to be able to send the mail.

**Comment by tunguyentk** [comment]
@gloriajw I realize that notifications (toast) are not designed to be always visible on the screen. Is it good if I set its display time to a large number (eg 1-2 minutes) and enable pauseOnHover (like it won't disappear if you move the mouse over it)

**Comment by vickis** [comment]
super thanks! :)

**Comment by helenvarley** [comment]
@tunguyentk - is it not possible to have the notification persist? even 1-2 minutes may not be long enough, for example if i hit send on a message & get interrupted by something else (often happens, in my multitasking life!) i may forget to look back.

if that's not possible, maybe there could be an interface to see a report about messages sent? something simple like a list of successful sendings with the date/time so that we can look back later & know that a message was sent. unless this is complicated of course.

**Comment by gloriajw** [comment]
I propose that you keep it even simpler and show a popup that requires the
user to X to close it.

**Comment by tunguyentk** [comment]
@gloriajw sorry for taking so much of your time, i just wanted to let everyone know the limitation i am facing. I have understood the request and will complete it. Thanks <3

**Comment by gloriajw** [comment]
@tunguyentk , it's fine. I want you to communicate as often as you need, with whatever issues you're having. I also want you to be able to move on to more exciting code changes/improvements. These small things can be kept simple: ugly popup works just fine :)

**Comment by vickis** [comment]
@tunguyentk <https://github.com/tunguyentk> awesome work - thanks team :D

**Comment by helenvarley** [comment]
great simple solution! thank you :pray:

**Comment by tunguyentk** [comment]
@helenvarley @vickis i deloyed it , please check. Thanks <3

**Comment by helenvarley** [comment]
very nice solution 😎
