### ISSUE TITLE
individual jitsi issues

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1058]
when using individual jitsi webcams, there are frequently issues with one or more players & audience not being able to hear or see one or more of the other cams.

we thought it might be that if you entered the stage after the webcam was already on the stage, you didn't hear it, but this is not always the case - when some audience joined after the webcams were on stage, some could hear everything and one could not.

the work-around is for the cam that is not being heard and/or seen by one or more people to be taken off and put on stage again. this usually works - however, especially for online audience, they may not know that they should be hearing/seeing something so won't know to say they're not hearing/seeing.

i am not sure how we can test this more, as it is not consistent. when rehearsing, we all experienced it at different times so it's not one person's set-up. we also tried changing browsers & it seemed that this fixed it, but then going back to the first browser the problem was not there anyway. so it doesn't seem to be connected to the browser.

any thoughts, suggestions for things we can try to narrow down what the problem is?

**Comment by gloriajw** [comment]
Since this is inconsistent, I don't know what to suggest. Are you exceeding some max in the person's bandwidth by having multiple streams? This is the only thing I could think of if you cannot reproduce this consistently.

**Comment by vickis** [comment]
That makes sense Gloria
Helen has been having wifi difficulties

Could when you load the stage also affect what you see/ hear

Eg if the individual jitsi is already on the stage when someone enters
might that cause them to not see or hear it?

It would be good to try and test across a few machines :)

**Comment by gloriajw** [comment]
Not sure, but we should test this. If it's a bandwidth issue, you could
test this by loading up a stage and watching when failures start to happen.

**Comment by helenvarley** [comment]
it's not to do with my wifi issues, as i have observed this ever since we had the individual jitsi feature, from my home connection in munich as well as from meta theater and when i was in portugal. when we experienced it last week, eva was in different places in austria.

what's consistent is that nearly every time that more than two people are on the stage, one or more person does not either see or hear one or more of the others. usually after the person having problems reloads the stage, the problem is fixed. 

i've also noticed this in the jitsi meeting, but less often, so have put it down to people's connections - when we've had a large group in a jitsi meeting there is nearly always one person who can't hear or see one or more of the others.

**Comment by helenvarley** [comment]
> Not sure, but we should test this. If it's a bandwidth issue, you could test this by loading up a stage and watching when failures start to happen.

i'm pretty sure it's NOT a bandwidth issue. the failures happen right away, for example last week when the three of us were on the stage and all put our jitsi individual webcams on. right away one person could not see or hear one or more of the others. we all reloaded and then it was a different one of us having this problem. it was solved by just the person with the problem reloading. so it seems like it is some kind of connection capacity issue?

**Comment by helenvarley** [comment]
i have just watched a recording that rick sacks made of our presentation on friday, and at the start when there should be 3 individual jitsi webcams visible, there are only 2 - eva's is fine, mine is frozen, and vicki's is not visible. but all 3 voices are heard.
when we come on again for questions at the end, our cams are visible but mine is frozen and eva's camera seems to freeze when she is not speaking. this is probably to do with rick's bandwidth. our voices are all heard. my image unfreezes when we get to the end of the questions.
(note: we didn't take our cams off, we just made them small and transparent, as we were speaking parts of the presentation. the audio was really good all the way through for all of us).

there's another recording made by mem which i'm waiting for a link to download. it will be interesting to see how her reception of the streams was (she is in serbia, rick in california).

**Comment by gloriajw** [comment]
We should test this one weekend so I can watch logs while this happens

**Comment by helenvarley** [comment]
yes - we need to make a time when we can have a group of people together at the same time, as it's not a good test when there are only 2-3 of us on the stage. but i'm away from the 8th for 2 & a half weeks so probably can't manage it before end of feb at earliest ... can you message in slack about a day/time that is good for you?

**Comment by helenvarley** [comment]
yesterday at our birthday party i tried to use my individual jitsi webcam but almost nobody could see me. most people could hear but not see, and didn't have a buffering icon.
here is the chat where we asked people if they could see and hear me. (after this we switched to the meeting tool and this worked)

elisa:ear yes

Loki:I can hear you

Adriene J:can hear not see

elisa:see no

katarina:only to hear you

anniea:hear yes, see no

Andy:yes

JohnnyBoy:OK: When the next Cyposium?

tamiko:no

BiancaJohn:Hearing not seeing

Adriene J:nothing

tamiko:no buffering icon

ViAv:nothing for me either ...

Adriene J:we can hear

tamiko:we can hear well though

katarina:sound s good

**Comment by vickis** [comment]
We have just been looking again at UpStage to test these things we found 
I could not hear Helen's individual cam in Chrome or Firefox 
In Chrome the individual window is not available in the meeting toolbar

also again tonight I could not see Helen's individual window in the meeting window I saw a black screen with a white object - not the normal avatar if video is off ...


11 Jan 2024, 22:06 by ***@***.***:

**Comment by helenvarley** [comment]
vicki and i took screenshots at the same time to show what each other is seeing or not seeing. here are mine:
![Screenshot from 2024-01-11 10-05-32](https://github.com/upstage-org/upstage/assets/3437324/31b7ad4e-1bd1-46dd-90ad-15fdda674264)
![Screenshot from 2024-01-11 09-57-20](https://github.com/upstage-org/upstage/assets/3437324/bcbcca4a-f525-48a7-a13c-056b9ba4b6a5)
![Screenshot from 2024-01-11 09-54-43](https://github.com/upstage-org/upstage/assets/3437324/a3d32fb1-8cf9-46de-962a-a1ee4b334306)

**Comment by helenvarley** [comment]
and here is my screenshot showing no individual jitsi window in chrome:
![Screenshot from 2024-01-11 10-04-02](https://github.com/upstage-org/upstage/assets/3437324/8710d618-a57c-4b51-a66c-39692033b5fd)

**Comment by helenvarley** [comment]
as gloria has noted previously, the issues with streaming are inconsistent & definitely sometimes to do with individual's network connections. however there are some things that are clear:

- generally the jitsi meeting functions consistently well, whereas the individual jitsi webcam is much less reliable; however the individual cam is much more useful for actual performances (especially while we have no RTMP stream option)
- the individual jitsi thumbnail doesn't appear in the toolbar in chrome, so it's not possible to use it in chrome
- yesterday evening the majority of people (there were ca. 25 connections) could hear but not see my individual jitsi cam. could this be a load issue at our server end?

**Comment by helenvarley** [comment]
just to add to this: for the Audioblast performance on 24.2.24, we sent an individual jitsi stream from eva's laptop in the venue. we had two other laptops in the space & there were about 10 online audience. as far as i'm aware, no-one received the stream.

**Comment by helenvarley** [comment]
i'm closing this now as there have been improvements to the streaming - we still need to test with larger numbers, but at the moment we have narrowed things down to 2 specific issues (one related to chrome on the mac, & the other about entering when an individual jitsi cam is on the stage - i'll make a separate issue for that).

**Comment by helenvarley** [comment]
this is still a problem, but we have a different issue, #1313
