### ISSUE TITLE
unable to change upload image because dropdown menu not fully displayed

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1059]
i need to increase my upload limit on dev-app, & discovered that when my name was the last on a short list (i searched for my username) the dropdown menu only partially appeared, so it is impossible for me to select the limit i need.
the work-around is to sort the list differently, but it would be good to fix it as it seems to affect the bottom two rows however you sort it.
![Screenshot from 2023-02-03 15:13:43](https://user-images.githubusercontent.com/3437324/216496184-803ccc99-e60c-48e4-a4b7-fb6b0c124a0b.png)

**Comment by tunguyentk** [comment]
@helenvarley can i change it like this . drop menu in the last 2 items will be displayed above
![image](https://user-images.githubusercontent.com/117065175/216880175-9f587519-a6e5-46cd-8f66-be5f0e95e824.png)

**Comment by vickis** [comment]
Looks great :)

**Comment by helenvarley** [comment]
yes excellent :+1:

**Comment by tunguyentk** [comment]
@helenvarley @vickis i deployed it , please check

**Comment by vickis** [comment]
thanks @Helen Varley Jamieson ***@***.***> :)

**Comment by helenvarley** [comment]
great! :pray:
