### ISSUE TITLE
display total file size of a stage

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1061]
previously in the old UpStage, it was possible to see a total size for all files on a stage. this is quite useful, as it can encourage players to reduce the size or number of files, or if it has to be large to give advice to the audience to take extra time for loading the stage.

it would be great to have this total available somewhere - i suggest the logical place would be in the Media tab of a stage's Stage Management interface. it would make sense for it to appear at the top of the "selected media" column.

while that's being done, could "selected" please be changed to "assigned", as this is the terminology that we use (assigning media to a stage) and also selected implies that it's only been selected, not actually assigned.

so the column heading could be "Media assigned to this stage - total filesize: XX MB"

**Comment by tunguyentk** [comment]
![image](https://user-images.githubusercontent.com/117065175/218290441-e5292191-1567-4424-837f-4a738ee0691d.png)
@helenvarley @vickis 
So I will change the title of this column, and will display the total capacity of all elements in the column?

**Comment by vickis** [comment]
Yes :)
That is what is meant - thanks :)

**Comment by helenvarley** [comment]
yes that's correct - change "Selected Media" to "Media assigned to this stage - total filesize: XX MB" (with XX being the total of all the files assigned to the stage)

**Comment by vickis** [comment]
Super thanks! :)
[image: image.png]

**Comment by helenvarley** [comment]
i am unable to check as https://dev-app1.upstage.live/ is not working - i get a blank foyer page, no stages appear, and there is no link to backstage ... can you please check? it could be the internet where i am but everything else is working fine ... :thinking:

**Comment by tunguyentk** [comment]
@helenvarley I also had the same problem. Gloria told me yesterday about some changes that seem to affect dev-app1. I still don't know how to solve this. Maybe I'll wait :)))

**Comment by gloriajw** [comment]
@tunguyentk when you see this, look for missing files. The old dev-app1 upstage dir was moved to "hold". I never delete the rpevious one for these reasons. Try to sove the issue yourself. Looks like maybe static content may be missing?

**Comment by helenvarley** [comment]
great - now i can access dev-app & it looks great. i think this will be very helpful :+1:
