### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by nguyenhongphat0** [upstage-org/upstage#1068]
- [x] Reduce stage list payload in the foyer (currently, it took so long to load because of many unnecessary fields in the query)
- [x] Optimize backstage list loading time (it is also the reason why the login seems to take so long because it took you backstage right after login)

**Comment by vickis** [comment]
thanks! :)

**Comment by nguyenhongphat0** [comment]
Here are some updates about the issue:

- The major cause of it was the old `StageList` query in GraphQL, which was implemented by client pagination and had so many fields inside the payload. So I refactored the list and put it into Studio since Studio was supposed to be our new Dashboard. 
- However, migrating everything into the new Studio would require more work; therefore, at the moment, features that aren't implemented yet would be accessible in Studio but as a part of Dashboard (a little bit confused, but I hope the screenshot below will help to explain 👇)

<img width="1389" alt="Screenshot 2023-02-25 at 22 53 04" src="https://user-images.githubusercontent.com/29925961/221366578-9fca6a7c-589f-4f96-bf62-31c66d03dc3b.png">
<img width="1388" alt="Screenshot 2023-02-25 at 23 05 44" src="https://user-images.githubusercontent.com/29925961/221367209-3e0aed91-3073-407f-9089-5ad8ec33a3e8.png">

**Comment by vickis** [comment]
Thanks Phat :D
