### ISSUE TITLE
unable to approve new player

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1073]
for the last few days i have been unable to approve a new player. if i click on the status toggle in the player management list, i just get the buffering icon and it never approves. i tried also clicking on the edit link, and here it shows the player's status as active, but when i close that window and go back to player management, the player is shown as not active.

an error message popped up when i went to the player edit window - maybe this has something to do with it?
![Screenshot from 2023-02-28 15-42-37](https://user-images.githubusercontent.com/3437324/221740698-34f59aae-9726-45cd-a5c9-b016d8716b47.png)

it is quite urgent as we need to be able to approve new players. @gloriajw assigning this to you as i'm not sure which of the devs is best placed to deal with it?

**Comment by gloriajw** [comment]
I installed this extension. Please retry.

**Comment by helenvarley** [comment]
great, it worked! :+1:
