### ISSUE TITLE
unable to assign players to stage

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1074]
when i assign a player to a stage, and click "Save Stage", i get the error message "can't set attribute" and the player has not been assigned to the stage.
![Screenshot from 2023-03-01 13:34:54](https://user-images.githubusercontent.com/3437324/222014978-8ba261bb-db8a-4037-b3f4-83fcef881b96.png)

**Comment by gloriajw** [comment]
@tunguyentk can you please find some time to see why this is happening?
If we can't fix it quickly I'll switch production back to the main branch.
