### ISSUE TITLE
remove Backstage link from right-hand UpStage logo dropdown in Studio

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1081]
in the revamped Studio interface (formerly Backstage) there is still a link that says Backstage and takes you to the old Backstage Stages list interface. this is from the UpStage logo in the top right-hand corner of the Studio interface. it has a dropdown menu with the options Backstage and Foyer.

Please leave the Foyer option there, and change Backstage to "UpStage Website" with the link to upstage.org.nz
![Screenshot from 2023-03-23 11:17:12](https://user-images.githubusercontent.com/3437324/227050931-61c652be-58d8-4ae1-9497-272da2a8c66d.png)

**Comment by vickis** [comment]
The order in the drop down should be
> foyer
> website (link: upstage.org.nz)

thanks! :)

**Comment by helenvarley** [comment]
not "UpStage website"? i thought that was what we talked about - that people get confused between UpStage platform & website, or what is a website & what is the platform ... ? not sure how we make it clear. maybe "website" is enough ...

**Comment by vickis** [comment]
Agree we talked about
Upstage.live is platform
Upstage.org.Nz  is the website :)

**Comment by helenvarley** [comment]
yes. the question is just what the text needs to be in the dropdown menu, so that it's clear to people where each link takes them. "Foyer" is i think clear, it goes back to upstage.live i.e. the platform. "Website" on its own is maybe fine, but for those who haven't understood the difference between the platform and the website, it may not be clear. mind you, "UpStage Website" maybe doesn't make it any clearer ... :thinking: 
"Community Website" ?
"UoStage Community" ?
something else?

**Comment by vickis** [comment]
I think
Foyer (makes sense and indicates you are staying in local space)
UpStage Website  either that or just Website (indicates you are leaving
this current space)

**Comment by helenvarley** [comment]
the dropdown just has Foyer now, i think we can leave it at that & close this issue :)
