### ISSUE TITLE
remove frame layout when going to Media from Profile or Admin

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1082]
If you are in either Profile or Admin and then click on the top right icon to go to Media, the Profile or Admin window remains visible in the lower half of the screen. This shouldn't happen.
![Screenshot from 2023-03-23 11:28:58](https://user-images.githubusercontent.com/3437324/227052718-5bb2d554-2acb-4a9c-b4ee-4c9a6ff9fdc0.png)

**Comment by helenvarley** [comment]
note: frames should not be used in any of the Studio interfaces - there's no need for players to have multiple interfaces visible together, and it makes the Studio even more difficult to use on small screens of mobile devices

**Comment by elisadcg** [comment]
Yes it's not common to have the previous page remain at the bottom of the page.

**Comment by helenvarley** [comment]
thanks!
