### ISSUE TITLE
Consistency of new Studio interface

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1083]
Phat has done a great job applying the Studio layout to Backstage, & as part of this the whole Backstage has been renamed Studio. The former Studio is now Media.

There are some inconsistencies in the new design and layout. For example, Profile and Admin still have the banner colour and breadcrumbs from the old Backstage. the breadcrumbs should be removed, but the coloured banner is helpful in making it easy to know what section you're in. Whereas the Stages list and Media don't have a coloured banner, and the only text indicator of the section you're in is the "New Media" or "New Stage" button. it would be helpful to give each section a coloured banner that lets the user know easily what section they are in.

There is a new icon menu on the top left, for Media, Stages, Profile, Admin and Manual. This should be re-ordered to have Stages first (Stages, Media, Profile, Admin, Manual).
The icon for Admin is confusing, it looks like a search icon. Can we find a better one for Admin? (Not the cog as that is used for the Stage Management link. Maybe a key? or what else would make sense there?)

there are a lot of implications for the manual with these changes - e.g. many screengrabs will have to be redone again :/

@elisadcg - when you have time, could you have a look at the updated interface and give us some suggestions for improving the design and layout? tagging icon-man @riadsalameh on this as well in case you have time & interest to have a look :)

**Comment by helenvarley** [comment]
adding @gloriajw and @nguyenhongphat0 to this so that you are aware of the design issues with the new interface. i haven't heard back from elisa or riad about it, but also haven't followed up on them. if either of them has time, i would like to get some design input on these things, particularly icons, as it's important to think these through.

**Comment by helenvarley** [comment]
i am wondering if the left-hand menu is actually necessary. this has 5 icons, & for most players (who aren't admins) it will only be 4. could we not fit all of this into the top navigation bar?
the Profile interface is already accessible by clicking on your player name in the top navigation, & this seems quite intuitive.
there's some space between the "clear filters" button and the player name, which would be more space without the left-hand tool bar, & i think all those icons would fit there. they could maybe each have the colour of their section or something more to differentiate them from the stage list filters and whatever other navigation would be there for each of the other sections ...

**Comment by vickis** [comment]
agree sounds good

**Comment by helenvarley** [comment]
@elisadcg is going to look at the interface issues but doesn't have time until late june :)

**Comment by teddyfullstack** [comment]
This would be one big issue that would span across many pull requests (like the good old #667 #681 #684 #692 #721). @heluDuyne will start with the Email Notification section (as part of resolving #883), and I will start with the Player Management (as discussed in #1089). Pls let me know if it's okay 👌  

![z4555770108123_e23201b5e8c1a872f01e4050963c0779](https://github.com/upstage-org/upstage/assets/29925961/434c0b35-91ed-495a-bb97-908d13b9f1dc)

**Comment by gloriajw** [comment]
All good. It's the best way to handle it.

**Comment by teddyfullstack** [comment]
Relevant issues with the Player Management: #1011 #995 #604 #86
Relevant issues with the Email Notification: #1054 #1044 #814

If I missed any issue please help me tag it in as well, thank you 🙏

**Comment by helenvarley** [comment]
we need some input from @elisadcg on this question of the left-hand menu, to have it or not ...

**Comment by vickis** [comment]
yes agree - it would be good from a ux perspective :)

**Comment by elisadcg** [comment]
I think it better to keep the same organization in all of the pages. Usually the top navigation it's common. There is a "coming back" vertical menu. But use the 2 options it's not the most common. Unless for hudge interfaces, which is not our case.
So for horizontal menu like we have since the first page :
![wireframe-upstage-modelo-01-lit](https://github.com/upstage-org/upstage/assets/7611913/843b8c80-e584-41b2-b8a9-45544d8f48a7)

**Comment by elisadcg** [comment]
We can win space on the menu with combining the Profile in a submenu dedicated for the User 
![06navigation](https://github.com/upstage-org/upstage/assets/7611913/2dfe57b2-349f-48a5-8d58-4fefde31a6c6)

**Comment by vickis** [comment]
Great thanks Elisa :D

**Comment by helenvarley** [comment]
i think these wireframes are older than the ones you posted on slack? :slightly_smiling_face:

**Comment by elisadcg** [comment]
And for adding quickly players admins and all players or/and all admins, is it possible to add this possibility near the "to:" form ?
![emailnotif-02](https://github.com/upstage-org/upstage/assets/7611913/65a87c84-712b-4f5f-9289-6a559c89d9ea)

**Comment by elisadcg** [comment]
![Createnewstage](https://github.com/upstage-org/upstage/assets/7611913/4ab4672d-18a4-48ec-9233-37a8f4dc9b4e)

**Comment by vickis** [comment]
super! :)

**Comment by helenvarley** [comment]
>  Question : which order for the navigation do your prefer : Stages/Media/Manual or Media/Stages/Manual ?

Stages / Media / Manual please

**Comment by helenvarley** [comment]
and for the internal navigation of that section:

- no need for the "Sccenes" menu item, this has not needed to be used in the Stage Management as it's possible to delete and re-order scenes directly in the live stage, where you can see what you are doing
- the buttons "Enter Stage", "Save Stage" etc do not need to have the word "Stage" there - i think that is obvious, no? they can just say "Enter", "Save", and "Delete" (for now keep "Sweep Stage" as "Sweep" on its own is less clear)
- i am wondering whether this is the best place for the "Clear Chat" and "Sweep Stage" buttons ... we have the possibility now to clear the chat directly on the live stage, and in the Archive section of Stage Management. these functions are a bit different to the Enter / Save / Duplicate / Delete functions.
@vickis - thoughts? do we need the Clear Chat and Sweep Stage buttons here as well or would it be cleaner to take them off and let those things be done in Archive and/or on the live stage as we can now do?

**Comment by helenvarley** [comment]
@elisadcg - note the menu item and section title should be "Media" (not "Medias" - media is one of those special english words that is both plural and singular just as "media" :wink: )

**Comment by helenvarley** [comment]
@vickis "Create Stage" versus "New Stage" - what do you prefer?

**Comment by helenvarley** [comment]
hi team, great progress with updates to the layouts :+1:  
as always a few comments from me - apologies if these are things you're already working on ...

- [ ] when i arrive in the Studio from links with the url https://dev-app1.upstage.live/studio/, it's bringing me to the player list rather than to the Stages list. it should bring me to the Stages list and have a banner for the Stages section.
- [ ] the Admin section menu is expanded by default - maybe because it's bringing me to the Admin section? but when i click to another section, e.g. Profile, Stages or Media, the Admin menu is still expanded.
- [ ] most of the pages within the Admin section have the old banner still, with breadcrumb links to the old interfaces. there should be a section banner that says Admin, for all of the pages within the section. (@elisadcg - do we need to have mockups for the section banners? colours etc.?)
- [ ] will the other section menus, e.g. update and change password in the Profile section, also come out into the left-hand menu?

**Comment by helenvarley** [comment]
@elisadcg can you have a look at dev-app, when you have time, to see the new interfaces? now all three sections (Media, Stages & Admin) are in the new format. the Profile one is still the old interface. 

i think the Profile could be just the pop-up window for the profile, which is what happens on the Player Management interface - i've uploaded a screenshot.

what i miss in the new interfaces is something to make it clear all the time which section i am in. for the Media and Stages sections there is the "new" button at top left ("New Media" or "New Stage") but the Admin section doesn't have this. 

could there be a different colour background for that top bar in each section? doesn't need to be very strong colours but just something to make it clear that it is a different interface; & also a change to the logo on the left, so that the section you are in is highlighted in some way.

**Comment by helenvarley** [comment]
nice work on the differentiation of the sections with the background colours @teddyfullstack :+1:

**Comment by teddyfullstack** [comment]
Do you think differentiating the sections with primary colours (below) is a good idea? It is more obvious which section you are navigating, but make it less... "upstage" than the pastel background colours option 😅 

<img width="1440" alt="Screenshot 2023-11-19 at 22 35 53" src="https://github.com/upstage-org/upstage/assets/29925961/ae38eec4-6901-4cac-ab8e-a7031b9cf691">
<img width="1439" alt="Screenshot 2023-11-19 at 22 34 42" src="https://github.com/upstage-org/upstage/assets/29925961/1654965c-ba26-44ab-8f26-48aa80e37c34">
<img width="1438" alt="Screenshot 2023-11-19 at 22 35 19" src="https://github.com/upstage-org/upstage/assets/29925961/5c163dad-8895-4134-8831-ee045647f78b">

**Comment by helenvarley** [comment]
i agree, the primary colours is too much - please keep all the buttons and toggles green.
the background colours as i'm seeing in dev-app at the moment are much better - more subtle but still clear. however it would be great to have some input from @elisadcg and @vickis on this. 
regarding the background colours: previously blue was associated with the media management. green feels good for the stages. & i think we had a yellow for the admin section. (i'm not a big fan of the pink colour that's on the admin section background on dev-app)

**Comment by helenvarley** [comment]
i've just checked the above list, & ticked the ones that are done. of the two remaining things, one is now a separate issue (#1143). 
the remaining one is VERY important as there are still links here to the now non-existent Backstage.

**Comment by teddyfullstack** [comment]
I've finished the easier one (#1143) 😅 I've split the other VERY important one into a new issue (#1194) since this issue is already too long and hard to track what needs to be done!

**Comment by vickis** [comment]
awesome work @Teddy - colours looking good
however when having a look (testing) I found a bug in the profile link I have submitted an issue #1201 <https://github.com/upstage-org/upstage/issues/1201> but at this stage just assigned Helen and I until you have space for this :)


20 Nov 2023, 07:34 by ***@***.***:
