### ISSUE TITLE
"Enter" button on Stages list doesn't work

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1084]
When you are in the Stages list (https://upstage.live/studio/) and click on "Enter", it does not open the stage. It reloads the Stages list but with no stages showing.

You can enter a stage by first going to Manage Stage, then clicking Enter - but this opens the stage within the Studio frame. At the moment we cannot think why this would be necessary - especially as at the moment if you then navigate to Media for example, the stage minimises to be in the bottom half of the screen with the Media list in the top half - and there is then no way to return to the full stage.

It would be much better if the Enter button opened the stage in a new tab, so that you have the Studio still open in a separate tab if you want to do something, and you remain in the live stage in another tab.

**Comment by helenvarley** [comment]
this is same as #1094, this issue was tested on upstage.live and the other one tested on dev-app

**Comment by teddyfullstack** [comment]
PR #1106 fixed this issue, but it's not yet live on `upstage.live`. I'll close this issue when it be there 👌

**Comment by gloriajw** [comment]
That teddy bear is adorable. I've never seen that at the 7/11s we have here.

**Comment by teddyfullstack** [comment]
Yeah they were special gifts, not for sale 😎

**Comment by gloriajw** [comment]
Awww 8)

**Comment by helenvarley** [comment]
> All of this will be live when we merge Modelo. I am not sure if people want to do that now or not. If so, let me know and we can start a new release branch.

vicki & i should test these things on dev-app before they are rolled out to upstage.live. i will have a look now & if they're on dev-app i can test :)

**Comment by helenvarley** [comment]
great - just tried this on dev-app & it worked - the Enter button on the stages list opens the stage in a new window :+1: +1

**Comment by teddyfullstack** [comment]
Yay 🥳
