### ISSUE TITLE
missing media items?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1086]
since the recent update (AnchorSteam) there seem to be some missing images.

In the Stages list, many stages do not show a thumbnail preview image. this is often because no cover image has been set (in which case there should be a default thumbnail image - or perhaps this is not actually necessary? it's come from the Media list layout, where the preview image is helpful, but we did not have this previously for stages). 

However some of these stages definitely did have cover images and these have disappeared.
@vickis  can you please add more info here? at the moment i can't tell if any media is actually missing, or if it is only because there is now a thumbnail & not all stages have a cover image. but you said that your holodeck stage had a cover image, yes?

**Comment by teddyfullstack** [comment]
Hopefully, the issue was not carried over to the new Studio 😅

**Comment by vickis** [comment]
i have uploaded an image - there may not have been one ....
but its working now anyway :)
thanks for all your work devs!!
