### ISSUE TITLE
urgent - blank foyer, cannot log in, cannot access backstage

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1087]
today the foyer at https://upstage.live/ is blank - there is no title, no description, no top navigation, no tiles showing stages.
i tried to log in, but this just refreshed the login window.
i tried on both firefox and chrome, same blank foyer.
on firefox i had been already logged in so i tried going directly to the studio, & got a security error. - there must be an expired certificate
![Screenshot from 2023-04-19 17:41:27](https://user-images.githubusercontent.com/3437324/232977399-58eaad2a-4e24-45b1-8a28-359263c70dfc.png)
![Screenshot from 2023-04-19 17:43:09](https://user-images.githubusercontent.com/3437324/232977741-59fc28b9-db59-4959-a75d-81495d5dc1d4.png)

**Comment by helenvarley** [comment]
also stages are not accessible. maybe it's just a matter of renewing the security certificates & all will be well??? :crossed_fingers:

**Comment by vickis** [comment]
hope it is just the certificate - refinery.upstage.live working as expected
:)

**Comment by gloriajw** [comment]
It's fixed. Looks like the server did some auto-update, and broke certbot.
I uninstalled and reinstalled it, and it's fine now.
For posterity:
pip3 uninstall certbot certbot-nginx acme
apt install --reinstall python3-certbot-nginx python3-acme python3-certbot
certbot

**Comment by gloriajw** [comment]
The full problem and solution:

An unexpected error occurred:
ModuleNotFoundError: No module named 'acme.magic_typing'

pip3 uninstall certbot certbot-nginx acme
apt install --reinstall python3-certbot-nginx python3-acme python3-certbot
certbot

**Comment by vickis** [comment]
Super thanks Gloria! :D
