### ISSUE TITLE
jitsi individual streams not working??

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1088]
i am unable to make the individual jitsi streams work on upstage.live ( UpStage v2.0.3 - AnchorSteam-2.0.3)

in firefox, i can see my webcam in the toolbar and drag it onto the stage, but nothing happens when i click on the lightbulb. the image remains black and white, and doesn't show up if i view the stage from another browser. the X icon to remove the object from the stage also doesn't work, nor does the "Remove" option in the context menu. i'm also not able to remove it from the stage using the Depth toolbar.

in Chromium, i don't even see my webcam in the Meeting toolbar. there's a brief flash when i open the toolbar, then it only shows the New Room icon.

@vickis can you please check and see whether this is also the case for you?

**Comment by helenvarley** [comment]
aaahhh - it's working now! i swept the stage :smile: 

@vickis please do still check streams as much as possible, to be sure they will do what you want on the weekend ...

**Comment by vickis** [comment]
yes tested and working :)

**Comment by helenvarley** [comment]
i just briefly saw & heard you :)

**Comment by vickis** [comment]
ooo :)
