### ISSUE TITLE
Modelo-2.0.4 - visibility toggle in stages list inaccessible

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1092]
the visibility toggle in the stages list is greyed out and not possible to change. this is the case for stages owned by me as well as other stages (as admin i should be able to change this for others' stages)
when i change it by going to a stage's management interface, the change shows as changed on that interface, and the stage no longer appears on the foyer page, but it is still greyed out in the stages list.
![Screenshot from 2023-05-22 15:29:39](https://github.com/upstage-org/upstage/assets/3437324/8c970093-b5a7-4f8f-837d-1232217868ed)

**Comment by teddyfullstack** [comment]
The synchronisation of stage status changes between the stage table and the (old) stage management would be part of #1083! At the moment, you should update the stage status directly on the table to get a better UX. Thank you 🙏

**Comment by vickis** [comment]
thanks!

**Comment by helenvarley** [comment]
:+1:

**Comment by helenvarley** [comment]
this appears to work properly now 😄

**Comment by vickis** [comment]
:) thanks team
