### ISSUE TITLE
Modelo-2.0.4 - "enter" button in stages list does not work

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1094]
the "Enter" button in the stages list does not work. it keeps the studio navigation and "opens" a blank window within that.
it would be better to open the stage in a new tab.

**Comment by helenvarley** [comment]
same as #1084 - which was on upstage.live. this issue is from testing on dev-app

**Comment by teddyfullstack** [comment]
PR #1106 fixed this issue 😅
