### ISSUE TITLE
Modelo-2.0.4 - layout of each section's navigation

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1096]
the Media and Stages sections have the "Studio" layout with search / filter tools at the top and no section title or colour to remind you which section you are in; the Profile and Admin sections have the old "Backstage" layout, with a different coloured banner and a title (although in the Profile section the title says "Update Information" which is not really right).
in Profile and Admin there is no UpStage logo anywhere (previously this was in the top navigation strip)

there should be a consistent layout for each section, that includes the title, the UpStage logo, a colour ...

**Comment by helenvarley** [comment]
note: the 5-icon left-hand navigation strip is not so great on mobiles as it takes quite a bit of screen real-estate for what could perhaps be incorporated in the top strip

**Comment by elisadcg** [comment]
You mean horizontally ?

**Comment by elisadcg** [comment]
Yes on Mobile it's quite awful
![mobile-studio](https://github.com/upstage-org/upstage/assets/7611913/a50419ef-fffc-4e5b-a101-624f5bae1117)

**Comment by helenvarley** [comment]
personally i find it really difficult to do much at all in UpStage on a mobile :rofl: 
we probably should prioritise the things that are actually useful to be able to do via mobile (eg send a stream, upload a file, watch without the chat getting in the way)
let's keep this issue for the desktop version, & think separately about a mobile interface? (i recall ages ago gloria suggesting an app for mobiles, & we thinking that it works in a browser so why not just use a browser on a mobile, but maybe an app is a better solution) (but a whole other project!)

**Comment by teddyfullstack** [comment]
As explained in #1083, we will transfer each section in the old interface to the newer/more consistent equivalent in the Studio. And the mobile layout will be discussed in #1114 👌
