### ISSUE TITLE
Modelo-2.0.4 - stages should always open in full window

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1097]
having a stage open within the frame of studio navigation does not really work - we need as much screen space as possible to be able to work comfortably in the live stage.
especially on mobiles, the studio navigation takes up too much space.
it's much easier to have the studio and live stage open in separate tabs.

**Comment by vickis** [comment]
yes definitely

**Comment by elisadcg** [comment]
Yes agree

**Comment by helenvarley** [comment]
this is not yet fixed - when i'm in the Stage Management interface for a stage, & click on the Enter button, it is still opening in the same window & within the stage management navigation interface. it should open in a new window.

i think the only time a stage should NOT open a new window, is when you click on its button in the Foyer page. then it should open in the same browser window, in the full window.

**Comment by teddyfullstack** [comment]
Sorry, I forgot that we also have another entrance to the live stage from stage management. PR #1108 fixed it 😅

**Comment by gloriajw** [comment]
Should we get rid of the duplication so you don't have to maintain both entrypoints, and sets of code? It sounds like it's confusing for users and devs.

**Comment by teddyfullstack** [comment]
I think these entry points are necessary to take a user to the live stage from wherever location they are in our backstage/studio. Besides, removing the entry point would not reduce that much code 😅

**Comment by gloriajw** [comment]
OK, all good then.

**Comment by helenvarley** [comment]
yes it is necessary to have all these entry points, sorry! & there is one more ... :rofl: 
in the Media section, you can click on the stage in the Stages column (stages that a media item is assigned to) & currently it opens the stage in the same window - full screen which is good, but it's not a new window. now that we have the other entry points (from the Stages list and from Stage Management interface) opening in a new window, it would be consistent to have this one also open in a new window ...

**Comment by helenvarley** [comment]
:+1:
