### ISSUE TITLE
can we use OBS with jitsi?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1099]
previously with RTMP streams, we could use software such as OBS to do a lot of things with our streams, including streaming in video from links like youtube.
it doesn't seem possible to do this with the individual jitsi feature. 
but it would be a very useful thing to be able to do, for a lot of artistic reasons. is it possible to use OBS with jitsi?

**Comment by gloriajw** [comment]
Not sure, but we will find out. If not, maybe we can support RTMP again now that we have a new dev ramping up.
We need to weigh the support time and energy to do this. The constant inconsistencies with streaming that demanded a lot of time and energy is something that caused dev burnout here, so we have to make this decision carefully.

**Comment by vickis** [comment]
agree :)

**Comment by helenvarley** [comment]
YES WE CAN - latest version of OBS has the "Virtual Camera" feature & it's very easy to use. so closing this issue :slightly_smiling_face:
