### ISSUE TITLE
Modelo-2.0.4 - archiving function not working properly

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1103]
After our meeting today I wanted to save the chat; so i went to stage management and to the archive section, and clicked "Download All Audience Chat". the resulting file is completely empty, yet there is a lot of chat there on stage.
i copied and pasted the chat to a text document to be safe, then clicked Archive Performance. now the file i download from the archive listing for that performance does indeed have the chat in it, and the stage has been swept.

i then remembered that we have the possibility to download the chat from the stage, so i tried this - but again this file was blank.

Maybe we should remove the "Download All Audience Chat" and "Download All Player Chat" from the Archive section of Stage Management? and make the function work properly on stage??
At the moment it is a bit confusing.

**Comment by vickis** [comment]
agree it might be a useful fix
the download audience and player chat was to help in the devising process
(but we are able to copy and paste... :)

if  :"and the stage has been swept

i then remembered that we have the possibility to download the chat from
the stage, so i tried this - but again this file was blank."

then shouldn't the chat file indeed be blank ...

**Comment by helenvarley** [comment]
well obviously i put some chat in there before trying the download from the stage :laughing:

**Comment by helenvarley** [comment]
closing this as i think it has been resolved.
