### ISSUE TITLE
Icons on Studio

### ISSUE THREAD

**Issue by elisadcg** [upstage-org/upstage#1104]
As the Admin page is only player management, what about change the icon : 
![admin-icon](https://github.com/upstage-org/upstage/assets/7611913/ad4d2045-0756-4fd0-856e-deac80281a19)

**Comment by elisadcg** [comment]
Anothers
![all-icons](https://github.com/upstage-org/upstage/assets/7611913/fad50d05-6ebb-4058-8602-1dc158c4aba1)

**Comment by helenvarley** [comment]
nice ideas!  :smile: 
i think the manual & admin ones are good & clear. the stages one is clear when you are already familiar with UpStage, but maybe not so easy for newbies?

since this menu is so small, is there a better place for it than on the left where it ends up leaving a long empty strip below it? or does it make sense to be there ... ?

**Comment by vickis** [comment]
Agree icons could be alongside menu items (text) along top
That way would be super clear
Chat image is UpStage logo icon also so sensible connection to stages (and
especially if clarified by text :)
Nice work!

**Comment by teddyfullstack** [comment]
It would be more convienence and consistent if we could use the icon here: https://ant.design/components/icon
Here are the icons that matched Elisa's suggestion the most, although they're not exactly the same:

<img width="927" alt="Screenshot 2023-12-06 at 22 37 02" src="https://github.com/upstage-org/upstage/assets/29925961/13680d58-ca08-4819-8fad-da8369089d4b">
<img width="929" alt="Screenshot 2023-12-06 at 22 37 53" src="https://github.com/upstage-org/upstage/assets/29925961/d7f30ef1-f05f-45c1-aa0d-d307370ad710">
<img width="926" alt="Screenshot 2023-12-06 at 22 38 37" src="https://github.com/upstage-org/upstage/assets/29925961/2f7df734-29c3-45f5-8f10-8999a3ec75e9">

**Comment by elisadcg** [comment]
I agree the log off button is "PoweroffOutlined" 
 and what do you think about these proposal from Teddy, Helen ?
There a good match !

**Comment by helenvarley** [comment]
great, i see them all on dev-app now. everything is good except:

-  i'm not sure about the speech bubble one for the stages list ... :thinking: maybe the "comment" one would be better? 
![Screenshot from 2023-12-09 17:08:14](https://github.com/upstage-org/upstage/assets/3437324/96bede8d-22fd-40eb-addd-ef95797ce71f)

- and i'm really not liking the pink in the admin section; can we try a pale blue?

by the way: are the ant design icons copyright free / creative commons? i'm assuming it is ok for us to use these icons, but i had a bit of a look on the website & didn't find anything saying that they are free to use ... just checking!

**Comment by teddyfullstack** [comment]
Here you go 👇 

<img width="272" alt="Screenshot 2023-12-10 at 22 13 55" src="https://github.com/upstage-org/upstage/assets/29925961/4b04c8f4-6370-4b5c-a1c4-b76ca6434e14">

About the icons' copyright free, Ant Design icons are licensed under the MIT License and free to use for both personal and commercial purposes. You can check their license here: https://github.com/ant-design/ant-design-icons/blob/master/LICENSE or here: https://www.figma.com/community/plugin/1199123469451512066/ant-design-icon-set-by-iconduck

**Comment by helenvarley** [comment]
looks great! :pray:
