### ISSUE TITLE
unable to unassign media from a stage via the Stage Management interface

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1118]
If i try to unassign media from a stage by going to the Media section of Stage Management, it does not work.
when i roll the cursor over a media item that i want to delete, it goes red and has the minus sign on it, but clicking achieves nothing.

@gloriajw  - not sure who to assign this to, i don't want to disturb the devs if they are focussed on anything else. but it would be good to get this fixed as it's confusing for newbies. they can unassign media through the Media section, but we still need this part of Stage Management as it's here where they can see the total file size of the stage & manage that if it's getting too big. it would be perhaps more useful to show the file sizes of individual media items here rather than the thumbnails, which take ages to load & aren't so necessary.

**Comment by teddyfullstack** [comment]
I was focused on the streaming issues, but those would need some help from the Jitsi devs. I'm back to this now, as part of the #1083 👌

**Comment by vickis** [comment]
🙏

**Comment by helenvarley** [comment]
this is still an issue. it also takes a really long time for the interface to load.
we can of course unassign individual media items from the Media interface of the Studio, but the Stage Management section is where we can see the total file size of a stage, & get a clear overview of what media is there or not. so it's a very useful feature.

**Comment by helenvarley** [comment]
now working on dev-app :sunglasses:
