### ISSUE TITLE
version footer has disappeared from Studio interfaces

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1124]
i just noticed that the version footer has disappeared from the Studio interfaces (formerly it was displayed at the bottom of every interface in the Backstage).
it's on the Foyer, but it would be useful to have it on the Studio interfaces as well.

**Comment by teddyfullstack** [comment]
I noticed it took up a lot of space, so I moved it to the navigation dropdown 😅 

<img width="1439" alt="Screenshot 2023-09-04 at 19 12 33" src="https://github.com/upstage-org/upstage/assets/29925961/7c9f04aa-0c1d-46b0-9107-03be5e81b8e7">

Do you think it's fine to be there, or we should put it back?

**Comment by vickis** [comment]
Hmm makes sense for it to not be taking screen realestate
It is (good for elements to  be tidy and consistent

So I am happy with that :)
What are your thoughts @elisa

**Comment by helenvarley** [comment]
ah. hmm. it doesn't really take up much space on the computer screen, but i suppose it would be more of an issue on a phone or tablet.
i'm happy for it to be in a different place, but i don't think the dropdown menu is a very intuitive place for it to be. most people wouldn't look for it there (i don't think?) & it's a little confusing as it looks like it should be another link to somewhere.
would it work to have it immediately under the logo and language switcher, where there is a bit of space, so that it shows all the time?

**Comment by teddyfullstack** [comment]
I've put it below the language switcher 👌 

<img width="441" alt="Screenshot 2023-09-16 at 00 44 28" src="https://github.com/upstage-org/upstage/assets/29925961/26229732-e3d1-40f7-9b23-12cddae202b9">

**Comment by vickis** [comment]
super solution :)
