### ISSUE TITLE
Unable to batch create new user from admin

### ISSUE THREAD

**Issue by vickis** [upstage-org/upstage#1125]
when trying to make a new user for a demo I get the following message 
<img width="1254" alt="BatchUserIssue" src="https://github.com/upstage-org/upstage/assets/4249450/13372b94-0220-4a9d-a7df-6ff1163bbec2">

**Comment by gloriajw** [comment]
Can you try changing the email address and see if it succeeds?

**Comment by vickis** [comment]
In the batch creation there is no field for inputting emails

[image: image.png]

**Comment by gloriajw** [comment]
Ah, ok.

**Comment by gloriajw** [comment]
Please retest this on dev-app1. If it works, I'll port this to prod.

**Comment by vickis** [comment]
I am not able to login on https://dev-app1.upstage.live/
It appears to be not loading correctly (UpStage v2.0.3 - Modelo-2.0.4) is
the version I am getting - I have tried in chrome and firefox ...

**Comment by gloriajw** [comment]
Please retry, it was down. Sorry about that.

**Comment by vickis** [comment]
ok now it is telling me my account requires approving ....

**Comment by gloriajw** [comment]
Yeah, someone changed how the core auth works, and this is very confusing
to me. Please hold

**Comment by gloriajw** [comment]
Please retry.

**Comment by gloriajw** [comment]
Fixing, psl hold

**Comment by vickis** [comment]
nope sorry still getting this
[image: image.png]

**Comment by gloriajw** [comment]
pls retry

**Comment by gloriajw** [comment]
Found this code in two places, fixed. Pls retry.

**Comment by gloriajw** [comment]
This is a bit of a mess, I was not expecting this. I need to speak with the
other devs.

**Comment by gloriajw** [comment]
I see your login failing, and I'm not sure why this is happening. That code
was restored. Please send me a screenshot of the error you are seeing

**Comment by vickis** [comment]
Sorry I am getting the same needs approval message

**Comment by gloriajw** [comment]
Screenshot pls

**Comment by vickis** [comment]
[image: image.png]
this is the message I receive ...

**Comment by gloriajw** [comment]
Did your login succeed at all? Are you able to go to the studio?

**Comment by vickis** [comment]
Sorry no have not been able to enter
can go to studio (direct URL but when try to do anything am redirected to
login (and again the needs approval message - see no error message as I am
not backstage

**Comment by gloriajw** [comment]
ok, let me find out why. This code seems very broken to me. Please stop testing for now.

**Comment by helenvarley** [comment]
hi, i've just logged into dev-app and saw vicki's player account was not active so i have changed the status & it is now active.
i didn't have any problem getting in - & have been in & out several times in recent days without problem. (using firefox on linux).

**Comment by gloriajw** [comment]
OK, Please retest the batch feature.

**Comment by vickis** [comment]
Thanks! It is working now as expected :)
both adding the stage after and adding email

**Comment by gloriajw** [comment]
Excellent, thank you.
