### ISSUE TITLE
upload limit not actually working on dev-app

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1130]
the upload limit is not working again. i reduced my limit down to 2 MB and then attempted to upload a 29 MB file. the system allowed me to do this.

it should have come up with a message saying: "Your upload limit is 2 MB. The file you are trying to upload is too big. Please choose a smaller file."

**Comment by helenvarley** [comment]
continuing the discussion from #1003 - i just tested again on dev-app, & with my upload limit set to 2 MB i was able to upload a 3.6 MB file. i didn't get any messaage about the file being too big, it just uploaded and was there in my media list.

**Comment by teddyfullstack** [comment]
The file you're uploading, is it a video? I can see from the code that we have a special rule for video to bypass the limit. I've just tried uploading images > 2Mb (which is my upload limit), and it was blocked 🤔 

<img width="373" alt="Screenshot 2023-09-19 at 09 43 53" src="https://github.com/upstage-org/upstage/assets/29925961/719aca16-a1fd-4436-9985-d452c10449d3">

**Comment by vickis** [comment]
great! :)

**Comment by vickis** [comment]
just tested and this is also the case with me (upload limit 1mb)
[image: image.png]

**Comment by teddyfullstack** [comment]
It looks like your attachment didn't work, @vickis  😅 

<img width="420" alt="Screenshot 2023-09-20 at 22 34 39" src="https://github.com/upstage-org/upstage/assets/29925961/b337905d-9d89-4aac-a5a2-b09adc2d9105">

**Comment by vickis** [comment]
Oh well it was just a confirmation that my upload limit worked too
Thanks for sorting that 🙏🙌🌻

**Comment by helenvarley** [comment]
> The file you're uploading, is it a video? I can see from the code that we have a special rule for video to bypass the limit. I've just tried uploading images > 2Mb (which is my upload limit), and it was blocked 🤔
> <img alt="Screenshot 2023-09-19 at 09 43 53" width="373" src="https://user-images.githubusercontent.com/29925961/268825785-719aca16-a1fd-4436-9985-d452c10449d3.png">

you are so right! very silly of me - i was just lazy in looking for a big file :blush: as all the images etc i have for UpStage are already reduced down ... now i tried with a 4.5MB image & indeed i got the message telling me my upload limit is 2MB etc. so this is working now :smile:
