### ISSUE TITLE
link back to old interface

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1133]
from the Studio, if i click on my username at the top right to access my profile, it takes me back to the old Backstage interface.
it would be better if it just opens the pop-up window, as you get from Player Management in the Admin section if you click on a player's Profile button.
this could also be what you get when you click on the Profile icon in the left-hand menu.

**Comment by vickis** [comment]
Sounds useful - also is there any way to find all old interface links and
redirect?

**Comment by teddyfullstack** [comment]
> this could also be what you get when you click on the Profile icon in the left-hand menu.

Yes, and that page will also be rebuilt into the Studio like the former option 👌

**Comment by helenvarley** [comment]
i wonder if it's enough to have it as the pop-up? does it need to have its own page? @elisadcg @vickis do you have any thoughts about the profile - page versus pop-up?

**Comment by vickis** [comment]
i guess the only issue is the browser blocking pop-ups because they are
mostly ads ....
otherwise its fine with me :)

**Comment by helenvarley** [comment]
ah true. it works in the Admin section though. @elisadcg any usability thoughts on that?

**Comment by helenvarley** [comment]
reopening this because the link to profile from the top right of the Studio navigation still opens the old interface (https://dev-app1.upstage.live/studio/legacy/backstage/profile/information) as opposed to the pop-up profile window. the old interface includes navigation breadcrumbs that link back to the old interfaces.
i think the profile should just open as the pop-up - otherwise it's confusing to have the same information in two different formats. 
if people have pop-ups blocked they won't have been able to log in in the first place, as the log-in window is also a pop-up. so i think it's fine to have the profile everywhere as a pop-up window.
