### ISSUE TITLE
change name of "Batch user creation"

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1140]
the section and menu name "Batch User Creation" doesn't fit with the rest of the labels & is not very intuitive for those who are not developers. we refer to users as "players" so it would make more sense to call this "Add New Players", especially as it is also right after "Player Management". i think this will be more understandable.

**Comment by vickis** [comment]
Agree makes sense to change text :)

**Comment by teddyfullstack** [comment]
The text was changed, but we don't need the menu entry for this anymore since it is now part of the `Player Management` section. More details on #1139
