### ISSUE TITLE
link in new player approval email needs to be updated

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1142]
the link in the email sent to support for approving new players needs to be updated - it goes to the old interface (https://upstage.live/backstage/admin/player-management).
the new interface actually doesn't give a direct url to the player management interface. is it possible to do that?

**Comment by webdev604** [comment]
hi @helenvarley I updated with `/studio/admin/player` and deployed to dev server. please test

**Comment by helenvarley** [comment]
great, the link works :slightly_smiling_face: 

however, the default display of the players list shows (i think) the last logged in players, so the new registration isn't visible. i have to sort by last registered to find it. this isn't necessarily a bad thing, but it's a bit confusing when the email tells me to click on the link to approve the user, but when i click on the link i don't see the user waiting for approval ... can we improve this somehow??

**Comment by webdev604** [comment]
hi @helenvarley I resolved by adding a query param like `studio/admin/player?sortByCreated=true`. please test.

**Comment by helenvarley** [comment]
great! the link worked - it took me to the player management list sorted with most recent registration at the top so i could easily see who needed to be approved. thank you! :pray:
