### ISSUE TITLE
URLs of Manual & Studio

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1143]
i've just noticed that when i access the manual from within the Studio, it no longer has its own url, it just has https://upstage.live/studio/ on all pages. this is also the case for all interfaces within the Studio - there are no individual urls any more. it can be useful sometimes to give players a direct url when we are trying to explain something, for example where to find the stage management tools for their stage.

& it's particularly a problem for the manual, as often we want to direct players to a specific section of the manual. someone emails us with a problem, and we reply that they can find the solution here in the manual. i realise that we can give them a direct url by going first to docs.upstage.live/ and then finding the section, but it's a bit confusing that we don't have these same urls when we're accessing the manual within the Studio.

also, when i go to docs.upstage.live/ i get the Studio navigation on the left, and when i click on these links, the url remains docs.upstage.live/

is it possible to have the manual links going to docs.upstage.live/?

**Comment by vickis** [comment]
Yes agree navigation breadcrumbs are important :)

**Comment by helenvarley** [comment]
great work :+1:

**Comment by teddyfullstack** [comment]
Each section in Studio now has its own "copyable" url now. For example:
- https://dev-app1.upstage.live/studio/media will take you to the Media management
- https://dev-app1.upstage.live/studio/stages will take you to the Stages management

I don't quite get this:
> to have the manual links going to docs.upstage.live/

What exactly should be changed 🤔 Here is the current deep link to the Studio/Manual section: https://dev-app1.upstage.live/studio/legacy/https://docs.upstage.live/

**Comment by helenvarley** [comment]
this is great, to have the copyable urls for the different sections of the studio :+1: 

it's the same for the manual. at the moment in dev-app, when i click on the link to the manual, the manual opens within the studio (i.e. the navigation is still there on the left) and the url is https://dev-app1.upstage.live/studio/legacy/https://docs.upstage.live/ no matter which page or section of the manual you are in.

in fact it would be better if all links to the manual opened https://docs.upstage.live in a new window, which would show all the internal urls for the manual (which is good if you want to refer someone to a particular page) and also means that you still have the studio open in another window so you can follow instructions from the manual.

**Comment by helenvarley** [comment]
hi, manual link in the studio is still going to https://dev-app1.upstage.live/studio/legacy/https://docs.upstage.live/ - can it please go to https://docs.upstage.live and open in a new window?
