### ISSUE TITLE
add captcha to registration

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1151]
for the last couple of weeks we've been inundated with spam registrations on upstage.live. please add a captcha to reduce this.

**Comment by teddyfullstack** [comment]
Done. Let me know if you would like to change the message when a suspicious request is detected to something else 👇 

<img width="218" alt="Screenshot 2023-12-16 at 18 39 58" src="https://github.com/upstage-org/upstage/assets/29925961/0f802a65-9c17-4ced-a1a5-7b8dcca4f75e">

**Comment by gloriajw** [comment]
This looks good to me, thank you!

**Comment by gloriajw** [comment]
Please merge this into main yourself. It is urgent, and I will be in
transit all day today. Thank you!

**Comment by helenvarley** [comment]
hah - maybe it would be a bit kinder to say "We think you are not a human!" because i'm sure sometimes humans fail captcha tests ... ?

**Comment by helenvarley** [comment]
this has been done & the flood of spam has completely dried up 😎
