### ISSUE TITLE
UpStage Live Terms & Conditions

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1152]
I've created T&Cs for UpStage Live (until now the T&Cs link on the registration form has gone to the GPL which isn't relevant to artist-users of UpStage).
the new T&Cs are here:https://upstage.org.nz/?page_id=9622
and link to this privacy policy: https://upstage.org.nz/?page_id=9606 and our code of conduct: https://upstage.org.nz/?page_id=8361#conduct

in Admin > System Configuration i changed the link for the T&Cs to the new one & saved it.
but it doesn't work - now if i click on T&Cs from the registration form, it's just loading & loading & loading & loading ...

**Comment by Hnguyn911** [comment]
I see issues #1152 & #1156 have the same problem, so I merge them into new issue **"UpStage - Terms & Conditions #1180"**
So can we close the issue and just focus on issue #1180

**Comment by helenvarley** [comment]
correct, this has been fixed - i think i accidentally made multiple issues for it :flushed:
