### ISSUE TITLE
message when changing a player's role

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1154]
when i start to change a player's role, i get a message popping up asking if i'm sure i want to do this, and saying that changing a player's role is irreversible. this is not correct - we can easily change the player's role again.
please delete that second sentence and just leave it with the question "Are you sure you want to change [name]'s role?"
![Screenshot from 2023-11-18 19:27:33](https://github.com/upstage-org/upstage/assets/3437324/1ea78abd-aa50-40a5-b831-64ea305ca17e)

**Comment by webdev604** [comment]
hi @helenvarley it was already fixed. please check.
https://prnt.sc/dyUDMy1PsJjX

**Comment by helenvarley** [comment]
great, thank you! :pray:
