### ISSUE TITLE
terms & conditions

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1156]
Currently the Terms & Conditions link is going to the GNU GPL, which is irrelevant for players registering an account.
Please make the default link for the T&Cs go to https://upstage.org.nz/?page_id=9622

**Comment by helenvarley** [comment]
i updated the link in the system configuration interface on dev-app, to the new link (https://upstage.org.nz/?page_id=9622) but this doesn't work - when i click on the T&Cs link in the login screen, it just buffers and doesn't load the page ...

**Comment by Hnguyn911** [comment]
I see issues #1152 & #1156 have the same problem, so I merge them into new issue **"UpStage - Terms & Conditions #1180"**
So can we close the issue and just focus on issue #1180

**Comment by helenvarley** [comment]
sorry - probably my fault! i get carried away making new issues and sometimes forget that i already made one :flushed:
