### ISSUE TITLE
Default email subject prefix

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1157]
Currently the default email subject prefix is "DEV-APP1" 
it would be better if this was simply "UpStage" & then admins of other instances can change it.
![Screenshot from 2023-11-18 20:28:01](https://github.com/upstage-org/upstage/assets/3437324/3594e266-ecba-43be-80af-4e887d2ab7af)

**Comment by gloriajw** [comment]
It has been done. What do you mean subjects?

**Comment by helenvarley** [comment]
yes it is configurable, which is great :+1:  it was only to change the default from "DEV-APP1" to "UpStage", so that in future if there are instances where no-one realises or gets around to changing it, it's not an odd subject line. 
i'll close this issue :slightly_smiling_face:

**Comment by gloriajw** [comment]
For reference:
These parameters are in the DB under a table called "config" (not a good naming convention, and these really should be in the back end settings config file instead):

upstage_dev=# select * from config;
 id |         name         |                                value                                 |         created_on         
----+----------------------+----------------------------------------------------------------------+----------------------------
  3 | FOYER_DESCRIPTION    | Welcome to your new UpStage! Log in to get started.                  | 2021-12-09 11:17:30.868433
  5 | MANUAL               | https://docs.upstage.live                                            | 2022-03-07 04:22:08.763362
  2 | FOYER_TITLE          | Dev-App1                                                             | 2021-12-09 11:17:23.345738
  7 | SHOW_REGISTRATION    | true                                                                 | 2022-06-08 15:20:36.058718
  8 | ENABLE_DONATE        | true                                                                 | 2022-09-12 19:22:02.204009
  6 | EMAIL_SUBJECT_PREFIX | Upstage                                                              | 2022-04-19 15:19:42.871325
  1 | TERMS_OF_SERVICE     | https://upstage.org.nz/?page_id=9622                                 | 2021-04-12 11:28:14.391788
  4 | FOYER_MENU           | UpStage User Manual (https://docs.upstage.live/)                    +| 2021-12-09 11:17:36.905413
    |                      | Customise Foyer (/studio/legacy/backstage/admin/foyer-customisation)+| 
    |                      | More                                                                +| 
    |                      | > FAQ (https://upstage.org.nz/?page_id=115)                         +| 
    |                      | > Contact (/contact)                                                 | 
(8 rows)

**Comment by helenvarley** [comment]
should this also be where the admin email can be set? (#1145 )

**Comment by teddyfullstack** [comment]
> these really should be in the back end settings config file instead

I'm afraid the backend settings config file is suitable for read-only config, while (most) the settings above have to be writable so that admins can update them in the future!

> should this also be where the admin email can be set?

Which admin email are we talking about? 😅 Do we already have a separate issue for that?

**Comment by helenvarley** [comment]
> > should this also be where the admin email can be set?
> 
> Which admin email are we talking about? 😅 Do we already have a separate issue for that?

i'm talking about the admins of hosted instances, for example the mur.at one - we really don't want to be getting all their account registration emails, & they probably want to be able to send email from the email notifications system that has their email address as sender. but yes there is a separate issue for this, #1145 :slightly_smiling_face:
