### ISSUE TITLE
slight change to new registration approval email text

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1167]
today someone who registered on upstage.live (a genuine one this time) replied to the "your registration is awaiting approval"  email they received saying "No idea how to approve this" - so it seems they thought that they needed to do something more to approve the account themselves.

a slight change to the wording of the email would make it clearer. the current text reads: "We are glad that you're here! Your account has been created and waiting for approval! You will receive an email once your account has been approved. "

suggested change: "We are glad that you're here! Your account has been created and waiting for approval by an UpStage Admin. You will receive an email once your account has been approved."

**Comment by teddyfullstack** [comment]
I replaced the text and rolled it out on dev-app1. However, on upstage.live, we have to wait until Newcastle-2.0.5 got merged to release this!

**Comment by helenvarley** [comment]
i will try & do a thorough check through everything on dev-app over the weekend :+1:

**Comment by helenvarley** [comment]
sorry but there are quite a lot of things - still lots of links back to old Backstage! i'm updating issues and adding the priority tag, & will try to re-order in the Project columns ...

**Comment by helenvarley** [comment]
pretty sure this has been done so closing
