### ISSUE TITLE
no Demo stage on dev-app?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1169]
i don't find the Demo stage on dev-app since the last update.
there should always be the Demo stage, with the default media, and all approved players having access to it.

**Comment by Hnguyn911** [comment]
Hi @helenvarley, 
I saw the Demo Stage on dev-app (lastest update). So can we close the issue?

**Comment by helenvarley** [comment]
yes we can. but we need to make sure that whenever there is an update or new installation, that the Demo stage and default media for it are there. i think @teddyfullstack was running a script to do this - could it be automated? or somehow ensured that it is always done? :slightly_smiling_face:

**Comment by teddyfullstack** [comment]
> could it be automated

At this point, new installations or updates are being done manually, so the script must also be executed by hand. Only when we setup automation installation or updates (CI/CD or dockerise it) can we put the script in one of the automation tasks.

**Comment by helenvarley** [comment]
great, thank you for the explanation :smile: i will try to remember to be patient!
