### ISSUE TITLE
Create New Stage & Manage Stage goes to old interface

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1170]
I clicked on the New Stage button & found myself in the old interface, with the legacy url. creating the stage worked, but after i saved it was returned to a completely blank stages list, as if there were no stages at all. i clicked on Stages in the left-hand menu, & instead of showing my stages, i got all the stages.

![Screenshot from 2023-12-01 11:28:32](https://github.com/upstage-org/upstage/assets/3437324/b3cdda68-9124-450b-8358-f65113823a6f)

**Comment by helenvarley** [comment]
and this also happens when i click on Manage in the Stages list:
![Screenshot from 2023-12-01 11:37:05](https://github.com/upstage-org/upstage/assets/3437324/3e37acee-a40d-49f5-b74c-d87f92f5eec3)

**Comment by helenvarley** [comment]
this is connected to #1194 - presumably once the new Studio interface is applied to these pages the legacy urls will go?

**Comment by helenvarley** [comment]
i've tested and it works to create a stage, i was returned to the Stages list.
however "legacy/backstage" is still showing in the url - shouldn't this be tidied up?

also when the stage was created, i got this message: "Stage created successfully! ID: U3RhZ2U6MTMz"
i guess that is the code name for the stage, but it's a little confusing for a user who doesn't need to know that & has given their stage a meaningful name. is there a reason for including this ID in the success message?

**Comment by gloriajw** [comment]
@webdev604 will clean this up. Thanks for testing.

**Comment by webdev604** [comment]
hi @helenvarley 
I migrated Create New Stage & Manage Stage to new url in studio. please test on dev

**Comment by helenvarley** [comment]
looks good! i created a new stage successfully & see the updated urls, also when clicking on the Manage button in the Stages list. :+1:
