### ISSUE TITLE
unable to make stream or video round/oval

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1172]
jitsi streaming is working on dev-app (great!) but i'm unable to change the shape of the video to round/oval. this is a feature that we use a lot. the other options in the context menu seem to be working.
![Peek 2023-12-01 11-47](https://github.com/upstage-org/upstage/assets/3437324/b5f2c436-503f-405d-8070-98247efc9bf9)

**Comment by helenvarley** [comment]
weirdly, i just observed that when i removed the stream from the stage, it became oval as it disappeared!
![Peek 2023-12-01 11-51](https://github.com/upstage-org/upstage/assets/3437324/241b0029-2b16-4003-8a91-997042c5ab5e)

**Comment by Hnguyn911** [comment]
I have checked this issue. No problems at all, the  feature still working normally
So can we close the issue?
![as](https://github.com/upstage-org/upstage/assets/104263124/e51ca8cf-0a0d-4ae5-b333-be3a6d1e7187)

**Comment by helenvarley** [comment]
great, it's also working for me too now! closing this issue :sunglasses:
