### ISSUE TITLE
admin navigation goes to foyer

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1178]
in dev-app, apart from player management, the admin links just open the foyer within the studio. (maybe this is because teddy is working on it at the moment??)

![Peek 2023-12-09 17-13](https://github.com/upstage-org/upstage/assets/3437324/c76182cb-e43e-4a04-a0ae-800268e179a1)

**Comment by teddyfullstack** [comment]
> maybe this is because teddy is working on it at the moment??

Yes, sorry about that 😅

**Comment by gloriajw** [comment]
Teddy, please don't work further on Upstage until you have us review your changes. Wu is now also working on Upstage, and this is going to get messy.

**Comment by teddyfullstack** [comment]
Got this, Gloria! I closed this issue because it was resolved.

**Comment by gloriajw** [comment]
Thank you
