### ISSUE TITLE
UpStage - Terms & Conditions

### ISSUE THREAD

**Issue by Hnguyn911** [upstage-org/upstage#1180]
- T&Cs from the registration form don't work when click, just loading-loading- loading
- Make the default link for the T&Cs go to https://upstage.org.nz/?page_id=9622 
![Capture1](https://github.com/upstage-org/upstage/assets/104263124/0d2bac63-6ba2-4733-aa5e-cfacc2fcbc7c)

**Comment by helenvarley** [comment]
this is quite an important one; can it please be fixed before Red Horse is rolled to live?

**Comment by teddyfullstack** [comment]
We previously used markdown for ToS like [this url](https://github.com/upstage-org/documentation/blob/master/User%20Manual/introduction.md). 

However, the link currently in use is a webpage, so I change the code to use iframe instead. The downside of this approach is the full navigation of the original link will be displayed like below 👇 

<img width="1430" alt="Screenshot 2024-02-18 at 16 42 52" src="https://github.com/upstage-org/upstage/assets/29925961/dd5681a7-881f-4360-a831-394da2e1126f">

**Comment by helenvarley** [comment]
ah i see. but this is better than it not working at all, & for future instances belonging to other organisations it will be how it has to be - for example, when we set it up for QMU, i imagine that they will need to provide their own T&Cs link.

we could make a separate page on the UpStage website that has less navigation etc. but i think this is fine for now :+1:

**Comment by helenvarley** [comment]
reopening this as the default terms & conditions link in the QMU instance is again going to a non-existant link.
(it's working on dev-app & upstage-live, but this is because it's been manually changed).

please use https://upstage.org.nz/?page_id=9622

**Comment by helenvarley** [comment]
just tested on the new QMU instance and the link is still going to a non-existent page. please update it in the code to https://upstage.org.nz/?page_id=9622
