### ISSUE TITLE
Foyer Customisation, Email Notifications and System Configuration in Studio

### ISSUE THREAD

**Issue by teddyfullstack** [upstage-org/upstage#1194]
Admin section: only the Player Management interface has the new design; the other three interfaces in this section (Foyer Customisation, Email Notifications and System Configuration) all still have the old design and breadcrumb links to the old Backstage.

**Comment by helenvarley** [comment]
hi, this is all looking great! but as usual a couple of questions 😜 

- in email notifications, it seems that we now have to individually set each recipient to BCC, is that correct? there are already 98 players on upstage.live (excluding guests) so this would mean having to individually click 98 toggles to send BCC to all ... if it has to be an individual toggle then it might be better to have BCC as the default, & individual toggle to make it To ?
- it's great to be able to select by role 🙂 is it possible to select more than one role? for example, what i most often want to do is send to everyone apart from guests; so i would need to select player, admin & super admin. now, if i select player and move them to the recipient lists, then try to select Admin to add them, it removes the players from the recipient list.
- good idea to group the Foyer Customisation in with the System Configuration - for a moment i thought we'd lost the Foyer customisation 😆

**Comment by helenvarley** [comment]
previously in the Foyer Customisation for the Menu, there was a hint provided to help people get the links correctly formatted. could this be included in the new layout?
previously it was a rollover by the field name, but actually there is plenty of space here - it could even be text on the page?


![Image](https://github.com/upstage-org/upstage/assets/3437324/fd7fb731-8fb7-4f53-ac8b-aa675506e27b)

**Comment by helenvarley** [comment]
thanks @teddyfullstack for the clarification about selecting multiple roles to email too 👍 
my first point was about the individual BCC toggle; can the default be to send BCC? then we don't have to manually turn 98+ toggles ... 😆  we should not ever want to send to all players with their email addresses all in the To field.

**Comment by teddyfullstack** [comment]
> can the default be to send BCC

It surely can! 😎
