### ISSUE TITLE
unexpected double navigation

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1197]
not sure if this is a bug or not, & i'm guessing that it won't be a repeatable, but i'm documenting it just in case it happens again. so not assigning it to anyone apart from gloria & vicki, just in case something similar happens in the future.

after a browser restart when i went to the tab that i had dev-app open in, & got a message saying something like my token had expired, please log in again. so i did, & then i got double side navigation and a url with legacy/backstage in it - see screengrab:
![Screenshot from 2023-12-27 18:24:35](https://github.com/upstage-org/upstage/assets/3437324/3dab8991-8866-4c3c-b407-70ed17bad0fa)
i went back to the Foyer, clicked on Studio, and got the same thing.
so i logged out, & was back at the Foyer - but still the left-hand navigation showing and the legacy/backstage url:
![Screenshot from 2023-12-27 18:28:11](https://github.com/upstage-org/upstage/assets/3437324/9849b78b-e08e-4aa0-b932-2e2af7a36d25)
when i clicked on Media or Stages in the left-hand menu, it took me into the Studio, but without a player name showing in the top bar:
![Screenshot from 2023-12-27 18:29:05](https://github.com/upstage-org/upstage/assets/3437324/3a175113-b880-4415-b816-96d470b0337b)
i clicked on "New Stage" & it went back to the Foyer and the login window popped up. 
i clicked on "New Media" & it opened the upload window, but it wouldn't let me upload anything.
i could see the Stages list & Media list, but not do anything.
from the right-hand UpStage logo i could access the Logout so i did this, & then was back at the Foyer,  without the left-hand navigation bar.

**Comment by teddyfullstack** [comment]
This was a bug with the in-progress Email Notification section, which is not relevant anymore!
