### ISSUE TITLE
logged in as player, i can access the full player list and admin interfaces

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1198]
on upstage.mur.at i am logged in as a player, but i can see the Admin interfaces including the whole player list with everyone's emails. this should only be visible and accessible to those who have admin status. 
upstage.mur.at is currently Newcastle-2.0.5, which is also on upstage.live, so i assume it's the same there. 
quite important to fix this! but not sure who to assign to???

**Comment by vickis** [comment]
for Security i would think Gloria?

**Comment by helenvarley** [comment]
this is quite urgent, as today in the workshop everyone could access the admin section, without having the admin role.

**Comment by gloriajw** [comment]
I cannot fix this, and it is almost midnight where @teddyfullstack is.

**Comment by helenvarley** [comment]
sorry, when i said urgent i didn't mean right now! we have finished the workshop for today, & the participants understand that they're not mean to be able to access that part. there aren't many users on the mur instance yet.
but it will be really important to have it fixed before we do the QMU installation. i'm not sure when that will happen but they did say "january" ...

**Comment by gloriajw** [comment]
OK, thanks for the clarification.

**Comment by teddyfullstack** [comment]
Sorry for the late response! I've patched a hotfix for `mur.at`; No players should be able to access the admin section now!👇 

<img width="1438" alt="Screenshot 2024-01-28 at 23 54 40" src="https://github.com/upstage-org/upstage/assets/29925961/3a2a57d0-a3b4-47c7-8b81-f0c86080ba6c">

However, since `mur.at` is running an "in-progress version" of Newcastle-2.0.5 (I remember we did it for a reason), let me know when is the suitable time for us to roll out the completed version of Newcastle-2.0.5 to `mur` 👌

**Comment by helenvarley** [comment]
> However, since `mur.at` is running an "in-progress version" of Newcastle-2.0.5 (I remember we did it for a reason), let me know when is the suitable time for us to roll out the completed version of Newcastle-2.0.5 to `mur` 👌

please do it as soon as is convenient for you. we will have a follow-up session for saturday's workshop, but haven't yet set the date, & it would be good to have it done before then. thank you!

**Comment by teddyfullstack** [comment]
I've rolled it out & things look great on Mur 😎

**Comment by helenvarley** [comment]
:clap: :+1: :pray: 
looking good to me too. thank you!
