### ISSUE TITLE
discrepancy in same versions?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1199]
upstage.mur.at and upstage.live both show that they are running version Studio v2.0.5 - Newcastle-2.0.5, however upstage.live has the new logout link in the right-hand dropdown menu while upstage.mur.at still shows the old Backstage link & no logout.
shouldn't they be the same, if they are both the new version?
 
![Screenshot from 2024-01-04 15:03:05](https://github.com/upstage-org/upstage/assets/3437324/2eea1a25-9725-4a37-ae6d-ad7fdb719ed3)
![Screenshot from 2024-01-04 15:02:50](https://github.com/upstage-org/upstage/assets/3437324/e317675d-67ae-4186-a083-81b0c4fd4e63)

**Comment by teddyfullstack** [comment]
Yes, indeed 🥶 As I reported in #1198, please let me know when you would like to have `mur.at` sync with the completed version of Newcastle-2.0.5 👌

**Comment by gloriajw** [comment]
Please do.

**Comment by teddyfullstack** [comment]
Both `mur.at` and `upstage.live` are running the same completed version of Newcastle-2.0.5! The discrepancy should be gone now 👇 

<img width="1440" alt="Screenshot 2024-01-29 at 21 47 47" src="https://github.com/upstage-org/upstage/assets/29925961/e04eeb14-2c36-4b0b-9998-aef2db7516e2">
