### ISSUE TITLE
unable to send email - error says it's spam

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1202]
today when trying to send an email about the upcoming walkthrough to players on upstage.live via the email notification system, i got the following error:
![Screenshot from 2024-01-18 16:23:45](https://github.com/upstage-org/upstage/assets/3437324/6396581a-a503-4c30-9a8d-1036ff9d323b)
on gloria's advice i checked on a number of spam blacklists, and it came up as green / unlisted on everything apart from  that first search on mxtoolbox.com/.
![Screenshot from 2024-01-18 16:33:24](https://github.com/upstage-org/upstage/assets/3437324/0326c462-aa4d-4139-894b-3456fbcae0e0)
after searching on several other lists (that all showed upstage.live as green/unlisted), i did another search on mxtoolbox.com/ and that didn't show any blacklists any more, but it did show three email problems (see screenshot below). i looked at the "more info" for each one, & it is full of acronyms that mean nothing to me ... apart from DNS. i can't do anything to the DNS via Gandi (where the domain name is registered) because we're using external name servers, & i don't have access to those.
it would be good if we can fix these problems, but i wonder if that is really what's causing the problem in UpStage? because the domain name doesn't seem to actually be blacklisted on any spam services.
i last sent out email from upstage.live shortly before our 20th birthday party on 9th january, & as far as i know it went successfully (the message said it was sent, & i received it as well as others).
![Screenshot from 2024-01-18 16:37:09](https://github.com/upstage-org/upstage/assets/3437324/994b86f7-c64b-4955-a0ae-c611e8b6341c)
![Screenshot from 2024-01-18 16:42:58](https://github.com/upstage-org/upstage/assets/3437324/d054330b-e5cb-4bb3-a0d3-cadd63b2a912)

**Comment by helenvarley** [comment]
Gandi support answered me, saying "The error message "Reject for policy reason. RULE3_2" means that your message was flagged as spam by our automatic filters." They want me to save a draft of the email i'm trying to send and forward it to them, but i can't do this within the UpStage system. i tried logging in to Gandi's webmail, but the password i have doesn't work & i don't want to change it in case that causes another problem in our system ... so i've answered Gandi & await their next response.

**Comment by helenvarley** [comment]
not sure what this is, vicki - did you also try sending from the email notification system?

**Comment by helenvarley** [comment]
Gandi asked me to try sending again and save the original message in .eml format - which as far as i know, i can't do from our system. i did a number of tests, including sending a test message just to me & vicki, & this was sent successfully & i received it. i also tried sending the message that failed to myself only as a test, & this still got the spam error - which is pretty weird as there's nothing i can see in the text that could be classified as spam! it's just an announcement about the open walkthrough in february :thinking: 

@gloriajw is there any way that we can get a .eml file out of our system?? (just in case but i'm guessing not)

**Comment by helenvarley** [comment]
i tried to send the walkthrough announcement again today, after pondering a lot on what could be different about it since i successfully sent the announcement about the birthday party via the email notification system three weeks ago. i took out the tinyurl link, which was a shortening of the time converter link, & instead put a link to the event on upstage.org.nz where the time converter is, thinking that maybe the tinyurl was triggering the spam alert - but it still did not work.

last week Gandi sent a list of steps which i forwarded to @gloriajw as it involves things i don't have the access to do; hopefully you got that gloria? & can have a go at the steps.

**Comment by helenvarley** [comment]
next update: last week i managed to successfully send the email to 98 players on upstage.live by removing all the hyperlinks from the body of the email. obviously, we should be able to send hyperlinks, & have done as recently as 3 weeks ago. gloria has also made some improvements on our server side to the DNS.

gandi asked me to send a test email to https://www.mail-tester.com, our score was 6.4 out of 10, with very few things that really could be a problem.  i'll share the results with gloria & see if there is anything else she can do from her end.

**Comment by helenvarley** [comment]
update: i haven't heard back further from Gandi, but today i tried sending a similar email, a reminder about the walkthrough and request for feedback, which includes hyperlinks. & it just worked! so i'm going to close this issue for now, since we have enough else to worry about :rofl:

**Comment by vickis** [comment]
awesome! :)
