### ISSUE TITLE
error message - permissions system

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1204]
the permissions system is not working properly. when i clicked on the "acknowledge" button of a media item that another player had set to "use with acknowledgement", i got the following error message:
![Screenshot from 2024-01-27 17-04-42_crop](https://github.com/upstage-org/upstage/assets/3437324/6d7471aa-bccb-4b64-b097-75234612bcc5)
and the button did not change or allow me to use the media item. i had to reload the browser window to keep working.

**Comment by helenvarley** [comment]
this is not fixed yet

**Comment by webdev604** [comment]
@helenvarley it's fixed. please test
