### ISSUE TITLE
manual - link from Studio should open manual in new window

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1206]
the link to the manual from the left-hand naviation bar in the Studio should open the manual in a new window rather than within the Studio interface.
this is because we often want to give direct urls to a specific section of the manual, & when it opens within the Studio there aren't page-specific urls. 
also just now i needed to make a correction in the manual, & could not go easily to the wp-admin editing interface.

it's not a huge or urgent problem, but a small detail that will make things easier for us :slightly_smiling_face:

**Comment by vickis** [comment]
yes great idea :)

5 Feb 2024, 22:51 by ***@***.***:

**Comment by helenvarley** [comment]
this has been done
