### ISSUE TITLE
registration doesn't work?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1208]
hi, i am trying to do a test registration, mainly to check that the welcome email text has been updated (#1167) but it seems not to work. when i click "Register", nothing happens, & i have not received any welcome email.
![Peek 2024-02-08 17-18](https://github.com/upstage-org/upstage/assets/3437324/a61528b9-502e-4594-8524-b32116116598)

**Comment by helenvarley** [comment]
note: 8 days ago annie registered, so it was working then

**Comment by teddyfullstack** [comment]
Which instance and browser are you using, Helen? I cannot reproduce this issue on Chrome & upstage.live 🤔

**Comment by helenvarley** [comment]
i've just tried again and it worked, so it must have been a temporary glitch - sorry! closing the issue :slightly_smiling_face: 
(i was on upstage.live and using firefox on linux.)
