### ISSUE TITLE
top navigation bar in all Admin sections

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1224]
please can the top navigation bar be there in all Studio interfaces. currently it is missing from two of the Admin interfaces - Email Notification and Configuration.
in these interfaces there doesn't need to be any "new" button or filter tools, but it would still be helpful to have the info & navigation at the right-hand end of the top bar  as shown:
![Screenshot from 2024-03-04 17:27:04](https://github.com/upstage-org/upstage/assets/3437324/efea2649-da76-4aaf-b035-54b6f1843335)

**Comment by gloriajw** [comment]
@helenvarley please test this on upstage.live
It's going to be easier to reserve dev-app1 for Wu's testing, so we'll do this going forward (when upstage.live is not being used for a performance).

**Comment by helenvarley** [comment]
great, yes it's there now, thank you!
