### ISSUE TITLE
interface translations 

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1233]
elisa has done the spanish & portuguese interface transltions, & i've uploaded these files into the code (il8n directory) - es.js and pt.js - but they aren't yet appearing in the interface. can you do the magic to make them appear? :slightly_smiling_face: 

as i've had to transfer these translations, as well as the german & swedish, to the .js files, i've noticed that there's still quite a lot missing - things that weren't in the en.js file. i can see when i look at the interface and change the language that there are lots of things not translated.

what's the most efficient way to do this - shall i just make a list of all the things i'm finding for the translators then add them in to the files that i've uploaded?

**Comment by gloriajw** [comment]
Yes. It's best if we only deal with the fines at the end of the process.

**Comment by helenvarley** [comment]
i'm making a list of all the missing words & phrases that still need to be translated, & it seems that some already are translated, but are not showing up. for example, in French, "Manage" is translated in the .js file as "Gestion", and "Enter" as "Entrée", & this is showing correctly in the Stage Management interface, however in the Stages list the words are still displayed in English:

![Screenshot from 2024-04-05 11:02:59](https://github.com/upstage-org/upstage/assets/3437324/abcf3072-d582-46c5-94ff-98611dcd32c7)
![Screenshot from 2024-04-05 11:00:52](https://github.com/upstage-org/upstage/assets/3437324/d1bfd6bb-297e-4175-a4fd-71d0e13eef63)

do the translations need to be repeated multiple times for each place where the same words (e.g. "Enter") are used in different interfaces? if so, i'll need to have the code string for each one ...

**Comment by helenvarley** [comment]
and here i found a mixture of english & french, in the Archive section of Stage Management:
![Screenshot from 2024-04-05 11:32:24](https://github.com/upstage-org/upstage/assets/3437324/179181e1-9529-49c8-be2d-94dbd01be0f4)

**Comment by helenvarley** [comment]
closing this as portuguese & spanish are now on upstage.live (there are still some things missing but we can live with that until such time in the future there are people able to do more translations)
