### ISSUE TITLE
no individual jitsi tool 

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1237]
the individual jitsi thumbnail has disappeared from the toolbar on dev-app:
![Screenshot from 2024-04-03 11:54:39](https://github.com/upstage-org/upstage/assets/3437324/d8d9c8fc-41bb-40d9-9623-5b93a44e8fd4)

**Comment by helenvarley** [comment]
testing using firefox and chromium on linux, & it's not working.
when i click on the Meeting tool, the bar appears at the top and for a brief moment i see half of my player name to the right of the New Room icon, but it disappears before i'm able to do anything.
![Peek 2024-04-18 10-10](https://github.com/upstage-org/upstage/assets/3437324/7e55dfe5-3814-4b78-9185-b12d971c895d)

**Comment by webdev604** [comment]
hi @helenvarley I fixed. please check

**Comment by helenvarley** [comment]
great, i'm seeing the thumbnail now & able to put it onto the stage :smiley: 

one small detail: when i put my mouse over the thumbnail to drag it onto the stage, the cursor turns into a red circle with a line through it, which would normally indicate that i can't do something. i expect to get the pointing finger cursor, which is what i get in other toolbars e.g. avatars.
i tried to take a screenshot of it, but it doesn't show the circle, it shows the ordinary arrow cursor.
maybe it's just something unique to my computer? @vickis can you please try?

**Comment by helenvarley** [comment]
in testing for this one i also discovered that most of the right-click menu options are missing on the jitsi stream window. i've created a separate issue for this, https://github.com/upstage-org/upstage/issues/1259

**Comment by webdev604** [comment]
#1259 is closed.

**Comment by helenvarley** [comment]
here is vicki's screenshot showing the circle. for me it's red. it suggests that the drag & drop feature can't be used (but it can) - should be the pointing finger cursor.

![Image](https://github.com/upstage-org/upstage/assets/3437324/48523cc3-2be9-4eae-a067-019373d1f9da)

**Comment by helenvarley** [comment]
closing this issue as the original problem has been fixed and i've made a new issue for the remaining problem which isn't so serious (but would be good to fix as it's confusing)

**Comment by helenvarley** [comment]
re-opening this as it's happening again - also on upstage.live and qmu.upstage.live :(

**Comment by webdev604** [comment]
hi @helenvarley can you please test again? I switched to new stream server.

**Comment by helenvarley** [comment]
this is happening again: in firefox the individual jitsi tool appeared, i was asked to allow my webcam, and then the thumbnail disappeared - this happened on both upstage.live and dev-app.
so i tried on chromium, and there i didn't even get asked to share my cam or see the thumbnail even briefly :frowning_face:

**Comment by helenvarley** [comment]
tested today & it's working so closing this issue again.

**Comment by vickis** [comment]
<img width="715" alt="image" src="https://github.com/user-attachments/assets/b4a4e9da-35f5-45bf-a4b2-5c0f7958581f">



<img width="823" alt="image" src="https://github.com/user-attachments/assets/03f452af-2acd-4c2f-8047-04e3f23175e4">


<img width="1280" alt="image" src="https://github.com/user-attachments/assets/3a1597cd-1ae8-43a3-9172-b5573c87bf4b">

**Comment by vickis** [comment]
as above - when trying to test i noticed that in firefox i am getting the individual jitsi window and meeting
which seems (based on feedback) to be working 

however on chrome i am seeing the window for individual jitsi but do not have the option in the chrome browser

**Comment by helenvarley** [comment]
did you have both browsers open at the same time? i think when this happened to me the other day, it was solved by closing firefox, which i think means that the computer didn't handle sharing the one webcam between two applications. we can test this again today.

**Comment by helenvarley** [comment]
this is still an issue, however we have agreed that we can't make everything work on every browser & there are now multiple issues with firefox. so i'll close it for now.
