### ISSUE TITLE
new account registration not working

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1246]
i just tried to register a new account, but when i click on "register", the registration form doesn't disappear. 
i haven't received an email saying there's a new account, and when i log in as admin i don't find the new account in the player list. so it seems that the account registration isn't working.

**Comment by helenvarley** [comment]
great! i created a test account & it worked :slightly_smiling_face: 

as a test, i tried clicking "register" without ticking the T&Cs, & a message came up at the top telling me to agree to the "Terms of Servce" - can this please be changed to read "Please agree to the Terms & Conditions", as that is what it's called on the page, not terms of service.

![Screenshot from 2024-04-10 16-55-27](https://github.com/upstage-org/upstage/assets/3437324/de543f34-70f6-40f4-8408-e6831ed0dbb0)

**Comment by webdev604** [comment]
@helenvarley it's fixed. please check

**Comment by helenvarley** [comment]
perfect! :pray:
