### ISSUE TITLE
typo in message

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1248]
there is a typo in the message that shows when there are no replay recordings for a stage.
"reocrd" should be "records" - "no records match your criteria"

actually it's not really the correct message, as it isn't possible to search or filter the archived performances; so the message should really say "No replay recordings have been saved for this stage yet."

![Screenshot from 2024-04-12 14:54:31](https://github.com/upstage-org/upstage/assets/3437324/c352e7d2-0ecf-4907-8a96-13e9b2dc62b8)

**Comment by webdev604** [comment]
@helenvarley fixed. please check

**Comment by helenvarley** [comment]
wow! i think you get the gold star for fastest closing of an issue :sunglasses: :star2:
