### ISSUE TITLE
words missing in message text

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1249]
there are words missing from the pop-up warning message when you click to delete a media item from the media list. 
it should be: "Are you sure you want to delete this media?"
 
![Screenshot from 2024-04-12 15:13:28](https://github.com/upstage-org/upstage/assets/3437324/ab6f28ac-acda-4330-87a8-dec633b0f2c0)

**Comment by webdev604** [comment]
@helenvarley fixed. please check

**Comment by helenvarley** [comment]
amazing work! :smile:
