### ISSUE TITLE
rollover tooltips missing in live stage toolbar

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1250]
on dev-app, the rollover tooltips are not there anymore on the left-hand toolbar.

first screen capture is dev-app, second is upstage.live (how we want it):

![Peek 2024-04-12 15-33](https://github.com/upstage-org/upstage/assets/3437324/b24e3e10-81a0-440e-919a-0bb2f14f4b29)
![Peek 2024-04-12 15-32](https://github.com/upstage-org/upstage/assets/3437324/06723551-728d-4704-9a55-745bef694ebb)

**Comment by webdev604** [comment]
hi @helenvarley it should work now. please test

**Comment by helenvarley** [comment]
thank you! :slightly_smiling_face:
