### ISSUE TITLE
correction to warning message for removing media via the Depth toolbar

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1251]
please update the message when you use the Depth toolbar to take media items off stage.

It should read: "Are you sure you want to take this object off the stage?"
(at the moment it says "out of" instead of "off")

and please remove the checkbox and the line "Don't allow dev-app1.upstage.live to prompt you again" - i think it's good to always have this prompt.

![Screenshot from 2024-04-12 15:39:06](https://github.com/upstage-org/upstage/assets/3437324/4017c7fa-47ea-4693-bd24-9c68ea407a82)

**Comment by webdev604** [comment]
![image](https://github.com/upstage-org/upstage/assets/35217708/940d4eef-141a-4ca6-9744-4fcb1ebfbca5)
hi @helenvarley I can't see the checkbox on my side. what browser are you testing with? and MacOS or Windows?

**Comment by helenvarley** [comment]
interesting - now i don't see that message! but also the stage is showing as offline ... maybe you're working on it at the moment?
![Screenshot from 2024-04-12 17:25:08](https://github.com/upstage-org/upstage/assets/3437324/3cca2018-1ae5-4243-b659-45d02590ef69)

**Comment by webdev604** [comment]
hi @helenvarley it's fixed. please test

**Comment by helenvarley** [comment]
thank you! :slightly_smiling_face:
