### ISSUE TITLE
link in permission approved email is broken 

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1255]
i just checked the link in the permission approved email for wuplayer's request for permission to use auroraOhau.jpg, & it got me to the "stage not found" page instead of to the Studio.
the link in the email is https://dev-app1.upstage.live/studio so i don't know why it isn't going there ... :thinking: 
![Screenshot from 2024-04-15 10:52:53](https://github.com/upstage-org/upstage/assets/3437324/9040e83e-8ab2-4717-80a7-0996e566dec3)

**Comment by webdev604** [comment]
hi @gloriajw  can you update this url to https://dev-app1.upstage.live/stages in email template? I couldn't find this part in backend.

**Comment by gloriajw** [comment]
@webdev604 I fixed this in the Sapporo branch. Feel free to merge and restart dev-app1

**Comment by webdev604** [comment]
hi @helenvarley I pulled and restarted. please test

**Comment by helenvarley** [comment]
ok, now the link takes me to the Stages list, & i see the notification in the top bar & can click there to approve.
thanks! i'll close this issue :+1:
