### ISSUE TITLE
jitsi stream - most of right-click menu options missing

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1259]
with the individual jitsi stream, most of the right-click menu options are not there any more.

![Screenshot from 2024-04-25 10:58:44](https://github.com/upstage-org/upstage/assets/3437324/5e3651bb-6987-47b4-aa6d-22684076f4d3)

this is what there should be:

![Screenshot from 2024-04-25 10:59:12](https://github.com/upstage-org/upstage/assets/3437324/6419cc14-769b-4a3c-9d5e-c11439a1a82a)

**Comment by webdev604** [comment]
hi @helenvarley  it's fixed. please test

**Comment by helenvarley** [comment]
thank you :slightly_smiling_face:
