### ISSUE TITLE
multiframe avatar - strange proportions issue

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1260]
on dev-app, i noticed that my multiframe helen avatar was not behaving the same as it does on upstage.live - the size of each of the images was changing a lot more. 

i had a look and saw that the frames were in a different order on dev-app & upstage.live, so i changed them to be in the same order - but it is still different. you can see that on upstage.live, apart from the two seated poses and the one with my arms out, the standing figures are all more or less the same size and filling the frame. on dev-app, the frame is very long and thin, and some of the avatars fill it to the top but not all.

this is not a huge issue as probably we should take care to make each frame of a multiframe av or prop the same size anyway, but i'm curious about the different behaviour from dev-app to upstage.live ... what is the frame size based on? i thought it must be the first image, however when i changed the one on dev-app to also have the crouching pose first, the frame remained tall and thin. this is most noticeable with the standing poses that turn to the left and right.

the first one is upstage.live, second one is dev-app:

![Peek 2024-05-06 20-41](https://github.com/upstage-org/upstage/assets/3437324/87071e5f-4f2e-4594-980d-ddb773db2b34)
![Peek 2024-05-06 20-40](https://github.com/upstage-org/upstage/assets/3437324/955609bc-e008-4474-9d91-edf4ac7afeca)

**Comment by vickis** [comment]
perhaps try making the arms out the fist image (as this is the biggest width required)

**Comment by helenvarley** [comment]
we should of course take care to make each frame the same or similar size if we want the images to be the same, but the issue is that it is behaving differently on dev-app and on upstage.live. i made the frames be in the same order on both, but it still behaved differently. on upstage.live it starts with the frame proportions of the first image, but on dev-app it starts with frame proportions that are taller and thinner.

**Comment by helenvarley** [comment]
i just checked if this has been fixed, and curiously - it hasn't; however, the issue is only happening on dev-app. i tried re-uploading the frames as a new avatar, with the sitting one first, but it still has this tall thin frame.

it's a bit weird that it behaves differently on dev-app to upstage.live, isn't it?  i guess if it's behaving the way we want on upstage.live then we don't need to worry about it right now, but it's something that vicki & i should check with every update ...

**Comment by helenvarley** [comment]
can this please be looked into? it's important that we can understand what is happening, to avoid a lot of lost time remaking avatars because they behave differently from one version of UpStage to another.

**Comment by helenvarley** [comment]
i'm going to close this as it only seems to be affecting my avatar.
