### ISSUE TITLE
server error when trying to create a new stage

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1266]
clicking on "New Stage" returns a server error, with the old "legacy" url:

![Peek 2024-05-12 13-39](https://github.com/upstage-org/upstage/assets/3437324/df5b3ed7-e1af-4b1a-833a-c831ec03e6f5)

**Comment by webdev604** [comment]
hi @helenvarley it should work now. please test

**Comment by helenvarley** [comment]
working :sunglasses:
