### ISSUE TITLE
problems with creating a new stage

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1267]
i just created a stage called test-helen, but i cannot add media items to it from the Media list because it isn't showing up in the media edit interface. i am able to add media to it from the stage edit interface.

originally i had just called it test, & when it didn't show up i saw that there were already other stages called test. so i went to the edit interface for the stage & changed the name to test-helen, & saved it. the stage showed up in the Stages list as test-helen, but when i went back to its edit interface, it was just called test again.

![Screenshot from 2024-05-12 14:48:02](https://github.com/upstage-org/upstage/assets/3437324/7ebf92dd-2189-4ea6-9900-996f247dc082)

**Comment by webdev604** [comment]
hi @helenvarley  fixed. please test

**Comment by helenvarley** [comment]
great, seems to be working as expected now :slightly_smiling_face:
