### ISSUE TITLE
cover image for stage - upload new image option has disappeared

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1269]
when i'm in the stage management interface for a stage and want to upload a new image for the cover image, there used to be a button to upload a new image in that interface. it's not there anymore.

the workaround is to upload the image in the Studio and then select it in stage management, but it's convenient to have that upload option there, & it used to be there (it's not on dev-app any more either, so i'm not sure when it disappeared).

![Screenshot from 2024-05-13 11:52:25](https://github.com/upstage-org/upstage/assets/3437324/c191e68d-a087-4e6f-9017-fe332185eada)

**Comment by webdev604** [comment]
ok, I restored the function. 
@gloriajw but when upload new image, not sure why the image isn't shown. can you check?
![image](https://github.com/upstage-org/upstage/assets/35217708/281d5fae-20b1-4b1e-91ac-cb72abdf2319)

**Comment by gloriajw** [comment]
Can you show me the link you are getting for the broken image?

**Comment by webdev604** [comment]
@gloriajw https://dev-app1.upstage.live/static/assets/avatar/ddeb5cbc3077444e95b201581f494059.jpg?t=1715961168

**Comment by gloriajw** [comment]
I see the file under core, strangely:
root@dev-app1:/home/upstage/upstage/core/uploads/assets/avatar# ls
9632bf0c423c407495413ed509ab020c.png  ddeb5cbc3077444e95b201581f494059.jpg

I'm not sure why this is happening, but I symlinked this dir to the base upload dir in the upstage home directory:

lrwxrwxrwx 1 upstage upstage 34 May 17 16:16 assets -> /home/upstage/assets_all_releases/
upstage@dev-app1:~/upstage/core/uploads$ cd ..
upstage@dev-app1:~/upstage/core$ cd ../uploads/
upstage@dev-app1:~/upstage/uploads$ ls -l
total 0
lrwxrwxrwx 1 upstage upstage 33 Mar  6  2023 assets -> /home/upstage/assets_all_releases

This should work now.  Please retry.

**Comment by webdev604** [comment]
@gloriajw ok, it works now. thank you
hi @helenvarley this issue is fixed. please test

**Comment by gloriajw** [comment]
I fixed this on upstage.live too. Not sure why this was created.

**Comment by helenvarley** [comment]
great, thanks.
before i close this - it seems like the upload interface is from the old Backstage design? if it can easily be made the same as the current media upload interface this would be good. but this is not urgent, main thing is it's working now.
![Uploading Screenshot from 2024-05-18 09:26:38.png…]()

**Comment by helenvarley** [comment]
actually i will close this, & create a new issue for the updating of the interface
