### ISSUE TITLE
message window doesn't disappear

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1270]
i started uploading a media item then wanted to cancel it, so i clicked on the x to close the window, and got a pop-up message asking if i was sure i wanted to cancel. i said ok, & the media upload/edit interface disappeared, but the pop-up message didn't. i tried clicking elsewhere on the screen, and using the left-hand navigation to reload the page or go to another page, but the message persisted. it only disappeared when i did a shift+reload.

![Peek 2024-05-13 11-56](https://github.com/upstage-org/upstage/assets/3437324/859c6787-7975-4e0e-b78a-42e255fb33ab)

**Comment by webdev604** [comment]
hi @helenvarley fixed. please test

**Comment by helenvarley** [comment]
i tested this on upstage.live and got no message at all ...

**Comment by helenvarley** [comment]
great, the message disappeared as expected :+1:
