### ISSUE TITLE
upload new media item - always have to drag on twice

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1272]
this is something that i've noticed for a long time: when i drag a file to upload a new media item, the first time it does not work. i have to do it a second time, and then it works.
it's not an urgent problem as i think most people will try again if it doesn't work the first time, but there must be some bug in the system because it happens consistently, every time.

@vickis have you noticed this?

**Comment by vickis** [comment]
yes and no - i usually go through the click to upload rather than drag, on testing now Click requires two attempts 
Drag works on first attempt as expected

**Comment by helenvarley** [comment]
interesting - the opposite from what i experienced :laughing: i'll close it since it's not such a big problem.
