### ISSUE TITLE
formatting options in Admin section

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1273]
with the latest updates we have lost a lot of formatting in the Admin section.

[ ] 1. for email text and foyer description, the formatting bar is much more limited than previously, there are no tool-tips so it's sometimes difficult to know what a button will do, and for the links and image insert it doesn't actually do that, there is instead a pop up with instructions how to manually insert images or links. these instructions don't include how to make a text link, e.g. to have the words "UpStage website" as a link to the website, rather than showing the url in the text.
[ ] 2. there is no information about how to edit the Foyer menu; i can follow the format of the existing links, but i wanted to recreate the previous "More" menu that had a dropdown with links to FAQs and Contact, but i don't know how to format that & there is no information to tell me how.
[ ] 3. the Customise Foyer link doesn't work on the Foyer, and in the edit interface i can see it has "backstage" still in the url: Customise Foyer (/backstage/admin/foyer-customisation) (8,32). i can manually correct this url, but it needs to be corrected for future installs.
[ ] 4. presumably the "(8,32)" after this link is something to do with only exposing the link to those with admin status? if that's correct, isn't it a bit dangerous to have this editable?

here's a screengrab of the previous Foyer customisation interface, which was more user-friendly (the email text field also had the same formatting bar) :
![image](https://github.com/upstage-org/upstage/assets/3437324/51c1413c-a6c3-4b76-8b67-d2ebc6003b84)

**Comment by helenvarley** [comment]
by the way, i realised that upstage.mur.at is still running the older version (newcastle-2.0.5) and in this one you can see the better formatting options still. @webdev604 if it would help you to have the comparison, i can give you an admin account for that instance.

**Comment by webdev604** [comment]
hi @helenvarley  ok, please give me an account. thank you

**Comment by helenvarley** [comment]
done - i think you should receive an email, but i've also messaged you in slack

**Comment by helenvarley** [comment]
uploading screenshots of the options that we used to have compared with what we have now:
![Screenshot from 2024-07-17 18:11:08](https://github.com/user-attachments/assets/ec0fa765-5744-4786-a690-7003dd9240c8)
![Screenshot from 2024-07-17 18:10:46](https://github.com/user-attachments/assets/58ba0dd5-5360-4a1e-a10a-4c9ca03f6edf)

**Comment by helenvarley** [comment]
wonderful! thank you :smile: 

before i close this issue i just noticed one thing - now in the email and configuration interfaces the information that is normally over on the right-hand side of the top navigation bar (player name, language switcher, version and UpStage logo) is now on the left. can this be aligned back to the right so that it's consistent with the other Studio interfaces?

https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

**Comment by webdev604** [comment]
hi @helenvarley I fixed and pushed to dev server. please test

**Comment by helenvarley** [comment]
yay - all looking as expected! thank you :smiley:
