### ISSUE TITLE
unable to put video on stage

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1277]
it's not possible to put a video onto the stage. i try to drag the thumbnail from the streams toolbar onto the stage, but nothing happens. 
![Peek 2024-05-17 18-57](https://github.com/upstage-org/upstage/assets/3437324/dd224021-3a32-467c-9cf5-72f8ca28ba63)

**Comment by gloriajw** [comment]
Does this work on dev-app1?

**Comment by helenvarley** [comment]
no

**Comment by helenvarley** [comment]
great - tested on upstage.live and dev-app & it's working (note - i've only tested this by myself, so don't know if the audio is working, but i assume it will be)

**Comment by helenvarley** [comment]
reopening this as i mixed it up with the individual jitsi problem when i was testsing it: this issue is about pre-uploaded video, not live streams. 
it is working on dev-app, but not on upstage.live ...

**Comment by helenvarley** [comment]
fixed! :+1:
