### ISSUE TITLE
default cover image for stages

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1284]
i created a new stage and did not give it a cover image. when i set it to appear on the foyer, i saw that the default image that appears on the foyer as its image is the "Jeux de Massacre" image. 

we need to set an appropriate default image - perhaps just a plain colour? or something with the UpStage logo? but it definitely should not be "Jeux de Massacre" as this was for a specific performance & even has the names of the performers on that image.

it could be something that we are already putting in as the default media on the Demo stage of a new install (see #898) - either the green curtain or the beach backdrop? or maybe it's good to make a specific default image that conveys some information?

@vickis thoughts?

**Comment by helenvarley** [comment]
@webdev604 - please change it to the green curtain image as a quick fix for now, until vicki & i think of something better.

**Comment by vickis** [comment]
Message ID: ***@***.***>Yes I would like the default not to always be my image of the beach lounger ;) 
That was for a specific work 

Making a default be the upstage logo and key details url etc 
would be useful and also push players to create and add their own :)

**Comment by helenvarley** [comment]
i just created a cover image test stage & did not assign a cover image to it, but it is still showing up with the Jeux de Massacre image as a default image ...

**Comment by helenvarley** [comment]
this is now working with the green curtain as the default cover image
