### ISSUE TITLE
stage reset by itself in the middle of rehearsal

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1295]
i'm not sure if this is actually a bug as it's difficult to replicate, but it's happened twice now to john and bianca while rehearsing their "dance plague" performance so i'm opening an issue for us to log information.

what happens is that suddenly all the media is taken off the stage and the background colour resets, as if someone had clicked the archive button or swept the stage, but they did not do that. 

it happened on sunday evening and again on wednesday morning (UK time). the stages are different as due to some other odd problems they made a completely new stage on monday (& that seemed to have solved the other problems).

both times it happened about halfway through playing a video that is 8 minutes & 25 seconds long. john thinks it was more or less in the same place of the same video, however they have played it several other times on the stage without this reset problem happening.

they were copying and pasting text into the audience chat window when it happened, but not using any other on-stage tools.

john was using microsoft edge browser; he will change to chrome & see if it happens again.

**Comment by gloriajw** [comment]
Can you pls try to reproduce this by copy-pasting text into the audience window under the same circumstances?

**Comment by gloriajw** [comment]
Also see if this reset appears in the replay. That will be very valuable information.

**Comment by gloriajw** [comment]
@webdev604 is looking at it now, to see if sweep is being called inadvertently. If we can't find it, we'll turn off sweeping temporarily, and log anything trying to call it. This way we can catch calls to sweep.

**Comment by helenvarley** [comment]
yes it is in the replay recording: https://upstage.live/replay/DPTS2/135 - at ca. 1:41:41 - you can see in scrub bar where the middle part with activity comes to an end.

**Comment by helenvarley** [comment]
> Also see if this reset appears in the replay. That will be very valuable information.

yes it is in the replay recording: https://upstage.live/replay/DPTS2/135 - at ca. 1:41:41 - you can see in scrub bar where the middle part with activity comes to an end.

**Comment by helenvarley** [comment]
i've just assigned the video in question (DP extract 1v2.mp4) to another stage & it played right through without the reset happening.

**Comment by helenvarley** [comment]
note - the video restarted automatically, although in the context menu it is showing as set to no loop (this is probably a separate issue ... we also noticed that sometimes the videos finish, then some random time later start again. but it hasn't been consistent so i haven't yet created an issue for that).

**Comment by webdev604** [comment]
hi @helenvarley if possible, can you share a video? I tested, but I couldn't reproduce.
thank you

**Comment by helenvarley** [comment]
i have to go out now, & also i haven't been able to reproduce it myself when i put the video in question onto another stage. but you can see it happening in the replay recording from this morning's rehearsal (https://upstage.live/replay/DPTS2/135 - at ca. 1:41:41 - you can see in scrub bar where the middle part with activity comes to an end.)

i also just heard from john that he's switched to chrome & so far it hasn't happened again - but as it is visible in the replay recording, which i'm watching in firefox, i don't think it has anything to do with the browser.

john wrote that they had a break from the rehearsal & when they came back, the stage had been swept again - maybe this was something that you did?

**Comment by gloriajw** [comment]
I'm going to turn off sweeping for now, so we can see if this really is the result of sweeping.
I didn't know that the act of sweeping wipes out the stage contents. I thought it only cleared history. This is confusing.

**Comment by gloriajw** [comment]
Actually, yes, stage sweeping clears out events. it doesn't clear content:
`            if events.count() > 0:
                performance = PerformanceModel(stage=stage)
                local_db_session.add(performance)
                local_db_session.flush()

                events.update(
                    {EventModel.performance_id: performance.id},
                    synchronize_session="fetch",
                )
            else:
                raise Exception("The stage is already sweeped!")
`
Are you sure the stage is being swept, or is this just an assumption?

**Comment by gloriajw** [comment]
I found something called DeleteScene, with a note that this is called when a stage is swept. 
I'll turn this off for now on upstage.live, on the back end. If it is being called somewhere, you will see an error, and this will be informative.

**Comment by vickis** [comment]
Awesome :)

**Comment by vickis** [comment]
The situation the other night was just that everything disappeared to a blank stage (while I was in the rehearsal - all the assets remained but the stage had to be set up again (backdrop etc) 

Bianca and John made a new stage to try and see if there was an issue with the stage … in the final rehearsal apart from me experiencing a little lag the stage held together fine 

As I understand the first time it happened for them all the media assets were also gone from the stage (however I notice that while we were trying to work it out John set up a stage invited us to it then was adding media - we did discuss how this might be a complication 


20 Jun 2024 at 05:12 by ***@***.***:

**Comment by vickis** [comment]
Message ID: ***@***.***>we did also get John to rename videos as they had weird file names with multiple dots 

Eg Dance video.6t.mp4  - that may also have helped

**Comment by helenvarley** [comment]
all those things were done before it happened again yesterday morning. they were working on the new stage that was created on monday. that's the replay recording that shows it happening.

sweeping the stage should "tidy up" the stage, removing any visible media from the stage and clearing things like text and drawing. but it should not delete any scenes that have been saved. (according to the manual, which was written from how it was behaving). so it's interesting that that was being called when the stage was swept - i checked all of this when i wrote the manual to make sure i wrote what was happening, & it did not delete the scenes.

@gloriajw the "scrub bar" that i mentioned is the toolbar for the replay recording, that shows how far through the recording you are.

**Comment by helenvarley** [comment]
> Are you sure the stage is being swept, or is this just an assumption? 

it's just an assumption.

**Comment by helenvarley** [comment]
this hasn't happened again since june, so i'm closing this issue for now.
