### ISSUE TITLE
QMU - stages are always blank on entering

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1298]
if i enter a stage on qmu.upstage.live, all i see is the blank green stage - regardless of whether there is any media already on the stage. i don't see anything at all until something is done by a player on the stage, and then i still don't see anything else that was there before such as a background, curtain etc. even if there is a curtain down, and the players raise the curtain, i don't see this.

this is VERY important to fix! it is also not happening on upstage.live or on dev-app. 

i'm testing in both firefox and chromium on linux, it's happening in both browsers.

**Comment by webdev604** [comment]
hi @helenvarley can you share a screenshot? I can't reproduce
![image](https://github.com/upstage-org/upstage/assets/35217708/e786aa3a-c1a4-4486-8ee9-db4c520371e2)

**Comment by helenvarley** [comment]
![Peek 2024-06-25 20-12](https://github.com/upstage-org/upstage/assets/3437324/6eb08f7f-1f58-4297-a183-3212e47647e2)

**Comment by helenvarley** [comment]
when i enter or reload the stage, i should see what was left on it. here, i'm reloading the stage, and the media that was there is no longer there for me on reload - but for everyone else who has not reloaded the stage they will still be seeing it.

![Peek 2024-06-25 20-59](https://github.com/upstage-org/upstage/assets/3437324/06348c52-6c83-4005-a46e-72cbb0577145)

**Comment by webdev604** [comment]
hi @gloriajw did you check init load flow for stage?

**Comment by gloriajw** [comment]
I did not. I was going to go through all of that code until we discovered that it's only broken in QMU. On upstage.live, audience can enter at any time, and it works as expected.

**Comment by helenvarley** [comment]
f.y.i., i'm meeting with bianca & john tomorrow at 10:00 european time to introduce them to their qmu instance, in case that's useful for you to see how it's working when others are on the stage. i'll just explain to them that we know about this bug and are working on it :slightly_smiling_face:

**Comment by helenvarley** [comment]
closing this issue as it's fixed - yay! - apart from webcams not showing if you enter after it's placed on the stage; but this is not just a QMU issue so i'll add comments to the jitsi issue(s).
