### ISSUE TITLE
logging in as player, no link to Studio on Foyer

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1301]
on upstage.live, when i log in with a new account that has player access, i am returned to the Foyer with no Studio link.
normally when i log in with my admin account, it brings me directly into the Stages list of the Studio, and i have a link to the Studio on the Foyer, at the top right next to the logout button.

this is happening in both firefox and chromium, on upstage.live (but it's working as expected on dev-app & qmu).
 
![Peek 2024-07-05 16-45](https://github.com/upstage-org/upstage/assets/3437324/25cda9c7-cdd1-44f8-88a0-9be51d64deb9)

**Comment by helenvarley** [comment]
if i try putting /stages or /media after the url, it still returns me to the Foyer.
It's impossible for me to get into the Studio as a player.

**Comment by vickis** [comment]
Message ID: ***@***.***>Sounds like only audience permissions 
Previously there was a differentiation between being able to interact on a stage and to access studio (eg more
Like an editor not just player on a stage … with the ability to upload media etc 
 
Could these have reverted somehow?

**Comment by helenvarley** [comment]
this was my fault - it defaulted to a guest account. closing this issue & opening a new one for making the default account a player one!
