### ISSUE TITLE
masquerade message in strange place

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1303]
if i masquerade as audience then click the icon to go back to player mode, the masquerading message pops down to the lower right hand corner and stays there until i move the cursor over it.

this is REALLY REALLY MINOR issue - the audience won't see it at all; i'm just noting it here so that at some point it can be tidied up.

![Peek 2024-07-15 12-27](https://github.com/user-attachments/assets/d0babd51-b3cf-4369-a8fc-470264b72a0a)

**Comment by helenvarley** [comment]
great, this appears to be fixed, thank you! :smile: 

before i close it, one thing i noticed: i tested on the Demo stage and also another stage that i'm the owner of, which is set to Rehearsal mode. so when i clicked on the masquerade tool, it actually put me out of the stage to the loading page with the message that the stage is in rehearsal mode. 
this makes sense in that the audience can't enter when it's in rehearsal mode; but it means that when players are rehearsing and want to see how things look to the audience, they can't use the masquerade option. actually we want to use it mostly during rehearsals ... i'm not sure whether this was happening before or not, i can't remember if i'd tried the masquerade mode on a stage in rehearsal mode.

is it possible to have it that when a logged in player wants to masquerade as audience on a stage that's in rehearsal mode, they can do so, and see the stage as the audience will see it?

**Comment by webdev604** [comment]
hi @helenvarley I fixed and pushed to dev server. please test

**Comment by helenvarley** [comment]
great! it's working as expected now, thank you :smiley:
