### ISSUE TITLE
labels of "streams" and "meeting" in on-stage toolbar

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1308]
today annie got confused by the "streams" and "meeting" labels in the left-hand toolbar on the stage. 
this is a legacy issue - "Streams" used to include both RTMP streams, and pre-uploaded video, while "Meeting" is the jitsi tools - both meeting & individual jitsi. but now i see the old RTMP stream buffering icon isn't coming up in the "Streams" toolbar any more, it seems to be only video.

While i would love to have RTMP streams again, it seems like it might make sense to change these roll-over labels - & would i think not be a very difficult thing to do (??). it would be more helpful & logical if the one that currently says "Streams" actually said "Video", and the one that currently says "Meeting" was changed to "Streams". 

is this possible? (it will of course mean we need to update the manual, & also the video tutorial i just made last week ... but it would make more sense ... )

then if/when we have RTMP streams again, this could (hopefully) be included in the same toolbar as the jitsi stream options ... ???

**Comment by vickis** [comment]
I agree video makes more sense than streams 
But Message ID: ***@***.***>I don’t think meeting should change to streams as this is not accurate (it would be better to say live meeting … if needing to change at all 

Consistency would be better than switching imho

**Comment by helenvarley** [comment]
but it isn't only the jitsi meeting tool, it's also the individual webcams; so it is streams ... & definitely more "streams" than what's in the one currently labelled "streams" ... 
i think "meeting" is confusing, when you're looking for a tool that will allow you to send a stream from your webcam.

**Comment by helenvarley** [comment]
this confused eva as well yesterday; i think it would be very helpful to change the names on the toolbar rollover:

Streams > Video

Meeting > Streams

**Comment by helenvarley** [comment]
i've prioritised this issue, as i'm hoping it is something relatively easy to do, & both eva & annie have been getting really confused by it - especially as we talk about "jitsi meetings" and "individual jitsi streams", & they see icons labelled "meeting" & "streams" so keep going to "streams" when i ask them to put on their individual jitsi stream ...

**Comment by helenvarley** [comment]
this is helen (on phone, not logged in). i just tested (on phone) & it looks good. @vickis can you please test on computer?

**Comment by helenvarley** [comment]
reopening this issue as today in dev-app i'm seeing the old labels, "streams" (should be "video") and "meeting" (should be "streams")

**Comment by webdev604** [comment]
ok, fixed. please check

**Comment by helenvarley** [comment]
great, thank you!
