### ISSUE TITLE
video not saved in scene on mur instance

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1311]
on mur.upstage.live, if i save a scene with a video in it, the video is not there when i select the scene.

it's working fine on upstage.live, which is a newer version than on mur.upstage.live, so it's possible that this might be solved with an upgrade.

**Comment by gloriajw** [comment]
mur.at has been updated. Please test.

Note that mur.at still uses our streaming server. if you wish to change this, we need to contact them and ask for a new server, since they host these.

**Comment by helenvarley** [comment]
thanks gloria; however the scene is still not saving the video; we have two almost identical stages, on mur it's https://upstage.mur.at/whatmobliisesyou and on upstage.live it's https://upstage.live/whatmobilisesyou. on both there are scenes saved with the video playing. on upstage.live it works as expected - when i select the scene, the video appears on stage and starts playing. on mur, when i select the scene, it has the backdrop, background colour and a prop, but not the video.

i've also realised that on mur, if the video has been put on the stage and i re-enter, i don't see the video. whereas when i enter the upstage.live stage, the video is there & playing. this is different but perhaps connected to it not being saved in the scene. actually i think this might be the same problem we had on qmu with the stage being blank on entry; however it's only the video that is missing when i enter - now i tried sweeping the stage, recreating the scene, and re-entering the stage - and got a completely blank green stage :frowning_face:

**Comment by helenvarley** [comment]
wait, now it had things on the stage when i entered; but not the video ... backdrop, background colour, avatar and prop are there, but no video.

**Comment by helenvarley** [comment]
it's working now so closing the issue. (i think sweeping the stage helped!)
