### ISSUE TITLE
mur & qmu instances - stages offline in firefox on windows

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1318]
i've observed that on upstage.mur.at and qmu.upstage.live, if i use firefox on a windows pc and enter a stage, it is offline. 
using firefox on windows and entering the same stages, they are live.
when i enter upstage.live stages using firefox on a windows pc, the stages are live, so it seems like the problem is only on these two instances.

does anyone else have access to a windows pc with firefox? if so, please try entering the demo stages on upstage.mur.at and qmu.upstage.live and see if the stages are offline or live.

(tagging paul as well on the off chance that he might have access to more machines???)

**Comment by gloriajw** [comment]
@webdev604 can you please look at this? I don't run windows at all.

**Comment by helenvarley** [comment]
andy's laptop is also windows 11, version 23H2,& it's also the same version of firefox, 129.0.2 :thinking:  
i just checked again, & it's still stages offline in firefox, & immediately live in chrome.

but if it's working in firefox on windows for paul then it can't be that it's a browser issue. could it be something in the settings of firefox? but i've used firefox before on this laptop for testing & it's worked ...

**Comment by gloriajw** [comment]
It could be a settings issue, if you have some javascript functionality turned off.
