### ISSUE TITLE
live text toolbar - strange spacing

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1322]
when i create a new live text object, it sometimes gets strange spacing which makes the toolbar have a vertical scrollbar, and this makes it really difficult to find the text object that you want if you have a few there and one or more has added this space below it.
the space is not there when the text is on the stage, it's only in the toolbar.
there's also a lot of space around the text on the overlay that appears for you to enter the text, which seems kind of random - sometimes the text is in the middle of the stage but other times it's off to the side or higher up or down, i don't know why.

![Peek 2024-08-26 12-45](https://github.com/user-attachments/assets/30640fbb-8c95-4c1f-8b20-36c601007812)

**Comment by webdev604** [comment]
hi @helenvarley  please test on dev server

**Comment by helenvarley** [comment]
great! i tried creating several text objects of different font sizes, and the thumbnails now stay all the same size, fitting into the toolbar and readable. thank you! :pray:
