### ISSUE TITLE
Pycoverage testing, managing test DB for this purpose, other notes.

### ISSUE THREAD

**Issue by gloriajw** [upstage-org/upstage#1329]
Unit tests for each module should be invoked by pycoverage.
Please create and destroy the test DB outside of the test framework, so that each setUp and tearDown is not recreating it.
This implies the need for a control script that does setup, runs all tests under pycoverage, and then does the teardown. 

Please start with the auth system and the current tests you have, and let's see the coverage we're getting.

**Comment by nnguyenquangg** [comment]
```
cp .env.unit_test .env
export $(grep -v '^#' .env | xargs)

export PGPASSWORD=$DATABASE_PASSWORD
psql -h $DATABASE_HOST -p $DATABASE_PORT -U $DATABASE_USER -c "DROP DATABASE IF EXISTS $DATABASE_NAME;"
psql -h $DATABASE_HOST -p $DATABASE_PORT -U $DATABASE_USER -c "CREATE DATABASE $DATABASE_NAME;"
alembic upgrade head
coverage run -m pytest
psql -h $DATABASE_HOST -p $DATABASE_PORT -U $DATABASE_USER -c "DROP DATABASE IF EXISTS $DATABASE_NAME;"

```

@gloriajw  here is the setup when run tests with create and destroy the database

**Comment by nnguyenquangg** [comment]
![image](https://github.com/user-attachments/assets/f9ea41ef-6ebd-447d-827b-60c8801b4096)
Here is the result when I run `coverage report`

**Comment by gloriajw** [comment]
Beautiful! Try to get it as close to 100 as possible. very good.

**Comment by gloriajw** [comment]
> ```
> cp .env.unit_test .env
> export $(grep -v '^#' .env | xargs)
> 
> export PGPASSWORD=$DATABASE_PASSWORD
> psql -h $DATABASE_HOST -p $DATABASE_PORT -U $DATABASE_USER -c "DROP DATABASE IF EXISTS $DATABASE_NAME;"
> psql -h $DATABASE_HOST -p $DATABASE_PORT -U $DATABASE_USER -c "CREATE DATABASE $DATABASE_NAME;"
> alembic upgrade head
> coverage run -m pytest
> psql -h $DATABASE_HOST -p $DATABASE_PORT -U $DATABASE_USER -c "DROP DATABASE IF EXISTS $DATABASE_NAME;"
> ```
> 
> @gloriajw here is the setup when run tests with create and destroy the database

Please use the same backend settings convention for test configuration as we use for standard configuration. Call the test config file test_config.py, place it in the same config dir as the server one, and use it to do this configuration.
The rest looks good!

**Comment by gloriajw** [comment]
Please add pycoverage test results here for the asset code you've completed. Thank you!

**Comment by nnguyenquangg** [comment]
![image](https://github.com/user-attachments/assets/e9702652-6ed4-4920-998e-1b3e320e95ca)
Hi @gloriajw 

Here is the current coverage tests
Next path , I will add coverage test for stage module

**Comment by nnguyenquangg** [comment]
Report 26/09/2024
Hi @gloriajw  Here is the current coverage tests
I'm adding for module and fix for asset module
<img width="1181" alt="image" src="https://github.com/user-attachments/assets/c6e8d42b-8675-4342-ab6a-e80d79340c47">

**Comment by nnguyenquangg** [comment]
Report 27/09/2024

@gloriajw  Here is the current coverage tests 

<img width="1293" alt="image" src="https://github.com/user-attachments/assets/555d34a3-0256-4420-b831-28e691a20987">

**Comment by nnguyenquangg** [comment]
Report 3/10/2024

Writing coverage tests for stages and studio module

**Comment by nnguyenquangg** [comment]
Report 06/10/2024

@gloriajw  Here is the current coverage test result

![image](https://github.com/user-attachments/assets/22340662-6d75-4de2-aab1-e073c7a18d10)

**Comment by nnguyenquangg** [comment]
Report 7/10/2024
Hi @gloriajw  I'm adding pycoverage test for studio module

**Comment by nnguyenquangg** [comment]
<img width="1105" alt="image" src="https://github.com/user-attachments/assets/590180ed-6d58-4306-9c37-fd6635db281a">
Hi @gloriajw 
Report 10/10/2024
Here is the current coverage test result

**Comment by gloriajw** [comment]
I'll close this, trusting that you are still adding new tests to test coverage with all refactored functionality you're bringing over.
