### ISSUE TITLE
QMU instance - showing offline, but sort of live; probably firefox issue

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1338]
the QMU students are showing performances today, things are working at their end. however, from my computer, when i enter the stages, they are showing as offline.
if there is a stream playing, then i am able to see and hear the stream, but when it finishes nothing new happens.
if i enter text in the chat, it doesn't appear.
the chat doesn't move for me, until i reload the stage, and then i see that there has been a whole lot more chat.

so it seems that it is all working as expected at QMU, but for some reason it isn't working for me. i am on a windows laptop, using firefox. 
when i enter stages on upstage.live, they show as live and appear to be working normally.

previously i had also tried with chrome, & everything was offline, but now i've tried again in chrome & the stages are live. so it must be that old firefox issue again???
interesting that when the stage was offline, i could still receive the stream ...

my screenshot: 

![Screenshot 2024-11-28 133252](https://github.com/user-attachments/assets/2cb0a467-876a-401b-8f12-9bbf21e3b93d)

& bianca's video:

https://github.com/user-attachments/assets/07f12c15-1c1e-4c95-b2a5-4c0a3064c14c

**Comment by helenvarley** [comment]
wu has done an update, but it's the same problem: on chrome it's live and i can enter chat. on firefox it's offline and i can't do anything.
![Screenshot 2024-12-01 142218](https://github.com/user-attachments/assets/1d5e0afc-bdf7-4def-a07c-b7fb85bdff61)

**Comment by gloriajw** [comment]
This could be the mqtt support issue we faced before in Firefox. There are
rumors that Firefox is going to be shut down in the next year. I recommend
using brave instead. We should not waste time fixing this.

**Comment by helenvarley** [comment]
closing this issue as it's not experienced by all firefox users, and we cannot support all browsers.
