### ISSUE TITLE
stage edit screen

### ISSUE THREAD

**Issue by vickis** [upstage-org/upstage#18]
As a logged in player, I want to have a single interface for creating and editing a stage that includes all the options available for setting up and customising my stage. I expect features including the ability to delete or clone the stage, edit the stage name and url, select different colours for the stage background and interface, give players permission to perform on and edit the stage, and make the stage public or non-public.

**Comment by helenvarley** [comment]
bringing part of #101 to this issue: the stage edit or manage interface is where you will arrive when clicking on either the "duplicate" or manage " buttons.
- "manage" will allow you to edit the details of this specific stage.
- "duplicate" will create a new stage with all the same details, you will need to give it a new name & then work with it as a new stage.
- there could be a third button alongside duplicate & manage, that would be "delete"
- 
![image](https://user-images.githubusercontent.com/3437324/103203814-136d0a80-48f6-11eb-98ed-23d4f616f740.png)

**Comment by helenvarley** [comment]
once you click on "manage" or "duplicate", the interface needs to allow you to:

- edit the name of the stage (previously there has been also a "short name" from which the stage URL is created - will that be the same?)
- enter a description (previously only for the splash screen that displays while loading - do we need 2 description fields now, one for the foyer display & one for the splash screen?)
- list of media assigned to the stage and ability to add or remove media
- list of users who have player or edit access to the stage, and ability to add or remove players
- ability to clear all text from the chat window
- ability to clear all drawing & effectively "sweep" the stage, i.e. take off any media that has been left there so it is back to its default state (note: this is not about removing media that is assigned to the stage, it's about "tidying" the visible state of the stage; the media is still assigned to and accessible on the stage, just not visibly placed on the stage)
- stage layout: ability to choose if chat window is at left or right of screen, and any other layout options
- colours: ability to choose background colours for stage, chat, and any other areas possible
- stage status: need to discuss, but something like "live", "upcoming" and "rehearsal" - this would determine whether the stage appears in the Foyer for the public to see
- hide from stage list: this would prevent the stage from being listed on the dashboard stage list, so it would be invisible to logged-in players unless they have access to the stage
- ability to delete the stage

some of these things will need separate issues (some might already have them, i will check) and there may be some more things that need to be accessible from here, that relate to new features.

**Comment by helenvarley** [comment]
yay i created a stage! :)
but when i added users, the dropdown menu doesn't let me select more than one user; and then there is no display to see what users there are for the stage. 
plesae also see #15 - we want to be able to say if a player on a stage has permission to edit the stage, or just to play on the stage.

**Comment by nguyenhongphat0** [comment]
Oh right! I thought that was the dropdown to select the "owner" of stage 😅 

I'm thinking about remove that dropdown on create stage, so when we create new stage the "current logged in" user will be the owner of that stage. After that we can change the owner/permissions,... and all other stage attributes at stage edit screen. Is that sound good to you @helenvarley ?

**Comment by helenvarley** [comment]
yes, that sounds good - the person who creates the stage is the owner. then they can select the players who have PLAYER ACCESS to that stage (all other players would enter the stage as audience, even if they are logged in) and from those who have player access, the owner can also give EDIT permissions, meaning those players can also add and remove media and make other changes to the settings of that stage.
note: this might create some further issues as we now have the ability to add media via the stage; need to think about this some more! maybe we just let all players with access to the stage, also be able to add media; but not to alter the settings e.g. adding other players ...

**Comment by vickis** [comment]
Agree :)
once have player access should be able to add media - simplest option which
give permission levels

owner  can creates stage, add players, add media
player - can add media
audience - can view and engage in chat, (might further down the track be
granted other permissions)

**Comment by helenvarley** [comment]
player has access to all on stage tools on the stage they have been given access to

**Comment by nguyenhongphat0** [comment]
Are you sure you are login as a guest Helen 😅 I can see that **helen's stage** and **Mobilise/Demobilise** has **helen** as their owner, and the Access column said that the logged in user is the owner of these stage, which means you are login as Helen 🤐

**Comment by helenvarley** [comment]
definitely logged in as the guest, you can see that in the top navigation there is no "admin" link, plus when i entered the stages other than demo, i did not have the stage tools (which i do, when i'm helen)

**Comment by helenvarley** [comment]
i mean the guest logins, not guest as in audience - guest1, guest2, guest3 etc. i was logged in as guest3 when i took the screengrab, & i had logged in as several different guest numbers to make sure i had changed all the passwords

**Comment by helenvarley** [comment]
ah - maybe it's a caching issue?? i just did a refresh with shift key down, & now i see what i would expect to see:
![Screenshot at 2021-06-14 16-21-08](https://user-images.githubusercontent.com/3437324/121907688-93fcb780-cd2c-11eb-8b0b-4546bf93d7aa.png)

**Comment by nguyenhongphat0** [comment]
Phew~
