### ISSUE TITLE
account avtivation notification

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#227]
one of the testers mentioned that she hasn't received notification that her account had been activated, so was still waiting for that before testing.
is it possible to send an automatic email when the account has been activated?
i'm guessing that we might not have any email / notification system in place yet ?

**Comment by paul-rohrlach** [comment]
It is, yeah.

We need to be careful about how we implement it though.  It's easy to automatically send emails, but it's also easy to have SpamAssassin flag you. 

This likely won't make R1-2021, we'll aim for R2-2021

**Comment by teddyfullstack** [comment]
We had it 🥳
