### ISSUE TITLE
dropdown menus - multiple selection

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#25]
As a player, when I need to select options from a dropdown menu, I expect to be able to select multiple options if appropriate, by holding down the shift or ctrl key.

I also expect to see the available options in a logical order, e.g. alphabetical, numerical, time-based etc. (not a random list).

**Comment by helenvarley** [comment]
it's quite important to order the lists in dropdown menus, as we now have a lot of players so it's easiest to find a name when it's alphabeticalised.
being able to select multiple options in a list will be useful for example if i'm not sure who created a stage or media item, but know that it must be one of a small number of players.

**Comment by elisadcg** [comment]
What it's very useful it's a dropdown menu filter like in e-shop
![Screenshot_20210517_154649](https://user-images.githubusercontent.com/7611913/118498578-784ec300-b726-11eb-81cd-544a7d4e26e2.png)
Is it possible to have it ? in the top of the backstage > media ?
One dropdown menu is type of media, other is user in alphabetical order
another is sorted by chronological, antechronological, stage, owner (and size ???)

**Comment by helenvarley** [comment]
this is how it was in the old UpStage, with a number of dropdown filters that you could set or not:
![media_edit-page](https://user-images.githubusercontent.com/3437324/118638282-f5d20c00-b7d6-11eb-8d5e-cbf9981bf61c.PNG)
