### ISSUE TITLE
voice test doesn't work

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#250]
the voice test on the "upload an avatar" screen doesn't work. it also doesn't work in the preview pop-up from the edit/view media page. the voices do work on stage, so they are there on the server. but the test is really important as you need it to be able to select which voice you want for your avatar.

**Comment by helenvarley** [comment]
this is actually quite important; it's very frustrating not to be able to test the voice in the avatar upload process - especially when the button is there for you to do it, but nothing happens. it always used to work ...

**Comment by AUTUpStageTeam** [comment]
Note: If you test voice and an error shows up it will continue to bug out and will not work unless page is refreshed. (commonly happens after selecting --none-- but also happens with other voices)

"Error 200: Stream not found /admin/test.mp3?voice=....(voice)..&text=..(tested text to say).."

**Comment by helenvarley** [comment]
i can't get the voice test to work at all, in any browser or in any place (avatar upload or the edit interface). all that happens when i click on the "test voice" button is that, after a pause, a "cancel" button appears. i have waited in case it is just taking a long time (it didn't used to take long) but nothing happens at all.

**Comment by helenvarley** [comment]
has anyone looked at this? it really is a big problem, because we have a situation now where many (most??) of the voices do not work on the stage, but without being able to test them using the voice test it is almost impossible to work out what voices actually do still work. (to change the voice on an avatar, reload the stage & test the voice will take hours of work to test everything!!).

we really need to have the voice test function working asap!

**Comment by helenvarley** [comment]
this is fixed, we have 2 voices & the voice test works
