### ISSUE TITLE
 inconsistent positions of media on stage 

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#272]
yesterday in the workshop we observed some significant inconsistencies in positions of media on the stage. we were mostly working with the text tool, and with this there were a lot of variations in where the words appeared. is it to do with screen resolution? what can we do about it? here are some screengrabs (i was showing the audience view on a data projector and quite conveniently the screenshot function captured both screens side by side):
![Screenshot at 2021-04-17 18-49-09](https://user-images.githubusercontent.com/3437324/115147113-b25e7380-a059-11eb-9026-2c32e3783fc7.png)
![Screenshot at 2021-04-17 18-53-31](https://user-images.githubusercontent.com/3437324/115147126-c73b0700-a059-11eb-9ee3-8e282cd53d85.png)
![Screenshot at 2021-04-17 18-55-53](https://user-images.githubusercontent.com/3437324/115147137-d4f08c80-a059-11eb-9e42-18df02a02115.png)
![Screenshot at 2021-04-17 19-04-48](https://user-images.githubusercontent.com/3437324/115147145-e9348980-a059-11eb-9f94-f609ff5f51b0.png)

**Comment by nguyenhongphat0** [comment]
It's look like relative position is not working correctly with text tool. I'm quite sure that "image media" on stage (avatar, props and drawings) already have consistent position

**Comment by helenvarley** [comment]
yes, the avatars, props and drawings are MOSTLY consistently positioned; however frequently the layering is wrong - see how in the second image, dave is in one browser in front of the letter R and in the other one behind it. also in this image, on the left dave is smaller than on the right, but the letter R is bigger in the left browser and smaller in the right.
i did notice some other discrepancies but we were mostly working with the text tool and the screengrabs i took are all from that.
