### ISSUE TITLE
contact email address on R!-2021?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#283]
it would be great if the feedback@upstage.org.nz email address could be on the R1-2021 interface in one or more places, so that people who are now using this instance (e.g. the Mobilise/Demobilise participants) can easily send feedback when they discover things.

in future we can have a proper contact page, i just mean this to be a testing & development thing to make it easier for people to report issues (it's too much for most of them to put things on github)

**Comment by nguyenhongphat0** [comment]
For now a "proper contact page" would be easier to implement than a mail server, @helenvarley 😆 
Or maybe upstage already have a mail server, I'm not sure about this

**Comment by helenvarley** [comment]
no we don't have a mailserver. there is a contact page in the navigation for the website, from the foyer page, but in terms of people testing at the moment it would be most helpful to just have an email link e.g. in the bar at the top, that goes to feedback@upstage.org.nz

**Comment by elisadcg** [comment]
Menu and submenu still pointing throught nothing.

**Comment by vickis** [comment]
***@***.***?

We have info for general

**Comment by helenvarley** [comment]
> Menu and submenu still pointing throught nothing.

which menu do you mean, @elisadcg ?
we need to re-think the foyer page and what contact we have there - for situations where others are installing their own UpStage server. there should at least be a way to contact the developers. not sure that the info@upstage address is the best, as that is used for general contact rather than specifically technical/development. maybe the feedback one for now is best.

**Comment by vickis** [comment]
yes as suggested we have info@ for general contact
need  a new email eg. help@, technical@  or something similar
and a way to set up a specific email alongside install :)
