### ISSUE TITLE
voices broken

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#289]
many, perhaps most, of the voices are no longer working. it is currently almost impossible to work out which ones are still working, as the voice test isn't working (see issue #250).

if it's not possible or unrealistic to make all the voices work again, we need to at least remove those that do not work - it's very stupid to have a dropdown of 100 voices if only 10 of them actually work. 

the ideal solution would be to find a better way to make the voices, but if that is not something that could also be useful for the new UpStage perhaps it's not the best use of time.

**Comment by rohrlach** [comment]
Turns out this is a festival configuration issue.

**Comment by helenvarley** [comment]
& is that a good thing or a bad thing? what can we do?

**Comment by rohrlach** [comment]
So it's fixed in the sense that the ISSUE is resolved.  But I DO still need to install extra voices.
