### ISSUE TITLE
unable to upload .mp3 files

### ISSUE THREAD

**Issue by millemem** [upstage-org/upstage#295]
i tried to upload several .mp3 files today, and every time i had got same result, which is shown in attached screenshot.

![screen shot 2016-10-28 at 15 15 09](https://cloud.githubusercontent.com/assets/15329022/19808382/e61598f8-9d24-11e6-944f-6e9e6dcdf042.png)

**Comment by rohrlach** [comment]
Thanks for the report @millemem 

Could you please attach an example .mp3 file

**Comment by millemem** [comment]
here they are (can not attach them on github: "We don’t support that file type. Try with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP.") 

On 28.10.2016., at 15.53, Paul Rohrlach wrote:

> Thanks for the report @millemem
> 
> Could you please attach an example .mp3 file
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 



"Which form of proverb do you prefer 'Better late than never', or 'Better never than late'?" (C. L. Dodgson)

**Comment by millemem** [comment]
ok, here they are.
[Archive.zip](https://github.com/upstage-org/upstage/files/558587/Archive.zip)

**Comment by helenvarley** [comment]
@rohrlach have you had a look at martin's patches? he wrote:

ok, so the problem regarding the mp3 upload is related to the "pymad" library. AFAIK it is only used to calculate the duration of a mp3 (respectively verify that it is really a mp3). in my code on github i had replaced it with some custom code to get rid of the dependency to pymad. IMO it is not needed to introduce a new dependency here. the code which replaces the pymad dependency is here:
https://github.com/foobarlab/UpStage-v3-beta-with-patches/tree/master/server/src/upstage/mpeg1audio
it is used then here:
https://github.com/foobarlab/UpStage-v3-beta-with-patches/blob/master/server/src/upstage/web.py#L413-L429

**Comment by rohrlach** [comment]
@foobarlab are you willing to submit a PR to resolve this issue?

**Comment by foobarlab** [comment]
sorry, unfortunately i do not have a testing environment anymore, so i can not verify if it works. if you just copy the lines mentioned above and replace the corresponding lines in the newer code it could possibly work. you might also need some additional import statements. and of course the native implementation for mpeg1audio mentioned above. if it does not work it is likely not (only) related to pymad... i am not 100% sure... can not test ;)

**Comment by foobarlab** [comment]
alternatively you also can just install the pymad library. the screenshot above just says it is not available...

**Comment by rohrlach** [comment]
Yes, I noticed that after pinging you. - I must have been tired when I originally looked at this.  I'll have to try it later as I'm behind a rather strict firewall at the moment.

**Comment by foobarlab** [comment]
If the firewall does allow SSH you can try to tunnel the traffic...

Am 2. November 2016 16:03:59 MEZ, schrieb Paul Rohrlach <notifications@github.com>:

**Comment by rohrlach** [comment]
I have installed pymad and its dependencies.  Could we please test this again?

**Comment by helenvarley** [comment]
SUCCESS!!!!! :)

**Comment by rohrlach** [comment]
Awesome. :)

**Comment by millemem** [comment]
thanks! i love you! @rohrlach
