### ISSUE TITLE
adding images causes stage not to load

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#297]
i've just added a png backdrop to the WHAS Coventry stage, & now the stage will not load. i get the image and message "Error loading Image: Bad images"
![screen shot 2016-11-17 at 10 03 45 pm](https://cloud.githubusercontent.com/assets/3437324/20410024/134792ba-ad13-11e6-9d26-a708f5933760.png)

**Comment by helenvarley** [comment]
i've tried saving the image as a gif and a jpg, but i can't upload either - i just get the "something went wrong" message. so at the moment it's not possible to upload any backdrops!!!! i haven't tried avatars, & need to go to bed now. but i am planning to show how to upload things tomorrow !!!!

**Comment by helenvarley** [comment]
today i tried the stage again. the first time, it loaded fine; there was one backdrop, that i had uploaded some time earlier, there. then i tried to load it again, & got the bad images error message. i tried to reload a few times & still got the bad images error. i closed the browser tab, and opened a new tab, & this time it loaded. 
so then i went to view/edit media, found the backdrop i'd uploaded 3 days ago that i thought was causing the problem, and assigned it to the stage. the stage reloaded fine & the backdrop is displaying.
so it's quite confusing about what is causing the bad images error. this is still very urgent, as if audience members encounter this error, it will be very off-putting.

**Comment by rohrlach** [comment]
The stage not loading was a permissions issue. Has been resolved.

There is however an issue whereby img2swf gets called twice and fails on the second time through (Causing 'Something went wrong' during upload) It shouldn't be called twice so I'm assigning to @AUTUpStageTeam  for a fix.

**Comment by helenvarley** [comment]
today paul wrote "So as stated this is more of a permissions issue.  I've put an acl on the media directory so hopefully this won't be an issue (at least in our case) anymore."
today we tested the images that we had uploaded yesterday: they are now able to be assigned to a stage without causing that stage not to load.
however, we then uploaded 2 more images (pngs, backdrop & avatar), & the same thing happened - when assigned to a stage, the new image causes the stage not to load & gives the above error.
i uploaded an mp3 file to see whether that would also stop a stage from loading, but it works fine.
i noticed that in the view/edit media screen, the images uploaded today don't show a preview image. from memory, this also happened with the ones uploaded yesterday - & they are now showing a preview image.

**Comment by rohrlach** [comment]
Turns out the ACL wasn't recursively actiing on the thumbnail directory.  So the media was fine, but the inaccessible thumbnails caused everything to crash and burn.

**Comment by helenvarley** [comment]
sadly this is happening again this morning :(
just for a bit of variation on the theme, this time the person who has uploaded the media item can see its preview, & is able to enter the stage that it's assigned to. but i am not (i'm assuming nobody else can, but at the moment everyone else is busy with other tasks so only carys & i are working on it). i get the same bad images error as above, & don't see any preview for the media in the edit screen.

**Comment by rohrlach** [comment]
Have provided a code based fix for this. Seems excessive... but I also don't see a reason not to.
