### ISSUE TITLE
"none" voice still speaks

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#305]
as voices are being totally wierd, i have tried setting all the avatar voices on the WHAS coventry stage to "none"; they are showing in the edit media screen as this.
however, on stage, they are still speaking - with the male voice.

**Comment by rohrlach** [comment]
Is this different to issue  #303 ?

**Comment by helenvarley** [comment]
er - no; it's the same .... this is more of a reflection of the state of my brain at the moment than of the UpStage code! ;)
