### ISSUE TITLE
UpStage community website and UpStage info on Foyer page

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#325]
We have "sort of" merged the UpStage community website into the Foyer page: the navigation at the top of the Foyer page is the same as the navigation of the community website.
In the user manual it says that the UpStage logo at the top left corner of the Foyer page will take you to the community website (upstage.org.nz) - but if that is the case then why do we have all the of the same navigation on the Foyer page?
If people are installing their own UpStage server they will not want all of the UpStage community navigation on their Foyer. 

i think we need to de-merge it; the UpStage logo on the Foyer page should link to upstage.org.nz, & when our UpStage instance is live it can have the upstage.live url. 
the centre navigation menu in the Foyer needs to either go, or be rethought - what navigation do we need here? e.g. an FAQ about the UpStage platform? Link to documentation? customisable links for whoever is running an instance to set?

also the title that currently says "Cyberformance Platform" needs to be customisable by the instance owner; for our instance it would be better to say something like just "UpStage" or "Open UpStage" or ... we'll have to think about what is appropriate.

**Comment by vickis** [comment]
i think we need to de-merge it; the UpStage logo on the Foyer page should
link to upstage.org.nz, & when our UpStage instance is live it can have the
upstage.live url.

yes Agree -


the centre navigation menu in the Foyer needs to either go, or be rethought
- what navigation do we need here? e.g. an FAQ about the UpStage platform?
Link to documentation? customisable links for whoever is running an
instance to set?

>>  this link going to FAQ is useful (documentation of the new UpStage
should also be on this page )
this way visitors can also find out a bit of the herstroy of the platform


also the title that currently says "Cyberformance Platform" needs to be
customisable by the instance owner; for our instance it would be better to
say something like just "UpStage" or "Open UpStage" or ... we'll have to
think about what is appropriate

yes customisable

**Comment by vickis** [comment]
currently the first three links appear to be working but are not active 
![image](https://user-images.githubusercontent.com/4249450/132264587-6dad1950-1a33-49b3-b27a-28b069c1cdde.png)

stage links are fine 

more importantly neither is the donate button ;)

**Comment by vickis** [comment]
currently the first three links appear to be working but are not active 
![image](https://user-images.githubusercontent.com/4249450/132264587-6dad1950-1a33-49b3-b27a-28b069c1cdde.png)

stage links are fine 

more importantly neither is the donate button ;)

**Comment by vickis** [comment]
there is also the latest news on the Foyer page - which goes to the demo stage (this could take the form of a notice board - as the name suggests ... :)

**Comment by helenvarley** [comment]
> currently the first three links appear to be working but are not active

we don't need any of those links on the Foyer page - they are on the community website and relate to the UpStage community, not to an instance of UpStage.
for the Foyer, we need to think what links would another organisation, for example the university or a theatre company, need here?

**Comment by vickis** [comment]
sure agree
(the # should be removed and text changed to example :)

perhaps as part of installation it csn be decided how many and for what
purpose the top navigation is created
that would allow each to define what is useful in their instance :)

**Comment by helenvarley** [comment]
let's focus on what should be on the Foyer page:

- [ ] customisable title area (where it currently says "Cyberformance Platform" - this should be possible to say for example "Meta Theater UpStage" or whatever the instance is)
- [ ] customisable text description (under the title: should be possible for other instances to edit this text)
- [ ] log in / log out / backstage / register buttons (as they are now)
- [ ] UpStage logo that links to UpStage community site (www.upstage.org.nz - as it is now)
- [ ] live stages: image, title, editable text that can include dates/times, player/audience counter; clickable to enter the stage
- [ ] upcoming stages: image, title; editable text that can include dates/times; not clickable
- [ ] option to add customisable blocks, e.g. image and link back to Meta Theater website
- [ ] link to UpStage manual?
- [ ] anything else?

 question: what happens when the instance is new or dormant, & there are no live or upcoming shows? placeholders?

**Comment by riadsalameh** [comment]
Do we want to have "Buy ticket" option on the foyer page?

**Comment by helenvarley** [comment]
no - initially we had the idea to integrate ticketing into the system, but it is too difficult. people will need to use their own third party ticketing systems. at least for now ...
we also don't need the "latest news" option - or rather, this should be a customisable option.

**Comment by riadsalameh** [comment]
Regular Foyer page
![Upstage_Foyer](https://user-images.githubusercontent.com/71765608/134018796-93f51d09-a457-44ee-952f-27c8f29e80db.jpg)

Option to add navigation Links to own pages
![Upstage_Add_Navigation](https://user-images.githubusercontent.com/71765608/134018824-a6d04bb8-83d1-485c-bcf3-8b3e687ff1f5.jpg)

Creating Link for new navigation 
![Upstage_Create_Link](https://user-images.githubusercontent.com/71765608/134018852-2d5e60d9-2a63-46e2-b4e4-e1755a67e1a1.jpg)

Added Link 
![Upstage_Added_Navigation](https://user-images.githubusercontent.com/71765608/134018864-44b35e9d-350c-4fec-9724-244cd831428d.jpg)

New Navigation added to foyer page
![Upstage_New_Navigation](https://user-images.githubusercontent.com/71765608/134018874-8553190f-7272-40a0-a9c4-cf0e81df3bd3.jpg)

**Comment by riadsalameh** [comment]
The manual and to create a stage (avaialble to create a stage  in both foyer and the backstage) are static and not part of the navigation header. The main header contains only the Upstage Logo, login, register, logout and an option to customize the navigation header  (Through links). When a stage is added then there is an option to choose the photo for the Box on the foyer . The other boxes contains the current stages (Maybe can include their recordings after they were performed)

**Comment by helenvarley** [comment]
thanks riad :) some questions from me ...
do you mean that the boxes would be there from the beginning, and you could click on one to change it to the link you want? 
how would the foyer look when the instance is first installed and there are no stages at all or any media yet uploaded?
is the "new stage" link to create a new stage, or to add a new stage to the boxes on the foyer? creating a new stage should only be possible when you have logged in to backstage; & the stages should automatically appear on the foyer when they are set to live or upcoming.
what does the green cog icon next to the login button do?

**Comment by riadsalameh** [comment]
I tried to explain things here more clearly. I will be removing the add stage option 
![WireFrame_Foyer-01-01](https://user-images.githubusercontent.com/71765608/134152411-ecb08788-0253-4967-9cf3-5ad4884a4b1a.jpg)

**Comment by riadsalameh** [comment]
The customizable bar is only available for logged in users

**Comment by helenvarley** [comment]
ok, thanks - that makes sense :) i guess the login & register buttons should be logout and backstage when you are logged in & seeing the navigation customisation icon?
& the squares for the stages are automatically displayed according to what stages are set as live or upcoming, right? i was confused because the pop-up window was on top of a stage square so it looked like it was connected to that.
a few more thoughts:

- [ ] can there be a customisable text header area? for example, meta theater might want to have "Meta UpStage" or something like that appearing as a heading.
- [ ] maybe also an option to add a customisable text or HTML area, if they want to add some information about this UpStage instance?
- [ ] what is the default, when the instance is new and there are no stages? should there be some dummy images in the squares, or no squares appear?
- [ ] would it make sense for the manual link to be next to the login & register buttons?

**Comment by riadsalameh** [comment]
I'll do some adjustments and we can discuss it tomorrow in details. The meeting is still at 1:00 pm CET? or did we change it

**Comment by helenvarley** [comment]
yes 1pm - i just sent out a reminder :)

**Comment by vickis** [comment]
great work Riad :)

- @helen cog usually indicate settings this would be the case here too
right?

also is there a way to prioritise the live and upcoming layout to ensure
for example the foyer stage has the most prominence fior a festival with
multiple shows/stages

or could this be dynamically adjusted by a date setting in the stage?

agree to manual link in relation to login & register

thanks :)

**Comment by helenvarley** [comment]
> - @helen cog usually indicate settings this would be the case here too right?

yes that's clear, but the cog doesn't need to be visible to non-logged in people.

**Comment by riadsalameh** [comment]
Here are the adjustments to the foyer page 
![Upstage_Prototype_Foyer-01-01](https://user-images.githubusercontent.com/71765608/135070475-6e3662cc-6d1b-4f00-9669-2340fe64383e.jpg)

**Comment by helenvarley** [comment]
looks really good @riadsalameh ! i like where you've put the link for the manual.
it's made me realise that we don't have a link to the manual anywhere in the backstage - maybe it could be the same as where you've put it now, but on the right, as the UpStage logo is over on the right in the backstage.

**Comment by vickis** [comment]
Great @riadsalameh :)
once there are active stages these would show on the landing page (before needing to login) as images and links right?

perhaps below the photo/announcement
this way audience are able to arrive orientate then attend any show that happening or enter any stage that is live

**Comment by helenvarley** [comment]
@vuhuynhsk8 @nguyenhongphat0 - can this be implemented with IG-11?

**Comment by helenvarley** [comment]
> Great @riadsalameh :) once there are active stages these would show on the landing page (before needing to login) as images and links right?
> 
> perhaps below the photo/announcement this way audience are able to arrive orientate then attend any show that happening or enter any stage that is live

@vicki i think the photo announcement is only there when there are no stages; & once there are stages that are live or upcoming, these will automatically display.

**Comment by vickis** [comment]
Perfect :)

**Comment by riadsalameh** [comment]
@vickis Excatly what Helen said. The image is only when there are no stages but often it will have the live and upcoming stages

**Comment by riadsalameh** [comment]
Here is again the same walkthrough of the foyer page with the manual bar on the right and I change the add navigation button to a + as it makes more sense. I also uploaded a preview of what it can look like if we end up with the masonry grid. The Live stages will be highlighted in the boxes while the rest will only be a photo preview of the stages. 

![Foyer Walkthrough-01](https://user-images.githubusercontent.com/71765608/142764966-00aefa52-e58e-4b06-9852-fe0a42d5aa4c.jpg)
![Foyer_Masonary Grid](https://user-images.githubusercontent.com/71765608/142764981-550b7380-cb69-48ed-ae20-bcedcccd750c.jpg)
![Foyer-Masonary Grid](https://user-images.githubusercontent.com/71765608/142764983-cebeba4e-05d2-4306-a288-ae2706bf36f6.jpg)

**Comment by vickis** [comment]
Great thanks @Riad Salameh ***@***.***>

@Vu this is to be implemented as the new Foyer - please let @Phat
(or @Gloria or @Paul know if you are struggling with this

vicki :)

**Comment by helenvarley** [comment]
i wonder, could it be an option to have either the tiles or the masonry grid? (as well as the option to have a single image there when you have no live shows)

**Comment by phat** [comment]
no thanks

**Comment by helenvarley** [comment]
:laughing:

**Comment by helenvarley** [comment]
here is the link to use for the manal: https://docs.upstage.live/
@riadsalameh - i just saw that the manual button in the wireframes has a download icon on it, but in fact the manual is not downloadable (at the moment anyway). would it make sense to take off that download arrow? sorry for more work ...

**Comment by riadsalameh** [comment]
Ouuuuuuh I love how the manual look. Great job!! 
And of course, the download icon can be removed

**Comment by helenvarley** [comment]
i think this issue can be closed? we have the customisable foyer on upstage.live and meta.upstage.live now :)
