### ISSUE TITLE
media items have square frame again

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#416]
i thought we ad solved this, but i see that all media items have a square frame on the stage again. this means that if you have a prop or avatar that is tall and thin, or wide but not high, there is always a square frame taking up more space than necessary on the stage. this creates problems of clicking on the wrong media item, or having to use the depth tool to move a prop or avatar or stream.
it should be that the frame fits to the dimensions of the media object: if it is taller than it is wide, then the frame should also be taller than it is wide.

**Comment by helenvarley** [comment]
it also means that video is squashed:
![Screenshot at 2021-06-18 16-03-04](https://user-images.githubusercontent.com/3437324/122573133-be14e900-d04e-11eb-8403-757e10544b4a.png)

**Comment by helenvarley** [comment]
streams are showing as a rectangle, but if you increase the size it is like it zooms in to the top left hand corner. then you have to add a frame, and remove the frame, in order to see the full video:
![Screenshot at 2021-06-18 16-06-49](https://user-images.githubusercontent.com/3437324/122574142-a5590300-d04f-11eb-9a3a-5426aa198987.png)
![Screenshot at 2021-06-18 16-07-03](https://user-images.githubusercontent.com/3437324/122574152-a853f380-d04f-11eb-8573-40f7b8fb5590.png)
![Screenshot at 2021-06-18 16-07-36](https://user-images.githubusercontent.com/3437324/122574165-aab64d80-d04f-11eb-9d13-0d63bf059123.png)

**Comment by nguyenhongphat0** [comment]
I did some improvements on this. Let me know if you're happy with it by uploading some media with tall or wide size, and put it on stage 👌 

And about the round streaming shape, you can make it thinner to remove the left and right space 🤔

**Comment by vickis** [comment]
Frame should be automatically detected
If the stream changes from landscape to circle frame needs to adjust
accordingly :)

**Comment by helenvarley** [comment]
> I did some improvements on this. Let me know if you're happy with it by uploading some media with tall or wide size, and put it on stage ok_hand
> 
> And about the round streaming shape, you can make it thinner to remove the left and right space thinking

is this on app1 yet? i'm trying to test with a video on dev-app, but it won't upload. 

on app1, my video (pre-uploaded, not live stream) is still squashed into a square ...

this is quite urgent to address. we are rehearsing tomorrow & need to know whether or not we'll be able to use streams at the weekend in our presentations ...

**Comment by helenvarley** [comment]
and as far as i can tell it is still the same on app1 for avs and props, that the frame is square. but seems better on dev-app, apart from not being able to test video

**Comment by helenvarley** [comment]
this seems to be fixed for avatars but not for props:
![Screenshot at 2021-06-21 16-53-23](https://user-images.githubusercontent.com/3437324/122782708-3bd82f00-d2b1-11eb-8d6a-44094afd22c6.png)
![Screenshot at 2021-06-21 16-53-09](https://user-images.githubusercontent.com/3437324/122782712-3c70c580-d2b1-11eb-8031-690cf812b612.png)

**Comment by nguyenhongphat0** [comment]
It is fixed for both avatar and props, but for those media that was saved before the fix was applied, it still have square frame. For example, edit and save that DEMOBILISE prop again will make it frame fit to it 👌 

<img width="1369" alt="Screenshot 2021-06-22 at 00 30 20" src="https://user-images.githubusercontent.com/29925961/122803622-08b59000-d2f1-11eb-81ef-c933844e03b2.png">

**Comment by helenvarley** [comment]
great! got it :) there may still be an issue with the videos and streams, but that can be a separate issue. i'll close this one now :)

**Comment by helenvarley** [comment]
re-opening this as it's happening again (on https://meta.upstage.live/demo) - the UpStage logo avatar has a square frame but the image is 300 px wide & 104 px high. 
this is quite important as it makes it very easy to select the wrong object on the stage when the frame is covering a larger area than the image, & even when we have the solution in the depth tool it takes more time & can slow down the performance and lead to mistakes.
![Screenshot from 2021-12-01 12:00:41](https://user-images.githubusercontent.com/3437324/144223212-a960e43e-b793-4171-a41a-efd26b7b0468.png)

**Comment by helenvarley** [comment]
note: this is not happening on upstage.live, only on meta.upstage.live - but aren't they the same code?
this is the same image on upstage.live (but here, it is a prop; and the original file has a size of 500 x 174 px - bigger, but same proportions as the one that is an avatar on meta.upstage.live)
![Screenshot from 2021-12-01 12:04:37](https://user-images.githubusercontent.com/3437324/144223590-2e134c1a-cdb1-4e41-8122-392cd05446a9.png)

**Comment by nguyenhongphat0** [comment]
As explained before, it was some missing code to crop the frame in Studio, and this got fixed ✅

**Comment by helenvarley** [comment]
great! looks fixed to me :)
