### ISSUE TITLE
replicate voice settings

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#426]
i have two versions of the same avatar, that need to be two separate multiframe avatars which are used at different times.
i want the same voice for both avatars.
i have to guess the settings, looking at one and then adjusting the other settings to as close as possible to match the voice.
could there be a function in the voice settings of the avatar edit interface, that is "replicate voice" from another avatar, & a search field to search for the name of another avatar that you want to copy the voice from?
(note - sometimes there are more than one avatar with the same name ... )
(another note - this might not be relevant once we have the costume prop, as this issue has arisen because the avatar sometimes has a mask on and sometimes not - the mask could be a costume prop & then only one avatar would be needed)

this is not a high priority issue!

**Comment by elisadcg** [comment]
I suggest an access direct from the media tab, at the top or the bottom to allow duplicate the voice settings from another media.

![issue426](https://user-images.githubusercontent.com/7611913/132225114-4e568163-1991-4f76-9a8f-43e092812959.png)

**Comment by vickis** [comment]
Interesting idea!
Is it difficult to achieve though?
Because the sliders are visual you can check in any avatar you like the
sound of

Also it is good to have different voices  in a performance having multiple
voices helps differentiate character types too :)

**Comment by helenvarley** [comment]
@vickis - see my original post, explaining the situation where i wanted it, with separate multiframe avatars that are the same character, used at different times. so preferably the voice would be exactly the same on both.
 you can compare the settings with another avatar & try to replicate them, but it's pretty difficult to get the exactly the same. if it's not difficult to achieve, it would be a nice-to-have feature :)

**Comment by vickis** [comment]
ok sure - nice to have :)

**Comment by nguyenhongphat0** [comment]
Here you go 🙌 
<img width="1125" alt="Screenshot 2021-12-19 at 18 36 23" src="https://user-images.githubusercontent.com/29925961/146673614-b0a927bd-90c3-4a46-998d-a0c4ee045981.png">

**Comment by vickis** [comment]
Wahoo!  :)
