### ISSUE TITLE
delete stage - what happens to chats and replays?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#479]
if i delete a stage, what will happen to any chats and replays that are currently shown in the stage management for that stage?
what do we want to happen?
in the past, we sometimes had to delete and recreate a stage when there was a bug ... maybe this will happen in the future too, so probably we want a way to keep chats and replays until we manually delete them? or an option in the delete process - for example, if we know we don't want to keep the chats & replays, they could be deleted at the same time as the stage is deleted.

**Comment by nguyenhongphat0** [comment]
At the moment, when a stage is deleted chat and replays will be gone as well!

> we sometimes had to delete and recreate a stage when there was a bug

Please don't do that, instead report the bug to me and we will find a way to solve it 😆 

> we want a way to keep chats and replays until we manually delete them

This sound like a soft delete, which is actually assign an "inactive" flag to a stage, and treat them as deleted. I don't really prefer soft delete, because it will only make our system heavier 😅

**Comment by vickis** [comment]
Agree
I think keeping archive material linked to a stage that has been deleted
seems like a good way to create confusion

Could the replay function also have the ability to package for export?
So required objects etc are included and the replay can be extracted later

Archived material should then be deleted after x amount of time
:)

**Comment by helenvarley** [comment]
> 
> > we sometimes had to delete and recreate a stage when there was a bug
> 
> Please don't do that, instead report the bug to me and we will find a way to solve it laughing
> 
we only had to do that because we didn't have you! :laughing: 

& yes agree, we don't want soft delete; we like deleting! properly deleting! but we need to know what we are & aren't deleting ... vicki's suggestion of being able to export the chat & replays before deleting sounds like a good solution. could the delete button have a popup window that asks if you want to download the stage's archive as it will also be deleted?

**Comment by nguyenhongphat0** [comment]
Chat log can be exported, and we already have that function. I can show a button to download archived chat when you are about to delete a stage 👌 
About replay, it is possible too, but might need some more works.

**Comment by nguyenhongphat0** [comment]
I just realized that this issue had been propagated through a lot of milestones 😅 

> could the delete button have a popup window that asks if you want to download the stage's archive as it will also be deleted

Pull request #850 will do it for you

> About replay, it is possible too, but might need some more works.

I will create a separate issue for this, since it would need a lot of efforts and ideas to be discussed.

**Comment by vickis** [comment]
is definitely would be good to have
but not at the expense of other things because objects etc used on the
stage can be archived themselves ...

be good to keep an eye on and discuss its actual worth especially if it
will be a significant amount of time to compile code for
vicki :)
