### ISSUE TITLE
use british english spellings in the interface

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#484]
please can we use british english spellings in the interface (& manuals & everywhere). this is because UpStage was born in aotearoa (new zealand) where we use british spellings, & there are more kiwis than americans in the project ;)

at the moment the only thing in the interface that i've found that needs correcting is customisation (instead of customization) in the left-hand navigation menu of the stage management section. if i find anything else i will add it here.

**Comment by vickis** [comment]
yez agree!! :)

**Comment by nguyenhongphat0** [comment]
Customisation was changed 👌

**Comment by helenvarley** [comment]
colour needs to be correct - it should always be "colour" (not "color"
![colour_not_color](https://user-images.githubusercontent.com/3437324/134152687-998bf042-2375-4a20-ae54-1899f5834f53.png)
)

**Comment by nguyenhongphat0** [comment]
Colour was updated 🙌

**Comment by vickis** [comment]
super Phat :D

**Comment by nguyenhongphat0** [comment]
Feel free to re-open this issue when you have new British spelling to correct 👌
