### ISSUE TITLE
streams: more options on context menu?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#538]
when i right-click on my stream, the only options i have are pause or frame (rectangle or circle). can we have more options? 
these would be useful:

- move speed (slider same as for other objects)
- volume control (might be easier to adjust audio stream volumes on stage, if there are 2 or more streams & volumes are different)
- bring forward and send back
- remove 

basically all the same ones that are on other objects, apart from those that are not relevant for streams.

**Comment by helenvarley** [comment]
related to #539

**Comment by helenvarley** [comment]
would be nice also to have the horizontal & vertical flip that we have on other objects :)

**Comment by helenvarley** [comment]
we're testing streams again on sunday 3rd, so will test this then.

**Comment by helenvarley** [comment]
great! 
what does the animation speed slider do on a stream? do we need that option?

**Comment by elisadcg** [comment]
nop :/

**Comment by nguyenhongphat0** [comment]
> what does the animation speed slider do on a stream? do we need that option?

@vuhuynhsk8 has removed that slider on a stream 👌
