### ISSUE TITLE
streams: how does the pause function?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#539]
if i pause and then restart my stream, it seems like it picks up again where i paused it & carries on streaming everything.
this is probably how it should work if we are streaming a video, but if it's a live stream it might be better if when it's restarted after pausing, it refreshes the stream with what is there now rather than playing "old" stream.

this could be really useful if someone was having a lot of lag on their stream, they could pause it in UpStage, wait a few seconds and then restart it at the current frame. this could also be done by any player on the stage, which could be useful if the streaming player has connectivity issues.

i realise it might not be possible to distinguish between a video and a live stream so maybe this isn't really workable, but thought i'd put it out there anyway.

**Comment by vickis** [comment]
This might be differentiated by having a stop and pause button on the stream

* pause - halts playing at current point (if a stream or video then resumes
)
* stop  - would ignore  connection to the stream
* removing the stream from the stage would sever the connection

that might help with understanding what button  controls each action

**Comment by helenvarley** [comment]
related to #538

**Comment by helenvarley** [comment]
i think we can close this one - it's related to both #538 and #716
