### ISSUE TITLE
streams: mute button for all streams?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#542]
currently i see a mute icon on my own stream. it would be useful to have that icon also on other streams, so that if necessary players can locally mute all streams. this would be useful in feedback situations and workshops.

players should be able to mute their streams from Larix or OBS, so this button shouldn't be necessary, but there are still often times when they don't do this & it would be good to be able to do it. 
but it's a "nice to have", not "must have" :)

**Comment by vickis** [comment]
agree 'nice to have' :)

**Comment by elisadcg** [comment]
White not have an icon on the top overlay which is active and allow you to mute any stream on Stage whith the next click?

![issue542](https://user-images.githubusercontent.com/7611913/132198034-8164a54a-444d-42cb-b474-ec4186c44b29.png)

**Comment by vickis** [comment]
That’s a good idea Elisa I do think though that where possible actions to
an object should be associated with that object
As in context menu (right click)
I could see the possibility for confusion with the mute icon  in the stream
bar (especially when there are multiple streams  :)

**Comment by helenvarley** [comment]
it fits with other toolbar actions, e.g. the audio controls, to have a mute there. also easier to access when there are overlapping media items on the stage.
wondering if there could be local and global mute options in a right-click menu? we used to have this in the old UpStage & i know that we don't want to replicate things that people can control through the streaming software, but we know that sometimes people don't get it to mute their own audio. it's also a useful feature if the person streaming is dancing or performing and not able to mute or unmute at the same time.

**Comment by helenvarley** [comment]
looks good, altho needs to be tested when multiple streams are on stage - i've tested with more than one of my own stream on stage, but need to be there with others to test with others' streams. should happen in the next days.

**Comment by helenvarley** [comment]
this has been implemented for EVERYONE including audience - which means that audience will not hear streamed audio unless they manually unmute the stream.
actually what i meant with this issue was that all players on a stage could mute or unmute streams, not the audience. is this possible?

**Comment by nguyenhongphat0** [comment]
Yes, it is possible, @vuhuynhsk8 will take care of that 👌

**Comment by vickis** [comment]
Yay Vu! 🥳

**Comment by helenvarley** [comment]
i'm not removing this from the project yet because we need to test it at the rehearsal on monday when more than one person is sending a stream.
