### ISSUE TITLE
streams: difficult to have more than 2 playing on stage at a time

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#543]
last night 4 of us were sending streams. we could see all the streams at the node admin page. we all had had our streams on successfully one by one. then we tried to be all on at once - and got buffering icons. at one point all streams were buffering.
it seems that when there are more than 2 streams on the stage, further streams take a really long time to display.
can we improve this?

**Comment by teddyfullstack** [comment]
> can we improve this

Maybe the Meeting tool or Individual streaming with Jitsi can improve that 😅

**Comment by helenvarley** [comment]
we have a funding application in that will hopefully bring some money to improve streaming :crossed_fingers:

**Comment by helenvarley** [comment]
i'm closing this, because it's from so long ago, & i think it may have been the RTMP streams that i was writing about at the time, which we now don't have.
