### ISSUE TITLE
clickable links on stage?

### ISSUE THREAD

**Issue by vickis** [upstage-org/upstage#545]
Could we have a way to assign a new URL to an object onstage to create a flow through from one to stage to another for example - or if not could we enable URLs in chat to be live 
are there any unforeseen issues with allowing/creating this?

* I can assign a hotlink to an object onstage (eg prop)
* audiences clicking on the link are taken to a new page/stage etc
* hotlinks are possible in audience chat - but only if posted by logged in players

thanks :)

**Comment by helenvarley** [comment]
urls in chat are clickable, & open in another window.
but it would be cool to be able to embed links in on-stage objects, that could be clickable by the audience. then we could make signs, doorways inviting audience to enter etc

**Comment by vickis** [comment]
yes exactly!

sorry can we restrict viability of links to logged in players?
just in terms of avoiding general public adding links into chat ...

**Comment by helenvarley** [comment]
see #40 - removing inappropriate links & text from chat
sometimes it's good for the audience to be able to post links, for example if they are finding out relevant information.

**Comment by vickis** [comment]
ah sorry

**Comment by helenvarley** [comment]
Discussed at meeting on 8.9.21: workflow would be to have an additional tab in the media edit interface for avatars and props that is "Link". here you could enter a URL, and set it to either open in the same browser window or a new one.
When the media item is placed on the stage, the audience are invited to click on it to enter another stage or open a webpage.

**Comment by paul-rohrlach** [comment]
Assuming #558 closes this issue.

**Comment by vickis** [comment]
Yay! works as described thanks heaps :D

**Comment by helenvarley** [comment]
the links are not working on stage for me (firefox on linux) - i'm trying to click on an avatar that i can see in the media management has a link attached, & i get the pointing finger when i hover on it, but when i click on it nothing happens. if i double click i get the frame & tools.

**Comment by vickis** [comment]
Try clicking on the wheki woman prop on the demo stage - she works
the sign post url is the issue there i think :)

**Comment by helenvarley** [comment]
do you mean the crinoline woman? it doesn't function as a link for me. i don't even get the pointing finger on her, which i get on the signpost image.

**Comment by nguyenhongphat0** [comment]
The link only works for audience, not players (you might want to open a cognitive tab to try it). If players click on the avatar and got redirect to the link location, they can't double click to hold the avatar anymore 🤨

**Comment by helenvarley** [comment]
ok, i managed to log out and test the links as audience (first encountering a bug which i've created an issue for).
this now works as expected :)
however we need to think how this will work for the players. what happens if you are a logged in player who doesn't have access on this stage? these players should be able to click the links, right?
and for the players ... do they just have to know where to go, if there are links they should follow? could there be an option in the context menu, to "open link" or something like this?

**Comment by vickis** [comment]
ok, - this now works as expected  = great :)

"however we need to think how this will work for the players. what happens
if you are a logged in player who doesn't have access on this stage? these
players should be able to click the links, right?

* if logged in but without player access on the stage - links to be
presented as guest

and for the players ... do they just have to know where to go, if there are
links they should follow? could there be an option in the context menu, to
"open link" or something like this?

i am not sure about this
- if someone is a player on the stage or involved in the work then they
should be aware of where the action will move
- If not they should not be in the stage as a player but rather attending
as audience

the ability to 'see' where links go might be useful when the 'volunteer'
avatar is implemented ...

**Comment by nguyenhongphat0** [comment]
> if logged in but without player access on the stage - links to be presented as guest

Yes, and this is already implemented 👌 

> could there be an option in the context menu, to "open link" or something like this?

Yes we could 😆 Hover on that "Open link" will show the destination

<img width="420" alt="Screenshot 2021-09-13 at 23 19 28" src="https://user-images.githubusercontent.com/29925961/133120445-51236cea-b19e-49ce-8722-ac94109a0e40.png">

**Comment by vickis** [comment]
Fantastic! :D

**Comment by helenvarley** [comment]
is this on dev-app? i have cleared cache but not yet seeing the open link option in right-click menu ...

**Comment by nguyenhongphat0** [comment]
Sorry I created a pull request to a wrong branch 😅 Which cause these changes to go in app1 😆 dev-app1 will be next, sorry about that!

**Comment by helenvarley** [comment]
there seems to be no way to add a link to a prop in the new studio interface - or am i missing something??

**Comment by helenvarley** [comment]
i just realised i made a separate issue for this #778 so closing this one.
