### ISSUE TITLE
media permissions: "use with permission"

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#547]
how does the "use with permission" setting work, for media items? what is the workflow? we need ways to:

- player requests permission from the owner of the media
- owner of media grants permission to that specific player to use the media
- can that player then also edit the media, e.g. assign to stage, change voice, name, etc? or only assign to a stage?
- owner removes permission from player when they no longer need to use it

if a player has permission to use a media item and assigns it to their stage, it needs to be accessible there to any other players who have access to that stage. do those players then also have access to it backstage? probably they should not, as long as they can operate it on the stage.

**Comment by nguyenhongphat0** [comment]
When you choose Use with permission, 3 columns will appears so that you can decide which users will have the ability to "see" and "edit" your media.

<img width="1091" alt="Screenshot 2021-09-16 at 22 54 03" src="https://user-images.githubusercontent.com/29925961/133644938-2c245f74-661d-4699-bbe2-44e0ecb9d205.png">

So technically we have "owner of media grants permission to that specific player to use the media", but not "player requests permission from the owner of the media" 🤔

> can that player then also edit the media, e.g. assign to stage, change voice, name, etc? or only assign to a stage?

If they are granted the editor access, they can do that. If not, they can only see and download it. Take a look:
- Readonly access: <img width="1028" alt="Screenshot 2021-09-16 at 22 58 43" src="https://user-images.githubusercontent.com/29925961/133645912-a3387dd8-1848-4d11-b0b4-7ee7a747c727.png">
- Editor access: <img width="1021" alt="Screenshot 2021-09-16 at 22 59 12" src="https://user-images.githubusercontent.com/29925961/133645904-49d9eb55-0512-4599-893b-b68ceeb3679c.png">


> owner removes permission from player when they no longer need to use it

Yes they can always do that 😅

**Comment by vickis** [comment]
Awesome - the is a useful mechanism to control the way your work is used :)

**Comment by nguyenhongphat0** [comment]
I wonder what actions is required for resolving this issue? 😅

**Comment by helenvarley** [comment]
the main thing we are missing here is a way for a player to request permission from the owner of a media item; i have set the Dave avatar to "use with permission". let's say another player who does not know me personally wants to request permission to use this avatar. 
they can find the avatar in the Media list, and see that i am the owner and that it is set to "use with permission". could they click on "use with permission" and have a pop-up window that says "player x is requesting permission to use [media name]" and this gets sent to the owner of the media? 
where would i receive this notification? can i be sent an email from UpStage, saying that a player is requesting permission?

**Comment by nguyenhongphat0** [comment]
> where would i receive this notification? can i be sent an email from UpStage, saying that a player is requesting permission?

Yes and this is the hard part, since we doesn't have a mail server (yet). Another option would be a notification system in UpStage, but would it be overkill 🤔

**Comment by helenvarley** [comment]
and that would also mean you would have to be in UpStage to see the notification, & some players might do one show and then not be in UpStage for some time.
we could put this in the "after the launch" basket, since at least for now all of the people using UpStage know each other or would know how to contact vicki or me to ask another player for permission.

**Comment by vickis** [comment]
Agree :)

**Comment by nguyenhongphat0** [comment]
Finally the feature has arrived 😅 Here is the new `Use with permission` flow:

- Player requests permission from the owner of the media <img width="1440" alt="Screenshot 2021-11-28 at 21 02 31" src="https://user-images.githubusercontent.com/29925961/143771481-e00fa67e-499b-40df-a5e1-ceb4acef8cb1.png">
- Owner of media grants permission to that specific player to use the media <img width="1365" alt="Screenshot 2021-11-28 at 21 07 56" src="https://user-images.githubusercontent.com/29925961/143771485-6dc0a939-b453-4b00-ad9c-a5580760a687.png">
- In the permission tab, owner can remove permission from player when they no longer need to use it, and they can add other players without requesting too: <img width="1439" alt="Screenshot 2021-11-28 at 21 08 25" src="https://user-images.githubusercontent.com/29925961/143771488-4646187f-3227-41fb-ab4c-2b31937a7a7e.png">

The `Use with acknowledgment` flow also has enhancement:
- Before using the media with this copyright level, player have to click on that button <img width="1366" alt="Screenshot 2021-11-28 at 21 10 53" src="https://user-images.githubusercontent.com/29925961/143771653-146fb8ca-3b9a-4294-9d10-9da21d1ded5e.png">
- Owner of the media can be "acknowledge" of who is using his/her media by viewing the permission tab: <img width="1440" alt="Screenshot 2021-11-28 at 21 20 49" src="https://user-images.githubusercontent.com/29925961/143771870-5cf59a10-c5de-400a-b687-e74d30aa66ef.png">

**Comment by vickis** [comment]
Super! :)

**Comment by helenvarley** [comment]
great :) where can we test this? i just looked on dev-app & there is no media there any more ... is it on upstage.live already? i'm only seeing the edit button by all media, no option to request permission (is that because i'm an admin?)

**Comment by helenvarley** [comment]
great!! i approved your test & sent you a test ... :sunglasses:
