### ISSUE TITLE
speed of scaling of avatar or prop

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#567]
the artists have asked if it's possible to adjust the speed at which an avatar scales (resizes) - they would like to be able to have something very slowly increase or decrease in size. is this possible? could the "move speed" slider also affect the speed of resizing?

**Comment by vickis** [comment]
If it is going to be part of the show could be an animation ?

Could be useful :)

**Comment by helenvarley** [comment]
the idea is that the avatar appears to move forward and backward in the space, i.e. it's small when it's further away & i comes towards you as it scales up. this effect can already be achieved with the scaling & looks good, but the default & only speed of resizing is quite fast. it would be great to be able to adjust it.

**Comment by helenvarley** [comment]
this is kind of possible using the lightbulb - turn it off then do all the movements then turn it on & audience sees it all; maybe not really slowing down scaling but has that effect.
