### ISSUE TITLE
avatar voices

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#57]
as a logged-in player, i expect to be able to select a voice for an avatar from a vast range of voices with a variety of intonation, pitch and accent.

on stage, avatar text should be spoken in that avatar's voice and heard simultaneously by all players and audience members on that stage.

**Comment by elisadcg** [comment]
I imagine a Sound option in the palette for avatar > open other voice option.
![avatar-voice-choice01](https://user-images.githubusercontent.com/7611913/95989170-32e1b480-0e2a-11eb-98eb-8f74c487e95c.png)

**Comment by vickis** [comment]
Agree shout and whisper a code but changing speech to text voice option as
a right click function if possible would be great!

**Comment by elisadcg** [comment]
Do you think the shoud and whisper have to be direct accessible since the chat ? Or do you prefer in the others palettes ?

**Comment by helenvarley** [comment]
i prefer directly accessible in the chat. you need these options when you are about to input text, so having them somewhere else means more cursor movement so it slows it down.

**Comment by vickis** [comment]
agree :)

**Comment by elisadcg** [comment]
Ok so probably this action have to be near the chat, we have to think in a good integration. Probably in hover on the text input or just aboce like in this github filed :)

![issue57](https://user-images.githubusercontent.com/7611913/97996015-9044a200-1de7-11eb-99fc-93f390e69029.png)

**Comment by helenvarley** [comment]
this looks good :) but i wonder if we need options to change the voice here? or it should just be the think/shout options?
normally, we select a voice for an avatar & that's the voice it has for the whole performance. we do try out different voices during rehearsals, but then we don't need to be accessing them so quickly. 

i think that the "normal" one doesn't need to be included in these options - it could be that you select "shout" & then there is something to indicate that you are in shout mode (e.g. a red line around the text input field) until you de-select it. 

the other option needs to be called "think" rather than "whisper" - whispering is different, that's what we've used for private chat with other players, not visible to the audience. if we don't need to use "whisper" as the term for that, maybe we could have 3 options for text2speech (as well as the "normal" or "default")
- shout: slightly louder volume, slightly higher pitch; text in speech bubble & chat window is in capitals & red; shouting speech bubble shape
- think: silent; text in speech bubble & chat is pale blue (?); thinking speech bubble shape
- whisper: quieter volume, slightly slower pitch; what colour for text & shape for speech bubble?

**Comment by elisadcg** [comment]
![issue57-b](https://user-images.githubusercontent.com/7611913/98219391-3bbb3700-1f4d-11eb-95cf-4011dff7cca2.png)
ok i change the wireframe. Probably the order of the button will change. I don't know if we need to change the color in the chat, maybe a simple style is enought (like italic for thinking and UPPERCASE FOR SHOUTING). But i have update the bubble for the avatar too.

**Comment by helenvarley** [comment]
great :) 
previously in UpStage we have had these bubbles; i'm not saying they have to be the same, but i quite like the fluffy cloud of thought and the jagged edges of shout.
![speech_helen](https://user-images.githubusercontent.com/3437324/98269302-d89dc480-1f8d-11eb-93ed-7d18ff50da33.jpg)

![think_vicki](https://user-images.githubusercontent.com/3437324/98269198-c459c780-1f8d-11eb-8309-c5abf56685aa.jpg)

![shouting_dan](https://user-images.githubusercontent.com/3437324/98269140-b146f780-1f8d-11eb-863e-d151468ec20e.jpg)

**Comment by helenvarley** [comment]
can the avatar's speech bubbles be a bit bigger, and also stay visible longer?
once we have the text2speech voices this will probably need to be adjusted again, but the length of time that the speech bubble is visible should relate to the length of the text - it stays visible longer if there is a longer piece of text.
previously the speech bubbles faded away - this is perhaps better than the current quick disappearance, as it means that you have a bit of warning that it's going to disappear.

**Comment by elisadcg** [comment]
![Screenshot_20210402_111543](https://user-images.githubusercontent.com/7611913/113401854-61395900-93a4-11eb-8fb4-4d06713d15a9.png)
do you think something like that could be good ?

**Comment by helenvarley** [comment]
is it not possible to have the comic-book style? a cloud for thinking & spiky for shouting?

**Comment by gloriajw** [comment]
This is a very good demo of some possibilities using the window.speechSynthesis library: https://eeejay.github.io/webspeechdemos/
I'll pass this to Phat and ask him to set up similar options for an avatar.

**Comment by gloriajw** [comment]
The advantage of this is that there's nothing for users to install. The disadvantage is that voice options are entirely determined by what is available in the browser, which means some user experiences could be different during a live event.

**Comment by helenvarley** [comment]
interesting ... how different might the voices be?

**Comment by helenvarley** [comment]
hi, we need to be able to "think" - that is, have un-voiced avatar speech that comes out in a thought bubble (see images above).
how hard is this? we kind of need it urgently for the works-in-progress that we are rehearsing now & will show in late june ... @nguyenhongphat0 ??

**Comment by helenvarley** [comment]
can we have an option for an avatar to have no voice? sometimes you want to have an avatar that can speak with text bubbles but without sound.
i guess a work-around would be to reduce the volume, but it would be good to have a "no voice" option in the voices list as well.

**Comment by vickis** [comment]
the option to mute?

**Comment by helenvarley** [comment]
that would be good too - quicker than going into the context menu and sliding the volume right down. 
i still think it would be useful to be able to have an avatar that has no voice at all - can't think of an example right now but i'm sure in the old UpStage we had reason to use the no-voice option ...

**Comment by vickis** [comment]
we had  : whisper
which was text thought but not spoken

(and also ! SHOUT )
both of these are useful for dynamism in the spoken parts of any perfromance

**Comment by helenvarley** [comment]
thinking! (whisper was the private communication) & yes we definitely want thinking! but this is also different to having no voice. i "think" there is already an issue for thinking & shouting (#136?)

**Comment by vickis** [comment]
Omg yes thinking
If no voice ... isn’t that then a prop

**Comment by helenvarley** [comment]
ah, good point! ok, then let's not worry about no-voice option for avatars :)

**Comment by helenvarley** [comment]
should we close this issue, as we now have avatar voices, and open a new issue for thinking / shouting speech bubbles?
