### ISSUE TITLE
playing video on stage

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#571]
it has been that a video could be played as a stream on the stage. there is still the bunny video as a test. however now, it doesn't seem possible to add a video or a url to a video online, as a stream.
how can we play a pre-recorded video on the stage?
can we just upload it as another media item?

**Comment by vickis** [comment]
the action is replace (this gives you an option to upload a file
[image: image.png]

>. eg replacing a stream with a video


however i just tried by uploading a file and adding to
- demo stage on dev app
- holodeck on app1 (this appeared to be uploading the video

but neither appear to be working

**Comment by helenvarley** [comment]
> the action is replace (this gives you an option to upload a file

ok, that's not very intuitive.
there are video formats listed in the permitted media formats (that show up when you hover over the New + button to add media) so it should be possible to upload video and play on the stage ... maybe it works as a prop? i will try to test it tomorrow.

**Comment by vickis** [comment]
you can create it by going straight to the file (in this case mp4) but the
option you have is stream

however i have created the video file and added to the holodeck stage
but  it will not remain on stage  or play ....

**Comment by helenvarley** [comment]
i tried just now with an .mp4 video that is under 1MB. i was able to upload it & assign it to a stage, but like vicki says, it does not remain on stage when i drag it on, it just disappears.
i tried this on dev-app, on my test stage.

**Comment by helenvarley** [comment]
maybe we just leave this for now and if we want to stream video we do it through OBS as a live stream (manel was doing this today & it nworked well)

**Comment by vickis** [comment]
Ok but useful to have both options if wishingbto stream live and later
video which we should be able to do :)

**Comment by helenvarley** [comment]
that can be managed pretty easily with sources in OBS :)

**Comment by helenvarley** [comment]
i'm closing this issue because we are now discussing in #716 whether or not we want to be able to upload video or just play it as a stream.
