### ISSUE TITLE
clear player chat?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#576]
it doesn't seem to be possible to clear the player chat.
the on-stage clear chat button clears public chat, but not player chat
the clear chat and sweep stage buttons in stage management do not clear the player chat
how can we clear the player chat?

**Comment by nguyenhongphat0** [comment]
Sweep stage button in stage management clear the player chat, I remembered we discovered it somewhere 😅

**Comment by vickis** [comment]
great!

**Comment by helenvarley** [comment]
i can't test this as the stages are all offline for me :/
but also i'm not sure that it's the solution we need. sometimes we will want to clear only the player chat, and not the public chat, or the other way around ...

**Comment by helenvarley** [comment]
this is connected to #658 #659 and #661 i think? - it's about separating out the player chat from the public chat.

**Comment by tunguyentk** [comment]
@helenvarley  @vickis  I have created 2 clearchat buttons in public chat and player chat , and I have adjusted the clear chat button in stage management to clear player chat too .  I have deployed it, please check.

**Comment by vickis** [comment]
great work tested and working :D

<img width="1241" alt="image" src="https://user-images.githubusercontent.com/4249450/207740874-b789b4fd-38fa-433a-93d0-7604a13cd98e.png">

**Comment by helenvarley** [comment]
great, this looks good and works as i expected.
i also checked that the clear chat button in the backstage stage management interface clears chat in both windows.
and the clear button is not visible to audience - perfect :sunglasses:
