### ISSUE TITLE
after watching replay recording, backstage navigation does not work

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#586]
i watched a replay recording, then used the back button in the browser to go back to the recordings archive. from there, none of the navigation worked,
when i clicked on the top nagication (stages, media etc) or the left-hand navigation options, i saw the url change, but the page did not change.
clicking on the enter button to enter the stage did nothing.
the buttons for the recording (chat, download, edit, delete) all work.
i discovered this in Firefox, and replicated it in Chromium, so it's not just a Firefox problem.
i had to do a shift+reload to reload the page, and then the navigation worked.

**Comment by helenvarley** [comment]
i have also encountered this today when in the backstage, and using the back button in the browser to return to a previous screen. i was in stage management, went into media management, and then tried to go back to stage management of the specific stage i had been in by using the back button. reloading the page solves the issue, but it's annoying ...

**Comment by helenvarley** [comment]
also when i'm in a stage and use the back button to go back to the stage management, none of the navigation works until i refresh the page.

**Comment by vickis** [comment]
Is this because of local caching
Which we need for the stage to function smoothly

**Comment by helenvarley** [comment]
why would that stop the navigation from working?

**Comment by vickis** [comment]
sorry - I just tried the same and better understand the issue :)

**Comment by elisadcg** [comment]
yep i noted this behaviour. You have the refresh the page. 
It's like : if you resize the window, none of the content resize itself, like in another website. You have to refresh.
Don't understand why :/

**Comment by nguyenhongphat0** [comment]
This got fixed on dev-app1 now ☝️

**Comment by helenvarley** [comment]
excellent - tested on firefox and chromium & navigation now working when using back button after watching a replay :)
