### ISSUE TITLE
watching replay in firefox, frame of object drawing is visible

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#587]
i made a recording to test the drawing tool, and found that when i watch the replay in firefox, i see the frame of the object drawing. i do not see this in chromium.
replay: https://app1.upstage.org.nz/V4.0/ui/replay/helen/26
![Screenshot from 2021-09-27 13:00:38](https://user-images.githubusercontent.com/3437324/134896385-a2cee7d4-1445-4626-b744-7c8c4651f7b1.png)
![Screenshot from 2021-09-27 13:02:49](https://user-images.githubusercontent.com/3437324/134896500-7ce0b2b0-2b56-4378-9d24-a10baba547de.png)

**Comment by nguyenhongphat0** [comment]
This was fix as part of PR #608

**Comment by nguyenhongphat0** [comment]
> in this recording, i made first an object drawing and moved it around the stage

Did you turn on the light bulb? Just asking 😅
