### ISSUE TITLE
can same image be used for backdrop and curtain without reuploading?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#591]
currently if i want to use the same image as a backdrop and also a curtain, i need to upload it twice, once as a backdrop and once as a curtain. is it possible to select a curtain from uploaded backdrops?

for the cover image, it seems possible to select any type of graphic media - i see backdrops and also avatars as available media when i want to select a cover image. so it should be possible for curtains to be selected from backdrops ?

**Comment by vickis** [comment]
It makes sense to have two images as they have separate functions as
objects but if it’s possible and saves on stage load due to file size then
it would be useful would the instruction be to make a copy and assign that
the new action as object :)

**Comment by helenvarley** [comment]
vicki & i decided that it's better to just leave this that you have to upload the image twice, in each media type.
