### ISSUE TITLE
multiframe upload workflow

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#592]
there are several issues with the mutliframe process:

i want to make a multiframe backdrop, starting with an image that i have already uploaded to test.
i click on the edit button for that image and open its edit interface. 
i select the multframe tab, and set the toggle to multiframe.
i expect the image that i had started with to appear already selected as a frame, but it does not.
if i've recently uploaded it, then it's not difficult to find. but if it's been uploaded a while ago, or a lot of players are currently uploading, i have to scroll a LOT to find it. i can't even filter by media type to make it easier. 

- [x] can it be that, if i have come to the multiframe tab from the edit screen of an already uploaded media item, it automatically appears in the right-hand column as selected?
- [x] can it also only display media of the same type as available? (presumably if i'm making a multiframe backdrop, i'm not going to be adding avatars or props as frames, or vice versa)

i find and select the image that is already uploaded. then i want to add more images. there is a drag&drop option. i drag the next image there, and the browser displays the image.  just the image. i'm not on the media edit interface anymore. so i use the back button to return, and i'm back on the media management page. i have to start the process again. 

- [x] it seems that the drag&drop upload doesn't work at all.

so i try again. this time i click to upload, and it works. i give the multiframe backdrop a name and then i click on stages to add it to the stage. then i click on the multiframe tab again - and discover that the second image i added to upload is no longer there. i click to add it again, and this time click save immediately without going to any other tabs. 

- [x] can the added images be remembered if you go to another tab before saving? if not, there must be an instruction to save there on the mutlframe tab.

**Comment by vickis** [comment]
it is understandable if you navigate away from the form that is not saved
it will lose information so save progress is important
agree updating a current backdrop to ad further frames is important :)

**Comment by helenvarley** [comment]
but it's not navigating away from the form, it's just going to another tab within the form. there's only the one save button at the top for all the tabs, so it would be logical that you only need to click that save button once you've entered the info in all or any of the tabs.

**Comment by vickis** [comment]
ok thats clear
perhaps there could save and proceed?

**Comment by nguyenhongphat0** [comment]
There is so many issues about the current media tab 🤦. I'm thinking about a full rework of it, but it might not be completed soon (at least in IG-11), the bug fixes need to be taken out first!

**Comment by helenvarley** [comment]
yes, let's re-think it after the launch :)

**Comment by nguyenhongphat0** [comment]
Ah we still have the `Add existing frame` button under construction :sweat_smile:

**Comment by helenvarley** [comment]
i just tested the new upload workflow in the Studio & it's great :)

but now there is a problem in the media list of the studio - my one multiframe avatar takes up half the screen space because it has 11 frames.
for multiframe media items in the media list - would it work to have just the first frame showing, with the multiframe icon in the lower left corner, & when you hover your mouse over it, the other frames show as a rollover?
