### ISSUE TITLE
multiframe backdrop speed slider not visible

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#593]
with backdrops of 800x600 proportions, the slider for adjusting the animation speed of a multiframe backdrop is not visible or accessible in the toolbar.
![multiframe_slider](https://user-images.githubusercontent.com/3437324/135068396-8b44ea67-e3ad-46bd-b018-867f05d5881b.gif)

the slider is also pretty difficult to adjust precisely, and even at slowest speed is still not very slow. would it be better instead of a slider to have a number value in the right click menu that could be adjusted?

**Comment by helenvarley** [comment]
note - it is necessary to have 800x600 backdrops if you have the 16x9 layout and want the backdrop to fill the stage when it's viewed in full screen.

**Comment by nguyenhongphat0** [comment]
The slider is now part of the context menu now 👇 I can't remember why I put it below the backdrop while we have a context menu for that 😆 I also fix the issue when you right click on the backdrop, it switch back to first frame 👌 

<img width="422" alt="Screenshot 2021-09-28 at 22 48 46" src="https://user-images.githubusercontent.com/29925961/135122414-a6db99c7-f9c0-4d74-b71a-e97ebcc3323f.png">

**Comment by nguyenhongphat0** [comment]
> the slider is also pretty difficult to adjust precisely, and even at slowest speed is still not very slow

Yeah I also updated the slowest speed limit

**Comment by helenvarley** [comment]
awesome! is it on dev-app to test?

**Comment by vickis** [comment]
great!

**Comment by vickis** [comment]
![image](https://user-images.githubusercontent.com/4249450/135163998-add0a9c8-cdfe-4fc4-9548-f7b4e8b6f491.png)

**Comment by vickis** [comment]
Agree :)

**Comment by vickis** [comment]
The animation speed needs to allows be set to lowest as you have to push play to access the animation - and you can adjust change from first frame - currently still with slider at midpoint on UpStage.live

**Comment by nguyenhongphat0** [comment]
You can start the animation at any speed that you want now 👌 

![multiframe-backdrop-speed-slider-always-visible](https://user-images.githubusercontent.com/29925961/141799029-9c57a064-2e83-43fb-a058-b2b16304f658.gif)

**Comment by vickis** [comment]
super thanks Phat :)
