### ISSUE TITLE
multiframe backdrop: right click returns to first frame

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#594]
i have a multiframe backdrop on the stage, set at the second frame. i want to change it to the third frame, so i right-click on its thumbnail in the backdrop overlay to access the context menu.
but as well as opening the context menu, the right-click also changes the backdrop back to the first frame. this should not happen, it should stay on the selected frame.

**Comment by vickis** [comment]
agree

**Comment by helenvarley** [comment]
this has been fixed & is working as expected on dev-app :+1:
