### ISSUE TITLE
odd bug when stage cleared

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#595]
on the mobilise/demobilise stage, and a new one that i have just cloned from this stage, the icon for a missing stream is showing, huge. i can't move it, select it, delete it or do anything with it. 
nothing is showing in the depth tool so i can't remove it from there either.
i clicked Blank Scene to try and remove it, but all this did was remove the selected background colour. the missing stream icon is still showing. 
i have reloaded several times but it's still there.
if i select a backdrop, it covers this icon, but the icon should not be there ..
![Screenshot from 2021-09-28 15-21-12](https://user-images.githubusercontent.com/3437324/135096152-691bec4c-cd5c-4a21-9edf-efb5ecca56d1.png)
.

**Comment by helenvarley** [comment]
i also tried sweeping the stage in the stage management, this also hasn't removed it.

**Comment by nguyenhongphat0** [comment]
This means the current backdrop is missing, this could be happened if you delete the backdrop in the backstage while it is still being used 🤔

**Comment by helenvarley** [comment]
ah ok! i am making a multiframe backdrop and having to replace several images as things were too big.
however i have now reuploaded the images and refreshed the stage and i'm still getting this when i take the backdrop off ...

**Comment by helenvarley** [comment]
so now i made a completely new stage on dev-app (https://dev-app1.upstage.org.nz/V4.0/ui/live/mobilise-demobilise/) and uploaded my multiframe backdrop, then entered the stage and ... there's the big missing stream icon!!!!!

**Comment by helenvarley** [comment]
![Uploading Screenshot from 2021-09-28 18:57:59.png…]()

**Comment by helenvarley** [comment]
today i am seeing this big icon in firefox, and not in chromium. i am on elisa's test stage as audience. she is there as player and doesn't see it.
![Screenshot from 2021-09-29 14:05:05](https://user-images.githubusercontent.com/3437324/135265827-33b3b9eb-8439-499a-b62f-52ba4b37d07b.png)
.
![Screenshot from 2021-09-29 14:06:22](https://user-images.githubusercontent.com/3437324/135265878-f8fe5ffb-6194-46e9-8df2-5d38120e5306.png)

**Comment by helenvarley** [comment]
still seeing it ...

**Comment by vickis** [comment]
Ghost in the machine!

**Comment by nguyenhongphat0** [comment]
The bug fix is not yet merged to dev-app1, please be patience 😅

**Comment by helenvarley** [comment]
oh, that's the one thing i'm really bad at - patience! :rofl:

**Comment by nguyenhongphat0** [comment]
Now it is on dev-app1 now, you can try this stage: https://dev-app1.upstage.org.nz/V4.0/ui/live/brand

**Comment by helenvarley** [comment]
great! it looks like you squashed that bug! :clap:
