### ISSUE TITLE
stage status and order of stages on foyer page

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#598]
this is probably two issues but it is going together in my head so i am putting it down as one :smiley: 

it would be helpful to see, and be able to change, the status of a stage in the stages list. is there room for another column that shows the status (live, upcoming, rehearsal) and that can be changed there in the stages list? 

and the order of stages displayed on the foyer should reflect their status: live stages should be first, then upcoming. at the moment on app1, i see the demo stage (which is live) and my stage (which is upcoming) in the first row. the streaming test stage (also live) is in the very last row.

**Comment by vickis** [comment]
Agree!
A way to pin particular stages if there is a way to order them would also
be good (although at this stage a nice to have perhaps :)

**Comment by nguyenhongphat0** [comment]
> it would be helpful to see, and be able to change, the status of a stage in the stages list. is there room for another column that shows the status (live, upcoming, rehearsal) and that can be changed there in the stages list?

We already have that 👍 

The order of the stages is belong to issue #840, so this issue can be closed now 👌
