### ISSUE TITLE
masquerade as audience

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#599]
often during rehearsals we want to see how the stage looks for the audience. currently the only way to do this is to open another browser and enter the stage without logging in, but in order to be able to do this, the stage has to be made live.
right now this isn't a problem because our url is not public, but once we have launched then actually it will be a problem - if we have to make a stage live just to see it from audience perspective, then other random people would also be able to enter.

can there be a way that logged in players can masquerade as audience, or somehow access the stage in audience view, when its status is still rehearsal or upcoming?
assigning several people in case someone has a brilliant idea about how this could work :smiley:

**Comment by vickis** [comment]
Simplest would be minimise toolbars button (not quite audience as would
still see live bulb and frames
But an audience preview option if possible would be fabagree :)

**Comment by helenvarley** [comment]
minimising the toolbars won't mean we're seeing what audience is seeing. for example today, we were still seeing other people's media frames on the stage as players, but checked & saw that audience do not see these frames - so this is annoying but not as bad a problem as if the audience were seeing them (as during the presentations in june).

**Comment by elisadcg** [comment]
Excellent idea. I think this option should be on the toolbar. What do you think. Like the last tool ?

**Comment by helenvarley** [comment]
actually what might make more sense is to have a toggle by your name in the statistics drop=down of who is on the stage, as it's not really a performance tool, which is what all the left-hand tools are for. normally you would want to do it during rehearsals and when trying out media on the stage, or when testing new features. you wouldn't normally want to do it during a performance.

is that technically possible, to have an icon at the right of your name that would allow you to switch to audience mode and back again? this would only be available for logged-in players who have player access on the stage. when you clicked on the masquerade as audience toggle, you would then see the stage exactly as audience see it, but you would still have the toggle in the statistics dropdown so that you could then toggle back to player view, without having to reload the stage.

**Comment by vickis** [comment]
Agree to toggle placement by individual status /settings on the right (if
possible :)

Generally in online building a preview function has to reload from ‘editor’
to remove all the tools
perhaps the toggle could open in a new tab or window

 Or in backstage you have an enter as audience option?
Which follows usuallwrmissions but avoids having to log out
Vicki :)

**Comment by nguyenhongphat0** [comment]
> Excellent idea. I think this option should be on the toolbar. What do you think. Like the last tool ?

I'm not fully understand the idea of putting it inside the counter statistic 🤔 So I followed Elisa idea to put it in the Settings tool, since it requires less effort to implement 😅 Let me know what you think about this:


<img width="1393" alt="Screenshot 2021-10-02 at 14 52 20" src="https://user-images.githubusercontent.com/29925961/135708595-6ef9146f-dbf6-4e35-ad16-94df266e7153.png">

<img width="1394" alt="Screenshot 2021-10-02 at 14 52 33" src="https://user-images.githubusercontent.com/29925961/135708600-8f8421f0-3f83-4f7a-9fe3-0f27f6ba30e8.png">

**Comment by helenvarley** [comment]
ok, that looks fine & if it's easier then let's do it.
one suggestion - could the button showing that you are masquerading and that you can click to go back to player view, be over by the "live" button and statistics, above the chat?
it means less mouse movement, if you are just quickly checking how something looks and then want to go back to player view; and it makes sense to me to have it over there with the status & player/audience numbers. we haven't used that top left corner for anything else yet & maybe at some point there will be something that needs its own place that we could put there.

**Comment by nguyenhongphat0** [comment]
> one suggestion - could the button showing that you are masquerading and that you can click to go back to player view, be over by the "live" button and statistics, above the chat?

You got it 👌 It is on dev-app1 now, feel free to test 😆

**Comment by helenvarley** [comment]
very cool! :sunglasses:

**Comment by vickis** [comment]
Great work! :)

**Comment by helenvarley** [comment]
one thought - the icon is not in the same style as all the other icons. @riadsalameh do you have any ideas for it?
