### ISSUE TITLE
GDPR regulations

### ISSUE THREAD

**Issue by vickis** [upstage-org/upstage#6]
as an admin the creation of a new user has capacity built into it to ensure compliance with current GDPR regulations on data collection and security

**Comment by helenvarley** [comment]
yes we need to make a privacy policy!

**Comment by paul-rohrlach** [comment]
Didn't we reach out to CCT for assistance wit this?

**Comment by helenvarley** [comment]
actually it was the Creative Europe project officer who said that she would look at it. one of the many things i haven't had a chance to follow up yet ...

**Comment by vickis** [comment]
Yes I think there was discussion about this because of the data privacy
focus in EU
There must be something we could modify to fit surely :)

**Comment by helenvarley** [comment]
phat has removed the phone & "ok to sms" from the player profile, & replaced it with a toggle "agreed to terms" (see #199) - so there should be a link to the terms here on the profile page, AND on the registration page

**Comment by paul-rohrlach** [comment]
The registration page should contain a checkbox "agreed to terms" which must be checked in order to click the Register button. 

We could also put a "fine print" hyperlink to the terms on the log-in dialog that says "by logging in, you are agreeing to..."

**Comment by paul-rohrlach** [comment]
SEE #228 and #229

**Comment by helenvarley** [comment]
do we need to agree to the terms of service every time we log in? it doesn't hurt, but given that most players will be logging in regularly, & have already agreed to the terms & conditions when they registered, it's maybe a bit too much? but i guess it gives them a reminder that these things exist ... ??
& do we need a way to contact all registered players on a particular instance if/when the terms & conditions change? or could we use the login screen to do that, e.g. a notice comes up saying "the t&c changed on [date] - please click here to read the latest version" ... ?

**Comment by elisadcg** [comment]
I don't think an agreement each time we log in is necessary. Only when we creat a login for player. And for audience, if they need to agree, only when they subscribe to a Stage or go in a Live Stage ?

**Comment by helenvarley** [comment]
probably the best place for the audience to accept the T&Cs is in the ticketing process; then they have time to actually look at it. but there can be situations where they are getting a ticket at the last minute, in which case i think the best thing is a sentence like "By entering this stage you are agreeing to the T&Cs" with a link there to the T&Cs for anyone who really does want to read them.

**Comment by paul-rohrlach** [comment]
On login, we're simply reminding the user that using the system is subject to the terms of service, we're not asking them to confirm each time.  Most people will probably just ignore it, but it's a "cover your @$$" measure on our part.

**Comment by paul-rohrlach** [comment]
I'd like to focus this back on our requirements under GDPR - Do we have any idea what we actually need to do?

**Comment by vickis** [comment]
I would say comply with all EU regs as we are currently being funded
through Creative Europe (for the performance series anyway which includes
the UpStage update

although legally still an NZ entity as I understand it?
its seems a useful list of things to consider
https://advisera.com/eugdpracademy/knowledgebase/a-summary-of-10-key-gdpr-requirements/

**Comment by helenvarley** [comment]
UpStage itself is not a legal entity anywhere; but as you say we are EU funding & under the CCT umbrella so we should go with GDPR.
here is what we adapted from the CCT's policy: https://github.com/upstage-org/mobilise/wiki/Privacy-Policy
our EU project officer, Olga Sismanidi, said she could pass it on to their in-house legal people for input. i sent it to her on 4th march but have had no response (one of my earlier emails went into her junk mail so maybe this one also did). i will write to her again tomorrow.

if you have any other templates or other platforms' policies that might be close to ours, let's have a look at them.

**Comment by helenvarley** [comment]
as an update to this: UpStage has now got a legal identity, as a registered company in New Zealand. however we are operating internationally (most of the people working on UpStage - developers and artists - are not in NZ). i think GDPR is stlil the most comprehensive so it's good to keep going with that.
as well as the privacy policy, we need a Terms and Conditions for players. at the moment the T&C link from the login & registration forms goes to the GPL licence for the software, which is better than going nowhere but is not relevant for artists wanting to create a player account. they are not downloading the software. we need T&Cs that relate to a player's use of https://upstage.live/
(i cannot work on this right now but am noting this here in the hope that we get to it at some point ... )

**Comment by helenvarley** [comment]
closing this as we do have the T&Cs now & the link is working correctly.
