### ISSUE TITLE
scroll bar has disappeared on audio toolbar

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#600]
we are working on https://app1.upstage.org.nz/V4.0/ui/live/mobilise-demobilise which has a lot of audio files on it, and the scroll bar has disappeared from the audio overlay. there used to be one ...
it's possible to scroll if you have a tablet or trackpad, but if you don't, then there is no way to access the audio tracks that are not visible; & for some of the artists even with a trackpad it is difficult to scroll.
we don't have enough audio files on dev-app for me to see if the problem is also there, but basically - we need to have a scroll bar when there are more audio tracks than can be visible at once.

(we are using both firefox and chrome, and no scroll bar for audio overlay)

**Comment by nguyenhongphat0** [comment]
Which browser are you using, Helen? I'm using Chrome and the slider is still showing for me 🤔 

<img width="958" alt="Screenshot 2021-09-30 at 09 11 12" src="https://user-images.githubusercontent.com/29925961/135374231-a12e5b57-488a-432a-b458-75b9a3e63204.png">

**Comment by helenvarley** [comment]
i was using firefox, the artists were using both firefox and chrome and could not see it on either.

**Comment by nguyenhongphat0** [comment]
Oh I remember now 😅 Since I cannot make the scrollbar thinner on Firefox, I have to hide it so that it won't cover the duration slider 👇 

<img width="307" alt="Screenshot 2021-09-30 at 22 58 32" src="https://user-images.githubusercontent.com/29925961/135490301-5ab4e1a6-55c4-42d0-be7e-659c66809cea.png">

I'm bringing the slider back, and adjust the position of the audio player (a little bit higher) to fix the issue. I also make the scrollbar auto dismiss, so you will see it when hovering on it, let me know if you like it or not 👌

**Comment by helenvarley** [comment]
sounds like a good solution; the play button could also be smaller, would that help?

**Comment by vickis** [comment]
Great job at working back through that issue ;)
Agree a slightly smaller play button and the scroll bar visible OnHover  is
a great solution
I have a track pad so scrolling was always possible for me!

**Comment by helenvarley** [comment]
well the scroll bar is there now, but with an interesting effect in firefox - this gif animation doesn't quite capture it, it's a bit more strobe-like in reality!
![audio_scroll_glitch](https://user-images.githubusercontent.com/3437324/135760420-daae9a44-edd9-4833-924c-5e96bd8bcaa0.gif)
:

**Comment by nguyenhongphat0** [comment]
> every time she scrolls to the left she leaves the stage.

This is the browser swipe left gesture, we can't prevent this on UpStage. We already have an issue for that #277

**Comment by helenvarley** [comment]
oh this is weird - now it's stopped doing that. i made my browser window much smaller as i realised that this stage has 10 audio files, so in fact i was seeing them all already, when the scrollbar was flashing.
when i made it smaller - the scrollbar appeared and did not flash & was useable.
then when i made it bigger again, the scrollbar does not appear & isn't needed.
so i think it is fixed! :)

**Comment by helenvarley** [comment]
apparently there is still no scrollbar in opera - has anyone tested? i don't have opera at the moment on this laptop ...
