### ISSUE TITLE
loading screen message

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#601]
could the loading screen message please just say "preloading media" rather than "preloading avatars, props and backdrops" ?
it's also preloading audio files, but really the audience only needs to know that it is loading media.
this is a really minor & non-urgent thing.
![Screenshot from 2021-09-30 08:34:17](https://user-images.githubusercontent.com/3437324/135399940-211be551-1120-462f-ba2d-c2618859ee77.png)
,

**Comment by vickis** [comment]
agree - something that _should_ be just a text change in code right?
a useful change to implement if possible :)

**Comment by helenvarley** [comment]
great!
