### ISSUE TITLE
player upload limit enhancement

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#609]
this is a non-urgent issue, can wait until after the launch :)

i added some more audio files to dev-app in order to test the audio scroll bar, and one of them was 2MB so i increased my upload limit to be able to upload it.
i moved the upload limit slider a miniscule amount to the right, & got the message:
![Screenshot from 2021-10-03 17:19:23](https://user-images.githubusercontent.com/3437324/135760540-f6eab56d-9a7e-405f-9397-a93dceb9d9dd.png)
i don't want to increase my limit to 28MB, but it's almost impossible to increase it to anything less.

Normally we wouldn't want to increase anyone's upload limit to more than about 5MB, or perhaps in an extreme situation 10MB. anything bigger than that (unless it's video, & i think at the moment we can't actually upload video at all???) is really going to slow down the stage load & may impact on performance.

is it still possible to upload video? i thought we had said that the limit for video files would be 300MB, so presumably this upload limit slider is for all media types other than video?

could it be changed to a dropdown menu that has the options 2MB, 5MB, 10MB and unlimited? (the latter to be used only in extreme situations)

**Comment by vickis** [comment]
Yes agree - it’s a shame to keep everything nice and light for loading then
allow huge files to be uploaded

**Comment by helenvarley** [comment]
this is maybe connected to #1003 or can be done together?

**Comment by vickis** [comment]
Great this works thanks! :)
<img width="375" alt="image" src="https://user-images.githubusercontent.com/4249450/203163085-d982123a-42b5-456e-8856-dc1d248f70cf.png">

**Comment by helenvarley** [comment]
yes this is a great improvement!
the only question is about video: we want to have the default limits be 1MB for audio & images, and 300MB for video. with this system it looks like we would have to manually put it up to 300MB for anyone who wants to upload video, is that right?
is it possible to have a separate setting for video?

**Comment by vickis** [comment]
Perhaps a solution to this would be to have a toggle for video 
> the upload limit for all media apart from video can be changed 
> the upload limit for video is either toggled on (<= 300MB) or off (user must request permission from admin)

**Comment by helenvarley** [comment]
after discussion with vicki, we are wondering whether it might make sense to separate out video from the rest of the media, and make it that players have to be manually allowed to upload video, with a fixed limit of 300MB (we do not want people to unnecessarily upload video and we don't want them to upload long videos at all - this is a LIVE performance platform). i will make a separate issue for this.

**Comment by helenvarley** [comment]
new issue is here: https://github.com/upstage-org/upstage/issues/1036
at this stage for discussion, rather than development - so that we can define what we think will work best first :)
