### ISSUE TITLE
media disappeared from on-stage toolbars

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#611]
tonight during our stream test, when we had been testing for an hour, suddenly there was much less media on the stage.
it seemed to happen at the point that doris and i both took our streams off the stage, so that there were no streams, to see if people who were experiencing slow response when typing in the chat would have a better experience (they did - so we deduced that it was their computers not coping with the streams).
after this, there were only 5 streams showing in the streaming tool bar (there are actually 23 streams assigned to the stage)
i see no audio files (the applause audio is assigned to this stage & earlier in the session i had played it)
i see no avatars (several are assigned to the stage, i had used one earlier, & now doris is putting some onto the stage & i can see them on the stage, but not in the toolbar)

screengrab showing the avatars doris has put on the stage, and me seeing no avatars in the toolbar
![Screenshot from 2021-10-03 21:27:07](https://user-images.githubusercontent.com/3437324/135768814-58ddb9aa-9fc3-46cb-ab00-ef7048fcae6d.png)

screengrad showing that two curtain images are assigned to the stage, but only one is showing in my toolbar
![Screenshot from 2021-10-03 21-23-55](https://user-images.githubusercontent.com/3437324/135768834-a0da3ffe-677c-450a-9327-79aad48e4598.png)

screengrab showing avatars assigned to the stage but not visible to me in the toolbar
![Screenshot from 2021-10-03 21-23-33](https://user-images.githubusercontent.com/3437324/135768846-b1d41263-d6f2-4714-a4ce-5e03aa3b73ee.png)

screengrab showing the 5 streams that i can see, whereas before i could see a lot more (including my own)
![Screenshot from 2021-10-03 21-09-22](https://user-images.githubusercontent.com/3437324/135768886-b79c950b-7afc-40d9-8843-3101bcf0a0f6.png)

tagging elisa, vicki & riad on this issue as they were also there when this happened so may have other info to add

**Comment by nguyenhongphat0** [comment]
As explained before, this is not a stage bug since the toolbar is displaying correctly these assigned media of the stage. I will pull off the bug label, so we can put it in lower priorities and come back again if it still happening 👌

**Comment by vickis** [comment]
Agree :)

**Comment by helenvarley** [comment]
this has not happened again to my knowledge, so i will close it.
