### ISSUE TITLE
purpose of "agreed to terms" toggle on profile page?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#615]
what is the purpose of the "agreed to terms" toggle on profile page?
you have to agree to the terms in the registration process, so presumably this toggle should always be on. because it's a toggle, it means that players can later disagree to the terms by turning the toggle off ...
admins need to know that a new player has agreed to the terms before approving them, but presumably a new registration can't be submitted until you've ticked to agree to the terms ... so if it's showing up in the admin list as waiting for approval then they must have ticked the box.

if there is no need for it to be on the profile page, and it offers the temptation for players to disagree to the terms, perhaps it should be removed?

**Comment by vickis** [comment]
Sure
seems out of place
