### ISSUE TITLE
firefox - offline even though i have done the websocket thing 

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#619]
i am on a different network this week, & am not able to enter live stages using firefox. i get the message popping up to change the websockets setting, but i already have changed it, & i checked that it has not somehow changed itself back (it has not).
i can enter stages using chromium, so it's not really a problem, but i'm wondering what might be stopping firefox from working on this network when it has until now on my network at home - can it be something to do with the network? if so, is this something that we can document somewhere for anyone else who has the same problem?
i can access the backstage, and the stages load (slowly) but remain offline.

**Comment by nguyenhongphat0** [comment]
> i can access the backstage, and the stages load (slowly) but remain offline

This issue must have happened during the mqtt broker outage 🤔 It shouldn't happen in normal condition!
