### ISSUE TITLE
include audio in scenes?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#621]
currently the scenes tool only works with pre-uploaded image objects (backdrops, avatars, props)
it would be very good if it also included pre-uploaded audio files - is this possible?
this would mean that when i select a new scene, any audio tracks currently playing would stop, and any audio tracks that were saved as part of that scene would begin.

**Comment by vickis** [comment]
would be great to enable this!
but perhaps the same potential as the multiframes in terms of sounds
popping up another locations ....

**Comment by tunguyentk** [comment]
@helenvarley @vickis  I made the audio saveable by scenes. When you use newscenes the sound will be stopped and all its state will be stored. Also, I was testing again and found that the blank scenes button could not stop the audio, and then the display in the Audio Tool would fail. I fixed it. Pls checking , Thanks you
![Untitled](https://user-images.githubusercontent.com/117065175/213113646-b19ae297-a73f-4088-9a49-4c3e17e8ba09.png)

**Comment by tunguyentk** [comment]
@helenvarley @vickis I forgot about this, this change only works with new scenes, let's create new scenes to test. Thanks

**Comment by vickis** [comment]
awesome work! closed as completed - thanks :)

**Comment by helenvarley** [comment]
great work!
i noticed that in the test scenes that vicki created on https://dev-app1.upstage.live/viva, the audio files are set to loop, and if i played the second scene (called test two) and then switched to the first scene (test scene audio) the typing audio from test two continued as well.
if i do it the other way around - selecing first test scene audio then switching to test two, the music from the first one stopped.
i made a third scene (test audio) with non-looped sound, & if i switch to this one from either of the other scenes, the looped audio from the previous scene doesn't continue.

vicki - can you try to replicate this?

**Comment by vickis** [comment]
Yes it seems the typing file on loop does not stop with the scene change on
viva stage
however i created a new scene without typing on
https://dev-app1.upstage.live/teststage1111
when different scenes (previously saved and including typing are switched
for the new soundsave scene the typing stops as expected
other sound files or unlooped react as expected

perhaps anomalous to the typing file on loop .... and/or on that stage

**Comment by helenvarley** [comment]
ok then let's close this & monitor it in use :slightly_smiling_face:
