### ISSUE TITLE
audio overlay - enhancement

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#622]
why do we need to turn the volume slider on or off? wouldn't it be better for it to be visible all the time?
also the slider handle being white makes it difficult to see - could it be green?
![Screenshot from 2021-10-09 11:19:55](https://user-images.githubusercontent.com/3437324/136652410-72a6240c-6458-4348-ae2d-0cf42ed96882.png)

**Comment by nguyenhongphat0** [comment]
> why do we need to turn the volume slider on or off? wouldn't it be better for it to be visible all the time?
also the slider handle being white makes it difficult to see - could it be green?

Here you go 👍 
<img width="434" alt="Screenshot 2021-11-14 at 16 24 22" src="https://user-images.githubusercontent.com/29925961/141675392-db347a7c-23e9-458a-90d6-ae35a0b3c89e.png">

**Comment by vickis** [comment]
super!
thanks Phat :D
