### ISSUE TITLE
Multiframe backdrop: animation speed in context menu missing  only available as transparency 

### ISSUE THREAD

**Issue by vickis** [upstage-org/upstage#627]
on right click the context menu shows the individual frames, play button and slider which has changed to transparency not animation speed 

![image](https://user-images.githubusercontent.com/4249450/137014450-b0f9d970-5caf-4d54-a2fd-526112518a09.png)

**Comment by vickis** [comment]
yes please! - that would resolve the need to set animation speed while
saving the scene which i think contributed to the random frame issue :)

**Comment by helenvarley** [comment]
this has been resolved - both sliders display in the right-click menu :+1:
