### ISSUE TITLE
background colour changes when i select a scene

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#640]
i have set the background colour for the mobilise/demobilise stage to a grey-blue colour. when i select a previously saved scene, the background colour changes to a grey-green colour

not urgent, but strange

**Comment by nguyenhongphat0** [comment]
I'm closing this issue now, why? See the picture below 😅 
![61aShmmYzxL](https://user-images.githubusercontent.com/29925961/137588272-134d2edb-31c8-42cf-990f-02f3dfd11564.jpg)
