### ISSUE TITLE
"no voice" option for avatars

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#645]
it would be good to have a "no voice" option for avatars. i think it can be achieved by making the voice volume be right down, but it would be good to have the option to have no voice at all.

for me it would be most logical to have this as the first option in the drop down list of voices.

**Comment by nguyenhongphat0** [comment]
You can click on that `clear` sign to remove voice from an avatar 👇 

<img width="754" alt="Screenshot 2021-12-19 at 18 43 35" src="https://user-images.githubusercontent.com/29925961/146673653-d06637a8-8a42-4c69-b5a0-860fb0168183.png">

**Comment by helenvarley** [comment]
actually i wonder if it's a little dangerous to have it in the same place where we click to change the voice? just now i clicked on it by mistake, when i wanted to try a different voice, & the voice settings immediately disappeared.
i closed the edit window without saving, then reopened it, so i didn't lose the avatar's voice settings, but it was a bit annoying. could there not be a button similar to the replicate button, to remove the voice? then it would be a bit more obvious & less easy to do by mistake ...

**Comment by helenvarley** [comment]
i see that in the voice settings on stage (context menu) "no voice" is listed in the dropdown menu. can it also be like this in the edit avatar interface in the Studio?

**Comment by nguyenhongphat0** [comment]
> i see that in the voice settings on stage (context menu) "no voice" is listed in the dropdown menu. can it also be like this in the edit avatar interface in the Studio?

Sure it can 😄 👇 

<img width="1033" alt="Screenshot 2022-02-03 at 23 41 01" src="https://user-images.githubusercontent.com/29925961/152387620-7de1c05b-69dd-41a9-8a68-66d76ed89494.png">

**Comment by vickis** [comment]
thanks Phat! :)
