### ISSUE TITLE
edit scenes

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#647]
it would be great to have the option to edit a scene that has already been saved.
for example, i have created a number of scenes and now realise that the wrong background colour was there. i would have to resave every scene with the correct backdrop colour, which is possible to do, but it would be easier if there was an option to edit an existing scene.
this could be another right-click option on the scene icon.
and it could be possible from the "scenes" interface in the stage management.

**Comment by vickis** [comment]
agree - i have been deleting and recreating scenes, which does allow clearing and saving the stage between which i hope removes any residual objects attached this needs some attention
