### ISSUE TITLE
issue with second play of non-looped audio track

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#649]
if i play an audio track once, not looped, the slider stops at the end of the track and does not return to the beginning.
so when i try to play the track a second time, it does not play.
the workaround is to manually move the slider back to the beginning.
it should be that when it reaches the end, the slider automatically returns to the beginning, but does not keep playing when it is not set to loop.
![audio_stop](https://user-images.githubusercontent.com/3437324/137582880-b4758453-4d47-474b-9e67-dede74709e58.gif)

**Comment by vickis** [comment]
Yes close and stop return slider to start
Pause retains current play position to restart from :)

**Comment by helenvarley** [comment]
i just checked the pause button & it's functioning correctly, in that it pauses and when you click play it restarts from that point. but i noticed that when you've paused it, there are only the play and loop buttons - the stop button is not there. it would be handy if the stop button was also available in the paused state, because then the play button would be in the same position as the pause button, so you would not have to move your mouse if you are pausing and restarting soon after. it would also mean that you could then easily stop the track, sending it back to the beginning ready for another replay from the start, if you wanted to. otherwise you would have to manually move it back to the start and unpause it.
![Peek 2022-05-09 22-51](https://user-images.githubusercontent.com/3437324/167496892-5764cbdb-64ac-4afd-a6cf-4ed40715fd09.gif)

**Comment by helenvarley** [comment]
this is a double-up with #972
