### ISSUE TITLE
audience chat doesn't always scroll up

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#650]
today in the performance ReMove we observed that the audience chat is not always moving up automatically to show new chat.
if you enter chat yourself, it moves up.
if someone else enters chat, it doesn't always move up. So then you don't know that someone has said something.

**Comment by helenvarley** [comment]
During the Saturday performance of Go Go Go, the chat seemed to be working fine to me. I was watching on 2 computers, one in audience view and the other logged in. both firefox & both linux. the chat always automatically went up, but on the audience computer it was sometimes a bit slow. that computer is on wifi, the other on ethernet cable.

**Comment by helenvarley** [comment]
so far today the chat is scrolling up for me

**Comment by nguyenhongphat0** [comment]
I cannot re-produce this issue. The code logic looks very good to me 😅
