### ISSUE TITLE
media disappearing after adding 

### ISSUE THREAD

**Issue by vickis** [upstage-org/upstage#655]
strange issue where there were no avatars in the stage 
then i went back and added some - saved , saved in general page also and they are there... but when i went in earlier following the same process they had gone ....

![image](https://user-images.githubusercontent.com/4249450/137605029-49a8f505-df3a-4f15-9e76-639771e8337a.png)

![image](https://user-images.githubusercontent.com/4249450/137605059-897bfb10-b3d2-4382-842e-7966ca90b79b.png)

**Comment by vickis** [comment]
![image](https://user-images.githubusercontent.com/4249450/137605108-9d0178f7-9ff1-49f2-9cfd-abc963f7499a.png)
missing from media management (so without saving i go into stage 
![image](https://user-images.githubusercontent.com/4249450/137605122-1d7aee4a-78b6-44fa-9abe-c7ad845a14d4.png)
and they are still there ....

**Comment by nguyenhongphat0** [comment]
As @vickis commented in issue #654: This issue is happening again

- assigning new media (backdrops) is causing other media, previously assigned to disappear

**Comment by nguyenhongphat0** [comment]
Sorry but I cannot re-produce this issue, it's look like network or caching issue. I will close this issue for now, feel free to open it if it is still happening!

**Comment by helenvarley** [comment]
i'm not aware of it happening again :)
