### ISSUE TITLE
option to save chat in on-stage chat settings

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#658]
it would be really useful to have an option to save the chat in the on-stage chat settings (where you can also change your name & do other things). this would make it easy to quickly save the chat while on the stage.
the chat in the Archive section of stage management is confusing - the "download all chat" button creates a different file to the chat that is saved by each recording, & some of these chats are blank even when there has been chat. 
also how is the player chat and public chat separated? usually we don't need to save the player chat, but maybe sometimes we want to.

**Comment by helenvarley** [comment]
this is connected to #659 and #661

**Comment by tunguyentk** [comment]
@vickis @helenvarley  i finished this task . Please check
![image](https://user-images.githubusercontent.com/117065175/211178738-fb29ae58-dded-406f-842c-058520969c9a.png)
It connect to #661 . If everything ok please tick the corresponding box.
![image](https://user-images.githubusercontent.com/117065175/211178777-7d87f027-9a6c-48d5-85a5-2bc2cbee1482.png)

**Comment by helenvarley** [comment]
this is great! works as expected :pray:
