### ISSUE TITLE
player chat also increases when i increase font size for public chat

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#659]
when i increase the size of the font in the public chat, it also increases in the player chat. it would be better to be able to adjust the player chat separately, as i don't need it to be as big, & it takes more space of the stage when it's bigger.
this is very non-urgent.

**Comment by helenvarley** [comment]
this is connected to #658 and #661

**Comment by fuyloon2018** [comment]
Hi @helenvarley I have deployed this issues on Dev-Env, pleas help me check it

**Comment by tunguyentk** [comment]
I have completed the function, but not sure if its interface is really suitable or not?

**Comment by vickis** [comment]
Looking great and tested as working thanks @fuyloon2018 :)
<img width="853" alt="image" src="https://user-images.githubusercontent.com/4249450/205463015-1042a56a-ed4b-4add-9028-91b049860af4.png">
