### ISSUE TITLE
User connection counts not accurate

### ISSUE THREAD

**Issue by paul-rohrlach** [upstage-org/upstage#662]
In the foyer, all stages display one player when there's nobody connected.

![image](https://user-images.githubusercontent.com/2830313/138085038-f738f8fa-472c-46da-b6d2-4e2458531335.png)

**Comment by paul-rohrlach** [comment]
This may not be a problem in dev - Need to test

**Comment by helenvarley** [comment]
i am closing this and adding a reference to it to issue #1146  as this is a newer one.
