### ISSUE TITLE
ability to mute other players' streams

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#669]
during the festival there were a couple of times when someone had a stream on stage that was not muted and was generating feedback, but the player did not seem to be aware or to be able to mute. it would be useful to have a way for players to mute someone else's stream globally.

currently we can mute our own and others' streams locally using the on-stage mute icon. but we don't have a way within UpStage to mute a stream for everyone - we can only do this at the stream source (OBS or Larix) which means that only the player sending the stream can do it.

could this be managed with a right-click menu on the stream thumbnails in the toolbar overlay - similar to the controls for audio, and multiframe backdrops?

adding elisa & riad in case there are icon / workflow implications.

**Comment by vickis** [comment]
we need to be more skilled in the use of the tools - user behaviour training workshops and walkthroughs need to reinforce this :)
