### ISSUE TITLE
Typo in media management

### ISSUE THREAD

**Issue by elisadcg** [upstage-org/upstage#672]
When you upload a new media, and you choose the licence of your media, i think the "information hover" have a mistake : 
![Screenshot_20211030_113218](https://user-images.githubusercontent.com/7611913/139527793-b97ccfd0-7b67-4776-b37b-69aeeceb2391.png)
'Nobody except the owner can user the media item:that is, only the owner can assign it to stages - if it is assigned to a stage then it would be available for players who have access to that stage"

it shoud be 
'Nobody except the owner can use the media item....'

**Comment by helenvarley** [comment]
maybe it can also be simplified a little?

'Only the owner can assign this media item to a stage.. Once it is assigned to a stage it can be used there by players who have access to that stage."

**Comment by nguyenhongphat0** [comment]
Whoops, I hit the merge button before I saw your comment @helenvarley 😅 It won't be able to make it to the hot fix, but it will be shipped along with the next release 👌

**Comment by vickis** [comment]
Great thanks Phat :)

**Comment by nguyenhongphat0** [comment]
It is on dev-app1 now :point_up:
