### ISSUE TITLE
cover image - select, replace but no remove ...

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#676]
once you have set a cover image for a stage, it is not possible to remove it - you can only replace it with a different image. it may not often be used, but it would be good to have an option to remove the cover image without replacing.

and: the pop-up window where you choose a cover image displays ALL images - curtains, backdrops, props and avatars - and there is no way to search if you are looking for a specific image. mostly people will want to use a backdrop or curtain image, but i guess it could be that they might also want to use a prop or an avatar. but already this list is now huge, and unsorted.

can we have dropdown menus here for media type and player, so that we can more easily find what we're looking for?

**Comment by vickis** [comment]
Yes useful addition
