### ISSUE TITLE
clarification of player roles & permissions

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#677]
i am writing the Admin section of the manual, and need to be able to describe the different roles.
We have: guest, player, maker, admin, creator and super admin.

previously, in the old UpStage, "player" had access to the stage tools but not to the workshop. this is the same as what we are now calling guest.

maker had access to the workshop (now Backstage) - so this is what we are now calling player. i think we do not need "maker" any more in the new UpStage.

admin is the same - access to the admin section and also can make changes in the Backstage to other players' stages and media as well as their own. (can players currently make changes to others' media? i'm not sure ... they should not be able to edit media that is not their own ... )

creator is i think basically the same as super user.

so can we remove maker and creator, leaving:

- guest
- player
- admin
- super admin

@vickis does this sound ok to you?

**Comment by nguyenhongphat0** [comment]
Yes some of the roles are redundant, I think we can remove them if they're really unnecessary. Besides, role changes dynamically based on stages. For example, I can be the "maker" of `demo stage`, "player" of `mobilise/demobilise` but "guest" in `repose` 😅

**Comment by helenvarley** [comment]
yes that's true. we need to separate "roles" and "access" :

- a role is the status set by an admin, & it can be guest, player or admin (assuming that super admin is the person who has installed the UpStage instance & created the first admins)
- access is the status given to a player for a specific stage, by the owner of that stage or a player who has been given edit access (or an admin can also do this). access can be audience, player or editor (player and edit access)

it would be logical that an account with the role of guests cannot be given player and edit access on a stage, as the guest role does not include Backstage access.

i think we can delete the "maker" and "creator" roles - unless @vickis remembers some reason that we need them???

**Comment by helenvarley** [comment]
note - we are also using "owner" to describe the player who has created a stage, or uploaded a media item - they are then the "owner" of that stage or media item. 
players who are not admins should only be able to edit their own media, not the media of other players; and should only be able to edit stages that they own (have created) or that they have been given edit access to.

**Comment by helenvarley** [comment]
i just realised that "guest" is also a little confusing, as it is both the role of a guest player and the default nickname for audience members on stage. 
can we think of an alternative name for one of them?

**Comment by vickis** [comment]
perhaps we could use
'temporary player' for the guest logins
because either they go on to have a login or their access is terminated if
unused  :)

**Comment by vickis** [comment]
I don't see any reason for them (i think originally it was to have a more
nuanced level of permissions but this is unnecessary :)

**Comment by vickis** [comment]
Sure - could be just temporary - they can be encouraged to change nickname
 :)

**Comment by helenvarley** [comment]
@vickis - it's not about the nickname, it's about the role & permissions. players can't change this themselves unless they are admins. let's just leave it as Guest for now.

@nguyenhongphat0 please remove "maker" and "creator" from the list of player roles - these are still showing up in the dropdown but we do not need them:
![Screenshot from 2021-12-01 12:11:54](https://user-images.githubusercontent.com/3437324/144224716-9d3ed355-34ac-4d8b-9b65-0a7267b91c06.png)
:

**Comment by helenvarley** [comment]
@nguyenhongphat0 can you please prioritise removing the roles that aren't needed? now that we are rolling out the platform to other instances, it's a bit confusing for them to see options that don't exist - & we need to make screenshots for the manual :)
thanks!

**Comment by nguyenhongphat0** [comment]
Oops I forgot to do that (again), so many things on my to do list 😅
I will do it tomorrow!

**Comment by helenvarley** [comment]
i just realised i have been forgetting to put things into the project ... sorry! i will try to remember ... am about to stop for the evening, but tomorrow ... everything can be done tomorrow! :laughing:

**Comment by nguyenhongphat0** [comment]
Hi @helenvarley, I removed the unnecessary roles (and sorted them) on `upstage.live`, `dev-app` and `meta` instances 👇 

<img width="393" alt="Screenshot 2021-12-17 at 20 53 14" src="https://user-images.githubusercontent.com/29925961/146554700-26403fa6-026a-4c10-832f-3cee721e87cf.png">

**Comment by vickis** [comment]
Super! :)
