### ISSUE TITLE
on chrome/chromium player counter is zero when players on stage

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#686]
there are 3 players on the stage and the counter is showing this in firefox, but not in chromium. the other players are using chrome and also report that it shows zero players
![Screenshot from 2021-11-26 12:38:24](https://user-images.githubusercontent.com/3437324/143575435-ca77016b-254c-4409-b211-3eaa14884d35.png)
.
![Screenshot from 2021-11-26 12:38:02](https://user-images.githubusercontent.com/3437324/143575441-55061a24-fcb9-41aa-ab36-8b49c2b16ea7.png)

**Comment by nguyenhongphat0** [comment]
This was the same cause of #687, due to `event_archive` service stopped, sorry. And it got fixed 👌

**Comment by helenvarley** [comment]
great! i'm seeing numbers on chromium now :)
