### ISSUE TITLE
scenes bug: on entering stage, a specific scene shows, even if a different scene has been selected

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#687]
when a player or audience enters a stage, the same scene shows every time, even if the players have selected a different scene. the scene does not update until another scene is selected.

i have tested this on 3 stages and it is happening on all of them. interakt are also experiencing it. we are using firefox and chrome on a variety of operating systems and it's the same for everyone - when you enter the stage, no matter what scene has been selected, you see always the same scene on entering until a different scene is selected.

tagging all of you as this is urgent - interakt have a performance in 3 hours!

**Comment by helenvarley** [comment]
on https://upstage.live/mobilise-demobilise when i enter it is loading a scene that doesn't even exist on that stage. i had selected the scene "theme", in firefox, then entered using chrome as audience and see this:
![Screenshot from 2021-11-26 12:54:38](https://user-images.githubusercontent.com/3437324/143577250-e1e90869-78aa-46c2-b967-0705886b71c7.png)
when i should be seeing this:
![Screenshot from 2021-11-26 12:55:54](https://user-images.githubusercontent.com/3437324/143577328-0402adb6-74eb-4410-a4bd-1855a670f8ec.png)

and you can see in this firefox screenshot the list of scenes, and there is no scene such as i am seeing in chrome

**Comment by helenvarley** [comment]
![Screenshot from 2021-11-26 13:02:50](https://user-images.githubusercontent.com/3437324/143578213-9d455622-5f9c-4b94-884b-1458daa0a94c.png)

**Comment by helenvarley** [comment]
i just checked every stage on upstage.live and this scene with the go board and dog that appears when i enter the mobilise/demobilise stage doesn't actually exist anywhere at all ...

**Comment by nguyenhongphat0** [comment]
Turned the `event_archive` service on, everything work fine 😅

**Comment by vickis** [comment]
Thanks @phat Helen that was the gif experiment from ages a go ...

**Comment by helenvarley** [comment]
no it was a new bug, as phat explained on slack "It was because of event_archive service got turned off (somehow :sweat:) since 20/11, so the state of the stage couldn’t able to be kept. Turn the service on fixed it. " & then gloria found what had caused it to stop :)

**Comment by vickis** [comment]
yes all understood - i was commenting that the screen / scene you mentioned
as not existing was one from the experiment with the gif/not gif when i was
updating the manual :)

**Comment by helenvarley** [comment]
oh sorry, totally misunderstood that! :laughing:

**Comment by phat** [comment]
For the love of god, please stop tagging me

**Comment by nguyenhongphat0** [comment]
Sorry @phat, they was trying to tag me 😅 Nice account name by the way 😆
