### ISSUE TITLE
backdrops disappearing

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#689]
during rehearsals & performance today on a number of occasions, a backdrop simply disappeared from the stage and left it green (default background colour).
this was not connected to changing a scene.

**Comment by helenvarley** [comment]
i took a clip out of the recording that shows it happening - there is a smooth scene transition, then a moment after writing begins the backdrop disappears; i saw green on my screen, but in the recording it is black. i couldn't get the recording clip smaller so have compressed it to upload.
[2021-11-26 16-29-04-00.05.36.567-00.06.14.818.mp4.tar.gz](https://github.com/upstage-org/upstage/files/7609947/2021-11-26.16-29-04-00.05.36.567-00.06.14.818.mp4.tar.gz)

**Comment by nguyenhongphat0** [comment]
Sorry for the issue. It was that the backdrop image was preloaded but not its frames, so only when someone started animating it, these frame are began loaded. And backdrop are usually large in size, so it took quite long to complete loading. Putting the frames into preload queue fixed it 👌
