### ISSUE TITLE
studio preview of stream ...

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#693]
in the Studio, a stream's preview is showing up as a kind of error message. is it possible to have a placeholder here, or the QR code as shows currently in the media management interface?
not urgent, just something to tidy up at some point :)
![Screenshot from 2021-12-01 14:38:54](https://user-images.githubusercontent.com/3437324/144244535-d95fd8ba-d178-4202-807a-c3ff2e45dd95.png)

**Comment by helenvarley** [comment]
where do we find the preview in the studio? i am trying to test this but don't find the stream preview anywhere.

**Comment by helenvarley** [comment]
actually i am unable to connect to the server to send a stream so perhaps this is why i can't find a preview anywhere ...

**Comment by helenvarley** [comment]
reopening this because i still don't find anywhere that i can see a preview of my stream in the studio ...

**Comment by nguyenhongphat0** [comment]
> i still don't find anywhere that i can see a preview of my stream in the studio

Does that mean you don't have the QR code in the stream preview (like screenshot)
![image](https://user-images.githubusercontent.com/29925961/154815713-3ad00161-710c-4795-8ffd-0671bfca9385.png)

or this is identical to #746? :thinking:

**Comment by helenvarley** [comment]
it's a different issue; the other one was to be able to see the OBS set-up info in the studio as well as on stage. this is about seeing a preview of my stream in the studio. when i am creating a new stream in the studio, or testing which streams are which, or trying to work out what is not working if i'm having trouble with my stream, it would be helpful to be able to see a live preview - as i think we used to have in the media management (& definitely had in the old UpStage). 

the QR code is now showing in the media list, which is good, but it would be good if, when the stream is active, the QR code changes to a live preview. is that possible?

**Comment by vickis** [comment]
I don't recall seeing the preview in media management - just used OBS
if this is not a major then useful addition yes :)

**Comment by helenvarley** [comment]
it's not super urgent :)

**Comment by helenvarley** [comment]
closing this as we don't currently have RTMP stream functionality at all.
