### ISSUE TITLE
multiframe backdrops - upload

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#701]
a curious thing when creating a new multiframe backdrop:
i have 3 backdrop images that i want to upload together as a multiframe backdrop. i click the New + button, and have to select just one image in order to start creating the image.
then in the edit interface, i turn on the multiframe button and have the option to drag or navigate to the other images (drag & drop doesn't work but i think that's a known bug already).
i navigate to the images on my computer and select the second & third images, because i've already selected the first one to start with.
i saw it, and see in the media list preview the three images - one is the main icon and the second two are shown small below it, so the 3 images are there.
on the stage, i see in the backdrop bar the first image with the multiframe icon.
i right click on the multiframe icon, and there i find only the second and third images; when i play the multiframe, it only plays these two images. if i turn the speed of the animation down so that it stops, it shows the first image.
it's confusing - it's like it has created 2 separate backdrops - a single backdrop from the first image, and a multiframe backdrop with the second two.

maybe this will all be resolved in the Studio?
![Screenshot from 2021-12-08 12:39:37](https://user-images.githubusercontent.com/3437324/145202844-e1d3161c-9a3c-4c37-bcf0-326e17b50ff4.png)

![Screenshot from 2021-12-08 12:34:43](https://user-images.githubusercontent.com/3437324/145203047-fdaba1fd-8f6c-4abe-bfe2-030b25856924.png)

**Comment by nguyenhongphat0** [comment]
Jeez, that's why the old media management must be get rid of :laughing: This is already resolved in Studio :ok_hand: 
![image](https://user-images.githubusercontent.com/29925961/145206843-bc18fff6-bb2a-4b26-a6c4-7c546cf28e60.png)

**Comment by helenvarley** [comment]
oh great, i was hoping that was the case! :clap:
