### ISSUE TITLE
multiframe backdrops: slower fade speed

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#706]
currently the slowest possible fade speed for transitioning between the frames of a multiframe backdrop is actually not very slow. it is about 3 seconds. could the slowest speed be really slow, something like 10 seconds?

maybe in general the speed ranges for all multiframe media transitions is something that could be set in the stage customisation? so that people could choose if they want a really slow effect there, and then adjust the individual media items' transition speed within those parameters on stage.

**Comment by vickis** [comment]
agree - that would be great :)
