### ISSUE TITLE
dark mode for chat?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#708]
meta theater asked if it's possible to have a dark mode for the chat. this is partly because one of them was doing a performance in another platform where she wanted a dark scene in her webcam, but discovered that the brightness of the chat window in that platform affected her webcam image and it wasn't possible for her to close or darken that chat.
we talked about whether this should be something that can be done locally or globally, and they thought it would be useful to have it global, as it can also make the chat work better with different backdrops.
i think it would be good if it could be either local or global. is that possible?
adding elisa & riad to this as it could have icon implications.

**Comment by vickis** [comment]
could be useful yes :)

**Comment by nguyenhongphat0** [comment]
I added another switch for toggling dark mode chat in the Settings tool 👇 

<img width="316" alt="Screenshot 2021-12-12 at 00 49 18" src="https://user-images.githubusercontent.com/29925961/145686590-1876ba8c-2ee8-4c10-b571-a9e641e6ab91.png">

<img width="311" alt="Screenshot 2021-12-12 at 00 49 26" src="https://user-images.githubusercontent.com/29925961/145686586-ae4d5dbe-8bc7-4e0f-a205-42c68c29a31b.png">

**Comment by vickis** [comment]
superstar Phat! :D

**Comment by helenvarley** [comment]
wow, so fast! :D 
we might need to tweak it a bit - for example the audience text is now less readable. but let's start with this & see what the artists think.
thank you!

**Comment by elisadcg** [comment]
![Screenshot_20211213_084021](https://user-images.githubusercontent.com/7611913/145771481-30249179-b85e-4e1b-ad24-65036e9fee1d.png)
My suggestion

**Comment by helenvarley** [comment]
that looks good elisa! to have the background not actually completely black makes it less harsh :+1:

**Comment by vickis** [comment]
Yes agree :)

**Comment by elisadcg** [comment]
![Screenshot_20211214_102202](https://user-images.githubusercontent.com/7611913/145969980-99ee3718-5e46-4416-ac0b-b72dadb3e979.png)
If the "bluish" is bad, we can go throught the darkgrey as well.

**Comment by helenvarley** [comment]
yes i think dark grey is better :+1:

**Comment by vickis** [comment]
Agree :)

**Comment by helenvarley** [comment]
@nguyenhongphat0 have you adjusted the colours?

**Comment by nguyenhongphat0** [comment]
Sorry I missed this. It will be available on dev-app1 as soon as someone else approve it 👇 

<img width="333" alt="Screenshot 2022-01-15 at 16 41 02" src="https://user-images.githubusercontent.com/29925961/149617275-252c33ab-08c6-4326-a7b6-279c8773c44d.png">
