### ISSUE TITLE
is "Replace" needed for stream in media edit interface?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#710]
I just noticed that the "Replace" button exists in the media edit interface for Streams as well as all other media types - this makes sense if it's a pre-uploaded media item, but not really for a stream. clicking Replace for a stream opens a window for me to browse to a file on my computer, so this is not appropriate for a stream.

can the "Replace" button be removed from the stream media edit interface?
![Screenshot from 2021-12-13 15:57:21](https://user-images.githubusercontent.com/3437324/145835245-e121c474-7a07-49ae-9629-ee69c5f6b619.png)

**Comment by nguyenhongphat0** [comment]
This issue is about the old Media Management section which had been shut down 👎
