### ISSUE TITLE
stream - frame has no width when stream dragged onto stage

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#712]
today we started to have a weird problem with the streams on meta.upstage.live: sometimes when we drag a stream onto the stage, it looks like there is no frame - it just shows the slider and the buttons but not the frame or the stream.
we discovered that if you click on the mute button, the frame appears as a single vertical line. you can then take the middle handle & drag it out to reveal the stream.
we were both using firefox - me on linux & sebastian on mac. i tried to replicate the issue on chromium but could not. 
but it did not happen immediately, only after we had already been testing streams for about half an hour - so we had already been putting them on & off the stage without this bug happening. it happened first to sebastian, & i was still getting the normal sized frame when i dragged on a stream, then after a few more times it started happening to me as well, but not every time.

this is what it looked like when i dragged the stream on:
![Screenshot from 2021-12-15 10-58-50](https://user-images.githubusercontent.com/3437324/146170204-2550ec8d-ad44-4d13-b17c-f24af19fe23a.png)

and sebastian's screenshot when he dragged a stream on:
![Bildschirmfoto 2021-12-15 um 10 56 44](https://user-images.githubusercontent.com/3437324/146200122-e6cf4252-c214-43e6-adde-7243c56467a5.png)

then when i had tried dragging a couple on, so there is more than one that had this problem, and they showed only the mute button:
![Screenshot from 2021-12-15 11-00-24](https://user-images.githubusercontent.com/3437324/146170401-0d2ec657-6b28-4c6f-87a8-de7fc040e63b.png)

i clicked on the mute button and the frame appeared as a vertical line with the 3 handles; dragging the middle handle out revealed the stream.
![Screenshot from 2021-12-15 11-07-33](https://user-images.githubusercontent.com/3437324/146170492-fefbe7c5-2269-4058-a076-a11a6c62b319.png)

**Comment by vickis** [comment]
Sounds like a problem that needs addressing
But also why are you still using Firefox - is it to find the
incompatibilities?

**Comment by helenvarley** [comment]
:laughing: actually i find i prefer firefox for most things, so it's my default browser. i have chromium as well, & if something doesn't work in firefox then i try it in chromium. i tried to replicate this bug in chromium but as i said i didn't succeed - however i only tried a few times. what happened this morning, when we were both using firefox, is that for the first half hour or so it worked as expected. it was only after some time that first sebastian had the problem, & i did not, so we thought it was his problem - but then a short time later it started happening for me as well. so it seemed like it was something that happened after a time of putting streams on & off the stage quite a lot. maybe if i had kept going with chromium it would have also happened there ...
it is not a problem i have encountered before, in any browser.

**Comment by helenvarley** [comment]
i'm not sure that this is still happening so closing this issue.
