### ISSUE TITLE
stream sometimes replays a little bit

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#713]
sometimes when i stop and restart a stream, it replays a little bit from earlier. this is quite difficult to replicate, but we noticed it happening a couple of times today during our testing, when we were stopping and restarting our streams quite a bit.
is this something to do with the browser cache? or buffering?
i am not sure if it is a problem or not, just that it's odd to see a bit of something from earlier, when nothing is recording the stream.

**Comment by helenvarley** [comment]
is this connected to #738 ?

**Comment by nguyenhongphat0** [comment]
> is this connected to https://github.com/upstage-org/upstage/issues/738 ?

Yes this issue and #738 is duplicated, I will close one to focus on the other!

**Comment by vickis** [comment]
Thanks Phat! :)
