### ISSUE TITLE
streams have a voice but no possibilty to adjust it

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#714]
currently streams have the same kind of voice as avatars - if i'm holding a stream & i type in the chat, it will be spoken aloud, appear as a speech bubble, and appear in the chat with the name of the stream.
but there is no way to alter the voice - the right click menu doesn't have a voice settings option, and in the media edit interface for a stream there is no tab for voice.

i don't think streams need to have voices. 
do they also need to be held in the same way as avatars? i think probably not ... ?? @vickis thoughts?

**Comment by vickis** [comment]
Agree voice is not crucial
Having the stream be handled like an avatar would avoid there being a voice
- (and would mean if you wanted a voice you could attach the stream to an
av ...

wondering though if this might lead to other issues

**Comment by vickis** [comment]
making them props would be useful :)
