### ISSUE TITLE
RTMP streams - muted until lightbulb turned on, except for player who puts stream on stage

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#715]
RTMP streams (not jitsi streams)

in the manual it's written that "streams that include audio are locally muted by default." in fact they are not - no stream is muted by default, you have to click the mute button.
i guess it is not possible to have it locally muted by default because UpStage does not know who is sending the stream; it isn't necessarily the player who puts the stream onto the stage - i can put the stream of another player onto the stage, so then who would it be locally muted for - me or the other player?

if i am sending a stream with audio, it should only be heard by others when i turn the light bulb on; but it's helpful if i hear it when the light bulb is off - this is what happens with avatar voices - so that i can be sure the audio is streaming. 
then i can mute locally before turning the light bulb on.

@vickis does this sound right?

**Comment by vickis** [comment]
Yes that is a good working solution :)

**Comment by helenvarley** [comment]
i changed the name of this issue because the locally muted thing is actually not what it's about.

maybe it already works like this, but what we want is:

- when i first put my stream on stage, it is not visible or audible by anyone except me until i turn on the light bulb
- i want to hear it, before i turn the light bulb on, so that i know the audio is working
- when i turn the light bulb on, everyone else should see it and hear it
- i can then click the mute icon if i need to mute locally

**Comment by vickis** [comment]
agree that is how it would work best :)

**Comment by helenvarley** [comment]
closing this as we don't currently have RTMP stream functionality.
