### ISSUE TITLE
can we upload video?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#716]
this is still in the manual, & we have one pre-uploaded video on the demo stage & video formats showing when you hover over the media upload button; but i have the feeling that we cannot pre-upload video ... ???

we don't really need to as it's possible to play it via the streams; this is probably better than allowing people to upload video & fill up the server with video files.

@nguyenhongphat0 - does this option exist at all?
@vickis  - do you think we need it?

**Comment by nguyenhongphat0** [comment]
> does this option exist at all?

Yes! I just uploaded a video using Studio, and place it on stage :point_down: 
![image](https://user-images.githubusercontent.com/29925961/146222800-9f3fba4f-6d3c-4d98-9850-46a49b7b3683.png)

However if we open a poll for "do you think we need it?", I will vote `No` :sweat_smile: The reasons are:
- Video can be played over streams
- It would reduce the server storage
- I can remove many lines of ugly code for handling different logic between different type of streams

**Comment by vickis** [comment]
In that same poll

agree - video can be streamed (i used that feature in Repose)
an issue might be latency (has to connect and start stream ... ) video can
be uploaded and play for all at the same time which means for slower
connections they have a longer load time but then all assets are there....

reduced server storage is indeed a desired outcome

streamlining code by streaming video seems an ideal situation

I am interested in how live streams and video can be layered and interacted
with (which I know can be done outside of UpStage in the streaming
application ... but this increases the dependancy on apllications outside
of UpStage

I am interested to discuss this more :)

**Comment by helenvarley** [comment]
yes it's a tricky one. if the feature is there and it's possible to upload video, people will upload it; even with the limit of 300MB for video files, this is potentially a lot of data taking up server space without being used very much. 

might a solution be having a time limit on video as well? e.g. after one month it's automatically deleted? or being able to upload video is a "pro" feature that people have to pay more for? or this is just making it all way too complicated ... :wink: 

:thinking:

**Comment by vickis** [comment]
Time limit is a good idea yes :)

**Comment by gloriajw** [comment]
Last night at our meeting, we discussed the possibility of using the Jitsi-videobridge to allow people to stream content from their own machines. This would relieve us of the burden of allowing large files to be uploaded and stored. What do you think, @nguyenhongphat0 ?

**Comment by nguyenhongphat0** [comment]
Sorry for my absent in the last meeting. If our purpose is to stream content from our own machines, I think RTMP (what we already have) is enough :sweat_smile:. However I think we will need Jitsi Videobridge for a more convenience way of streaming without noticeable latency :+1:

**Comment by vickis** [comment]
Great thanks Phat! :D

I will be interesting to be able to compare how video bridge functions
it opens interesting options

one of the interests for me was ensuring accessibility (in the actual
ability to see and participate over various connections
but also if we move more towards conferencing tools do we also create a
greater potential increase in load on our servers
the agility and lightness of UpStage is important
also that everyone has relatively the same experience :)

**Comment by helenvarley** [comment]
i do not know anything about jitsi videobridge, but if it is compatible with UpStage & can improve latency with real-time streaming, it would be wonderful! :)

**Comment by helenvarley** [comment]
i'm going to close this issue because we now have jitsi bridge, rtmp streaming and also the possibility to upload small video clips; so we can keep all these features available and set limits on them if necessary :)
meta theater are probably going to want to upload small video clips, but they are paying for their own hosting so the issue of filling up the server space is theirs not ours.
