### ISSUE TITLE
Studio - multiframes in media list

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#720]
in the media list of the studio, my multiframe avatar takes up half the screen space because it has 11 frames.

would it be possible to show the first frame as the thumbnail, with the multiframe icon in the lower left corner, & when you hover your mouse over it, the other frames show as a rollover?

![Screenshot from 2021-12-17 15:32:00](https://user-images.githubusercontent.com/3437324/146559833-5dc2e713-749a-49a7-8dad-35786e8456d2.png)

**Comment by nguyenhongphat0** [comment]
Looks better :+1:  

![image](https://user-images.githubusercontent.com/29925961/152180715-041634eb-2baf-4e9c-9785-8676c8d1731f.png)

**Comment by helenvarley** [comment]
yes that's definitely an improvement! :+1: 
the main/first image is still really big, it doesn't need to be as big as that.

**Comment by vickis** [comment]
awesome work thanks - agree smaller initial image more fit on a page  :)

**Comment by nguyenhongphat0** [comment]
I made the main image smaller, but it would make it collapsed when the multi frames preview appears, is this okay? 🤔 

<img width="557" alt="Screenshot 2022-02-03 at 23 44 23" src="https://user-images.githubusercontent.com/29925961/152387946-f389e4fd-7907-4f44-9612-98f6b75066e0.png">
<img width="741" alt="Screenshot 2022-02-03 at 23 44 41" src="https://user-images.githubusercontent.com/29925961/152387998-db2811eb-775a-41b3-b3ee-9d02d653bd01.png">

**Comment by helenvarley** [comment]
i think that's fine - we can also see it in the frame thumbnails :+1:
