### ISSUE TITLE
tiny typo

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#722]
in the media edit interface for multiframe media items there is a tiny typo in the info for dragging frames to reorder the position: "it's" should be "its" (this is a tricky one in english as normally the apostrophe indicates possession, e.g. "helen's avatar" - but with "it", it's different, because the apostophe indicates the missing "i" in "it is" = "it's", so when it's the thing belonging to it, it's actually just "its". easy, eh? :stuck_out_tongue_winking_eye: )

![Screenshot from 2021-12-19 21:54:23](https://user-images.githubusercontent.com/3437324/146690464-8b683da6-e23f-4921-8507-d18c21291e53.png)

**Comment by nguyenhongphat0** [comment]
Thank you very much for the details! You are an amazing English teacher 😆

**Comment by vickis** [comment]
Ha ha English is a really crazy language - your ability with it is
inspiring :)
