### ISSUE TITLE
Backstage & Studio navigation - new tabs or not

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#723]
currently if i click on Studio in the top navigation of Backstage, it opens the Studio in a new tab. but when i click on the top right-hand corner navigation in the Studio to return to Backstage, it opens in the same tab. this means that if i'm going back and forth between Studio and Backstage, it's easy to end up with lots of open tabs.

i don't think the Studio needs to open in a new tab. it's part of the Backstage, really, so it would be better to keep it in the same tab.

what would be useful is to have stages open in a new tab - as then you have the Backstage still open, which is often needed - for example when stopping & starting recordings, adding players to a stage, doing things with media.

@vickis - thoughts?

**Comment by vickis** [comment]
well for usability yes it might be useful - but you can always open in a
new tab with right click ... so perhaps not super necessary
i agree lots of tabs opening can be annoying and for those who are not
super computer savvy can be confusing

**Comment by helenvarley** [comment]
ok then let's just go for everything opening in the same tab. @nguyenhongphat0 can you make it that the studio menu item doesn't open a new tab? thanks!
