### ISSUE TITLE
Forgot password on the login page

### ISSUE THREAD

**Issue by nguyenhongphat0** [upstage-org/upstage#731]

**Comment by vickis** [comment]
super!! :)

**Comment by helenvarley** [comment]
great! i tested it out & it worked.
just one tiny typo - at the end of the email it says "Thanks you," - it should just be "Thank you," without the s :)

**Comment by nguyenhongphat0** [comment]
Oops, sorry 😅 

<img width="672" alt="Screenshot 2022-01-06 at 22 48 46" src="https://user-images.githubusercontent.com/29925961/148410195-4040c347-f4a0-4b76-baeb-d3785ef9d125.png">

And let me know if you would like to change the mail template 👌

**Comment by helenvarley** [comment]
great! it looks fine to me :)
thank you :wink:

**Comment by vickis** [comment]
Thank you phat! :)

**Comment by vickis** [comment]
Clara tried using the forgot password link but has not received an email so needed to be. manually reset

**Comment by vickis** [comment]
apologies - this was in upstage.live instance :)

**Comment by helenvarley** [comment]
i tested it on dev-app and received the password reset email, so it is working in that version.
i then tried on upstage.live, & so far have not received any reset email.
at the prompt to enter the OTP password my username was pre-entered in the field for the code - a bit confusing, as it asks me to enter the code but my username is already there. this did not happen on dev-app, the field was empty.
![Screenshot from 2022-07-19 12:16:03](https://user-images.githubusercontent.com/3437324/179727817-ac826282-d2a3-4b7a-b4dc-b795654493ed.png)

**Comment by TuyetGiang** [comment]
@helenvarley Please help me check again. Thank you

**Comment by helenvarley** [comment]
great! i tested it on upstage.live & it worked.
just one thing: on the screen where i should enter the OTP, my username appears in the field where i should put the OTP. this is a little confusing - can the field be blank? (sorry i did not take a screenshot of it)
