### ISSUE TITLE
jitsi firefox issues

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#735]
after some tries, i am now seeing the jitsi window properly on https://dev-app1.upstage.org.nz/alo using firefox.
at first i was still seeing the tiny window. i cleared cache, shift-refreshed, & reloaded numerous times & it was stlil small. i entered the stage in chromium, then re-entered in firefox, and finally saw it properly.

but now i cannot get it to work properly in https://meta.upstage.live/demo using firefox. it is fine in chrome, and the dev-app stage is fine in firefox, but on the meta instance demo stage i am still seeing my webcam squashed up in the upper left hand corner and cannot make it bigger.

![Screenshot from 2022-01-04 16:08:56](https://user-images.githubusercontent.com/3437324/148080043-0565bc0a-7a8e-487b-b73f-09a9f90fb237.png)

**Comment by nguyenhongphat0** [comment]
Can you try a fresh reload on `meta` please 😅 I just rolled out the latest fix!

**Comment by helenvarley** [comment]
it's looking much better!! :)
but it's asking me to enter a password for the jitsi meeting which i don't know.
so i created a new meeting, and this worked as i expected :+1: 
are you able to roll the fix to meta.upstage.live? we have a big working session on monday & i will show them this new feature, so it would be cool if it is working properly in all browsers.
thank you!

**Comment by nguyenhongphat0** [comment]
The issue on Firefox got fixed, for other features of Jitsi, please put it in one issue: #729
