### ISSUE TITLE
stream replays

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#738]
very weird thing is happening with a stream today - i was streaming from my phone, then stopped the stream but left the stream media item on the stage. after a few minutes the stream has started replaying itself ????? it keeps looping back through the previously shown stream. it freezes on the final image and then after some time it starts again.

**Comment by vickis** [comment]
Wow interesting
UpStage created a small video loop from the stream!

**Comment by helenvarley** [comment]
yes, hard to understand how it happens as UpStage does not save the stream anywhere (to my knowledge ??? ) but it was doing this for everyone so i don't think it was an individual browser caching thing

**Comment by helenvarley** [comment]
this might be the same as #713

**Comment by helenvarley** [comment]
i can't get streaming to work on dev-app so cannot test this. i created a new stream & scanned the code, & altho larix appears to be streaming, i don't see the live preview anywhere (in the on-stage toolbar or in the studio) and i can't drag the icon onto the stage. when i try to do this, nothing happens.

**Comment by nguyenhongphat0** [comment]
It's look like you didn't click the refresh icon on the toolbar after started streaming.

I'm not allowing QR codes to be dragged into stage anymore (like in the past), to prevent the square frame issue. You will see a yellow background when a stream is loading, that is when the stream is not ready, and when the background is white (as usual), it will work as expected.

**Comment by helenvarley** [comment]
actually when this happened during the april 7th walkthrough, i was already streaming and had not stopped the stream. we were discussing amounts of lag, and others were describing what they were seeing in my stream, & they were seeing a person crossing the street. i thought they must have terrible lag because the person had crossed several minutes earlier, then i saw on my own screen the person crossing the street again. so we were all seeing it replaying a part of the stream, and i had not stopped or restarted the stream since well before this happened.
