### ISSUE TITLE
drawing tool - can eraser be round?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#739]
when you erase a drawing, the eraser is square and this is quite noticeable especially in a projection of a stage. is it possible for the eraser to be round?

**Comment by nguyenhongphat0** [comment]
Yes, but it is a performance trade-off: clearing an arc on canvas require much more computing logic than clearing a square. And when you `drag` the eraser, there is a lot of clearing operation :sweat_smile:

**Comment by vickis** [comment]
Thanks Phat
I am fine with square

However sometimes the eraser tool might be used to clear sections of an
image might it be possible to to offer choice in tool shape?

:)

**Comment by helenvarley** [comment]
should we do some testing, to see how much of a trade-off it might be, if there was an option for a round eraser? (the square one does look noticeably jagged)
this is not an urgent issue by the way!

**Comment by nguyenhongphat0** [comment]
The round erase already on `dev` instance, you can try it here: https://dev-app1.upstage.org.nz/alo

**Comment by helenvarley** [comment]
oh wow! you are SO FAST!!! :laughing: 
i guess the real test will be when there are many people on the server, if it has a performance impact? anyway i will let chantal know that it's been done :+1:

**Comment by helenvarley** [comment]
i told chantal about the round eraser and she wrote:
wow. That was really fast!
All hail to Phat :)
Thank you so much.
