### ISSUE TITLE
difficult to select from dropdown menu to leave stage

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#742]
when you are on the live stage and want to leave you can use the logo at top right and you have the options to go to Backstage or the Foyer. but it's really difficult to select one of these options from the dropdown menu, as it keeps changing to the counter.
this is not an urgent issue, but it would be nice if it can be improved a bit as it's frustrating.

![dropdown_leavestage](https://user-images.githubusercontent.com/3437324/148931258-1fba759e-72d5-47d4-af77-087b7e785eb4.gif)
.

**Comment by nguyenhongphat0** [comment]
How about using right click context menu? :point_down: 

![image](https://user-images.githubusercontent.com/29925961/148975421-0be60e37-316a-4159-8786-621136c32352.png)

**Comment by helenvarley** [comment]
maybe - or, i have been finding that i nearly always want to go Backstage; a logged in player doesn't need to go to the Foyer so much. could it be that when logged in players click on the logo they are taken to Backstage, and when audience click on the logo they are taken to the Foyer? is that possible?

**Comment by vickis** [comment]
Right click seems a good solution to me
You at least always have the option :)

**Comment by helenvarley** [comment]
right-click is not so intuitive ... 
if a single click on the logo when you are on stage takes you to Backstage, then you can click that logo again & it takes you to the Foyer. this feels to me easier & more intuitive than a dropdown of the options, whether it's a right or left click to get the options. i can't think of many situations where i want to go from the live stage to the foyer when i'm a player - i usually want to go to the Backstage 
as a player, i really only need to go to the foyer to check that the right shows are there as live or to update info there, so i'm usually going there from the Backstage rather than the live stage.

**Comment by vickis** [comment]
sure

so as a player
by clicking the logo you are taken to backstage from any stage
in the backstage by clicking the logo you are taken to foyer

as audience
in a stage by clicking the logo you are taken to foyer

makes sense :)
