### ISSUE TITLE
stage offline over guest wifi at meta theater

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#743]
when using the guest wifi network at meta theater, nobody had a live stage: we could enter the stage, but it was showing as offline and we could not do anything.
it worked properly on the regular wifi network, which is apparently the same as the guest network, & it also worked on ethernet, also coming from the same network.
it would be good to put something in the troubleshooting section of the manual, but i am not sure what to put ... any ideas about what could cause it? there must be some setting that is different in the guest wifi settings ... ??

**Comment by gloriajw** [comment]
Guest networks often block everything except ports 80 and 443. Our software needs other ports to be open to function properly, such as ports in the 9000 range.

**Comment by helenvarley** [comment]
ok that is probably the issue then. please list all the ports that UpStage requires so that we can include it in the traoubleshooting & maybe also in installation documentation? (or it's already there?)

**Comment by gloriajw** [comment]
Well, port ranges could vary by installation. Plus, for security purposes, I don't feel comfortable telling the world which ports can be DDoSed. I like them to work for it, at least.

**Comment by vickis** [comment]
i recall it was assigned ports for instance the 8083 etc
and the range 19... - 3000 which was required (not specific numbers)

audiences should always be told to ensure they have no firewalls installed
etc to attend
i agree we should not be suggesting opening specific things (and in fact
should probably put a caveat on to ensure we are not liable for any
complications for users...

**Comment by helenvarley** [comment]
but we have to tell people what ports are stopping them from having access, if we want them to have access. it seems that the number of people who will be affected by it is quite small - the guest network at meta is so far the only network i know of that has had this issue; but it won't be the only one, & maybe with universities it will happen more often ...
in the past we always made the port information available on the website, & douglas always said that it was not a security risk to have these ports open ... has this changed?

we can definitely manage things directly with any organisations like meta that we are providing hosting for or supporting, but what about general public? how likely is it that individuals trying to connect from domestic connections are going to have issues with the ports?

**Comment by nguyenhongphat0** [comment]
We have this discussed in development channel on Slack, I believe this issue can be closed now :muscle:
