### ISSUE TITLE
stream setup info in Studio

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#746]
it would be helpful to be able to see the stream information in the studio - i just recreated my stream and it seemed like i could not get the OBS setting info until i went on to the live stage and clicked on the stream icon.

**Comment by vickis** [comment]
Yes agree

**Comment by nguyenhongphat0** [comment]
It is on dev-app1 now :+1: 

![Screenshot from 2022-02-20 02-13-02](https://user-images.githubusercontent.com/29925961/154815551-e82bd368-19f5-4991-918d-5524e5a719e7.png)

**Comment by vickis** [comment]
great thanks Phat :)
