### ISSUE TITLE
frame of stream does not fit to actual dimensions of stream

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#747]
currently on upstage.live (& on meta.upstage.live), streams have a square frame; on dev-app, the frame is portrait oriented and very long and narrow. scaling the frame does not adjust its proportions, it stays in the same shape.
this means that the frame covers up other media and makes it difficult to get the right object on the stage.

(sorry if this is a duplicate issue - i'm sure i made one recently, & wanted to add screengrabs to it, but now i can't find it)

![Screenshot from 2022-01-13 17:56:21](https://user-images.githubusercontent.com/3437324/149375145-f11ecda1-abc7-4370-a7e0-aa34bed1e3e8.png)
![Screenshot from 2022-01-13 17:55:21](https://user-images.githubusercontent.com/3437324/149375154-a473fbea-dd63-4d0e-b4bb-fd5e290c4de4.png)

**Comment by vickis** [comment]
appears to be resolved 
![image](https://user-images.githubusercontent.com/4249450/150028161-c4015504-e11e-4bff-81b4-386d21a3f1d3.png)
![image](https://user-images.githubusercontent.com/4249450/150028209-4ba4b349-b7e6-4044-85d5-3e9e0d826392.png)

**Comment by helenvarley** [comment]
great, & yes last night at the meta event the frame was fitting to the stream :+1:
