### ISSUE TITLE
no tooltip for backdrop thumbnails on live stage

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#748]
in the tool overlays on the live stage, when i hover my mouse over the thumbnails of avatars and props i get a tooltip showing the name of the media item. this is really useful when you have similar items and want to select one, or know which one to remove from the stage.
but the tooltip doesn't show up when i hover over backdrop thumbnails. can this be added?

**Comment by helenvarley** [comment]
thanks phat! :)

**Comment by vickis** [comment]
awesome thanks :D
