### ISSUE TITLE
backdrop proportions

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#749]
something has changed with the backdrop proportions ... for example, the tunnel beach backdrop used to fill more of the stage. i have tried changing the stage ratio but this doesn't really help. 
obviously backdrops of different sizes are going to display differently with different ratios, but it should never be that it's possible to have the background colour showing at the top and bottom of the backdrop as well as at the sides. this is now happening.

we need to make sure that the information about backdrop size included in the manual (https://docs.upstage.live/media-management/creating-graphics-for-upstage/) is as clear as possible - best dimensions for backdrops is one of the most common questions i get asked about creating graphics for UpStage, & i find it really difficult to answer!

this is with the ratio at 16:9, & the tunnel beach backdrop which i think is more of a 4:3:
![Screenshot from 2022-01-14 15:07:14](https://user-images.githubusercontent.com/3437324/149528933-86995930-ff0f-4c37-b183-401c2d9c15fd.png)

![Screenshot from 2022-01-14 15-06-50](https://user-images.githubusercontent.com/3437324/149528892-3a6bf2ad-3695-446c-a989-a244b927d494.png)

& if the ratio is changed to 4:3 then other backdrops such as this one appear with background colour all around, even at fullscreen:
![Screenshot from 2022-01-14 15-09-38](https://user-images.githubusercontent.com/3437324/149529017-b2f5a6e2-db0a-4aa9-940d-079b8b247e36.png)

**Comment by vickis** [comment]
strange indeed!
[image: image.png]

most of mine which were providing the backdrop I required were 450x800 -
not so the chart (which somehow shows the full file - when previously it
showed only the upper half
also it appears not to allow me to edit it (to check file dimensions

another thought I had was - going through the bugs it appears in the bug
about square frames helen, you are holding or have just placed the
VicPalace av - is it possible you had that media file open in another
window when you were uploading the blue wig - (and inadvertantly replaced
media?? it seems such a strange bug

**Comment by helenvarley** [comment]
yes - previously there were backdrop images that got cropped for the stage, such as one of the refinery interior shots that is actually portrait, this was showing as the upper half. & the tunnel beach one used to display differently, see image below from april 2021.
(re the other bug - it does appear that i somehow replaced it. i don't remember if it was on stage in another tab when i did that, but even if it was, it still shouldn't have happened)

![Screenshot_workshop_web](https://user-images.githubusercontent.com/3437324/149743667-4de1d42f-2aca-4029-bcf6-3702dbacf81b.png)
