### ISSUE TITLE
some avatars have square frames

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#750]
some avatars (on upstage.live) have square frames but others do not - why would this be? for example, these are single frame avs that both have dimensions 244 wide by 350 high, therefore should have portrait dimensions for their frame, but have square frames on the stage.
![Screenshot from 2022-01-14 15:46:56](https://user-images.githubusercontent.com/3437324/149534910-4d9fe71e-a5ef-454b-988a-beb246ed3588.png)
![Screenshot from 2022-01-14 15:46:39](https://user-images.githubusercontent.com/3437324/149534914-44b97267-3f29-48e4-9143-b7d4bcce31fc.png)

**Comment by vickis** [comment]
agree - easier to wrongly select other media when frames are larger than
the object
be good if the frames are dynamically generated by the object size .... :)

**Comment by nguyenhongphat0** [comment]
If you have square frame avatar, please go to studio, edit the media and click save again (you don't have to edit anything, just click save 😅) and the avatar will have fit frame like below 👇 

<img width="166" alt="Screenshot 2022-01-24 at 22 14 45" src="https://user-images.githubusercontent.com/29925961/150810035-cefd176c-31b4-4405-9b43-b7d2a0a3b2dc.png">
<img width="144" alt="Screenshot 2022-01-24 at 22 14 50" src="https://user-images.githubusercontent.com/29925961/150810056-54c6ea79-f891-48b3-aa72-5433419f772d.png">

**Comment by helenvarley** [comment]
thanks for the explanation :) i was unable to test on the two examples i gave above, as the VicPalace avatar is the one that i somehow replaced with the blue wig, and with the Audrey avatar when i click on edit, nothing happens ... i tried on a different media item also uploaded by phat & i was able to edit that. i guess there might be something a bit odd about audrey & the lost VicPalace due to them being uploaded early on?

**Comment by helenvarley** [comment]
it's no problem, that's why we have a development server :)

**Comment by vickis** [comment]
They were ones I uploaded so can replace them - thanks phat will go check
On the others I have
Great work :)
