### ISSUE TITLE
managing registrations

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#756]
today i noticed that someone (public) registered on upstage.live 10 days ago; i have written to him asking for some info about who he is & his interest in UpStage so that we know whether to approve it or not. then i noticed also that there was an unapproved registration from 7 months ago as well.
now that we have email set up & the notifications working, is it possible for admins to get email notification of new registrations?

**Comment by vickis** [comment]
yes Important for us to get the email indicating registration :)

**Comment by nguyenhongphat0** [comment]
So now we have email notification when:
- User registered successfully (send to user)
- Registration approval required (send to admins)
- User account approved (send to user)

Let me know if you would like to have other notifications as well :muscle:

**Comment by helenvarley** [comment]
great work phat! i received an email saying that approval is required for the test registration, & it's all good - except in the "to" field there are a LOT of email addresses - including some of the artists who have accounts ... has this email been sent to everyone with an admin role?
(it would be useful to be able to sort the players by role - i can't easily see who has admin status without scrolling through ... )

**Comment by nguyenhongphat0** [comment]
You can filter user by roles in the admin section 🤔 And yes the email is sent to all admins of UpStage, because any admin can approve the account. Or would you like it to be sent to specific admin only?

**Comment by vickis** [comment]
Ah maybe here is a reason for an extra permissions ?

Artists might be able to set up stages add assists etc

But approval of registrations especially for new accounts (perhaps the
approval remains at player only initially (perhaps just my lack of
understanding but if many can approve new accounts could we get a sudden
influx that we are not able to manage?

**Comment by vickis** [comment]
i clicked on the link to approve the registration (to see what would happen and got the following 
![image](https://user-images.githubusercontent.com/4249450/150026242-558d23a3-d2a9-4caa-ac7c-39f09b501c05.png)

**Comment by helenvarley** [comment]
oh yes i also got this undefined and blank page when i clicked on the link to approve the registration.

probably we don't need to have another role - we just need to be more clear about why someone is made an admin. for example eva was an admin on dev-app, but now i changed her to player as i don't think she needs to be an admin there. i also made her a player on upstage.live as well. so now there are 7 admins on both dev-app & upstage.live; 
(who is richard? is that vu? the gmail address is odd, surely the gmail address is not the email address of anyone in this project?)

it's good to have more than one person who is getting the registration emails, in case someone is on holiday or an email goes to spam or doesn't arrive for some reason.
the roles are described here in the manual: https://docs.upstage.live/upstage-administration/ - do they sound right?

**Comment by vickis** [comment]
yes great :)- actually i was thinking (if we use the Eva example)  she
would be admin to include other players in her company - but then after
initially sorting that she could be reverted to Player
I think not having a number of complicated roles is good :)
I assume richard was the dummy email Phat set up ;) ... although there is
possibly actually an early adopter out there who got the first name address
for gmail

**Comment by helenvarley** [comment]
agree @vickis - let's not add any further roles unless really necessary. normally an instance will only need to have a small number of admins.
i made richard/vu just be player rather than admin (unless he is still involved?) & also there was a helentest account which i've changed to player as well. (on dev-app).
on upstage.live gloria has 2 accounts which are both admin, maybe only one needs to be admin, @gloriajw ?
