### ISSUE TITLE
backstage: after saving, no scroll bar

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#766]
i have just added 16 new users to meta.upstage & have to go through adding all their email addresses so that i can then given them player status (this is a bit tedious - probably we can improve this workflow but that's another issue).
when i save each user's info, i am returned to the list of users, but there is no scroll bar so i can't scroll down to do the next one.
reloading the page solves the problem, but it is quite annoying.
this also happened sometimes when i was creating new stages, that after saving the new stage there was no scroll bar so i could not go down to the stage status or adding a cover image.

also, on the player management interface i set it to display 25 results rather than 10, as i had 16 new users' details to update, but each time after i save one user's details, it defaults back to only displaying 10 results.

**Comment by vickis** [comment]
Yes workflow that that would be helpful to fix :)

**Comment by nguyenhongphat0** [comment]
Sorry for the unconvinced :sweat_smile: I already submitted a fix, it will be available on `dev-app1` as soon as Gloria accept it :ok_hand:

**Comment by vickis** [comment]
Ooh my Phat you are so swift :D
Thank you!

**Comment by helenvarley** [comment]
thanks - i can't test it as i don't have any users to add at the moment, so i'll assume it's working :)
