### ISSUE TITLE
studio: unassigning avatar from stage does not work

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#768]
i am trying to unassign one of the "stay home" avatars from the demo stage via the studio but it does not work.
i click on the edit button for the avatar, select the stage and move it to the left-hand unassigned list, click save, and ... it's still assigned to the stage.
![unassign_avatar_from_stage](https://user-images.githubusercontent.com/3437324/153569114-a37ebf19-e16d-4642-9492-bd1be99c702b.gif)

**Comment by vickis** [comment]
thanks Phat!

**Comment by helenvarley** [comment]
great, i tested it on dev-app & it works :)
