### ISSUE TITLE
chromium: curious icon when no backdrop on stage

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#769]
using chromium on linux, there is a very small curious icon showing in the top left corner of the stage when there is no backrop selected. i tried this on different stages & it is always showing in chromium. it doesn't show in firefox. i don't know if it is on other operating systems or only a linux thing.
![curious_icon](https://user-images.githubusercontent.com/3437324/153571931-a7cec326-1c1b-4286-b0a5-76ddd825356c.gif)

**Comment by nguyenhongphat0** [comment]
In case you are curious, the symbol meaning is `broken source` :sweat_smile: But don't be panic, there is nothing broken, we just had a backdrop with no image attached to it. Let me made the icon disappear :ok_hand:

**Comment by helenvarley** [comment]
great - but i'm still seeing the icon, should it be gone?

**Comment by vickis** [comment]
yes looks like a broken image
should disappear when the stage compiler is not looking for the non
existent image - the change I am assuming Phat is going to implement
great work  :)

**Comment by nguyenhongphat0** [comment]
Sorry for not be able to do it earlier! The icon is gone on dev-app1 :point_down: 

![image](https://user-images.githubusercontent.com/29925961/154106847-272c2390-732f-4f48-be6e-91aa1259320d.png)

**Comment by vickis** [comment]
wahoo! :D
