### ISSUE TITLE
jitsi: unable to share cam or mic - chromium

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#770]
i am not able to share my webcam or mic to jitsi on UpStage when in chromium. it's working in firefox. i tried restarting the browser several times & clearing cache but still unable to share from chromium.
![Screenshot from 2022-02-11 11:08:34](https://user-images.githubusercontent.com/3437324/153573662-bddb211d-5921-41a7-9faf-2ef160b059fc.png)

**Comment by nguyenhongphat0** [comment]
When this dialog appear, please click Allow to let Jitsi access your camera and microphone. If you had chosen to deny, the above error will occur.
![image](https://user-images.githubusercontent.com/29925961/153634857-3815bbb3-cc10-4d70-8d04-a19269bc75ac.png)

To fix this, click on the lock icon on the left of the address bar, manually allow camera or `Reset permission`, then you will be able to use it :point_down: 
![image](https://user-images.githubusercontent.com/29925961/153635364-65f2d025-c58e-4b42-9f2f-f198b0ee64a6.png)

**Comment by helenvarley** [comment]
great, thank you! i am not sure how it got denied ... this is something to include in the manual, when i get round to doing a section on the jitsi tool ...

**Comment by vickis** [comment]
great thanks Phat
definitely something for us to put in the manual :)

**Comment by nguyenhongphat0** [comment]
You're welcome :hugs:
