### ISSUE TITLE
colour picker for background colour selection

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#772]
is it possible to have a colour picker for selecting a precise background colour for a stage? i mean like the eye-dropper tool that is in GIMP or other graphics apps, that lets you click on an existing colour to match it exactly. 
this would be helpful to choose a colour that blends with a backdrop image.

**Comment by nguyenhongphat0** [comment]
It is possible, but much depend on which browser you are using to open UpStage (because the color picker is the `native` tool). For example in Firefox you can follow these step to pick a color on your screen:

![image](https://user-images.githubusercontent.com/29925961/154101877-8a48b3f6-05fb-4ed0-9c96-0c9c4cadb78d.png)
![image](https://user-images.githubusercontent.com/29925961/154102121-7149334b-cec4-4d17-a862-b1765435fb93.png)

**Comment by nguyenhongphat0** [comment]
And here is on Chrome:
![image](https://user-images.githubusercontent.com/29925961/154104065-202bac25-6e37-4047-919b-224a332f5262.png)

**Comment by helenvarley** [comment]
thanks @nguyenhongphat0 - actually i don't have it in firefox - must be a linux thing; see screenshot. but the good news is, it's there in chromium :)
![Screenshot from 2022-02-15 18:05:51](https://user-images.githubusercontent.com/3437324/154112572-4a93fc9a-5d9d-4357-b90f-824e01865fd5.png)

**Comment by helenvarley** [comment]
BUT the bad news is - the colour picker does not work at all in chromium!!! :laughing:

**Comment by nguyenhongphat0** [comment]
Yes it is OS difference as well 🥶 Can you explain more about the issue you are facing? Is the backdrop doesn't change after you selected it? 🤨

**Comment by helenvarley** [comment]
no matter what colour i try to select, it just goes to white. this is in chromium on linux.
![Peek 2022-02-15 18-31](https://user-images.githubusercontent.com/3437324/154116875-e8d8aae6-22fe-4154-9d37-ac1c46488575.gif)

**Comment by vickis** [comment]
hmmm is it selecting a background colour?
or perhaps finding transparency

the picker seems to be working in Chrome for me ...

**Comment by nguyenhongphat0** [comment]
There's no workaround I can do in this case, sorry!

**Comment by helenvarley** [comment]
ok, good to know! i will update as soon as i can :+1:
