### ISSUE TITLE
video frame is square

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#776]
the frame of a video is square, but it should fit to the dimensions of the video. (streams are framed correctly, this is just happening with video files).

![Screenshot from 2022-02-16 09:52:15](https://user-images.githubusercontent.com/3437324/154229179-f5ab7f9a-4e3c-45b6-8431-c51cb9b11423.png)
![Screenshot from 2022-02-16 09:50:48](https://user-images.githubusercontent.com/3437324/154229187-3b775b1d-0acc-4ecf-8d86-946ac18d6351.png)

**Comment by vickis** [comment]
Yes Phat - sometimes to show a small bit of video and manipulate ss with
any object on the stage is useful
when streams might be being used for something else

vicki :)

**Comment by helenvarley** [comment]
yes we did - but the feature is there, & as vicki says it's useful. i am certain meta theater will want to use it.
i think we should keep it, monitor how it is used, & perhaps add things like the ability to auto-delete after a certain amount of time if it looks like it could create storage problems. but first let's see how we use it :)

**Comment by nguyenhongphat0** [comment]
This got fixed as part of PR #888

**Comment by helenvarley** [comment]
![Uploading Screenshot from 2022-04-16 18:01:42.png…]()

**Comment by nguyenhongphat0** [comment]
- It's on `dev-app1`, not `upstage.live` yet
- For those video that was uploaded in the past, please go to Studio and re-save it, to apply the new size. Sorry for the unconvinced!

<img width="250" alt="Screen Shot 2022-04-17 at 00 26 57" src="https://user-images.githubusercontent.com/29925961/163685253-69de7db3-3f45-459c-bacd-b4cf8f0dc1b1.png">

**Comment by helenvarley** [comment]
great! at first i thought it was still square, but then i saw that you uploaded the video again, & the second version of it displays with the frame fitting to the actual video dimensions, where as the earlier one that i uploaded still had a square frame. interesting ...

**Comment by helenvarley** [comment]
reopening this as i just discovered this is happening again on upstage.live  (but not on dev-app, which is odd as they should be the same??)
![Screenshot from 2024-03-22 15:59:31](https://github.com/upstage-org/upstage/assets/3437324/2c44e0fc-3ede-4cbe-ba0c-761a304a1453)

![Screenshot from 2024-03-22 15:59:15](https://github.com/upstage-org/upstage/assets/3437324/fb4f0291-2797-4555-a0cf-a621a0815b95)

**Comment by helenvarley** [comment]
closing as this has been fixed
