### ISSUE TITLE
multiple versions of stage possible (avatar addition)- is this a problem

### ISSUE THREAD

**Issue by vickis** [upstage-org/upstage#782]
When we were doing the walkthrough someone asked about adding avatars while everyone is in the stage 

to experiment i went into another tab and added an avatar - i then entered the stage in that tab (effectively i was in the same stage twice :0

but the other interesting thing - was i had added the new avatar to the other stage and everyone could see it (but it was not in the original toolbar - i would expect that when everyone reloaded it would turn up - but could thins cause problems?

**Comment by nguyenhongphat0** [comment]
Technically, avatars (and props, backdrops, curtains,...) are loaded at the moment you enter the stage. So if a new avatar got added to the stage, you have to reload the tab to see the new avatar in the toolbar. However if someone drag the new avatar to the stage, everyone will see it (no matter if they had reloaded the stage or not).

So if you open a stage in multiple tabs, these tabs that got loaded **after** the avatar was added will be able to access it in the toolbar, the other won't  :sweat_smile:

**Comment by helenvarley** [comment]
this is really two issues - one about adding media during a performance, the other about players being able to be in the same stage twice.

i think it's good if, when someone adds media during a performance, it is then visible to everyone when that player drags it on to the stage. it doesn't matter to the audience if it's not in the toolbar, & if another player needed to access it, they could reload the stage for themselves. i think it can be handy to add things on the fly, as long as it doesn't cause any problems.

for players being able to be logged into the same stage twice - what might be the potential problems?

**Comment by vickis** [comment]
Is this the same as the player will being represent by two instances of
themselves
in the same way that multiple avatars can be interacted with

i guess the player can only act in one version at a time ... so _should_ be
ok? :D

**Comment by nguyenhongphat0** [comment]
> for players being able to be logged into the same stage twice - what might be the potential problems?

It would cost double network bandwidth :laughing: Besides that it seemed not to have any other problem!

**Comment by vickis** [comment]
Huh cool thanks

**Comment by helenvarley** [comment]
and you might get audio echo or slightly strange audio, if there is audio playing and coming at fractionally different times ... but generally if it's not going to cause any technical problem, i think it's good to leave it as a possibility, as there might be some reason we can't think of right now that would make it useful.
would it be worthwhile to have an alert pop up, saying something like "You are already on this stage as a player, in another browser window. Do you really want to enter twice?"

**Comment by nguyenhongphat0** [comment]
The alert popup wouldn't take much time. But testing and make sure there won't be impact would :sweat_smile:

**Comment by helenvarley** [comment]
ok, then let's not worry about it for now. i think mostly people will not want or try to do it, maybe it happens sometimes by accident, but it's not too terrible :)

**Comment by vickis** [comment]
Agree if not problematic ignore :)
