### ISSUE TITLE
link to manual from backstage?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#786]
i just realised that there is no link to the user manual from Backstage - you have to go back to the foyer to find the link. would it make sense to have the link also in the top navigation menu of the Backstage?

**Comment by vickis** [comment]
Could be useful yes - although you might generally have open in another
window

**Comment by helenvarley** [comment]
only if you've opened it from the foyer; but i feel like i'm more likely to need it when i'm in the backstage & think, how do it do something ... so if the manual link is right there it makes it easier to access :)

**Comment by nguyenhongphat0** [comment]
I added the navigation in the backstage menu, and you can also change the manual link in Admin > System Configuration :raised_hands: 

![image](https://user-images.githubusercontent.com/29925961/155884377-449266b1-fc60-431d-9954-5c251d09b0ec.png)

**Comment by vickis** [comment]
brilliant! :)
