### ISSUE TITLE
players can edit others' media

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#787]
i just created an account for a new player and checked what it is possible for her to do. i discovered that in the Studio, a player is able to edit any media that does not have its permissions set to "not shared".
this should not be possible - it means that any player can effectively edit others' stages, by adding or removing media, even when they do not have edit access to that stage.
it also means that a player can delete or make other changes to anyone's media, such as changing the voice on an avatar or changing the permissions. they should only be able to do this with their own media.
making a media item copyright free or available to use with acknowledgement or permission should not mean that others can delete it or edit it, they should only be able to assign it to stages that they have edit access to.

this is quite urgent to address, as now that we are having open walkthroughs we are getting more new players who are not so closely involved with the project and not necessarily aware of what they should or shouldn't be able to do. i don't think any of them would deliberately delete someone's media, but they might do it by mistake e.g. thinking they are removing it from their stage or something like this.

**Comment by nguyenhongphat0** [comment]
Okay now players can only edit/delete media that they had created. For someone else's media, they can only assign it to their stages, and nothing more. I created a new button for this flow, let me know if you think it need any modification :ok_hand: 

https://user-images.githubusercontent.com/29925961/155183993-ebd3d369-d6be-49db-a9c9-367a4d3fe55f.mp4

And I remembered that Admins still need to be able to edit/delete any media they want, so you still see the edit/delete button on any media when logged in as Admin!

**Comment by vickis** [comment]
great Phat

yes we will need to be able to do the occasional sweep once we get more
people in and making media etc :)

**Comment by helenvarley** [comment]
that looks great, @phat :+1:  - let's roll it out & try it :smile:

**Comment by nguyenhongphat0** [comment]
It's on dev-app1 now!

**Comment by helenvarley** [comment]
looking good! 
i logged in as demo & sent a request to myself (helen) to use my avatar; i logged in as helen in another browser, & when i went to the studio i saw the request. i approved it, and then in the other browser as demo i refreshed the page & saw that i could now assign it. but there was no message for me that the request had been approved.

is it possible for the system to send an email, both to the player who is being asked for approval and then to the other player when the request has been approved or denied? it could be a generic message saying you have a notification on UpStage, please look. (this would be useful for all of the permissions system)

**Comment by nguyenhongphat0** [comment]
Sure, but let's create a separated issue for it: #790 :muscle:

**Comment by vickis** [comment]
super! :)
