### ISSUE TITLE
firefox message - is it still needed?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#788]
i am still seeing the firefox config info message pop up when i enter (and sometimes leave) a stage - do we still need this? i thought there has been an update to firefox that means it's not necessary any more. 
if it's worth keeping for people using older browsers then it's fine, but if it's not needed at all then it would be nice to remove it, or make it only appear for those with older browsers.

**Comment by vickis** [comment]
perhaps it can be changed slightly to indicate that the newer versions do
not have this issue
eg recommend an upgrade to ensure that the browser version is compatible
with how upStage works?

I think we need to be careful not to keep making sure UpStage is backwardly
compatible as this might require quite some significant work

**Comment by nguyenhongphat0** [comment]
> i am still seeing the firefox config info message pop up

It was on `upstage.live` or `meta`, wasn't it? These instance didn't have the latest release rolled out properly, so you still see the Firefox instruction. I've just rolled out the latest version, the popup should be gone now!

**Comment by helenvarley** [comment]
so true! thank you :smile:
