### ISSUE TITLE
no version footer in Studio

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#793]
there is no footer in the Studio, telling me what version it is. can this be added? it would be handy :)
(not urgent!)

**Comment by helenvarley** [comment]
i'm not seeing this on dev-app yet - should i?

**Comment by nguyenhongphat0** [comment]
It's on dev-app1 now 👇 

<img width="1439" alt="Screen Shot 2022-05-02 at 01 53 02" src="https://user-images.githubusercontent.com/29925961/166160267-48f38ad1-5646-4b58-90fb-4516afd09667.png">

**Comment by nguyenhongphat0** [comment]
Not sure why CI/CD seemed to stop working, I had to roll out changes manual lately 🤔

**Comment by vickis** [comment]
thanks Phat :)
