### ISSUE TITLE
default TOS link

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#795]
at the moment, the ToS link is to a dummy page that doesn't exist. we should make the default link go to our own ToS, which we need to make ... can we create a page somewhere even if it has nothing in it yet, so that we have a functioning url? 

should the page be on upstage.org.nz, as a web page? it's maybe useful for people to be able to find the ToS from the website, when they are considering signing up as p[l]ayers or requesting a hosted instance.

at the moment we have our diversity & inclusion policy & code of conduct on the website, but these are not ToS for individuals or organisations who are paying for a service. 

does anyone have good examples of other similar platforms' ToS that we could adapt? assigning @elisadcg also to this in case you know of some relevant open source examples??

![Screenshot from 2022-02-28 10:39:36](https://user-images.githubusercontent.com/3437324/155960779-526c121c-2065-40b6-bba8-4f0c79d3a0a8.png)
![Screenshot from 2022-02-28 10:40:19](https://user-images.githubusercontent.com/3437324/155960784-a7b8ad17-d32a-43ef-a089-2347fa3c625b.png)

**Comment by helenvarley** [comment]
ok now the ToS link is going to https://raw.githubusercontent.com/upstage-org/upstage/main/LICENSE - so it's going somewhere :) but this is the GPL licence, not terms of service for registering an account on UpStage.live. so we still need to write this.

**Comment by vickis** [comment]
Yes will be required - def a task within business model project to

**Comment by helenvarley** [comment]
we still don't actually have a TOS document ....
