### ISSUE TITLE
ability to control order of thumbnails in toolbar overlays

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#796]
it would be extremely helpful to be able to control the order of thumbnails in the on-stage toolbar overlays, in order to improve speed of finding things and moving to the next media item during a performance.
at the moment the order appears to be random and unchangeable. it would be great if the default order is alphabetical, as this would allow some control by changing media items' names to change the order.
it would also be really good if it's possible to drag and drop the thumbnails in the tool bar, as we can in the depth tool, so that we can change the order on stage.

if we can drag to re-order in the on-stage toolbar, would this mean that they stay in the order so that you only need to order it once and next time you enter the stage it's in the order you left it in?
alternatively, it could be that ordering in the onstage toolbar is just for that session, and there is a way in the backstage to re-order and save the order. 

please prioritise this, as the artists are saying it is something that causes them problems.

**Comment by vickis** [comment]
Would be useful yes :)

**Comment by nguyenhongphat0** [comment]
The feature is under construction :construction: :laughing:

**Comment by nguyenhongphat0** [comment]
> alternatively, it could be that ordering in the onstage toolbar is just for that session, and there is a way in the backstage to re-order and save the order.

Yes on stage you can drag items to reorder it (like the depth tool) and it will stay there until you reload or exit the stage. If you want to persist the position for multiple sessions, go to Media > Reorder Mode, and rearrange these media the way you want it to be. Please remember to hit the Save button after you finished :sweat_smile: 

https://user-images.githubusercontent.com/29925961/156920510-dd5a4476-81cf-4d72-bcc4-7aba90b11dde.mp4

**Comment by helenvarley** [comment]
exciting! i will test tomorrow as i am busy this afternoon & evening with our events in munich.

**Comment by vickis** [comment]
super - tested and working Thanks team :D

**Comment by helenvarley** [comment]
unfortunately i can't test this, as the page stops loading before all the thumbnails have loaded so i can't see what media is what, in order to reorder it. not sure if this is a problem with my internet, or what :frowning:

**Comment by helenvarley** [comment]
could it be that the reorder mode has somehow broken the thumbnails? on upstage.live, which is still tegenseer & doesn't have the reorder mode, the thumbnails are loading for me. i've tried dev-app on firefox and chromium and on both, no thumbnails at all load on Stage Management > Media

**Comment by helenvarley** [comment]
great - the thumbnails are all there now & i've tested & it's working. eva will be super excited by this!! (any chance it can be rolled to upstage.live before next wednesday when we have our performance?)

**Comment by nguyenhongphat0** [comment]
The code has changed a lot to implement this features, which means there could be lots of impacts! We should use it for a while to guarantee that it is stable to be released!

**Comment by vickis** [comment]
Yes agree!  testing is always the necessary and potentially exciting part
where we try and seek out those fun little glitches for you :)
