### ISSUE TITLE
all lists should be alphabetical or chronolgical by default

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#797]
as a general rule, all lists everywhere including dropdown menus should be either alphabetical or chronological by default. wherever possible, it should be possible to reverse the order (ascending/descending) as we can in the Studio. 

for example, it would make sense for the default view of the Stages list to be chronological, with the most recently active stages first.
it would make sense for the media list in Stage Management to be alphabetical - it is currently sorted by media type, which is good, but within the media type it is not alphabetical. (in fact the media list within Stage Management needs some enhancement but that is a separate issue).
it would make sense for the player lists in Stage Management to be alphabeticised - yes you can search for a player but sometimes you don't know the player's username & need to scroll to find them, & it's much easier to scan a list of names that is alphabeticised.

**Comment by vickis** [comment]
Agree as we get more people involved this will be increasingly necessary:)

**Comment by helenvarley** [comment]
i am closing this as it's a duplicate of #604 & there is a clear list there of the lists that need to be either alphabeticised or chronologically ordered.
