### ISSUE TITLE
unable to upload media on upstage.live

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#801]
we are unable to upload any media on upstage.live - we get the error message "Response not successful. Received status code 400"
it seems the last time someone uploaded successfully was 3 days ago.
![image](https://user-images.githubusercontent.com/3437324/156325931-ac331408-ec0b-417e-a381-6b056b4ea425.png)

**Comment by helenvarley** [comment]
i just tried uploading on dev-app & it worked, also met.upstage is working fine, so the problem is just on upstage.live.
we are working quite a lot on upstage.live now, in preparation for the event on 16th march.

**Comment by nguyenhongphat0** [comment]
Closing this issue as it got fixed!

**Comment by vickis** [comment]
Awesome thanks 🙏
