### ISSUE TITLE
registration process - ability to customise what email address they are sent to? 

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#803]
currently new registrations are sent to support@upstage.live - i'm wondering if it would be better for them to go to info@upstage.org.nz? in order to keep technical support requests separate from player management, which the devs should not need to have to think about.

at the moment we don't have a way to customise where these emails go, & this is something that meta theater & others with hosted instances will need to do. we might also need to do it at some point.

can it be in Admin > System Configuration? a way to set the email addresses for registration emails & maybe other email - this connects to #802 - i guess for instances that we are hosting, the support email needs to come to us. but in the future it could be that someone else installs their own UpStage server, and then support requests would need to go to that server's administrator.

**Comment by vickis** [comment]
yes agree :)

**Comment by helenvarley** [comment]
closing this as it's covered in #1225
