### ISSUE TITLE
drawing: largest paintbrush size is not very large

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#806]
the largest possible brush size for drawing is actually not very large. sometimes we want to "paint" over a large area to cover it up, & the size that the brush can be means this takes a long time.
can the largest brush size be about 4 times bigger than it currently is?

**Comment by vickis** [comment]
seems a good idea - as long as it doesn't comprise finer grain adjustment
at the lower paintbrush size :)

**Comment by nguyenhongphat0** [comment]
I made the paint brush 4x as large as possible, but please remember when the size of paint brush is larger than half the slider (twice as what we have now), the mouse cursor won't show the brush dot when hovering anymore (this is restriction of browser to prevent the cursor from covering most the webpage). Here an example:

https://user-images.githubusercontent.com/29925961/161431231-71810b02-5c59-4962-ab58-24c372183631.mov

**Comment by helenvarley** [comment]
ok, i think we can live with that - @vickis ?

**Comment by vickis** [comment]
Yes it’s fine- thanks Phat :)
