### ISSUE TITLE
new stages should be "rehearsal" status by default

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#810]
we just discovered that if you make a new stage & do not give it any status (live / upcoming / rehearsal) then it is not visible to anyone else e.g. admins cannot find it in the stages list.

stages should have a default status of "rehearsal".

**Comment by vickis** [comment]
agree - default setting is rehearsal is important especially for newbies
(otherwise we will end up with a heap of 'ghost' stages :)
