### ISSUE TITLE
email notifications - option to send to admins?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#814]
i have just used the email notification system to let the meta UpStage team know that jitsi is not working but being fixed - this is really useful to be able to quickly send a message to the appropriate people! :smile: 

it would be good if there was also an option to send to a particular group, for example today i just needed to send to those who are admins on this server. i had to scroll through the list of all the players (now quite long) and remember who was an admin. is it possible for there to be a drop-down menu, so that we could send to all of a particular role (e.g. admins), or else select individual players from the list? 
probably it's enough to have one option that is to email all admins, and the other option as it is now, to select from the list - since we don't have emails connected to the guest player accounts, so it's really only if we want to email just admins.

**Comment by vickis** [comment]
yes assigning filters to the list will be useful
v :)

**Comment by gloriajw** [comment]
Now every email sent out is CC-ed to admins as well, at the support@ address.

**Comment by helenvarley** [comment]
reopening this as i do not see selecting roles as an option. the request is that we can select for example all admins to send an email to.

**Comment by helenvarley** [comment]
> Now every email sent out is CC-ed to admins as well, at the support@ address.

which admins do you mean? i just sent an email to the meta theater people, & i selected their names from the list. i cannot see in the email notification interface what their roles are. i can't select to just send to the admins of this instance.

i've received a copy of the email so i guess it is cc-ing to upstage.live admins? but what this issue is about, is being able to select a group of players by role to send the email to, e.g. all those who have admin status on the meta theater instance.

**Comment by helenvarley** [comment]
just to clarify, in case it is not clear in the above discussion:
in the Admin > Email notification interface, we want to be able to select a group of players to email to, e.g. only those who have Admin status, or to all players (excluding guest accounts as these are not people's personal accounts).

**Comment by helenvarley** [comment]
great work! 😄 
i wrote my question on the other issue then saw that it fits better here:
is it possible to select more than one role? for example, what i most often want to do is send to everyone apart from guests; so i would need to select player, admin & super admin. now, if i select player and move them to the recipient lists, then try to select Admin to add them, it removes the players from the recipient list.

**Comment by teddyfullstack** [comment]
> if i select player and move them to the recipient lists, then try to select Admin to add them, it removes the players from the recipient list

Yes, but only if you decide to click send with that list. Otherwise, when you clear the filter, all of the users you have added before will be preserved. Here is a demo if my explanation is too vague 😅 (I cropped it to hide the emails)

https://github.com/upstage-org/upstage/assets/29925961/0c564a8a-ca6e-4186-8105-5d6471e3530d

**Comment by helenvarley** [comment]
aah, ok - this is good, but we're going to need to explain that in the manual ... & actually probably on the interface as well (i might not remember it myself! :laughing: ). let me have a think about how to best describe it.

**Comment by helenvarley** [comment]
how's this - for text at the top of the email form:
"From the list on the left, select the player or players that you want to email and click the arrow to move them to the recipient list. 
If you want to email a specific group, e.g. all Admins, use the dropdown menu on the left to filter the player list by role. 
To send to multiple role groups, use the dropdown again to select the next role, and transfer the desired players to the recipient list. Then clear the filter by hovering over the arrow in the dropdown, which will change to an X. Once the filter is cleared, all the players you have selected will show in the recipient list."

@vickis can you do a comprehension check on this? :stuck_out_tongue_winking_eye:

**Comment by teddyfullstack** [comment]
Here you go 👌 

<img width="1439" alt="Screenshot 2024-02-17 at 14 03 15" src="https://github.com/upstage-org/upstage/assets/29925961/50b83660-dc79-4fd6-a121-bc444b087b48">

**Comment by helenvarley** [comment]
great! :+1:
