### ISSUE TITLE
email notifications - refresh screen after sending

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#815]
after hitting send on the email, i got the pop-up message that the notification has been successfully sent & the names of the players it's sent to; then the notification disappears - and the screen remains with my message and the selected plaayers, as if i have not sent the message.

can the screen refresh after that, so that it's clear that the message has gone? it could either be a clean email notification screen (clicking on the Email Notification menu option did not do this) or else the successful notification could be on the body of the page instead of as a pop-up, with a button to click if you want to send another email notification.

as it is now, if i wanted to send a second message, i have to use the browser refresh button, or navigate to another screen and back again. i also feel nervous that the message has not been sent, because i'm still seeing it there on the screen.

**Comment by vickis** [comment]
yes agree - sounds like send is also clear message

does email notification archive anywhere?  in which case cc to self is
always a fail safe for checking messages have gone
:)

**Comment by helenvarley** [comment]
i don't think they do get saved anywhere - & probably not necessary, might just take up a lot of space.
i did send these messages to myself as well. but it should not be difficult to have the screen return to a new message screen or something that makes it more clear that the message has been sent.

**Comment by helenvarley** [comment]
very nice solution! 😎
