### ISSUE TITLE
all players from upstage.live are now also on dev instance

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#817]
i was going to send an email notification to all the players who have accounts on the dev instance, to let them know about the url change. however, i discovered that all of the player accounts from upstage.live have been duplicated on dev-app.
i guess it doesn't matter so much since most of them don't know about the existence of dev-app & would not use it, but it's a bit confusing as it would be quite handy sometimes to be able to email everyone on dev-app, for example now to let them know about the url change, or if we needed people to test things. 
it's maybe also not great for security, since people's emails are also there.
i can manually delete those who i know don't need an account on the dev instance, but will this happen again when there is an upgrade? and also i'm not sure that i remember everyone who should have an account on the dev instance ... :thinking: 
i see all the media & stages are also copied over - i guess it's not a bad thing to have the dev instance with all of that there, but does it raise any issues e.g. copyright?
for sure it's good to have a backup but maybe that should be something other than the dev instance?

**Comment by vickis** [comment]
agree dev instance is good for just minimal numbers, experienced? and also
not loaded with material
however it is good to have a range of media to test various aspects
and there would be no issue with copyright if we are just using for test
purposes - again a range is useful to test how things are working :)

**Comment by gloriajw** [comment]
dev wipe script takes care of this issue.

**Comment by vickis** [comment]
super thanks Gloria :D

**Comment by helenvarley** [comment]
so should i manually remove all the extra players? they are still showing up on dev-app (but the stages and media have been dramatically reduced).

**Comment by gloriajw** [comment]
Let's wait until @nguyenhongphat0 perfects his cleanup script, then he can run it and then dev-app1 will be clean. I asked him to make one change to it.

**Comment by gloriajw** [comment]
It would not hurt anything if you remove players. Just realize that anything you add may be deleted.

**Comment by vickis** [comment]
maybe wait for Phat to work his magic :)

What i think Gloria means is that if a player has added media then by
removing them you remove their media (this is perhaps something we need to
think about outside of this post
especially if we are having walkthrough etc and then that player goes on to
create their own UpStage instance for their organisation
when they leave (and their login removed to tidy things up - all media
attached to that player might or should be also cleaned up ...

**Comment by helenvarley** [comment]
yes that's my question - does deleting a player account also delete any media they have added.
actually this should probably be an option - when deleting a player can it be possible to either delete all their media, OR to assign that media to a different player (or to a generic owner?)
this would also apply to stages, when deleting a player to have the option to delete stages created by them or to assign them to another player (or generic owner).
i can imagine scenarios where one might want to have everything deleted, but also where you would not want that; for example if a player had ended up with two accounts (can happen if people forget their password & create a new account with a different email address), or if a player leaves for any reason but has contributed media for a performance that continues, & is happy for that media to still be used in the performance. it would be easier to transfer to another player rather than reupload stuff.
i guess this is becoming another issue ...

**Comment by nguyenhongphat0** [comment]
Currently the `clean up` script doesn't removing any players. It just:
- Remove all stages, excepts the one you want it to be kept, such as the `demo` stage
- Remove all media, except the one that are currently used by the "stages to be kept" above
- Remove all scenes, replays, archived events,...

If you would like me to remove the users as well, I can do it. But would it be inconvenience because we would need to register again (and waiting for admin approval) after each wiping?

**Comment by gloriajw** [comment]
Maybe in dev we do an automatic approval. You can check the ENV_TYPE 
variable to determine what to do.

I do recommend adding an htpasswd in the nginx layer in dev, ot prevent 
spam registrations.

**Comment by vickis** [comment]
agree we can probably remove players ourselves (and create an internal
process to transfer media )

**Comment by helenvarley** [comment]
if we remove the current excess players on dev-app, then just leave the ones that we want there, then the clean-up should not remove the small number of players that we want to have on dev-app. it won't normally copy all of the players from upstage.live, will it?

**Comment by helenvarley** [comment]
not sure we would want automatic approval, as random people could stumble on the foyer, couldn't they, then register an account?

**Comment by gloriajw** [comment]
This is why I recommended an htpasswd in nginx, to prevent that.

**Comment by gloriajw** [comment]
I'd like to see everything cleared, except static content that cannot be uploaded by users (stuff that Phat places in the static folder).

**Comment by helenvarley** [comment]
ok, i tried to delete all the players that we do not need. i started by deleting those who still had usernames that i recognised. some of these were possible to delete, others not - i got this error message:
![Screenshot from 2022-03-12 12-47-01](https://user-images.githubusercontent.com/3437324/158016822-ee64dbce-7382-4eea-b3e2-e489cd0cae38.png)

**Comment by helenvarley** [comment]
we certainly don't need 109 users on dev-app,- shall i remove all of the other ones that are just numbered users?

**Comment by helenvarley** [comment]
i am also trying to remove stages, and getting similar error messages as above on some, while others i can delete

**Comment by nguyenhongphat0** [comment]
> i am also trying to remove stages, and getting similar error messages as above on some, while others i can delete

Sorry for the inconvenience, the error above means you cannot delete users that owns some stages. I'm submitting a pull request to fix that!

**Comment by vickis** [comment]
it might be tricky if removing players also removes stages and media as
generally not everything on a stage will be associated with one player...

having clean processes for removing extra artefacts and users is important
:)

**Comment by helenvarley** [comment]
> 
> Sorry for the inconvenience, the error above means you cannot delete users that owns some stages. I'm submitting a pull request to fix that!

can there be a prompt that asks do you want to delete this player's stages & media or assign to another player?

i can imagine lots of scenarios where we might want to delete a player but keep stages created by that player or media uploaded by that player - for example if someone has ended up with 2 accounts by mistake, or if there is a group collaborating and one person leaves for any reason but things should still be kept.

**Comment by helenvarley** [comment]
i'm going to close this issue and open a new one about a prompt when deleting a player, since the original issue is resolved.
