### ISSUE TITLE
email notifications - option to send as BCC

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#819]
currently when an email is sent to multiple players, the recipients are all in the "To" field and can see each others' emails. 
i think this is not a problem when sending to a few players or to admins, as usually they will know each other or at least know that they are part of the UpStage community.
however when we are sending out a message to all players on upstage.live, it's not best practice for them to see everyone's email, as they do not all know each other. 
can there be an option to send as "To" or "BCC" ?

**Comment by vickis** [comment]
yes important bcc by default :)

**Comment by gloriajw** [comment]
Done!

**Comment by helenvarley** [comment]
i don't see any option to send a BCC? there is the option to add additional receivers which is great but seems like no option to select BCC ...?

**Comment by nguyenhongphat0** [comment]
You can now specify who would be in the `Bcc` / `To` group individually, using the new column👇
 
<img width="1184" alt="Screen Shot 2022-05-22 at 00 36 33" src="https://user-images.githubusercontent.com/29925961/169663043-fcc85e1b-4321-4d9c-9292-33006f1e194b.png">

(this is not yet on `dev-app1`, I'm not sure if this is really that you need 🥶)

**Comment by vickis** [comment]
this looks super :)

**Comment by helenvarley** [comment]
yes great! i see it is on dev-app - is it ready to be tested? i would send a notification to everyone apologising for them all being in the To field on the last email & saying that we have rectified it so that super-admins can use To or BCC to message UpStage players (did we limit it to super-admins? or admins?)

**Comment by nguyenhongphat0** [comment]
> is it ready to be tested?

It is ready now!

> did we limit it to super-admins? or admins?

Admin will do it. We already discussed about removing Super Admin. (or we didn't 🤔)

**Comment by helenvarley** [comment]
great, i will send a test mail. 

we did discuss about removing super admin, but i think the conclusion was that we needed to keep it for things such as the email notifications - because they are sent from the UpStage support email address. so it would be weird if, for example, one of the admins from meta theater could send an email to their players that was showing as coming from UpStage support.

we probably need to work through a few use cases on this to more clearly determine what the powers of a super admin might be, and how and for what purpose the email notifications are. (admins can of course contact players individually by finding their emails in the player list.)

**Comment by helenvarley** [comment]
& i just saw your test email so it looks like it's working :)

**Comment by helenvarley** [comment]
i tried to send an email with some players only in the BCC field, and no-one in the To field. it would not send it, i got a message saying "Please select at least one player or provide an email address"

in normal email it is possible to have addresses only in the BCC field, not in the To field. can we not also do this?

**Comment by nguyenhongphat0** [comment]
Technically, yes. But I think it would be "unnatural" to read an email that was sent to "no one". However I will remove the required to field 👌

**Comment by helenvarley** [comment]
thanks :)
i am often sending emails with nobody in the To field, and a bunch of people in the BCC ... i am not sure what shows up for the recipient, but i think i must receive similar ones. it's really just an etiquette thing - that if you are sending something to multiple people who may not know each other, it's polite not to share their emails.

**Comment by vickis** [comment]
in the instance of sending multiple BCC i would normally send to one of my
own addresses
this is usual practice 9it helps to see what everyone receives and i think
will help avoid spam filters weeding out unsolicited emails :)

**Comment by nguyenhongphat0** [comment]
I think this issue is done now!

**Comment by helenvarley** [comment]
thanks very much :)

**Comment by vickis** [comment]
woop! :)
