### ISSUE TITLE
audio not heard when i enter stage & it's already playing

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#820]
i realised today with phat's women's day gift, https://upstage.live/8thMarch, that no-one hears the audio unless it is started after they have entered. this is really a pity! can we solve this? 
if there's an audio track playing when you enter the stage, is it possible to start hearing it automatically, at the point that it is at? i know there is an issue with not knowing how far through the file is, & it's not the same as streamed audio. but it would be cool if we could find a solution.
if not, can there be an option somewhere that would let us decide - either that when someone enters after an audio has been started they hear it from the beginning (good for looping sound effects for example) or that when someone enters after an audio has been started they just don't hear it (useful if the track might then go on too long, or if it wouldn't make sense if they don't hear the beginning).
ideally though they should be able to enter & hear it where it is, as if they have walked into a theater & hear what everyone else is hearing.

**Comment by helenvarley** [comment]
and weirdly, just now the audio suddenly started playing by itself! i had the women's day stage open in a different tab, was in the demo stage talking to gloria & vicki so definitely no other audio, finished the meeting & was creating a different issue when suddenly the audio on the women's day stage started. there is no=one on that stage ... :ghost:

**Comment by vickis** [comment]
would be great to have everything that is happening for those already on
stage shared (i think we have gone through this before)

 - if it is possible? it would require the stage detecting the entrance -
perhaps like a sped up recording playing everything prior until the new
attendee is at the same point as others

or just consider that,  like in theatre,  if you arrive late you have
missed what already happened and are disrupting other audience
perhaps there is a facility where you can close the door to late comers ;)

**Comment by vickis** [comment]
oh ha ha that was me ;)
i went in to have another look ...

**Comment by helenvarley** [comment]
this one is a bit curious, as i thought it had been fixed, but i've just tested & it isn't working. at least, not just now ... i'm pretty sure i have entered stages & heard audio playing when i enter. 
also, the video on https://upstage.live/whatmobilisesyou has been working really well in terms of playing when people enter; but just now i entered the stage and it's not playing, even though it's on the stage & was playing before.
so it seems this still needs some attention.

**Comment by helenvarley** [comment]
on upstage.mur.at at the moment it seems that a video left playing will be playing when you re-enter, but audio not. then every now and again it IS playing when you enter, which is confusing!

**Comment by vickis** [comment]
Might be an issue or complication with mur instance as seems working in others and all instances now same version right?

**Comment by helenvarley** [comment]
it's not working on the other instances.
try going in to the Demo stage on upstage.live, where i have left the waves audio playing.
when i enter i don't hear it, but the icon in the audio tool bar looks like it is playing (instead of the play arrow it shows the pause button) but the seconds are on zero and not moving. same thing on qmu.

**Comment by helenvarley** [comment]
strange - i've tested again today on all 3 instances (upstage.live, upstage.mur.at and qmu.upstage.live) and it worked on all three. so i'm going to close this issue for now & hope that it keeps working!
