### ISSUE TITLE
studio: is "cancel sorting" necessary?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#822]
there is a loading issue with the demo stage on dev-app (it gets to 30/47 & stays there for ages before finishing loading) so i was trying to see if there was a very large file. in the studio, i filtered by demo stage and all players, then clicked on the "size" tab. the first click sorted by ascending, the second click is descending, & then if i click again it's "cancel sorting".
this seems unnecessary & a little confusing - at first i wasn't paying attention & just assumed that each click was toggling between ascending & decsending.
why would we need to cancel the sorting? can it just be ascending or descending?

** very minor & non-urgent!

**Comment by nguyenhongphat0** [comment]
> why would we need to cancel the sorting

Because we have multiple criteria sorting!

> can it just be ascending or descending?

In that case you won't be able to remove a sort criteria. For example: you are sorting `uploader ascending`, `media type descending` and finally `size asecending`. What if you you want to sort by media type without grouping them by `uploader`? Cancel sorting on the `owner` column will do it!

**Comment by helenvarley** [comment]
i think mostly we are not going to be doing such complicated sorting. because it's pretty confusing. for example now i tried sorting by all columns, so it means that when i get to "size" it doesn't make any difference to the displayed list.
i guess we should just leave it how it is & work out a bit more how we need to be able to use it. i'll close this issue for now :smile:

**Comment by vickis** [comment]
Good idea
