### ISSUE TITLE
ability to change email address that notifications are sent from

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#825]
can there be an option, either in the system configurations or email notification interfaces, to change the email address that the notification is sent from? it seems to be hard-coded to be sent from support@upstage.live, which is fine for us, but other instances might want something different.

**Comment by gloriajw** [comment]
This is a tough one. I would not recommend changing this, because its one of the flags that make email look like spam. It has to come from an upstage.live address to be sent through the upstage.live account and not be marked as potential spam.

**Comment by gloriajw** [comment]
It sounds like what you want is a dynamic email list, which survey monkey and others do. They allow you to upload user lists, attach content, and send to the masses from any email address. This is different than what we can do on our back end with the gandhi email account.

**Comment by gloriajw** [comment]
I think we'll have to set up valid email aliases in gandhi for each client "from" address we wish to use, so they won't be marked as spam. What would they look like? Is it something like metatheatre@upstage.live?

**Comment by helenvarley** [comment]
hmm, maybe this is not really such a good idea - we don't want to get into setting up email addresses for every hosted instance do we? it feels like it could create a lot of work, or would it not?
a dynamic email list on a third party platform is something people can do themselves if they want that. but what we want within UpStage is an easy way to send messages to players on a particular instance. these messages would mainly be maintenance notifications, but i can imagine other situations, for example if there has been a lot of activity and the admin(s) want to tidy up the instance by purging old stages that aren't needed any more or suchlike, and want to let players know. this kind of email should come from the admins of that instance, not from us.
if we decide that the email notifications within UpStage are only for official maintenance informations from UpStage i.e. us, rather than other communications of the group owning the instance, then the email notification part of the admin area should not be acecssible to other admins. maybe this is where the super admin role comes in?

**Comment by vickis** [comment]
ok yes - so the email is noreply - and the instruction is to send any
defects to the local support ...

**Comment by helenvarley** [comment]
there is a separate issue about making the support email accessible somewhere in backstage (#802 )

**Comment by vickis** [comment]
yes great

 - for support info and technical
for general admin to the players on any particular instance we might have
to have a separate channels

eg for technical issues support@ or metatheatre.support@

for general questions/suggestions/discussion an assigned email  (we want a
channeling system so 'support' does not get bogged with extraneous emails :)

**Comment by helenvarley** [comment]
closing this as it's duplicated = #1145 and #1225
