### ISSUE TITLE
studio: file manager stays in front of upload interface

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#828]
when i upload a new media item to the studio by dragging and dropping it to the upload window, the file manager window stays in front of the upload interface & i have to manually switch to the upload interface. but if i upload the media by clicking on the upload icon in the upload interface, the file browser window disappears after i've selected the file, which is nicer.
is it possible to make it automatically switch back to the upload interface after dragging the file there? i think this happens with things like wordpress.
if it's not possible, nevermind - this is a very minor detail!

**Comment by nguyenhongphat0** [comment]
On my machine, the `drag & drop zone` always pop in above the `media table` (like the recording). Does it behave differently on your browser, or is that I'm not understand what you are describing :sweat_smile: 

https://user-images.githubusercontent.com/29925961/158631681-0495be33-8737-4343-aca4-f77163396544.mp4

**Comment by helenvarley** [comment]
![file_manager_in_front](https://user-images.githubusercontent.com/3437324/158843631-1105cd80-9ad5-46f1-9c5e-bf91f34b9374.gif)

**Comment by nguyenhongphat0** [comment]
Ah I got it now 😆 It's the native file manager behavior and it's depend on the system you're using. We cannot control that 😅

**Comment by helenvarley** [comment]
ok, then no problem! :)
