### ISSUE TITLE
stuiod: uploading several audio files, preview plays first audio

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#829]
i just uploaded 5 audio files one after the other. i noticed that, before i saved the each file, if i played the preview that was showing in the upload interface it always played the first file that i had uploaded. 

after saving, the preview showing in the media list plays the correct file, however if i click on edit and play the preview in the pop-up window, it always plays the first one. if i don't stop the audio preview but just close the pop-up, i keep hearing it.

**Comment by vickis** [comment]
🙌
