### ISSUE TITLE
cannot place avatar on top of jitsi window

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#836]
today i had the jitsi window very large, filling the whole stage. i then wanted to place an avatar on top of it - but when i dragged the avatar onto the stage, on top of the jitsi window, it actually replaced the whole stage with the avatar image in the browser tab - i was no longer on the stage. in order to place the avatar, i had to reduce the size of the jitsi window so that i could put the avatar beside it.

is this something we can change, or is it a fact of jitsi? if it's the latter then it would be good to note in the manual.

**Comment by vickis** [comment]
it would be really great to move jitsi through layers like any other object
yes
i am excited about how the streaming and avatar interaction can work

**Comment by helenvarley** [comment]
we can move it through the layers (the right-click context menu is not an UpStage one so you can't do it there, but you can do it with the depth tool or by moving other objects in front or behind the jitsi window).
the issue is that i could not put the avatar on stage at all when the jitsi window was filling the whole stage.
if you drag an avatar or prop on top of the jitsi window when you are trying to place it (the avatar or prop) on the stage, the entire stage is replaced with the image file of the avatar or prop. so you have actually left the stage and are just looking at that avatar or prop opened in the browser tab.

this is really only a problem if you have the jitsi window very large, however in my experience so far using jitsi on UpStage - this is often what we are doing. the only solution is to reduce the size of the jitsi window, but if you want it filling the screen for performance or aesthetic reasons, then it's disturbing to have it reducing and increasing each time you need to place media on the stage.

previously in UpStage the area outside of the backdrop was actually also useable, & i've noticed that this does not happen anymore. it gave us a kind of "wings" as you have on a physical stage - we could place avatars etc "off-stage" and then move them in. i wonder if we could achieve that somehow ... but that's another issue.

will it be possible to have a way that media items can be placed on the stage when the jitsi window is filling it? or that's just not going to work??

**Comment by helenvarley** [comment]
great, thanks giang! i can now place an avatar on top of the jitsi window :smile: 

i am having difficulty resizing it - but maybe this is just me. i can make it smaller, but not bigger. when i try to make it bigger, it actually goes smaller or moves around as if it's got attached to my cursor. is this just me or does this also happen for you @vickis ?

**Comment by helenvarley** [comment]
i have just tried this on dev-app & i can now resize the avatar on top of the jitsi meeting window, BUT it is only possible to do this if i drag the corner beyond the frame of the jitsi window. 
if i try to make it a little bit bigger, within the jitsi frame still, it doesn't work - it will only go smaller. 
i have to click and hold, and drag the corner beyond the jitsi frame, then it will become much larger.
this was in firefox.
![Peek 2022-07-13 17-42](https://user-images.githubusercontent.com/3437324/178775332-27b46b54-dec0-4710-aff0-e9fd969614c2.gif)

**Comment by TuyetGiang** [comment]
@helenvarley please try again. The updated code already on dev-app1

**Comment by helenvarley** [comment]
sorry i got sidetracked with something else.
i am still having difficulty ...

**Comment by helenvarley** [comment]
ok, we have a solution! the trick is to place the avatar, click away from it onto something else (eg the jitsi window) and then click back to the avatar. then you are able to resize it as expected.
we need to note this in the manual ...
![Peek 2022-07-13 18-38](https://user-images.githubusercontent.com/3437324/178786205-17b1b115-9fcb-4e67-a23c-adba6fd5cdb6.gif)

**Comment by vickis** [comment]
i think the light bulb has the effect of wings in terms of things moving
from out of sight to onto stage

the work around would be to have the avatar on stage and then bring it in
front of the jitsi window with the depth tool (eg if you your
performance requires the entire stage realestate to be the jitsi window
then that in effect acts as a type of 'wings')
