### ISSUE TITLE
stage management - layout enhancements

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#841]
is it necessary for the player list to take up so much space on the stage management interface? could the lists of names be actual dropdowns, rather than visible all the time? it makes the "stage status" options a bit hidden and therefore easy to forget about.

i think it would make sense to have the "stage status" options higher up, e.g. between the stage description and the player access lists, and if possible the lists as dropdowns.
(NOT URGENT)

![Uploading Screenshot from 2022-03-14 09:43:37.png…]()

**Comment by vickis** [comment]
Tidy yes :)

**Comment by helenvarley** [comment]
closing this as the stage status options are now above the player lists; it still means that the cover image is very far down - wondering if that would be better on the "customisation" page ... but that's another issue!
