### ISSUE TITLE
using separate images of multiframe media items

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#842]
we have discovered that there seems to be no way to use a separate image from a multiframe media item. for example if you have a series of 10 images in a multiframe, and then want to use one of those images as a still object, or as a curtain, or in combination with different images in a new multiframe item.

we could of course upload the separate image again, but since they are already uploaded, it would be nice if it was possible to use them without having to upload again. can we think about a way to do this?

**Comment by vickis** [comment]
This seems To be creating a complication for code
Easier to just load the image to use for alternate purposes
Then that object has the rules by which it behaves assigned at upload :)

**Comment by nguyenhongphat0** [comment]
>  for example if you have a series of 10 images in a multiframe, and then want to use one of those images as a still object, or as a curtain, or in combination with different images in a new multiframe item

Actually you can, but it would take a fews more click:

![image](https://user-images.githubusercontent.com/29925961/158433166-5b01ad1a-0b51-4adf-9a08-b9819acaa1a9.png)

![image](https://user-images.githubusercontent.com/29925961/158433400-9e7033aa-3415-403b-bc7a-5b39d5a545da.png)

![image](https://user-images.githubusercontent.com/29925961/158433528-03f18b84-9d53-4805-81e9-dbd4c9f172d1.png)

![image](https://user-images.githubusercontent.com/29925961/158433983-763b6eab-3f07-4cba-a1d9-a20930d5da94.png)

**Comment by helenvarley** [comment]
hmm - i tried this process but it seemed to replace the multiframe backdrop with the single one. i guess i didn't manage the workflow properly.
but vicki & gloria are right, it's not so difficult to upload a single frame. the way we are working at the moment, eva had created & uploaded the backdrop images, then sara & i were working separately & wanted to easily find one frame, without having to ask eva for the original. 
it's not likely to be a common situation so for now let's not worry about it :smile:
