### ISSUE TITLE
adjust speed of scene transitions

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#843]
is it possible to be able to adjust the speed of scene transitions? in the Stage Management we have the possibility to adjust speed and animation of the curtain and speech bubbles, so it seems logical to be able to do the same here for scene transitions.

also at this interface, it seems that the default settings for speed is at the fastest possible. it would be better if the default speed was in the middle.

**Comment by vickis** [comment]
Agree :)

**Comment by helenvarley** [comment]
a slow scene change can be achieved by using a curtain - set the curtain to fade rather than lift up or down, and on a slow speed. put the curtain down, change the scene, put the curtain up.
