### ISSUE TITLE
changing url meant saved scenes not accessible on stage

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#846]
today i changed the url of a stage, because it had spaces in it & i thought it would be safer without. however, after removing the spaces, none of the scenes that we had saved were available on the stage. i think all the media was still there, definitely the audio files, but no saved scenes. i had a look in the stage management & saw the scenes were still there, so i changed the url back to the original, and then the scenes were once more available on the stage.

if this is how it's got to work, then there should be a warning when you change the url - saying "Changing the url may make some things such as scenes no longer accessible on the stage. Are you sure you want to do this?"

i think people will not want to change a url very often, but maybe there could also be a prompt by the url field, suggesting that people make it short & without spaces (or does this not matter at all anymore??)

**Comment by vickis** [comment]
That makes sense to me that the url change would affect scenes
They are like video editing where they hold the link to all the media and
assemble on request (or for video in export)

I would avoid changing the URL but I am probably thinking from a front end
perspective :)

**Comment by nguyenhongphat0** [comment]
Sorry to say this, but changing url would cause a lot of things to break at the moment, includings chat, performances and scenes,...

The reason are the `mqtt` broker and our stage doesn't glued with each other by `id`, but by `stage_url` instead. This is designed to be like that because I first developed the `demo` stage without having our stage dynamically created, that moment we don't have stage ids, we just have stage urls.

To fix this, we have 2 solutions:
- Chaining all connections from url to id. As a result, every performances, chat and scenes,... will be messed up (sorry about this, we should have done it earlier)
- Freeze url after stage are created. Which means you cannot change url after stage are created, so choose it carefully (this is the easiest solution)
Let me know which way would you like to proceed, and sorry for my bad design :facepalm:

**Comment by helenvarley** [comment]
let's go for freezing the url - if it's the easiest solution, & it also sounds like the safest solution.
BUT we need to make this clear at the time of creating the url, and provide some good hints about making a good url. i have seen some stages created with unnecessarily long urls, or with typos in them, or like the one i changed which had spaces. (spaces don't break the url, but they will break it if for example you put it into an email and it goes over a line break; also they can end up with lots of messy looking % symbols in them).

so there needs to be suggestions that the url have no spaces or punctuation, be short (should we give a character limit?) and meaningful. and a sign that once you have created the url it can't be changed.

we can of course easily clone the stage and give it a new url, so for example in the case of typos this would be the way to fix them - clone with new url and delete the old stage.

**Comment by nguyenhongphat0** [comment]
Okay, so here are the changes:
- Provide some good hints about making a good url:
![image](https://user-images.githubusercontent.com/29925961/158866888-240a0ca6-a2c1-430d-a896-a6d9212813b9.png)
- Prevent spaces and punctuations inside stage url :
![image](https://user-images.githubusercontent.com/29925961/158866996-930cda90-6a44-41cd-966c-94ec49ea9239.png)
- Freeze stage url after it had been created:
![image](https://user-images.githubusercontent.com/29925961/158864566-e6b9bba1-425c-4537-933b-aa38835d2d04.png)
- Maximum limit of 50 characters

**Comment by vickis** [comment]
Perfect Phat! woop :D

**Comment by helenvarley** [comment]
i suggest:
- instead of "Short name" we call it "URL" (most people understand what that means, & "short name" is less clear)
- instead of "Please watch out for ... " let's say "Please avoid ... "
- instead of "Short name should not contain ... " say "URL cannot contain ..."
- instead of "Demo / demo" it would be more clear to have "Demonstration Stage" in the stage name, and then "demo" in the url field

**Comment by helenvarley** [comment]
max limit of 50 characters is pretty generous - surely 10 is plenty?? or 20, i guess if someone really needs a lot ... a url that is 50 characters after upstage.live is surely not necessary?

**Comment by vickis** [comment]
i think max 20
and agree all above

super work team :)

**Comment by helenvarley** [comment]
great @nguyenhongphat0 - just one small correction, should be just "punctuation" (without the s) :smile: otherwise perfect!

**Comment by vickis** [comment]
great work thanks :)

**Comment by nguyenhongphat0** [comment]
No problem 🤗 :

<img width="897" alt="Screen Shot 2022-03-19 at 23 04 14" src="https://user-images.githubusercontent.com/29925961/159128723-c04fd663-be33-4255-89d8-7875af19b98d.png">

**Comment by vickis** [comment]
:D
