### ISSUE TITLE
possible to set another player as owner of media item?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#858]
today one of the meta theater artists sent me images for an avatar for her, and asked me to upload it. i have done this, so i am shown as the owner of this avatar. i would like to be able to set the owner as her. could this be something that admins can do? 

it could be an option that shows up on the "Permissoins" tab of a media item's edit interface, but only visible to admins (it should not be possible for ordinary players to change media item ownership).

this would also be useful in workshop / teaching situations.

**Comment by nguyenhongphat0** [comment]
> it could be an option that shows up on the "Permissoins" tab of a media item's edit interface, but only visible to admins

Here you go 👇 
<img width="1050" alt="Screen Shot 2022-03-28 at 23 58 18" src="https://user-images.githubusercontent.com/29925961/160449654-f528796e-69ba-4ca8-a739-d7b6d4e74a27.png">

**Comment by helenvarley** [comment]
that looks great! :+1: 
what happens when you have permissions showing up there, like this - can the owner field also fit?
![Screenshot from 2022-03-28 21:03:36](https://user-images.githubusercontent.com/3437324/160468625-79c2b629-8e3f-4c7a-9a18-e8c6ad28ec24.png)

**Comment by vickis** [comment]
great yes very useful :)

**Comment by nguyenhongphat0** [comment]
Should I move the owner dropdown to the top, like this?

<img width="998" alt="Screen Shot 2022-03-31 at 00 19 17" src="https://user-images.githubusercontent.com/29925961/160894637-66982aaa-2b34-40b9-bc25-b4009b80bb41.png">

And I fixed the floating question mark, didn't know that it look so weird in Firefox 😅

**Comment by vickis** [comment]
Looks great Phat :)

**Comment by helenvarley** [comment]
let's try it! :+1:

**Comment by nguyenhongphat0** [comment]
It's on dev-app1 now ☝️

**Comment by helenvarley** [comment]
great - seems to work. i uploaded an avatar & changed the owner to @vickis - with permissions "use with acknowledgement" so then i could also keep editing it.

**Comment by vickis** [comment]
super!
vicki :)
