### ISSUE TITLE
media permissions: possible to add more information?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#859]
it would be useful to be able to add more information on the permissions tab of a media item. for example, i've just uploaded a backdrop that is a photo taken by eva ursprung. she gave me permission to do this, and to set the permissions to "use with permission". the system allows players to request permission from me, but in some time i may have forgotten who created the original image. so it would be useful to have a "Notes" field on the permissions tab, where i could note the actual copyright owner when it's not me, and other information such as what the image is of, when or where taken, this kind of thing.

i'm imagining it would just be a text field where i could save these kinds of notes.

**Comment by vickis** [comment]
Yes useful :)

**Comment by helenvarley** [comment]
looks really good! it's a bit difficult to fully test with so few media items on dev-app, but it seems fine and once it's on upstage.live we can see if any refinements are needed.
