### ISSUE TITLE
backdrop replaced instead of new backdrop created

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#861]
i am trying to upload several backdrops, to meta.upstage.live. the first one uploaded fine, but now whenever i upload another, it simply replaces the previous one.
![backdrop_replaced](https://user-images.githubusercontent.com/3437324/160420434-83124860-69a4-4108-b19f-275f0c0d0eda.gif)

**Comment by helenvarley** [comment]
i went out of the studio and back in again, then uploaded a backdrop and it worked as expected. then i waited for a bit and uploaded another, it also worked as expected.

**Comment by nguyenhongphat0** [comment]
> i went out of the studio and back in again, then uploaded a backdrop and it worked as expected. then i waited for a bit and uploaded another, it also worked as expected.

The issue is quite hard to replicate because it only happen if you upload a media > open another media to edit and save > upload another one. It got fixed in pull request #866 , and will be available on `dev-app1` as soon as it got approved! Sorry for the inconvenience 😅

**Comment by vickis** [comment]
No problem phat - awesome work as usual :)

**Comment by vickis** [comment]
so this is closed?

**Comment by gloriajw** [comment]
Yes
