### ISSUE TITLE
audio playing on entry to a stage?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#869]
i know we have discussed this before & it's a tricky one, but it would be so good to be able to hear the audio that is playing on a stage when you enter it.
i'm particularly thinking about this right now because i was looking again at the women's day stage, & it seems such a pity that no-one will ever hear the music, unless they happen to be on the stage when a player adjusts it somehow. 
is there really no way we can get around this? 
even if it's not possible to make it that late-comers hear audio at the same point as everyone else is hearing it (i know this is the difficult thing), could it be that there is some option for situations such as the women's day stage, where it's not necessarily a live event, or another example might be an announcement that you want everyone to hear no matter if they enter late?

**Comment by nguyenhongphat0** [comment]
Modern browsers require user interaction to play audio. That’s why autoplay won’t work (except for movies that muted). I think we can cheat this behavior, by using the click that lift up the cover image (we used to do it with voice)!

**Comment by vickis** [comment]
thanks Phat
i too think it will be a useful attribute to have :)

**Comment by helenvarley** [comment]
i got confused with vicki's other issue, my brain is still full of covid & i thought it was about the audio but it's not it's about replays. so my comment there is really more about this issue:

could a prop's link make an audio file play?
if we could access the url of an audio file via the studio then give that link to a prop - i guess the tricky bit is that it would have to open the url in a new window ... is there any way for the brower to recognise that it's a sound file and just play it?
this could be useful in a lot of situations - for example to offer the audience an applause button that actually plays the sound.

**Comment by vickis** [comment]
I think it Might be disastrous to try and force the browser To auto play
when it is by default required  to be an action (as phat.describes )

It could mean being blocked or letting  security issue ...

**Comment by helenvarley** [comment]
hey, i just discovered that this works now! if you set an audio file to loop, it will play when someone loads and enters the stage.

**Comment by vickis** [comment]
Great! Thanks team :D
