### ISSUE TITLE
guest logins should not have access to the studio

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#871]
currently guest logins give access to the studio, as well as to the profile for the guest account. these accounts should only have access to the stage or stages that the guest account has access to.

in the manual we've defined the role like this:
Guest accounts are for use by people who do not have their own player log-in and may not want to have one, for example in workshops or demonstration situations. Logging in with a Guest account allows you to access and operate the on-stage player tools of the stage or stages that the Guest account has been given access to. Guest accounts do not give access to the Backstage.

**Comment by vickis** [comment]
Yes need limited access :)
