### ISSUE TITLE
fill tool in drawing palette?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#872]
today in the walkthrough one of the participants asked "where's the fill tool?" when using the drawing palette.
this could be handy, if it's not too tricky. is it possible?

**Comment by nguyenhongphat0** [comment]
You meant the fill tool like in Microsoft Paint app? That would paint the whole stage in black (or another color) if you don't have a closed rectangle on the stage 🥶

**Comment by helenvarley** [comment]
yes, that kind of tool; & yes, when the walkthrough participant asked where the fill tool was and we had some discussion about whether it would be a good feature, vicki did point out that there would need to be a closed line in order to fill it.

painting the entire stage would not be ideal, but presumably in a performance, the player doing the drawing will already have some familiarity with the drawing tool so would know about making a closed line.

@vickis = what do you think? is a fill tool useful? it's definitely not a must-have (we've got this far without it!)

**Comment by vickis** [comment]
personally i do not think it necessary especially as the brush size can be
so big

you need to have some familiarity with drawing tools to understand the
closed line (it can be just a few points off and end up being open (entire
stage filled) most drawing applications i kno do not intuit that you are
trying to create a closed shape

its very low priority i would suggest :)

**Comment by helenvarley** [comment]
ok, then let's close it :smile:
