### ISSUE TITLE
Stages list - refinements

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#874]
Could the Stages list be refined as follows:
- most recently created (or most recently active??) stages at the top of the list
- toggle to change a stage's status from Live to Rehearsal
- toggle to show or hide a stage in the Foyer

if there is starting to be not enough room, we could think about icons for the "Access" column (or would that not really take up much less space?)

**Comment by TuyetGiang** [comment]
This is on dev-app
![Screen Shot 2022-05-11 at 22 20 16](https://user-images.githubusercontent.com/30744004/167887011-2ac52a9f-3bf7-4832-ac26-8474d5675962.png)

**Comment by helenvarley** [comment]
great! :+1:
