### ISSUE TITLE
process for new public registrations

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#875]
i have just found 4 registrations on upstage.live that are from public (people we don't know) - one from 9 months ago, one from 3 months ago, and 2 from 2 months ago. they are unapproved. i've used the email notification system to write to each of them, asking them to answer with who they are and their interest in UpStage, so that we can find out if they are genuine registrations or spambots or what.

as the registration button on the Foyer is publicly available, and we are going to be doing more publicity around UpStage in general, we need to improve our processes for managing these kinds of public registrations.

- we need to be notified when there is a new registration - an email to info:upstage? or to all admins on the instance? (this is not so necessary for us, but might be for other instances?)
- a way to tag unapproved registrations so that we know they have been sent an email, either some kind of tag or a notes field on the profile pop-up where we can manually enter that info?
- a way to search for an individual player in the email interface - i will make a separate issue for this as the player list on the email interface is sort of but not really chronological ... 

@vickis we probably need to discuss (as part of the business plan?) the details of onboarding random newbie strangers ...

**Comment by vickis** [comment]
Yes agree we will need to address this :) and would be good to have an
alert for registrations
- set up a new user email alert

**Comment by nguyenhongphat0** [comment]
I thought we already had alert for registrations 👀

And the ability to look up user by filtering or changing sort order too 👇 

<img width="1322" alt="Screen Shot 2022-04-12 at 00 39 53" src="https://user-images.githubusercontent.com/29925961/162798075-345783c5-e6c1-4bbf-8717-84f9d65e4bfb.png">

**Comment by vickis** [comment]
The alert for new user
Seems not have been active ...

**Comment by helenvarley** [comment]
the place where it's difficult to find an individual player was in the email notification interface, not the player list (i made a separate issue for that, #876 )

i've never received notification of a new registration :thinking:

**Comment by nguyenhongphat0** [comment]
I just realized that the email notification system for new registration hadn't been running for a while. I've just submitted a patch for fixing it (#881). The feature had been developed in the past, and it would work normally now!
> i've never received notification of a new registration 🤔

**Comment by helenvarley** [comment]
great! i just tested it & it worked - the notification email went to support@upstage.live, and i also got an email letting me know that my registration has been received & is waiting approval.

however, i had to log out of dev-app to create this test user & now it won't let me log in again! so i haven't yet been able to approve the test account to see if i get an email informing me my test account has been approved ...

**Comment by helenvarley** [comment]
is there a place where we can edit the text for the registration emails? (sorry if this is already there, but right now i can't log in to dev-app)

**Comment by helenvarley** [comment]
i received 2 identical copies of my registration approval email, to the same email address

**Comment by nguyenhongphat0** [comment]
Your email was in the ADMIN_MAIL list, so it is always included in the `BCC`. That's why you receive 2 copies if the email is sending to you as primary receiver!

**Comment by nguyenhongphat0** [comment]
> is there a place where we can edit the text for the registration emails

At the moment we don't have it yet. You can send me the new template and I will apply it to our system, it won't take too much work!

**Comment by helenvarley** [comment]
> > is there a place where we can edit the text for the registration emails
> 
> At the moment we don't have it yet. You can send me the new template and I will apply it to our system, it won't take too much work!

if it's something that's coming, then the only changes at the moment are to fix the typo ("you're") and add a link to the manual. the sentence could be "Please look at the UpStage User Manual for documentation on how to use UpStage" and then the link.

**Comment by nguyenhongphat0** [comment]
Here you go 👇 

<img width="602" alt="Screen Shot 2022-04-14 at 22 42 15" src="https://user-images.githubusercontent.com/29925961/163425495-b03e2f1b-2d0d-4b39-89d8-5f6a83ac6298.png">

**Comment by vickis** [comment]
Super thanks :)
