### ISSUE TITLE
finding players in the list on email notification interface 

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#876]
it is currently difficult to find specific players to email from the email notifications interface, and this will get worse as there are more players on an instance.

currently, the list is sort of but not exactly in chronological order by date registered: the list on the email notifications interface reads lilamoore, mahdie, cindy, angeloftheearth, digitalrunner, aman, zahed, david, marlena ... but the actual order of registration from most recent, as shown on the player management interface, is lilamoore, omin, aman, mahdie, cindy, angeloftheearth, digitalrunner, aman, zahed, david ...

ALL LISTS should be ordered either alphabetically or chronologically, according to what makes sense for that list (see #797 ) 

this particular list on the email notification interface also needs to be searchable, in the same way that the player list on the stage edit interface is, so that when there are potentially hundreds of players on an instance it's still possible to find the individual you want to email.

**Comment by vickis** [comment]
yes definitely a searchable list please :)

**Comment by nguyenhongphat0** [comment]
I made the list `alphabetically` by default, and you can now filter the recipients by email or name 👌 

<img width="1169" alt="Screen Shot 2022-04-12 at 00 22 55" src="https://user-images.githubusercontent.com/29925961/162795405-8f74ccfc-9db8-400c-b984-9e404c541b37.png">

**Comment by vickis** [comment]
Super phat!! Thanks

**Comment by helenvarley** [comment]
great! looking forward to testing it :smile:

**Comment by nguyenhongphat0** [comment]
It is on `dev-app1` now ☝️
