### ISSUE TITLE
system configuration interface

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#882]
just a few minor things about the system configuration interface:
- please take the s off, so that it reads "System Configuration" rather than "Configurations" (it's slightly more grammtically correct, as it's where you configure the system so it's a verb)
- in the left-hand navigation, it seems logical to me for the system option to be the last one (after foyer customisation and email notifications) since this is probably the one people need least often
- would this also be the place where a super admin could change the name of the instance that appears in an email subject line? or is that something that's fixed at the time of installation? e.g. at the moment the registration emails have "Dev server" at the start of the subject line, so i'm guessing that the meta ones would have something like Meta UpStage, but it might be that after we've installed an instance they want to change that.
- 
![Screenshot from 2022-04-13 10:47:37](https://user-images.githubusercontent.com/3437324/163139085-c661b1a6-ade9-48de-b823-e73668f7dfd7.png)

**Comment by helenvarley** [comment]
:+1:

**Comment by vickis** [comment]
Cool thanks :)
