### ISSUE TITLE
email notifications

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#883]
if it is possible to have an edit interface for registration emails, could these be edited from the Email Notifications section in Admin?

could there be a dropdown where you choose which email you want, with the appropriate fields, e.g:
- announcement - this is the one we currently have, where you can write whatever you want in subject and body, and select everyone or particular players
- new registration - the automatic email that goes to the email address of a new account registration; here we only need to edit the body of the email
- registration approved - the automatic email that goes to the new player when an admin has approved their registration; here we only need to edit the body of the email

why might we want to edit these automatic emails? i would like to put in a link to the manual for starters, and perhaps a personal note if i know the person who has registered (e.g. they just attended a walkthrough). some hosted instances might want to have a welcome message in a different language, or with specific information about their instance, the group or people running it, etc.

(also there is a typo in the registration pending email - "your're" should be "you're" :wink: )

**Comment by helenvarley** [comment]
further to this: today someone has registered an account on upstage.live - it's not someone i know, they haven't been at an open walkthrough. they will have received the email saying that their account is awaiting approval, and now i have also emailed them (from the info@upstage.org.nz address) with this message:

thanks for registering for an account on UpStage.Live 😁
Before we approve your account, please reply to this email with some information about who you are, and why you are interested in UpStage.

i think we can streamline this process, for example:

- the welcome email that the new user receives could include the request for them to tell us who they are, before their account is approved
- the welcome email should come from info@upstage.org.nz rather than support@upstage.live - the support email is for technical support, whereas info is the one that vicki & i use for open walkthroughs and general enquiries (at least, this is how it has been). if the email comes from info@upstage.org.nz then the person can just reply to that email with their introduction.
- the welcome email invites them to email support@upstage.live if they have any questions - again, shouldn't this come to info@upstage.org.nz? since until their account is approved, they won't really have any technical questions ... and do we really want all UpStage players to be emailing the dev team whenever they have ANY questions?

**Comment by helenvarley** [comment]
another thought - maybe we could include in the registration form a field where they can tell us who they are & why they want to use UpStage, so that we don't need to go back and forth but can decide straight away if we want to approve the account?

the form could ask them if they have attended a recent open walkthrough or other UpStage workshop, and then have a text field where they are asked to say briefly who they are and why they would like an UpStage account.

**Comment by nguyenhongphat0** [comment]
> Before we approve your account, please reply to this email with some information about who you are, and why you are interested in UpStage.

Is that really necessary 👀? I thought the more user we have the better, especially we're an open source project 🤔

**Comment by helenvarley** [comment]
yes i think it is, we need to know who is using our server and for what otherwise we could end up in some tricky situations (racist/sexist or otherwise inappropriate content, for example).

**Comment by vickis** [comment]
it could be useful to help weed out anyone who does not comply with our
diversity and inclusion policy eg (hate speech et al) and also it will help
in how we approach them - perhaps we already know a bit about a couple of
others who have aligning or similar kaupapa (ways of doing things)
it is not to exclude just to continue to ensure a safe space ;)

**Comment by vickis** [comment]
yes agree to the extra form fields - more likely to easily screen bots
and less to and fro

and also yes to info@ rather than support for the registration process
i also do not recognise the registration but have recently heard from one
of the local sensing places team so perhaps word is getting out  :)

**Comment by helenvarley** [comment]
some of this issue has been completed: there is now a field in the registration form for people to say why they want to register. (this should be a required field, i am not sure if it is). however the only place where we can see what they put in this field, is in the rollover in the player list, and there it's not possible to read if they write more than a few words. there is a separate issue for this (#995 )

the parts of THIS issue that still are open, are:

- [ ] ability to edit the body text of the automatic email that is sent to new registrations, and when their account is approved (so that for example those with hosted instances can edit the information as appropriate, change language etc)
- [ ] these welcome and approval emails should be sent from info@upstage.org.nz (which is handled by me & vicki for general UpStage community things) rather than support@upstage.live (which is for technical support & goes to developers as well).
- [ ] in the case of separate instances (meta, refinery, QMU ... ) it would be good if they could change the email address that these registration-related emails come from, since we do not need to know or control who is registering on their instance.

would it be better to create separate issues for these things?

**Comment by helenvarley** [comment]
i'm going to close this issue as some of it has been done, & create separate issues for what's remaining.
