### ISSUE TITLE
video: restarting after pause does not work

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#890]
if i pause a video and then want to restart it, it disappears. i cannot restart it, i have to take it off and put it on the stage again.
![video_pause_restart](https://user-images.githubusercontent.com/3437324/163682784-c752aaed-c5bd-4669-baf1-004615d57a7a.gif)

**Comment by nguyenhongphat0** [comment]
To fix #713, streams now automatically got cleaned up when the host stop broadcasting the stream. So there wouldn't be the possibility to restart a stoped stream, you would need to broadcast again and drag the new stream to the stage.

Besides, I can't remember what that restart button supposed to do 🤔 Should I removed it?

**Comment by helenvarley** [comment]
actually this issue is to do with a pre-uploaded video rather than a live stream. i guess the live stream should not have the pause & restart buttons in the context menu - this can be controlled by the streaming app.

i know we have discussed not having video at all, but since we do already have the ability, and it has been used already in most of the recent performances & events, it's worth keeping and tweaking. as well as making the pause and restart buttons work as expected, it would be great if we could control whether or not the video loops, and also whether it starts automatically or not 

currently it starts playing immediately, before the lightbulb is turned on, so by the time you have resized and positioned it, already some seconds of video have played; and it does not loop (but this is where the play button does work - once the video finishes playing, if you press play then it replays once.)

restart doesn't seem to ever restart the video, rather it removes the video but leaves the frame on the stage. this isn't really what we want.

**Comment by nguyenhongphat0** [comment]
I fixed the issue with the restart button, and add an option to set the Loop attribute of the video 👇 

<img width="518" alt="Screen Shot 2022-06-18 at 02 15 59" src="https://user-images.githubusercontent.com/29925961/174388566-74da0125-c881-4ae6-be1b-df33485ce875.png">

> whether it starts automatically or not

You can pause the video before click the light bulb, that way the video won't start automatically in other players's view 😅

**Comment by helenvarley** [comment]
great :) it seems that now the video is paused when i put it on the stage, so i can choose whether to start it playing and then click the lightbulb, or click the lightbulb and then play it. 
play & pause work as i expect, & i understand that the restart button lets me restart the video from the beginning, if i have paused it partway through.
