### ISSUE TITLE
cover image - media selection options

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#913]
i uploaded an image as a curtain, so that it could be used as both a cover image for a stage and a curtain. but in the options to select an image for the stage's cover image, there are no curtains showing. backdrops, props and avatars are there but not curtains.

and: the current cover image selection interface is going to very quickly be unworkable, as it shows quite large thumbnails of the available media. it would be better to have filtering or drop-down options, as there are in other interfaces, so that you are shown by default your own images, and can filter by media type or search rather than be shown everything.

**Comment by TuyetGiang** [comment]
This is already on dev-app1

<img width="1438" alt="Screen Shot 2022-05-13 at 22 03 11" src="https://user-images.githubusercontent.com/30744004/168312236-a21f1edf-eca0-484c-98bf-ace939d6111e.png">

**Comment by vickis** [comment]
Super thanks!! :)
