### ISSUE TITLE
Choreography

### ISSUE THREAD

**Issue by paul-rohrlach** [upstage-org/upstage#92]
A player should be able to "choreograph" actions locally before sending them to the server.  The server should then send those actions out to connected users in a manner that reflects the timing and intent of the "choreographer".

**Comment by paul-rohrlach** [comment]
I'm bumping this from the milestone as it won't make it to the first release.

**Comment by helenvarley** [comment]
this is the "save scene" idea, isn't it?

**Comment by paul-rohrlach** [comment]
Not quite, no.  This is the ability to perform a number of actions locally and then sending them out in one go.  It's also enables the notion of "replay"

**Comment by helenvarley** [comment]
ah ok :)
