### ISSUE TITLE
streams disappeared sometimes after a few seconds

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#920]
last night there were several times when a stream disappeared off the stage after a few seconds. i would put a stream on, position it and turn on the light bulb. we would be seeing and hearing, then suddenly it would be as if another player had clicked on the x to remove the stream from the stage. i would put it back on again, and sometimes this would happen again maybe once or twice more.
then the stream would be fine and keep running.
i have just checked with all the other players, in case someone else was for some strange reason removing the streams, but everyone has said they did not (and i can't think why they would).
it was a bit weird.

**Comment by vickis** [comment]
hmm ok that is not good :(
i hope to make a presentation in UpStage on Saturday for the Refinery and
wish to use multiple streams ...

**Comment by helenvarley** [comment]
well the streams are definitely working - we had two simultaneous streams successfully during an impro of about 10 minutes - it seemed that once the streams got past the initial few seconds they were stable.
test before the weekend & see what happens ...

**Comment by vickis** [comment]
Hmm if the stream stops if there is connection loss this could become
problematic for anyone on a less robust network
Could the time of no connection be extended to ensure it is just an empty
stream not a struggling network please :)

**Comment by helenvarley** [comment]
> 
> Did you stop the stream in OBS Studio or Larix, and then resuming? If not then it must be a connection lost thinking

no, the streams were not stopped & as far as i'm aware there was no interruption from the sender. there were streams from 3 locations - us in the theatre, one person in berlin sending audio only, and an audio-video stream from another town. the problem seemed to happen in the first few seconds of me putting the stream onto the stage, & it happened with all of them at least once or twice. hard to believe that all of them experienced loss of connection just after i put their stream on. 
the streams all functioned fine once they stayed on the stage, there was no later interruptions.
