### ISSUE TITLE
We need an API call to send email from client installations.

### ISSUE THREAD

**Issue by gloriajw** [upstage-org/upstage#923]
In all of our installations, whether on our own systems or on clients systems, we want users to be able to send emails to Upstage admins, and groups of their own users. The problem is this: We currently have to provide our mail server credentials on every client system, in our back end config file, to allow each installation to send emails to admins. This is a security issue, and actually doesn't work as intended.

The ideal way for this to work is to be able to set up admin groups/aliases in our mail server settings, and have each client use an API to send email to an Upstage group, or as an Upstage admin (these would be site admins, while we are super admins). 

If we create an API that sends the email to a daemon on our svc1 server, we can prevent email credentials from being abused, and we can limit what clients can do as Upstage site admins re: emails.

**Comment by vickis** [comment]
Sounds great Gloria :)
Comms without security compromise
