### ISSUE TITLE
Hourly cron test, executed from app1, to make sure site is up. Sends email to admins if down.

### ISSUE THREAD

**Issue by gloriajw** [upstage-org/upstage#926]
This should try to connect to the database and query a record, try to connect to mqtt, then send and receive, try to connect to mongo db and write/read a test record, and then try to stream. This may require selenium, because of the stream test. If it does, it may be more useful to use headless selenium to load a fully functional demo stage.  We can try different ways to do this.

**Comment by helenvarley** [comment]
i know about headless chickens, but headless selenium is a new one for me :thinking:

**Comment by vickis** [comment]
Will be presenting about and having a play in UpStage - the refinery
instance on Saturday at 11am nzst
There might be some headless chickens music played as it is nz music month
:)
Please avoid anything being scheduled for then - will update on slack :)

**Comment by gloriajw** [comment]
Got it. Please do post this in general so everyone knows.

**Comment by vickis** [comment]
Thanks Gloria - will do
Actually the music track that I play is the residents (I am talking about
the c200 webcam (my first) it’s relevance to me and in performance and
surveillance etc
