### ISSUE TITLE
stages offline when entering with firefox

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#927]
using firefox (100.0) on linux, today all stages are offline on upstage.live, refinery.upstage.live and dev-app. 
on meta.upstage.live the stages are live.

in chromium, the stages on all four instances are all live.

i checked in my firefox settings and the websockets thing is set to false.

yesterday i was in stages on dev-app & upstage.live & it was all fine ...

**Comment by vickis** [comment]
As in refinery and upstage live yesterday for meeting with Todd - senses
places - Firefox and chrome working fine ...(Mac)
Todd on a pc did’t check his brwser but seeing as audience fine :)
upstage.live

**Comment by helenvarley** [comment]
could it be that the issue is only with firefox on linux? can someone with a windows pc try accessing the stages via firefox?

**Comment by nguyenhongphat0** [comment]
Stage is LIVE again on Firefox. Tested on `app1`, `dev-app1` and `refinery` 👌

**Comment by helenvarley** [comment]
yes! also LIVE for me on all three! :clap: :pray:

**Comment by vickis** [comment]
Yay thanks 🙌
