### ISSUE TITLE
I18n in both front and back end

### ISSUE THREAD

**Issue by gloriajw** [upstage-org/upstage#931]
In Vue, this looks like a decent option:
https://www.i18next.com/overview/getting-started
In Python, the default way to do this is Babel. I can set this up on the back end. @nguyenhongphat0, please let me now if you agree on the front end library, and start to think about setting this up.

**Comment by vickis** [comment]
THanks :D

**Comment by nguyenhongphat0** [comment]
I would recommend using https://vue-i18n.intlify.dev for implement `i18n` for Vue. But I have some questions:
- Which languages are we going to support?
- If we are going to support Germany I suppose, then our artists (@helenvarley , @vickis ,...) are going to be the one who translate these words to Germany, right? So do we need to have a "translating section" in the Admin section to do it (like WordPress), or we just tied it to the code?
- Where would you like to put the language selection dropdown on the Foyer? Maybe the top right before these Login / Register buttons?

**Comment by vickis** [comment]
Thanks for the vote of confidence @phat but I am not that well versed in
language And do not speak anything other than a few words (except perhaps
 in local pacific languages :)

I think using translation tools if possible (let the AI chew on the nuance
of sentence crafting in other cultures :)
The drop down by the login button makes sense to me :)

**Comment by helenvarley** [comment]
i've added @elisadcg to this issue as she has experience in software internationalisation
i do not know about the backend internationalisation, maybe this is not so necessary? but it would be nice to have some language options for the interface as this would definitely broaden accessibilty.
the languages that would make sense for the interface initially are german & french - & perhaps also swedish; most swedish people have very good english, however we do have some users who have swedish as a second langage and their mother tongue is dari or arabic, so english is quite difficult for them.
how easy / time consuming /technically complicated is it to add interface languages? could we start with one and gradually add others as we have the time?

**Comment by nguyenhongphat0** [comment]
> I think using translation tools if possible (let the AI chew on the nuance
of sentence crafting in other cultures :)

If we would like to have "automation translating", I would recommend integrating Google Translate Button into our website. It's very simple and fast to integrate into any website, free and automatic. We don't have to do the translate manually but sometimes the translated words might not be the one that we're waiting for 😅 Let me know what you think!

| English | Germany |
| ------- | --------- |
|<img width="701" alt="Screen Shot 2022-05-18 at 23 13 01" src="https://user-images.githubusercontent.com/29925961/169091199-2912161c-ce48-4fce-8f1c-69e7d8cefe06.png"> | <img width="702" alt="Screen Shot 2022-05-18 at 23 12 40" src="https://user-images.githubusercontent.com/29925961/169091210-8c5c2626-5c9a-4261-8f57-b51173237c19.png"> |

**Comment by gloriajw** [comment]
Google Translate does not properly translate colloquially, and is laughable at times. We should not use it.

**Comment by gloriajw** [comment]
Please, everyone, do not conflate the two problems of (1) translating existing text, and (2) making our software i18n compliant.
This is a discussion about how to make our software i18n compliant (2), not (1).
I have done this before, and it requires the following:

(A) Wrap a function around all hard-coded strings in the code.
(B) Run a tool (like Bable) that extracts all of the English strings.
(C) It automatically creates a map of English to X, where we pick the first language we translate to. "X" probably should be German, but it really does not matter.
(D) We give this dictionary of English strings and placeholders for the German equivalents to a translator. They type in the German equivalents and hand the dictionary file (usually a flat file) back to us.
(E) We install it in the place where the i18n package expects to find it, and run our software. When we set our locale and language in the browser settings (explicitly, or implicitly in the header settings, either one works), the i18n library auto-substitutes the English strings for the chosen language, and uses the english string as a dictionary key to look up the German (or whatever) equivalent.

Now that we know how this works, please let's focus on the dev task of (1) Which Vue library doe i18n support the best. On the back end, Babel is the default, best way to do this. And yes, we should be doing this on the back end too. We need to make sure we're passing the locale and langauge settings to the back end when a person (a) logs in, and (b) changes their default locale and language settings.

**Comment by vickis** [comment]
THanks for that clarification Gloria :)

**Comment by helenvarley** [comment]
should we make a separate issue for the translation of the interface text?

**Comment by helenvarley** [comment]
ok, we only need to come in at D with a translator :+1: 
& i agree we should not use an automated translation - we already have to be careful with english words, such as the distinction between words like clear, remove and delete; eva or someone from the schaumbad team will be able to do it.

**Comment by nguyenhongphat0** [comment]
I got `vue-i18n` setup in our `dashboard`, and I can tell it's working fine. I will setup `i18n` in the `studio`next!

<img width="1440" alt="Screen Shot 2022-05-21 at 23 56 25" src="https://user-images.githubusercontent.com/29925961/169661687-2e8c47d4-fd26-4069-9bc0-56ea8413c227.png">

Some of the text inside `javascript` logic is still got hardcoded, I'll split them into translatable string later (it's quite a lot) 😆

**Comment by vickis** [comment]
wow!

**Comment by helenvarley** [comment]
is it possible to have the dropdown language selector visible in the backstage as well? it can be in that same top left corner place.

**Comment by teddyfullstack** [comment]
> is it possible to have the dropdown language selector visible in the backstage as well? it can be in that same top left corner place.

The Studio has its own drop-down language selector now 😎
