### ISSUE TITLE
Stripe Integration

### ISSUE THREAD

**Issue by gloriajw** [upstage-org/upstage#932]
We will need Stripe integration for subscription-based payments to Upstage, and one-time donations to Upstage. 
After this is tested and working, we'll need to think about Stripe integration for performance ticket sales.

**Comment by nguyenhongphat0** [comment]
I'm not really an expert at U.S's payment methods, but I rarely seen any open source project that have donation using Stripe 🤔 I think the button `Buy me a coffee` would be more suitable, I heard that it is more convenient to setup than Stripe either: https://www.buymeacoffee.com. What do you think about this, @helenvarley?

**Comment by gloriajw** [comment]
Take a look at https://www.python.org/psf/donations/ . They accept PayPal, Zelle, ACH, wire transfers, etc. The use a payment processing platform to do this. This is not uncommon for complex projects. When I was in the PSF, we used Square. 

There is another goal here too: to enable artists to charge for their performances. We collect the payments, give them most of the proceeds, keep a small bit of it to pay for this service. EventBrite does this but charges a lot. Our goal would be to make it affordable and practical for everyone involved. This could also help us raise funds. As a not-for-profit org, any server we can offer which will benefit platform users and bring us funds should be considered.

**Comment by helenvarley** [comment]
yes i think it's good to give people payment options. stripe requires a credit card, and not everyone has one. paypal lets you pay with credit card or paypal account. we have a paypal account for UpStage as well as Stripe.
https://www.buymeacoffee.com/ is great but more for software i think. we need something that is more flexible - from our hosted installation clients paying ENORMOUS sums :wink: to micro-payments from artists as subscriptions, or shows that want to have different tiers of ticket prices, as well as donations that could be any amount.

**Comment by vickis** [comment]
Agree a flexible service required :)
I like buy me a coffee suggestion too but we need for tea drinkers and
those who don’t like hot drinks and the juice smoothie options ...

**Comment by nguyenhongphat0** [comment]
Giang did a great job on this 💪 

<img width="1428" alt="Screen Shot 2022-05-26 at 23 21 20" src="https://user-images.githubusercontent.com/29925961/170530695-d316a30f-19af-4a7e-ad4e-02321613ff3c.png">

<img width="376" alt="Screen Shot 2022-05-26 at 23 21 37" src="https://user-images.githubusercontent.com/29925961/170530709-96795767-2f62-4770-aa14-33ab8e1e006e.png">

I'll close this issue since we already got Stripe Integration. For further feature that require payments and Stripe, let's create another issue then 🎉

**Comment by vickis** [comment]
Thanks team :D
