### ISSUE TITLE
allowed characters in jitsi meeting name

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#934]
today i discovered that & is not an allowed character in jitsi meeting names. on the jitsi website there is a tip that comes up if you try to create a meeting with any of the not-allowed characters in the name.
could this information be in the pop-up window to create a jitsi meeting in UpStage? e.g. underneath the input field for giving the room a name.
![Screenshot from 2022-05-19 15:03:01](https://user-images.githubusercontent.com/3437324/169300113-c9dd2694-b0d3-48a1-a629-d91d736e09ae.png)
![Screenshot from 2022-05-19 15:06:20](https://user-images.githubusercontent.com/3437324/169300469-fef00eb0-5724-4e86-bff0-b183a82870f6.png)

**Comment by nguyenhongphat0** [comment]
This got fixed as part of #943 
<img width="691" alt="Screen Shot 2022-05-30 at 21 39 01" src="https://user-images.githubusercontent.com/29925961/171014875-ce7924fa-fead-46d2-96e1-cb61ae311ff2.png">

**Comment by vickis** [comment]
thanks Phat! :)
