### ISSUE TITLE
prop with link gets bigger when audience cursor rolls over it

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#940]
i just noticed that when there is a prop with a link and the audience roll their cursor over it, it gets bigger. this doesn't happen for logged in players.
i can understand that it can be a useful thing to help the audience know where there is a link, however i'm not sure that it's really what we want for performances, for several reasons.
firstly it can be disturbing to the visual experience that you want the audience to have, particularly if you have precise positions for objects in relation to each other. it's not so disturbing if the object is small, but when it's something larger the change is quite distinct (see below).
secondly, we may not want the audience to be aware that there is a link somewhere until a particular point in the performance. 

is it possible for this animation to be an option? for example that you can select in the Studio, in the same tab where you enter the link url and select for it to open in a new window or not - could there also be here a toggle to have the roll-over animation or not?

(i have not checked if this also happens with avatars that have links but i'm guessing it will be the same)

![Peek 2022-05-25 18-40](https://user-images.githubusercontent.com/3437324/170316737-f10091fb-6973-4100-a590-5a6d444911e0.gif)

**Comment by vickis** [comment]
yes this has always been the case
i am happy with it - as to me it helps indicate the action (especially
useful for inexperienced users)
its. like a visual jump to :)

**Comment by helenvarley** [comment]
i would prefer it to be an option, if that's possible?

**Comment by vickis** [comment]
yes an option could be good - in the old htmp it would be an onMouseOver
type instruction
if it could be an option and instructional a swop image feature would be
great too (so it could reverse out or similar :)

**Comment by nguyenhongphat0** [comment]
I will make the hover animation optional 👌

**Comment by nguyenhongphat0** [comment]
And please remember: changes applied to media in the studio won't effect these avatar/prop which were **already dragged into the stage**. It's only effect the future avatar/prop which will be dragged into the stage after saving 😅

**Comment by vickis** [comment]
Ha ha thanks Phat :)
We are always expecting miracles!

**Comment by helenvarley** [comment]
i see the test on the demo stage :) i guess we can close this issue :clap:
