### ISSUE TITLE
Individual mode in the Meeting tool

### ISSUE THREAD

**Issue by nguyenhongphat0** [upstage-org/upstage#944]
Here are the next step after integrating Jitsi low level API (as discussed in #877):
- Fix echo-ing issue
- Right click menu for each `individual` camera. Menu items are: 
  + Mute/Unmute
  + Change shape (Rectangle, Square and Circle)
- ...

**Comment by vickis** [comment]
sorry i can't test that as can't seem to access dev app
tried shift refresh ...

**Comment by helenvarley** [comment]
eva, sara & i went in just now to try it - me logged in & sara & eva as guests (they don't have logins for dev-app). sara could not hear us, and did not get the option to join the jitsi meeting, but eva did. again there were the two different kinds of jitsi, one window that was just me and the second window a new meeting that i made, which me & eva were in. 
when i added the first window that was showing just me to the stage, i could only see an empty frame; but eva could see me in it. she is sending a screengrab, i will add it when it comes. here is my screengrab:
![Screenshot from 2022-05-31 11:24:18](https://user-images.githubusercontent.com/3437324/171146670-f043b96d-4ba9-4b6a-aa85-872199f2607e.png)

**Comment by helenvarley** [comment]
here the screengrab from eva:
![Bildschirmfoto 2022-05-31 um 11 24 08](https://user-images.githubusercontent.com/3437324/171176035-88dba601-3506-433e-b3a9-8d966fdcda62.jpg)

**Comment by nguyenhongphat0** [comment]
> there were the two different kinds of jitsi

Yes we have the "Room mode" (full featured Jitsi meeting like we used to have) and "Individual mode" (each player hold their own camera and can move/change shape/opacity,... separatedly)

> i also don't get any right-click menu

It's on the next step as I explained above (which was the main purpose of opening this issue)

> sara could not hear us, and did not get the option to join the jitsi meeting, but eva did

Look like caching issue, the next time she try it please do a fresh reload (Ctrl + F5)

> i could only see an empty frame

That's a bug 🥶 Or maybe caching issue since I didn't experienced this issue before!

**Comment by helenvarley** [comment]
ah, ok! sorry, as usual i didn't read properly & just expected everything to be perfect :wink: :laughing: 

so for the right-click menu, as well as the points you put above, can it also have the other things that objects have e.g. flip horizontal & vertical, move speed or transparency slider options, send back and bring forward, & remove?

for me only seeing an empty frame: since eva could see both, and yesterday i saw both, i think it's more likely something at my end - maybe webcam confusion, or something like this. don't think of it as a bug unless it keeps happening :)

**Comment by nguyenhongphat0** [comment]
> so for the right-click menu, as well as the points you put above, can it also have the other things that objects have e.g. flip horizontal & vertical, move speed or transparency slider options, send back and bring forward, & remove?

Got this 👌

**Comment by helenvarley** [comment]
great - i see the right-click menu & everything looks really good! the only thing i haven't been able to test yet is the audio as i am alone. but as long as that works as expected, i think we can release this (it would be really great if we could have it on meta,upstage this week, so we can experiment with it on monday ... ???)

**Comment by helenvarley** [comment]
closing this as individual jitsi is working pretty well now!
