### ISSUE TITLE
additional required field for new registrations

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#945]
please add a required field to the registration form that says:
"Please say briefly who you are and why you would like an UpStage account."

this should be a text input field with enough room for a couple of sentences. it can come at the end of the form (after the email address & before the ToC checkbox)

**Comment by vickis** [comment]
yes - saves the extra email to ask for this information
mostly people are curious or might have a project in mind so it is good to
know why they wish to explore UpStage :)

**Comment by nguyenhongphat0** [comment]
It will be available on `dev-app1` as soon as PR #952 got merged. To view the introduction, you can hover on the ℹ️ icon like this 👇 

<img width="822" alt="Screen Shot 2022-06-12 at 21 10 45" src="https://user-images.githubusercontent.com/29925961/173237986-7670ca1c-ee5b-41af-aa28-f26e71257c0d.png">

**Comment by vickis** [comment]
Super awesome thanks :)

**Comment by helenvarley** [comment]
great, that's a nice way to show it :)
(in future it might be useful to also have this show in the pop-up window when you click to edit the player profile, and also in a player's own profile so that they can also edit it - but let's not worry about that at the moment)

**Comment by vickis** [comment]
Yes could be interesting  - but agree for later :) thanks team!
