### ISSUE TITLE
stage owner shows as audience access only in stage management

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#947]
if you have created a stage & are the owner of it, shouldn't your player username show up in the stage management interface list as having player and edit access?
i just noticed that this is no the case, for example on my stage on upstage.live, there are no usernames at all in in the player & edit column, & only phat in the player column. i find myself in the audience only column.
i do have player and edit access, so it is a bit confusing that it doesn't show that.
![Screenshot from 2022-05-31 16:24:09](https://user-images.githubusercontent.com/3437324/171197265-93c7114b-c6f8-475f-8a84-9b026d098cf8.png)

**Comment by helenvarley** [comment]
should we be seeing this now on dev-app? i just created a test stage, but i am still in the audience-only column.

**Comment by helenvarley** [comment]
i just created a new stage and find that not only am i not in the "player and edit access" column, my username doesn't appear in ANY of the columns:
![Screenshot from 2022-08-24 11:37:09](https://user-images.githubusercontent.com/3437324/186388064-cb1261d0-e5ac-4f77-a4cd-81dfe3d3289d.png)

**Comment by tunguyentk** [comment]
@vickis @helenvarley 
For this task, I have it always show the owner's name in the Player and edit access column. It can't move to another column and I make some changes to it: add permiss tag , change background color. I haven't deloyed it yet, I just want to know your opinion on my changes.
![image](https://user-images.githubusercontent.com/117065175/211179119-a6727f52-40f2-4709-b2de-07125d31d637.png)

**Comment by vickis** [comment]
looks great - yes please to deploying it :)

**Comment by helenvarley** [comment]
agree, looks great! :+1:

**Comment by tunguyentk** [comment]
@helenvarley @vickis i deloyed it. Pls checking. Thank you so much

**Comment by vickis** [comment]
working as described
