### ISSUE TITLE
do we need "Stage Management - Scenes" ?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#959]
currently there is a section in Stage Management called Scenes, where you can see a list of any scenes that have been saved on a particular stage. the only action possible here is to delete a scene. you can't see what media items are part of that scene, or edit its contents - & you wouldn't want to do that here because you need to be on the live stage to do that, to determine position, size etc. - & you can also delete scenes on the live stage very easily, so this interface seems pretty redundant. 

is there any reason that we need to keep it, or any other functionality that would make it useful? if not, i vote that we remove it, as it's confusing & unnecessary.

**Comment by vickis** [comment]
The only thing I would see as problematic is if stage is cleared without
removing attached scenes
otherwise seems best to keep within the management of the specific stage :)

**Comment by helenvarley** [comment]
i'm not sure what you mean is problematic, as that is the current situation - sweeping (clearing) the stage does not remove scenes. it just clears any media that has been placed on the stage. the only ways to delete scenes are from the on stage tool bar or from the Stage Management Scenes interface.

i think the Scenes tab in Stage Management is redundant, & potentially confusing for newbies; i can't think of a reason to keep it ...

**Comment by vickis** [comment]
Yes agree
Sorry I meant if stage is deleted (and scenes remained )

**Comment by helenvarley** [comment]
i think if a stage is deleted, the scenes will also be deleted, because you can only access them on the stage.
shall we go ahead & ask the devs to remove the Scenes section from Stage Management then? :smiley:
