### ISSUE TITLE
cannot delete scene without making it appear on stage

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#961]
if i right-click on a scene in the on-stage Scenes toolbar in order to access the delete option and remove it, it also makes the scene appear on the stage.
this is a bit frustrating as if i want to delete a scene, i don't usually want to show it as well. 
it should be possible to right-click on the scene to acecss the context menu, without also having the left-click function of selecting and activating the scene.
![Peek 2022-06-22 15-00](https://user-images.githubusercontent.com/3437324/175035555-42ffb8dc-f1ce-40ae-89c3-69bce0647a22.gif)

**Comment by nguyenhongphat0** [comment]
This got fixed in PR #968

**Comment by vickis** [comment]
Super :)
