### ISSUE TITLE
OBS stream disappears when put on stage

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#963]
today i set up two of the meta theater team for streaming; one with larix, all working fine; the other with OBS, & it's working, but every time he put the stream onto the stage, it disappeared as if someone had clicked the X to remove it. i also tried putting it on, same thing happened - as soon as it appeared, it disappeared. 
he restarted OBS & tried again, this time it stayed for several seconds and we thought the problem was solved - then it disappeared again!
after we finished our session, i started my OBS stream on the same stage that we'd been working on (https://meta.upstage.live/impro-open) and it is running fine.
he has a brand new mac computer and has recently downloaded the latest version of OBS. 
any ideas what could be causing the problem??

(i've added the "prioritise" label, as we need this stream for the presentation on monday - but if the individual jitsi feature can be rolled out before then, then we can use that instead)

**Comment by helenvarley** [comment]
after sleeping on this issue, i realised that the problem is probably that he was using his webcam in the jitsi meeting at the same time, and it could not handle working with two applications at the same time. i've asked him to try streaming again without jitsi at the same time, & i'm 99% sure this will be the solution. so probably not an UpStage bug at all!

**Comment by vickis** [comment]
Great work by the Ministry of Sleep :)

**Comment by nguyenhongphat0** [comment]
This is a duplicated of [#920](https://github.com/upstage-org/upstage/issues/920#issuecomment-1122622152). And as I explained before: stream will automatically disappear if the stream host stop broadcasting it!
In this case our artist obviously didn't stop broadcasting it, but it look like he lost the RTMP connection somehow. Maybe we should remove this behavior (automatically took off stream from stage) to prevent misleading 🤔

**Comment by vickis** [comment]
I think removing the stream if the broadcast stops is fine - sensible
Perhaps there can be a count of x seconds to ensure stream doesn’t
disappear if connection is lost cfor only a brief time eg 3 or 5 seconds

In the case of Helen’s artist it sounds like the issue was they had
multiple applications competing for the webcam - so not really an issue for
us to address in UpStage :)

**Comment by helenvarley** [comment]
yes - i am pretty certain that the issue was having both jitsi and OBS trying to use the same webcam at the same time. 
removing the stream in this instance is perfectly fine, the only possible improvement i can think of would be to have an alert message pop up saying something like "your webcam is already being used by another application and therefore cannot be used to send a stream". BUT this is not at all urgent. it is really just a case of everyone getting more experienced with how the streaming works. i will close this issue :)
