### ISSUE TITLE
"terms & conditions" in vietnamese even when english or deutsch langauge selected

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#965]
the text for "terms & conditions" is appearing in vietnamese when i have english or german selected, both in the admin section of Backstage and in the login or register pop-up window.
this is the only one i've noticed that is not translating.
![Screenshot from 2022-06-24 23:08:07](https://user-images.githubusercontent.com/3437324/175667764-0094f66a-93ca-4733-82af-56dde1a7757f.png)

**Comment by vickis** [comment]
hehe an easter egg from Phat or Giang? ;)
