### ISSUE TITLE
sending email as BCC notification doesn't say who sent to

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#966]
this is pretty minor, but when i send an email from the admin section and use BCC, the success notification says "Notification has been successfully sent to !" and does not show the names of those who it's been sent to. it's not hugely important to see who it's been sent to, but when there are no names/emails there, it makes me wonder if it has been sent at all ... did any of you receive it?
![Screenshot from 2022-06-24 23-04-27](https://user-images.githubusercontent.com/3437324/175694877-a2042e54-6edd-44e2-81f7-0195d1616279.png)

**Comment by TuyetGiang** [comment]
@helenvarley notification doesn't say who sent to because there are no users to the To column. The statement"Notification has been successfully sent to XXXX" just mentions Recipients, don't mention BCC. You want to mention BCC users here, right?

**Comment by helenvarley** [comment]
yes - is that possible? just to confirm that the email has been sent to the players you've selected. when there is nothing there it is a bit disconcerting, as if the email hasn't been sent to anyone at all.

**Comment by vickis** [comment]
it would be great to know who was on the list - but if there is a chance
that it might then send bcc details out to all then leave as is
the best situation it seems to me is that there is info or similar in the
to: field and the record of who the email is sent to is retained on the
local machine (eg by the sender) :)

**Comment by helenvarley** [comment]
this is only for the success notification that pops up in your browser when you send the email. i don't think anyone else gets to see it :)

**Comment by TuyetGiang** [comment]
> yes - is that possible? just to confirm that the email has been sent to the players you've selected. when there is nothing there it is a bit disconcerting, as if the email hasn't been sent to anyone at all.

Yes, it's possible. I updated on PR https://github.com/upstage-org/upstage/pull/979

**Comment by vickis** [comment]
if you sent it just now - then no have not seen

**Comment by helenvarley** [comment]
@vickis this issue was closed in july

**Comment by vickis** [comment]
Yes I see that - that is most likely when I was responding to the issue
-weird!
