### ISSUE TITLE
stage visibilty on foyer

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#967]
there were 14 stages appearing on the foyer, and many of them don't need to be there. so from the stages list i changed the visibility toggle to off, and checked that they were no longer on the foyer. then i went to chromium in another tab (not logged in), and saw that all 14 were still there. i did a shift+refresh, still showing. i went back to firefox (logged in) & did shift+refresh on the foyer - & all 14 stages are showing again. i went to the Stages list in Backstage, and saw that those i had toggled to visibility off, were now showing as on.
if i go into the Stage management of an individual stage and change the visibility setting there, then click Save, it works. but on the Stages list, even though it says it works, it seems that it does not.

**Comment by vickis** [comment]
yes this is something to get working
currently fine because individually can be fixed but as a tool stage
manager should be able to achieve that status change :)

**Comment by nguyenhongphat0** [comment]
This got fixed in PR #969
