### ISSUE TITLE
Foyer (landing page / public entry point)

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#97]
there needs to be a public entry point for an UpStage instance, the landing page where the public can find out what's on and how to access it, and where players and admins can log in to the Stages and Dashboard part of the instance. traditionally this has been called the Foyer, e.g. this page: http://upstage.live:8081/home

with my highly advanced design skills, i have made a mock-up of what this interface needs to include and where it leads to; i got a bit carried away & extended elisa's wireframe-structure.pdf proposal to try & show what things are in the Dashboard and what on the Stage:

[interface_overview.pdf](https://github.com/upstage-org/mobilise/files/5702388/interface_overview.pdf)

**Comment by helenvarley** [comment]
i already thought of something else to add :D
if we can have a title, thumbnail & brief description of current & upcoming performances displayed in the "What's On" section of the Foyer interface, then we need somewhere to enter this information for each stage; i think it makes sense for this to be done in the Dashboard, where there is the list of stages, & each stage has a button to enter, access logs/recordings, clone or delete. here there should also be a button to edit stage information or something like this, which gives you an interface where you can enter & edit the title of the show, upload a thumbnail image, & enter the brief description. maybe this is also the place where you can set whether the stage is public or private?
(paul is going to say that this needs to be a separate issue, i know ... :D )

**Comment by vickis** [comment]
sounds good :)

**Comment by helenvarley** [comment]
[interface_overview.pdf](https://github.com/upstage-org/mobilise/files/5743118/interface_overview.pdf)

**Comment by elisadcg** [comment]
Second me, the login box is so lost in the middle of nothing.
I suggest to stylise it like the other previoux box. With the #welcome .link class.
See image below :
actual pb on the left and proposition on the right.
![Screenshot_20210303_091037](https://user-images.githubusercontent.com/7611913/109776257-ae3dda00-7c02-11eb-810e-d09371430686.png)

**Comment by elisadcg** [comment]
And the logo UpStage appear very little.
I think we can scale it a little without any trouble.
![UpStagefixlogo](https://user-images.githubusercontent.com/7611913/109776785-41770f80-7c03-11eb-9c29-a53a46883635.png)
max-height:2.75rem sounds good.

**Comment by elisadcg** [comment]
One more. When the user is in the dashboad and try to register or login any message appear on the top right corner. If the user have big window, the message are not visible.
I suggest to put the message close the box. I suggest very on top of it :)
![Screenshot_20210303_093740](https://user-images.githubusercontent.com/7611913/109777566-28bb2980-7c04-11eb-8d53-f7e708bdbffa.png)
![Screenshot_20210303_093740-2](https://user-images.githubusercontent.com/7611913/109777575-2bb61a00-7c04-11eb-8c40-9acbebdc54b2.png)

**Comment by elisadcg** [comment]
And i suggest a box-shadow : 2px 2px 8px #0a; on the nav.navbar class.
![Screenshot_20210303_095006](https://user-images.githubusercontent.com/7611913/109778962-be0aed80-7c05-11eb-9255-95ab2813ea59.png)

**Comment by helenvarley** [comment]
yes - i have also been thinking about those 3 boxes on the home page (which i still haven't sent dummy images for, sorry!) and i wonder if we actually need the "ticketing" one - because people only need to go to "ticketing" when they want to buy a ticket for a specific show. so this can just be a "buy ticket" link on the show information, and the third box could be the log-in / registation - or maybe that doesn't need to be so highlighted ... maybe the 3rd box could be a "latest news" - news about the project rather than the specific shows?

**Comment by helenvarley** [comment]
> And the logo UpStage appear very little.
> I think we can scale it a little without any trouble.
> ![UpStagefixlogo](https://user-images.githubusercontent.com/7611913/109776785-41770f80-7c03-11eb-9c29-a53a46883635.png)
> max-height:2.75rem sounds good.

hmm - should it be sooo small? i suppose if it's another hosted instance of UpStage they don't want a huge one, but for OUR instance it would be nice to have the logo bigger ... could this be something that can be customised in the template?

**Comment by elisadcg** [comment]
Ok so let's max-height 3.75 rem ?

**Comment by nguyenhongphat0** [comment]
It's look like we're going to have a re-design in the Visual Identity: #119 . I'll move this issue to a later milestone
