### ISSUE TITLE
multiframe backdrop sticks on specific frames

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#970]
a multiframe backdrop on https://meta.upstage.live/impro-open is sticking on specific frames. when it is set to animate, it starts off as expected but about half way through it sticks on two frames, going back and forth between the two frames instead of continuing on the cycle.
it has a lot of frames - ca. 26 (it's hard to count - maybe would be useful to somewhere state the number of frames in a multiframe item?) - could it simply be that it's too much? as far as i know there is no limit on the number of frames. there is one on https://upstage.live/demo that has a similar number of frames and functions as expected.
the backdrop is also on another stage and also there does not cycle through its frames as expected. so i'm thinking it is probably a problem with one or more of the images rather than an UpStage problem, but it's hard to know ...

**Comment by vickis** [comment]
when i had theissue with animated backdrops i just remade them to ensure
there were no corrupted files
# of files _shouldn't_ be an issue but might be making it a very big file?
i can't login to Meta to review - but demo stage bkdrops working as
expected :)

**Comment by helenvarley** [comment]
i've asked her to try re-uploading, don't know if she has yet but i will ask her again tomorrow. 
i tried a few other backdrops with lots of images, e.g. one of the ones on the villa waldberta stage, with eva & sara in the cupboard doors, has a similar number of frames (more than 20) & it works fine. this one on meta.upstage is the only one i can find that is sticking, so it does seem like an issue with the image files rather than an UpStage problem.

**Comment by helenvarley** [comment]
i am not sure if this issue has been resolved, but it hasn't been replicated anywhere, so i'm closing it for now.
