### ISSUE TITLE
audio: does not return to start at end of playing track once

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#972]
if you play an audio track once, when it finishes the slider stays at the right-hand end of the track instead of returning to the beginning. this means that you cannot just start the track again if you want to play it again, you have to first manually move the slider back to the beginning.
it should be that if the track is not set to loop, when it finishes playing it returns to the beginning of the track.

**Comment by helenvarley** [comment]
see also #649 - this issue was reported twice.

**Comment by fuyloon2018** [comment]
Hi @helenvarley , @tunguyentk  done this issues yesterday(VN-time), and I have deployed it dev-app1, you can verify it on dev thanks you

**Comment by vickis** [comment]
great tested and confirmed working - thanks! :)
<img width="324" alt="image" src="https://user-images.githubusercontent.com/4249450/203248793-a87cb325-c21b-4da2-87c8-20678a2b6a98.png">

**Comment by helenvarley** [comment]
verified by me too 👍
