### ISSUE TITLE
player-audience counter is not right

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#973]
tonight during our presentation the counter showed 42 audience, but some of them were there multiple times - at least, if they had put in a nickname, some names were there multiple times. it seems that if people re-entered the stage, they are counted again.
now it is showing 3 players, one that is called Guest, & the player Elsa who is on the stage is not showing as there; but she is there, & a player. the "Guest player" shows as joining an hour ago, which was in the middle of our presentation. Elsa had been there for much longer than that and had not reloaded the stage an hour ago.
![Screenshot from 2022-06-27 20-26-24](https://user-images.githubusercontent.com/3437324/176013705-edf899c5-9b98-4715-af0e-71692e1f7add.png)
.

**Comment by helenvarley** [comment]
to add to this, yesterday for our walkthrough session, a player logged in with the username Max but in the dropdown from the counter he was shown as Guest. when he typed in the chat, his name showed as Max. he had not changed the display name in the chat settings, he had only just logged in & did not yet know about that possibility.
![Screenshot from 2022-07-14 21:01:08](https://user-images.githubusercontent.com/3437324/179193219-56b82327-51de-4c5f-a996-4ba1b5096b82.png)

**Comment by vickis** [comment]
is this because he had one of the guest logins?
or does he have a player login through Meta theatre...

perhaps we should consider changing our temporary (guest logins) to
'temporary' or similar to avoid future confusion

**Comment by helenvarley** [comment]
no i made him his own login, with username Max (the same as his meta.upstage login so as to be easy)

**Comment by vickis** [comment]
Guest login was not showing in counter and not allowing interaction in chat (as below) - her stage is showing as offline but she could obviously access tools = audio ...  <img width="1216" alt="image" src="https://user-images.githubusercontent.com/4249450/179725104-7abe1a8f-c469-445b-933e-f66878a0cd9b.png">

**Comment by helenvarley** [comment]
closing this as it may be fixed - i haven't noticed similar problems lately. we can open a new issue if there are problems.
