### ISSUE TITLE
british flag instead of american one for english language option?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#977]
very minor point, but i noticed that the flag used for english language in the language selector is the american flag. could it be changed to the british one? (union jack) - not that the british government is really any better than the usa at the moment, but i prefer it, since it is where the english language comes from & it's also a small counter against usa dominance of the internet ... :)
this is of course not at all urgent, but maybe a nice easy small thing to do.

**Comment by vickis** [comment]
could we just use text?

**Comment by helenvarley** [comment]
we could :)

**Comment by helenvarley** [comment]
i realised why it's good to have the flag as well as text: if you're not a speaker of whatever language the languages are showing up in text, the flag helps you to know a) that this is the language selector, & b) what language you're selecting (also if you are dyslexic or any other kind of reading/visual disability). 
(i realised this because google thinks i'm danish - i was in denmark 3 weeks ago, & it changed everything it could to danish without asking me. since then i've been in germany & now portugal - but it still thinks i should be danish. there must be a setting somewhere, but i don't know the words in danish for changing the language!)

**Comment by helenvarley** [comment]
thank you! :pray:

**Comment by helenvarley** [comment]
reopening this as in dev-app the american flag is still showing in the Studio. everywhere else it's changed to british.

**Comment by TuyetGiang** [comment]
@helenvarley I have updated the British flag in the Studio on dev-app. Please help me check again. thanks

**Comment by helenvarley** [comment]
great! thank you :pray:
