### ISSUE TITLE
did not receive notification of new registration

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#984]
today someone registered an account on upstage.live but we did not receive a notification email that there is a registration awaiting approval. she also did not receive any confirmation or anything. is the email system broken?

**Comment by TuyetGiang** [comment]
@helenvarley Please help me check again. Thank you

**Comment by helenvarley** [comment]
should i check on dev-app or upstage.live?

**Comment by helenvarley** [comment]
i also checked with 3 other players, and they have all now received emails that i sent via the system some weeks ago :laughing: 
one question: do we know what caused it to break? i'm concerned that it could happen again in the future and we don't realise for some time (this time it must have been broken for about 4 weeks without us realising, & i sent emails asking people to help with stream testing on 8th july which they just got now, even though i saw the notification saying the email was sent).

**Comment by gloriajw** [comment]
@TuyetGiang : to make sure the service stays up, please be sure to do this as root:
sytemctl enable name_of_service
Then test by: ps awux | grep name_of_process  and then kill -9 pid
It should restart itself.

**Comment by TuyetGiang** [comment]
@helenvarley We have another process to send an email and that service was not configured upstage.live. All emails are in a queue. When I config that service, all emails are sent.

**Comment by TuyetGiang** [comment]
> 

Thanks @gloriajw

**Comment by helenvarley** [comment]
probably we can close this one then? :smile:
