### ISSUE TITLE
should not be possible to set media type as "Media"

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#986]
in the Studio, it is possible to select "Media" at the top of the Media type dropdown list (avatar, prop, etc). If you select "Media" and save your avatar with the media type "Media", it is not available on any of the stages you have assigned it to because it does not have a media type.
Please change "Media" to read "Media Type" and make it be the name of this dropdown list but NOT a selectable option.
(hopefully this is something quick & easy!)

**Comment by TuyetGiang** [comment]
@helenvarley because that dropdown always displays 1 in 3 options "Audio"(audio file), "Stream"(video or virtual file), "Avatar"(others) when the first time uploading a file, so I just remove Media out from the dropdown list, don't add the name "Media Type". Do you agree with it?

**Comment by vickis** [comment]
super thanks Giang :)

**Comment by TuyetGiang** [comment]
@helenvarley I have updated on dev-app1, please help me check again. If anything needs to change, please let me know. Thank you.

**Comment by helenvarley** [comment]
@TuyetGiang great, i have checked and it's now better, i just see Avatar, Prop, Backdrop, Audio, Curtain.

one minor request: we have said that by default, dropdown lists should be alphabeticised as this makes it easier to find what you are looking for. lists should always be either alphabetical or chronological (unless there are specific circumstances for a different ordering).
could you please make the list be Audio, Avatar, Backdrop, Curtain, Prop

**Comment by helenvarley** [comment]
closing this as the original issue has been fixed. see #604 for the ordering of lists.

**Comment by vickis** [comment]
yes good to resolve
