### ISSUE TITLE
"Stream" does not need to be in Media type list

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#987]
I don't think we need the "Stream" option in the Media type list (in the media edit interface in the Studio) - if you are creating a stream, you use the three dots to the right of the "New" button, and you do not want to change the media type later.
If you change the media type of a previously uploaded media item to Stream, it breaks it.
So it would be good to remove this option from the list.
![Screenshot from 2022-07-15 16:47:13](https://user-images.githubusercontent.com/3437324/179247819-a2a8e23e-ab2e-4964-8972-e2a8692b2388.png)

**Comment by helenvarley** [comment]
Note: we also have "Shape" as an available media type; this is left-over from earlier versions of the streaming functionality, where we could upload any shape and have this as a possible frame for a stream. phat removed this because it was causing more lag, so now we only have the rectangular or round/oval options. 
unless it's likely that we can soon have other shapes again, this should probably be removed from the list as well, as it is confusing. if you give a media item the type Shape, it is not available anywhere on the stages you have assigned it to.

**Comment by vickis** [comment]
agree amend to remove stream and shapes

**Comment by helenvarley** [comment]
and another note: "Shape" is also in the media type dropdown for filtering the media list in the Studio. it should be removed from this list, and it should not be possible to select "Media" in that list.
![Screenshot from 2022-07-16 20:35:02](https://user-images.githubusercontent.com/3437324/179367926-69dfe130-245c-4e94-b039-2723cd9a3f49.png)

**Comment by helenvarley** [comment]
curious - i just noticed that meta.upstage.live, which has the footer showing "UpStage v1.22.0 - Stiegl-22" does not have Shape or Media in the media list of the Studio or in the media type dropdown of the media edit interface.
dev-app, where the footer says " UpStage v1.23.0 - Krombacher-23", still has these items there.

not sure whether there is a version control issue here? or these types got taken out in one update & put back in another? just checking ... :thinking:

**Comment by helenvarley** [comment]
hi, i just noticed that Stream has also been removed from the filters in the media list of the Studio, but actually we still need it here, otherwise we can't search for Streams.
it's only from the media edit interface where it isn't needed (& i'm still seeing Shape and Stream there in dev-app)
Sorry if this was unclear.
![Screenshot from 2022-07-19 09:59:43](https://user-images.githubusercontent.com/3437324/179698758-d318c76d-4bb4-4e86-894d-57dc63772478.png)

**Comment by TuyetGiang** [comment]
@helenvarley Do we need Stream in the dropdown when clicking on the New button (don't use the three dots to the right of the "New" button)?

**Comment by helenvarley** [comment]
i don't get a dropdown when i click on New - it opens the upload window. the three dots are to create an RTMP stream :)

**Comment by vickis** [comment]
Clicking on new to create a stream is working fine @giang thank you :)

**Comment by TuyetGiang** [comment]
@helenvarley  I have updated on https://dev-app1.upstage.live/, please help me check again. If anything needs to change, please let me know. Thank you.

**Comment by helenvarley** [comment]
it's great, thank you! just the same note as on #986 - please always alphabeticise the lists. so the dropdown of media types for filtering in the Studio should be ordered: Audio, Avatar, Backdrop, Curtain, Prop, Stream

**Comment by vickis** [comment]
superb work thanks Giang :D

**Comment by helenvarley** [comment]
i will close this as the original issue of removing "stream" from the media list in the edit interface has been fixed.
