### ISSUE TITLE
stream configuration expiry information

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#991]
rtmp stream configurations are set to expire after 6 months - i forget the reason why, but phat had a good reason for doing this. however, there is no way to know exactly when this is. in the studio, the date of creation shows in days for the first month, and after that it only shows the number of months ago when the stream was created. 

we had a situation on monday where sebastian's stream stopped working just before the presentation; it had been working in the afternoon during set-up, then when he wanted to start it for the performance it did not work. he solved it by renewing the stream key, so i am guessing that it just happened to expire in this short time (less than an hour) between the set-up and the performance - an unfortunate coincidence. 

1. is it still necessary for the stream configuration to expire? (we may need input from @nguyenhongphat0  or @gloriajw to know if the reason is still valid)

2. if it is still necessary to expire:

- can we have some kind of alert or notification, at least 24 hours before it expires?
- can we see more precisely the date of the stream's creation? i think that in the media list in the studio, it's fine to have it as it is - usually we only want to know approximately when a media item was created, and to be able to sort the media according to most recent or oldest. but it would be good to see in the media item's edit interface (for streams and all media) the precise date of creation. could this be included for example top right in the edit interface?

**Comment by vickis** [comment]
Yes useful
Think it good for expiry but need to clearly know when :)

**Comment by helenvarley** [comment]
closing this as we don't currently have RTMP stream functionality.
