### ISSUE TITLE
where can we see the reason for registering an account?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#995]
we now have in the registration form the field for people to enter their reasons for registering an UpStage account, so that we can more easily see who is a genuine registration and what is bots or spam. 
in the player list in the admin section, we can hover over the little "i" icon by the new registrant's username to see their message. however, if the person has entered a long message, it's impossible to read it all - see screengrab below.
it's also likely that someone might enter a url or other information that might be handy to copy and paste, but there is nowhere that we can do this.
is it possible to have this field also shown in the player's profile?

**Comment by TuyetGiang** [comment]
@helenvarley You want to add a column like this image, right?

![Screen Shot 2022-07-31 at 17 11 04](https://user-images.githubusercontent.com/30744004/182021433-ede35ed7-f2e3-4448-b24b-332b97323b15.png)

**Comment by helenvarley** [comment]
@TuyetGiang actually no - this would not help, as sometimes people will write quite long messages. what would be more useful is to have their introduction message appear in a field in their profile, that we can see in the pop-up edit window - i suggest below the email field, & that it can be as long or short as it needs to be.
![Screenshot from 2022-07-31 14:22:35](https://user-images.githubusercontent.com/3437324/182026207-8618864c-a0b1-4d2c-af2b-e7d498b2de5c.png)
it would make sense for this field to also show in the player's own profile, and be editable (i don't think it's very important that it's editable, but it's a good policy to allow players to be able to edit their own information if they want to). also under the email field.
![Screenshot from 2022-07-31 14:22:35](https://user-images.githubusercontent.com/3437324/182026312-4ed5753d-77d0-4840-a0a4-63916ece6143.png)

**Comment by helenvarley** [comment]
oops - i uploaded screenshots but then realised that they showed usernames & email addresses so have deleted them. if you need the screenshots let me know & i'll email them to you.

**Comment by helenvarley** [comment]
just deleted the previous ones as well as they also showed usernames & emails - oops! we need to take care about that.

**Comment by teddyfullstack** [comment]
> is it possible to have this field also shown in the player's profile?

Absolutely ✅

**Comment by teddyfullstack** [comment]
> i don't see players' introductions showing in their profile
Did you check it on dev-app1 or other instances? On dev-app1 introductions are shown in either your profile or other's profiles 👇 

My profile:
<img width="1437" alt="Screenshot 2023-11-29 at 23 46 58" src="https://github.com/upstage-org/upstage/assets/29925961/4bc28899-e982-4b62-babc-bd9b60ef2e6e">

Other profiles:
<img width="1439" alt="Screenshot 2023-11-29 at 23 47 20" src="https://github.com/upstage-org/upstage/assets/29925961/54991da3-cafe-4c82-b2b6-c2195a399cba">

**Comment by helenvarley** [comment]
ok, i see it now - i had been looking on dev-app, but hardly any of the player accounts on dev app have entered an introduction :laughing:  now i put one into mine & i see it. 
however the link to the profile from my player name in the top menu is still going to the old interface rather than pop-up menu, and here there is no field for the introdcution. i made a separate issue for this already #1133 (there are also old links to backstage in this interface so it really should be replaced with the popup)
